import '../quotes_randomizer.dart';

/// **Curiosity and Exploration Quotes & Images**
final List<String> curiosityQuotesRaw = [
  "Curiosity is the spark that ignites the flame of discovery.",
  "Exploration begins where certainty ends.",
  "A curious mind is never bored.",
  "The unknown is an invitation to explore.",
  "Curiosity is the engine of achievement.",
  "Never stop questioning; every question is a doorway to knowledge.",
  "Exploration is curiosity put into action.",
  "The joy of discovery is the reward of curiosity.",
  "Curiosity is the secret ingredient of genius.",
  "New worlds are found by those who dare to look beyond the horizon.",
  "The greatest journeys begin with a single question: 'What if?'",
  "To explore is to live fully.",
  "Curiosity is the key that unlocks endless possibilities.",
  "Exploration is the art of seeing what others ignore.",
  "Knowledge grows when curiosity is nurtured.",
  "The mind that wonders is the mind that learns.",
  "Curiosity is the seed from which all innovation grows.",
  "Adventure is curiosity in motion.",
  "The best discoveries are made by asking 'Why not?'",
  "A curious mind sees opportunities where others see obstacles.",
  "Curiosity opens doors that fear keeps closed.",
  "Exploration is the bridge between dreams and reality.",
  "Wonder is the beginning of wisdom.",
  "The more you explore, the more you understand.",
  "Curiosity leads to knowledge, and knowledge leads to growth.",
  "Dare to question, dare to learn, dare to explore.",
  "The universe rewards the curious.",
  "Curiosity is the compass that leads to wisdom.",
  "Exploration is an endless journey of learning.",
  "To be curious is to be alive.",
  "Discoveries are made by those who refuse to accept the status quo.",
  "A curious mind creates a limitless future.",
  "Curiosity is the magic ingredient that transforms the ordinary into the extraordinary.",
  "Great explorers see beyond what is and imagine what could be.",
  "The thirst for knowledge is never quenched by ignorance.",
  "Curiosity turns the impossible into the inevitable.",
  "The world is full of wonders for those who seek them.",
  "Without curiosity, there is no progress.",
  "Exploration turns questions into answers.",
  "A life without curiosity is a life half-lived.",
  "Curiosity is the passport to a journey without end.",
  "Every new discovery begins with curiosity.",
  "The future belongs to the curious.",
  "If you never explore, you'll never truly know.",
  "The greatest scientists, artists, and thinkers were all driven by curiosity.",
  "Curiosity is the heartbeat of progress.",
  "Learning is fueled by curiosity.",
  "Curiosity transforms the mundane into the marvelous.",
  "Every discovery starts with the courage to explore.",
  "Be curious today, and the world will surprise you tomorrow.",
  "Adventure begins where curiosity takes over.",
  "Curiosity is the antidote to boredom.",
  "Curious minds make the world a better place.",
  "Exploration expands the boundaries of possibility.",
  "The thrill of exploration is the joy of being alive.",
  "Innovation is born from curiosity.",
  "Every child is born curious—never lose that gift.",
  "A questioning mind is a growing mind.",
  "Curiosity is a muscle—exercise it daily.",
  "Exploration is the soul of progress.",
  "Never fear the unknown—embrace it.",
  "Discovery belongs to the bold and the curious.",
  "Curiosity makes ordinary things extraordinary.",
  "The best way to learn is to explore.",
  "Seek knowledge like a traveler seeks new lands.",
  "A curious mind is a limitless mind.",
  "Curiosity is the root of all wisdom.",
  "The universe is full of questions waiting to be answered.",
  "Keep exploring—there’s always more to learn.",
  "Curiosity turns problems into puzzles waiting to be solved.",
  "A mind that questions is a mind that grows.",
  "Curiosity fuels creativity.",
  "The greatest adventure is the pursuit of knowledge.",
  "A curious person sees learning as a lifelong journey.",
  "Curiosity is the best teacher.",
  "Never let routine kill your curiosity.",
  "Exploration is the road to understanding.",
  "If you're not curious, you're not truly alive.",
  "Curiosity creates paths where there were none before.",
  "The power of curiosity is the power to change the world.",
  "Every day is an opportunity to explore something new.",
  "Curiosity breaks down the barriers of ignorance.",
  "If you want to go far, start by asking questions.",
  "Curiosity makes the impossible possible.",
  "There is no failure in exploration—only learning.",
  "Explore not just the world, but also your own potential.",
  "Curiosity is the beginning of adventure.",
  "The world belongs to the curious and the bold.",
  "Exploration is never a waste of time.",
  "Curiosity keeps the mind forever young.",
  "To learn is to explore the unknown.",
  "Curiosity and courage go hand in hand.",
  "Questions are the seeds of discovery.",
  "Every question leads to another door of knowledge.",
  "To explore is to challenge the limits of possibility.",
  "Curiosity opens your mind to infinite possibilities.",
  "Great discoveries come from those who never stop wondering.",
  "Every problem has a solution waiting to be explored.",
  "The best discoveries happen outside your comfort zone.",
  "Curiosity is the mind's best adventure.",
  "Curiosity bridges the gap between ignorance and wisdom.",
  "Exploration leads to evolution.",
  "A life driven by curiosity is a life of fulfillment.",
  "Curiosity connects us to the wonders of the universe.",
  "The world is an endless puzzle—solve it with curiosity.",
  "A curious person never runs out of things to learn.",
  "Every journey begins with a single question.",
  "Curiosity makes life endlessly interesting.",
  "True exploration requires an open mind.",
  "Curiosity is the key to unlocking potential.",
  "The curious mind never stops seeking.",
  "To explore is to find new meaning in the familiar.",
  "A curious soul is a boundless soul.",
  "Exploration fuels innovation and creativity.",
  "Every day is an opportunity for a new discovery.",
  "Curiosity and imagination shape the future.",
  "The best explorers are those who refuse to settle for what they know.",
  "Learning is a lifelong adventure fueled by curiosity.",
  "Curiosity challenges the limits of knowledge.",
  "A curious mind finds wonder in everything.",
  "Explore your passions, and life will be an adventure.",
  "Curiosity transforms limitations into stepping stones.",
  "The world is full of mysteries waiting to be explored.",
  "Curiosity is the seed of every great achievement.",
  "The art of discovery lies in asking the right questions.",
  "There’s always more to explore—keep searching.",
  "Curiosity sees no boundaries.",
  "Be bold enough to ask the big questions.",
  "Discovery is the result of relentless curiosity.",
  "Curiosity fuels the engine of progress.",
  "The curious never stop learning, and the learners never stop growing.",
  "A question today can lead to a revolution tomorrow.",
  "Curiosity is the roadmap to possibility.",
  "Dare to explore the depths of your own potential.",
  "The journey of curiosity leads to limitless horizons.",
  "Curiosity is the gateway to infinite possibilities.",
  "An exploring mind is a thriving mind.",
  "Adventure and curiosity are two sides of the same coin.",
  "The world reveals its secrets to those who seek them.",
  "Every discovery begins with a single step into the unknown.",
  "Curiosity is the antidote to stagnation.",
  "The best journeys are those fueled by endless questions.",
  "Exploration is the spark that ignites progress.",
  "Curiosity is a powerful force that shapes the future.",
  "Nothing is beyond reach for a mind willing to explore.",
  "The universe is an open book for those who dare to read it.",
  "Curiosity leads us to truths we never imagined.",
  "Wondering is the first step toward knowing.",
  "Exploration isn't about the destination; it's about the journey.",
  "A curious heart sees adventure in the ordinary.",
  "The only limits are those we refuse to explore.",
  "Daring to ask is daring to learn.",
  "New horizons exist for those who seek them.",
  "Curiosity turns the impossible into the inevitable.",
  "Exploration starts with a simple ‘Why?’",
  "A questioning mind is never confined by boundaries.",
  "Every answer leads to another question.",
  "Discovery belongs to those who refuse to stop looking.",
  "Curiosity is the mother of all great ideas.",
  "The unknown is simply a world waiting to be explored.",
  "One question can change the course of history.",
  "To explore is to believe in endless possibilities.",
  "Curiosity breathes life into innovation.",
  "Never lose the wonder of a child’s curiosity.",
  "A world without curiosity is a world without progress.",
  "Exploration is proof that we are alive.",
  "Curiosity makes the ordinary extraordinary.",
  "With curiosity, every day is a new adventure.",
  "To seek is to expand the limits of reality.",
  "A curious mind sees beyond the obvious.",
  "Exploration is what keeps the human spirit alive.",
  "Curiosity transforms the familiar into the fascinating.",
  "The curious never stop discovering.",
  "If you want to understand the world, start exploring it.",
  "Exploration is the courage to step into the unknown.",
  "Curiosity is the secret ingredient of wisdom.",
  "Every great discovery starts with a spark of curiosity.",
  "Curiosity turns mistakes into lessons and failures into stepping stones.",
  "The greatest minds never stop questioning.",
  "Innovation is simply curiosity in action.",
  "Curiosity doesn’t kill—it creates.",
  "Knowledge begins with curiosity.",
  "Exploration is the natural instinct of an inquisitive soul.",
  "The road to discovery is paved with curiosity.",
  "The best discoveries often happen by accident—driven by curiosity.",
  "A world full of questions is a world full of possibilities.",
  "Curiosity is the beginning of every great achievement.",
  "Those who explore never run out of things to learn.",
  "Dare to wander, dare to wonder.",
  "Curiosity turns small ideas into great revolutions.",
  "Every mystery is an opportunity for discovery.",
  "Life is richer when you embrace the unknown.",
  "Curiosity builds bridges between what is and what could be.",
  "Keep exploring, for the world is full of surprises.",
  "Great things happen when curiosity meets determination.",
  "The best explorers never outgrow their sense of wonder.",
  "A life spent exploring is a life well lived.",
  "The mind that questions will always evolve.",
  "Exploration is an adventure into possibility.",
  "Every discovery once started as an unasked question.",
  "The joy of learning begins with curiosity.",
  "Dare to go beyond what you know.",
  "Curiosity is the driving force behind every great story.",
  "Exploring is about seeing the world through fresh eyes.",
  "What lies beyond the horizon is for the curious to find.",
];

final List<String> curiosityImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled curiosity quotes with random images.
final List<QuoteItem> curiosityQuotes = getShuffledQuotes(
  curiosityQuotesRaw,
  curiosityImages,
);
