import '../quotes_randomizer.dart';

/// **personal growth and development  Quotes & Images**
final List<String> growthQuotesRaw = [
  "Personal growth begins where your comfort zone ends.",
  "Every small step you take today shapes the person you become tomorrow.",
  "The key to self-improvement is consistency, not perfection.",
  "Growth is painful, but nothing is as painful as staying stuck.",
  "Your mindset determines your growth.",
  "The journey of self-improvement is endless and rewarding.",
  "The best investment you can make is in yourself.",
  "Learn to embrace failure—it’s the stepping stone to success.",
  "Every challenge you overcome strengthens your character.",
  "Be willing to grow even when it’s uncomfortable.",
  "Personal growth happens when you dare to do what scares you.",
  "You are always one decision away from a better version of yourself.",
  "The only way to truly grow is to keep learning.",
  "Your future self is created by what you do today.",
  "Strive for progress, not perfection.",
  "Change begins with self-awareness.",
  "Every lesson you learn adds value to your journey.",
  "Success is built on a foundation of continuous self-improvement.",
  "Growth requires effort, but staying stagnant costs more.",
  "The best way to predict your future is to create it.",
  "Personal growth is about becoming the best version of yourself.",
  "Small daily improvements lead to big results.",
  "Embrace change—it is the catalyst for personal growth.",
  "You are capable of more than you believe.",
  "Your habits shape your destiny.",
  "You grow when you push beyond your limits.",
  "Growth is about progress, not perfection.",
  "The more you learn, the more you grow.",
  "Self-discipline is the bridge between goals and achievement.",
  "Your struggles today are building your strength for tomorrow.",
  "Personal growth means learning to let go of what holds you back.",
  "Your potential is limitless when you commit to growth.",
  "Be patient with yourself—growth takes time.",
  "Fear is a sign that growth is near.",
  "You can’t grow if you don’t challenge yourself.",
  "Self-reflection is the key to personal growth.",
  "Make growth a daily habit.",
  "Failure is not the opposite of growth; it’s a part of it.",
  "Keep moving forward, even if progress is slow.",
  "The best way to grow is to keep pushing your boundaries.",
  "Every mistake is a lesson in disguise.",
  "Your growth journey is unique—embrace it.",
  "Never stop evolving into a better version of yourself.",
  "A positive mindset fuels personal development.",
  "Read, learn, and apply—that’s how you grow.",
  "Your comfort zone is the enemy of progress.",
  "You don’t grow when things are easy; you grow when you face challenges.",
  "Become a student of life and never stop learning.",
  "The road to personal growth is paved with self-discipline.",
  "Developing yourself is the first step to developing the world around you.",
  "Every experience, good or bad, contributes to your growth.",
  "Surround yourself with people who encourage your growth.",
  "Growth is a journey, not a destination.",
  "Your personal development is in your hands.",
  "Take responsibility for your growth—no one else will.",
  "The secret to success is continuous self-improvement.",
  "Your potential is only limited by your willingness to grow.",
  "Be intentional about your growth every day.",
  "Growth means stepping into the unknown with courage.",
  "You must outgrow who you were to become who you are meant to be.",
  "The greatest project you’ll ever work on is yourself.",
  "Commit to learning something new every day.",
  "Strength comes from pushing beyond your limits.",
  "Growth is the reward for perseverance.",
  "You either evolve or remain the same—the choice is yours.",
  "Life rewards those who seek personal growth.",
  "Every effort towards growth is a step towards success.",
  "You can always improve, no matter where you are in life.",
  "Setbacks are a sign that you're growing.",
  "Developing new skills is a path to endless opportunities.",
  "The more you invest in yourself, the more valuable you become.",
  "Growth happens when you get comfortable being uncomfortable.",
  "Learning from others accelerates your growth.",
  "Your thoughts shape your growth.",
  "Your personal growth inspires those around you.",
  "A growth mindset turns obstacles into opportunities.",
  "Reflect, improve, and grow daily.",
  "Learn from the past but don’t live in it.",
  "Becoming your best self is a lifelong journey.",
  "Challenge yourself daily to become better.",
  "True growth requires self-discipline.",
  "Don’t be afraid to reinvent yourself.",
  "Make progress your priority, not perfection.",
  "Your future depends on the actions you take today.",
  "Stay hungry for knowledge and self-improvement.",
  "The best way to grow is to step into discomfort.",
  "Every challenge is an opportunity to grow stronger.",
  "Find joy in the process of self-improvement.",
  "There is no finish line in personal growth.",
  "Growth requires action, not just intention.",
  "The journey of growth starts with a single step.",
  "Success comes from daily self-improvement.",
  "Make personal growth a daily priority.",
  "The more you grow, the more you can contribute to others.",
  "A commitment to growth is a commitment to success.",
  "Self-improvement is the key to unlocking your potential.",
  "Each day is a new chance to improve yourself.",
  "You are never too old to learn something new.",
  "Growth is about learning, unlearning, and relearning.",
  "Master yourself, and you can master anything.",
  "Your growth is in your control—own it.",
  "The journey of growth is never wasted.",
  "Your struggles shape your strength.",
  "If you’re not growing, you’re standing still.",
  "Your greatest investment is in your personal development.",
  "Transform your challenges into lessons for growth.",
  "Effort and persistence fuel personal growth.",
  "Embrace failure as a stepping stone to growth.",
  "You can grow at any age and at any stage.",
  "Self-improvement leads to self-empowerment.",
  "Be open to feedback—it accelerates growth.",
  "Small changes create big transformations.",
  "You are your greatest asset—invest in yourself.",
  "Growth requires taking risks and embracing change.",
  "The road to success is paved with personal growth.",
  "Growth comes when you challenge yourself daily.",
  "Your mindset is the foundation of your development.",
  "Success starts with self-discipline and persistence.",
  "Your personal growth benefits everyone around you.",
  "Take small steps every day to become better.",
  "Great things come from pushing past your limits.",
  "Growth happens outside of your comfort zone.",
  "Reflect on your journey, but keep moving forward.",
  "Who you become is more important than what you achieve.",
  "The best version of yourself is waiting to be created.",
  "Invest in your mind—it’s your greatest asset.",
  "You are a work in progress—keep building yourself.",
  "Personal growth transforms every area of your life.",
  "The only way to improve your life is to improve yourself.",
  "Great success is built on personal growth.",
  "Never stop striving to be a better version of yourself.",
  "The road to mastery starts with self-discipline.",
  "Growth is a choice—make it daily.",
  "Evolve into the person you were meant to be.",
  "Growth begins the moment you decide to improve yourself.",
  "A better you starts with a single step forward.",
  "Personal growth is a lifelong journey, not a destination.",
  "Success comes to those who never stop learning.",
  "Small changes today lead to big transformations tomorrow.",
  "You don’t have to be perfect, just better than yesterday.",
  "Growth is about progress, not perfection.",
  "The best way to grow is to challenge yourself daily.",
  "Discomfort is a sign that you are growing.",
  "Your actions today define your future self.",
  "True growth starts with self-reflection.",
  "Personal development is the key to unlocking your potential.",
  "Every setback is an opportunity for a comeback.",
  "Growth is choosing courage over comfort.",
  "Feed your mind with knowledge, and watch yourself grow.",
  "You can’t change the past, but you can shape your future.",
  "Believe in your ability to evolve into something greater.",
  "Step outside your comfort zone and watch yourself transform.",
  "The person you become is shaped by the habits you build.",
  "Your greatest competition is who you were yesterday.",
  "Invest in yourself; it pays the highest dividends.",
  "The road to success is built on continuous self-improvement.",
  "Failure is just another step toward personal growth.",
  "Your mindset determines your progress in life.",
  "The biggest room in the world is the room for improvement.",
  "Be patient with yourself—growth takes time.",
  "Life’s challenges exist to help you grow stronger.",
  "The key to personal growth is lifelong curiosity.",
  "You grow when you push beyond your limits.",
  "Surround yourself with people who inspire you to grow.",
  "Growth happens one step at a time—just keep moving.",
  "Transformation begins the moment you commit to change.",
  "You are always a work in progress, and that’s okay.",
  "Self-improvement is about persistence, not perfection.",
  "Your journey of growth is unique—embrace it.",
  "Learn from every experience, good or bad.",
  "The only failure is the failure to learn and grow.",
  "You are never too old to become a better version of yourself.",
  "Growth is the result of daily commitment and discipline.",
  "Your potential is limitless—keep striving for more.",
  "Take risks; personal growth lives outside your comfort zone.",
  "Keep learning, keep improving, keep growing.",
  "Your greatest achievements start with personal growth.",
  "The secret to success is a commitment to self-development.",
  "Growth isn’t about speed; it’s about consistency.",
  "Self-discipline is the fuel for personal transformation.",
  "Focus on progress, not perfection, and success will follow.",
  "Become the person you needed when you were younger.",
  "The best way to grow is to never stop questioning and learning.",
];

final List<String> growthImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled perseverance quotes with random images.
final List<QuoteItem> growthQuotes = getShuffledQuotes(
  growthQuotesRaw,
  growthImages,
);
