import '../quotes_randomizer.dart';

/// **Knowledge & Education Quotes & Images**

final List<String> knowledgeQuotesRaw = [
  "Knowledge is the foundation of progress.",
  "Education is the most powerful tool to change the world.",
  "A curious mind is a growing mind.",
  "Learning is a journey that never ends.",
  "The more you know, the more you grow.",
  "Knowledge without application is wasted potential.",
  "Education is the passport to a brighter future.",
  "Wisdom comes from both learning and experience.",
  "A book is a doorway to infinite knowledge.",
  "Curiosity is the spark that ignites lifelong learning.",
  "An educated mind sees opportunities where others see obstacles.",
  "Every lesson learned is a step toward wisdom.",
  "Knowledge is not just power; it is freedom.",
  "Education opens doors that ignorance keeps closed.",
  "A mind once expanded by knowledge can never shrink back.",
  "The pursuit of knowledge is the pursuit of excellence.",
  "Never stop learning, for life never stops teaching.",
  "Education is the best investment with the highest return.",
  "True knowledge comes from questioning everything.",
  "The roots of education are bitter, but the fruit is sweet.",
  "A wise person knows that learning is a lifelong process.",
  "Knowledge is the key to unlocking potential.",
  "Education is not preparation for life; it is life itself.",
  "A strong foundation in knowledge leads to a stable future.",
  "The best teachers show you where to look but not what to see.",
  "Reading is to the mind what exercise is to the body.",
  "Knowledge empowers people to make informed decisions.",
  "An educated person knows how much they don’t know.",
  "The more we share knowledge, the more it grows.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "An investment in knowledge always pays the best interest.",
  "Education is the movement from darkness to light.",
  "Ignorance is expensive; knowledge is priceless.",
  "The first step to wisdom is knowing that you know nothing.",
  "Every expert was once a beginner.",
  "Learning never exhausts the mind, but ignorance does.",
  "Knowledge is the cure for fear and uncertainty.",
  "Education is the foundation of every strong society.",
  "The pursuit of knowledge is a never-ending adventure.",
  "Reading a book is like having a conversation with the greatest minds.",
  "Education is the gateway to endless possibilities.",
  "An open mind is a mind ready to be filled with wisdom.",
  "True education teaches how to think, not what to think.",
  "The greatest enemy of knowledge is the illusion of knowing.",
  "Every teacher plants the seeds of future generations.",
  "The joy of learning is a gift that keeps giving.",
  "Wisdom begins in wonder and curiosity.",
  "A well-educated mind is the best defense against manipulation.",
  "Education breeds confidence; confidence breeds success.",
  "Your knowledge determines your destiny.",
  "Curiosity fuels the fire of education.",
  "Knowledge shared is knowledge multiplied.",
  "Education is the best legacy one can leave behind.",
  "Learning from failure is as important as learning from success.",
  "Those who keep learning, keep rising.",
  "A well-read person sees the world differently.",
  "The more you learn, the more valuable you become.",
  "A book in hand is a future in motion.",
  "Teachers change the world one student at a time.",
  "An educated society is a prosperous society.",
  "Learning is the art of growing wiser with each experience.",
  "Education is the tool that turns dreams into reality.",
  "Your knowledge is your greatest asset.",
  "Never stop learning; never stop evolving.",
  "Great leaders are lifelong learners.",
  "Education is a journey, not a destination.",
  "Ignorance is a voluntary misfortune.",
  "A library is a treasure chest of knowledge.",
  "The power of education lies in its ability to transform lives.",
  "True wisdom is the ability to apply knowledge effectively.",
  "Knowledge is a ladder that helps us reach new heights.",
  "Learn something new every day to keep your mind sharp.",
  "Education is the foundation of innovation and progress.",
  "Your brain is like a muscle—the more you use it, the stronger it gets.",
  "A well-informed mind is a powerful tool for change.",
  "The gift of knowledge is one that lasts a lifetime.",
  "Learning gives you the wings to soar beyond limitations.",
  "A strong education builds a strong future.",
  "Books are the bridges that connect us to knowledge.",
  "Education is the great equalizer in society.",
  "Knowledge is the light that dispels the darkness of ignorance.",
  "An inquisitive mind is never truly old.",
  "Lifelong learning is the secret to staying relevant.",
  "The most valuable treasures are found in books and experience.",
  "To learn is to empower oneself for the future.",
  "Wisdom is not having all the answers, but knowing where to find them.",
  "A hunger for knowledge leads to endless opportunities.",
  "An educated person can turn challenges into opportunities.",
  "Education is a flame that, once lit, never fades.",
  "Knowledge is the bridge between dreams and reality.",
  "Reading expands your mind and your world.",
  "Learning is the essence of human progress.",
  "Education turns information into transformation.",
  "A thirst for knowledge is never truly quenched.",
  "The seeds of knowledge bear the fruit of wisdom.",
  "A curious mind leads to a knowledgeable life.",
  "Success is built on a foundation of knowledge.",
  "The only true failure in life is the failure to learn.",
  "When you stop learning, you stop growing.",
  "A society that values education is a society that thrives.",
  "Knowledge is the fire that fuels innovation.",
  "To educate is to liberate the mind from ignorance.",
  "Education transforms obstacles into stepping stones.",
  "Every great achievement begins with the pursuit of knowledge.",
  "A curious mind is a key to unlocking new possibilities.",
  "The beauty of learning is that it never ends.",
  "Education builds the confidence to chase your dreams.",
  "The more you know, the less you fear.",
  "Every book read is a step towards a better future.",
  "Lifelong learning keeps the spirit youthful.",
  "Knowledge is not just about facts, but understanding and wisdom.",
  "To seek knowledge is to seek a better life.",
  "Education fuels the engine of innovation.",
  "The best way to learn is to teach others.",
  "A well-educated person values the pursuit of truth.",
  "Education is the bridge between ignorance and wisdom.",
  "A teacher’s influence lasts a lifetime.",
  "An educated world is a better world.",
  "Those who seek knowledge never stop growing.",
  "The love of learning is the foundation of wisdom.",
  "Books are the quietest and most reliable teachers.",
  "True education is learning how to learn.",
  "Knowledge is the fuel for progress.",
  "The more you read, the more you understand the world.",
  "Education is a treasure no thief can steal.",
  "Learning expands the mind and enriches the soul.",
  "Education is the foundation upon which we build our future.",
  "Curiosity is the first step toward wisdom.",
  "Reading is a superpower that unlocks knowledge.",
  "Education is the golden key to opportunity.",
  "A wise person never stops seeking knowledge.",
  "Knowledge is the foundation of wisdom.",
  "An educated mind can solve the world's greatest problems.",
  "Education is the bridge between ignorance and understanding.",
  "The pursuit of knowledge is a lifelong adventure.",
  "A well-educated mind is a mind prepared for the future.",
  "Books open doors to worlds yet unseen.",
  "Learning is the art of growing without limits.",
  "The roots of knowledge run deep and strong.",
  "Wisdom begins when curiosity is nurtured.",
  "Every lesson learned shapes a brighter tomorrow.",
  "Education is the light that eliminates darkness.",
  "A thirst for knowledge leads to endless discoveries.",
  "Reading is the passport to infinite knowledge.",
  "Knowledge is a treasure that grows when shared.",
  "A well-informed mind is a mind that can make a difference.",
  "Education is the foundation of a thriving society.",
  "With education, opportunities become limitless.",
  "Knowledge is not just power—it is freedom.",
  "An open mind is a growing mind.",
  "To educate oneself is to empower oneself.",
  "Books are the silent teachers of the wise.",
  "Every question leads to new knowledge.",
  "The value of education lies in its ability to transform lives.",
  "True intelligence is the ability to learn from every experience.",
  "A library is a sanctuary of knowledge.",
  "Education sharpens the mind and strengthens the soul.",
  "The path to wisdom is paved with curiosity.",
  "Knowledge grows when curiosity is encouraged.",
  "An investment in education pays dividends for life.",
  "Ignorance fades in the presence of knowledge.",
  "A love for learning is the key to boundless success.",
  "The power of knowledge is the power to change the world.",
  "A wise person seeks to learn from every opportunity.",
  "Education is a tool that builds a better tomorrow.",
  "To seek knowledge is to seek the keys to success.",
  "True knowledge is knowing how much there is to learn.",
  "A single book can change a lifetime.",
  "Knowledge empowers individuals and strengthens communities.",
  "Education fuels progress and innovation.",
  "To read is to embark on a journey of discovery.",
  "Wisdom comes from knowledge, but also from experience.",
  "A classroom is where dreams begin to take shape.",
  "The pursuit of knowledge is never in vain.",
  "Education is the compass that guides us to new horizons.",
  "A day without learning is a day wasted.",
  "Knowledge is the currency of the future.",
  "The beauty of knowledge is that it knows no bounds.",
  "The best investment is in the education of the mind.",
  "Education transforms obstacles into opportunities.",
  "A mind enriched with knowledge is a mind prepared for success.",
  "Education is the foundation upon which we build our future.",
  "A curious mind is the beginning of all wisdom.",
  "Knowledge is a light that never dims.",
  "The true purpose of education is to open the mind, not fill it.",
  "A love for learning is the key to unlocking potential.",
  "The best teachers inspire their students to think for themselves.",
  "Every bit of knowledge gained is a step towards success.",
  "The journey of learning never truly ends.",
  "Education gives you the wings to fly towards your dreams.",
  "The beauty of learning is that it enriches both the giver and the receiver.",
  "Knowledge is the only wealth that grows when shared.",
  "Education fuels imagination and turns ideas into reality.",
  "A teacher's influence can last a lifetime.",
  "Ignorance is defeated the moment we decide to learn.",
  "The classroom is where the seeds of greatness are planted.",
  "The best way to predict the future is to learn and create it.",
  "Education shapes not just minds, but entire generations.",
  "Wisdom comes from questioning, observing, and applying knowledge.",
  "Reading is the key to unlocking new perspectives.",
  "An educated person knows how to think, not just what to think.",
  "The world belongs to those who never stop learning.",
  "Every book holds a lesson waiting to be discovered.",
  "Education is the silent force that changes lives.",
  "Knowledge is the foundation of a strong character.",
  "A true scholar remains a student for life.",
  "The best way to grow is to seek knowledge relentlessly.",
  "A single spark of curiosity can ignite a lifetime of learning.",
  "A well-educated mind can turn obstacles into opportunities.",
  "Learning is the bridge between dreams and reality.",
  "With knowledge, even the impossible becomes possible.",
  "Education doesn't just teach facts—it teaches how to think.",
  "One good book can change your entire perspective on life.",
  "Education is the master key that unlocks countless doors.",
  "A day spent learning is never a day wasted.",
  "The more you learn, the more you understand the world.",
  "Education is the cornerstone of progress and innovation.",
  "Never stop asking questions—curiosity fuels intelligence.",
  "Knowledge is the most valuable gift you can give yourself.",
  "Education builds confidence, and confidence leads to success.",
  "Books contain the wisdom of centuries, waiting to be explored.",
  "The best investment you can make is in your own education.",
  "A well-read person is never truly alone.",
  "Every great leader is a lifelong learner.",
  "Education is a journey, not a destination.",
  "A child's mind is like a sponge—fill it with wisdom and curiosity.",
  "To learn is to grow, and to grow is to succeed.",
  "Those who embrace education embrace endless possibilities.",
  "A well-informed society is a powerful society.",
  "The pursuit of knowledge is the noblest adventure.",
  "The greatest minds never stop questioning and learning.",
];

final List<String> knowledgeImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

final List<QuoteItem> knowledgeQuotes = getShuffledQuotes(
  knowledgeQuotesRaw,
  knowledgeImages,
);
