import '../quotes_randomizer.dart';

/// **Learning from Failure Quotes & Images**
final List<String> learningQuotesRaw = [
  "Failure is the first step toward success.",
  "Every mistake is a lesson in disguise.",
  "Success is built on the foundation of past failures.",
  "Failure is proof that you are trying.",
  "The only real failure is the failure to learn.",
  "Mistakes are the stepping stones to achievement.",
  "Failure is the opportunity to begin again, this time more wisely.",
  "A setback is a setup for a comeback.",
  "Great success is often preceded by great failure.",
  "Embrace failure as part of the learning process.",
  "Failure teaches resilience and builds character.",
  "Each failure brings you closer to success.",
  "The road to success is paved with failures.",
  "Fail fast, learn faster.",
  "You never lose—you either win or learn.",
  "Failure is a teacher, not a judge.",
  "Mistakes are proof that you are growing.",
  "Failure is feedback in disguise.",
  "The greatest lessons come from the hardest falls.",
  "Don't fear failure; fear not trying.",
  "The only way to avoid failure is to stop trying.",
  "Failure makes success taste sweeter.",
  "Success is failure turned inside out.",
  "A failed attempt is better than no attempt at all.",
  "Those who fail the most, learn the most.",
  "Growth begins at the edge of failure.",
  "Don't let failure define you; let it refine you.",
  "Your failures are just plot twists in your success story.",
  "Behind every success story are countless failures.",
  "Learn from failure and let it fuel your progress.",
  "Even the best fall before they rise.",
  "Failure is simply a redirection to something better.",
  "Turn your failures into stepping stones.",
  "Every failure brings new wisdom.",
  "Struggle and failure build resilience.",
  "If you haven't failed, you haven't tried hard enough.",
  "Don't dwell on failure; extract the lesson and move forward.",
  "Failure is not fatal; quitting is.",
  "The only thing worse than failing is not learning from it.",
  "Failure humbles the proud and strengthens the determined.",
  "Embrace failure as a necessary part of growth.",
  "A champion is someone who gets up even after failing.",
  "The most successful people have failed the most times.",
  "Your failures shape your future victories.",
  "Every failure is an opportunity in disguise.",
  "Failure is the training ground for success.",
  "It's not about avoiding failure; it's about learning from it.",
  "Failure is not falling down but staying down.",
  "Great minds learn from failure, small minds fear it.",
  "Without failure, there is no innovation.",
  "Failure prepares you for the challenges ahead.",
  "The best way to deal with failure is to use it as fuel.",
  "Mistakes are temporary; lessons last forever.",
  "The pain of failure is temporary, but the lesson is permanent.",
  "A failed plan is better than no plan at all.",
  "Success is built on persistence, not perfection.",
  "Failure is the tuition you pay for experience.",
  "Failure is an invitation to try again with more wisdom.",
  "To fail is to gain insight.",
  "You are not your failures; you are your perseverance.",
  "Fall seven times, stand up eight.",
  "Success is a collection of corrected failures.",
  "Failure is the bridge between dreaming and achieving.",
  "Failure teaches us things success never could.",
  "Courage is trying again after failure.",
  "A stumble is not the end of the journey.",
  "Every failure is a bruise, not a tattoo.",
  "One failure doesn’t define your future.",
  "Failures today create the wisdom of tomorrow.",
  "Success begins when you learn from failure.",
  "Let failure teach you, not defeat you.",
  "Failure is a gift wrapped in disappointment.",
  "Mistakes show us where to improve.",
  "Don't be ashamed of failure—be proud of growth.",
  "Failure only hurts if you refuse to learn.",
  "See failure as an adventure, not a disaster.",
  "Even failure moves you forward.",
  "The only true failure is giving up.",
  "Failure isn't the opposite of success; it's part of it.",
  "The best leaders were once the biggest failures.",
  "Your failures are your greatest mentors.",
  "If you fail, fail forward.",
  "Don't avoid failure; embrace its lessons.",
  "Failures prepare us for greater things ahead.",
  "Perseverance turns failure into progress.",
  "Mistakes make the best teachers.",
  "Turn failures into fuel for your dreams.",
  "Every failure builds your story.",
  "The road to success has many detours.",
  "Success is a staircase built with failures.",
  "Failure shapes you into who you are meant to be.",
  "Fear of failure is worse than failure itself.",
  "Behind every failure is a lesson waiting to be learned.",
  "Failure is proof that you dared to try.",
  "You can't appreciate success without failure.",
  "Be brave enough to fail, and wise enough to learn.",
  "Never waste a failure—study it.",
  "Failure isn't falling behind; it's a step forward.",
  "The more you fail, the stronger you become.",
  "Failure is a sign you're pushing limits.",
  "Don’t hide from failure—use it to grow.",
  "Failure is a comma, not a period.",
  "Mistakes don't define you; how you respond to them does.",
  "Every master was once a beginner who failed.",
  "The strongest people are shaped by their failures.",
  "Failure leads to reinvention.",
  "Struggles today build strength for tomorrow.",
  "The key to success is failing fast and learning faster.",
  "A failure is an unfinished chapter, not the end of the book.",
  "Success is built on countless setbacks.",
  "Failure helps you understand what doesn't work.",
  "Each failure is a rehearsal for success.",
  "Failure can break you or build you—choose to build.",
  "The best lessons come from the hardest failures.",
  "A failed attempt is not a wasted attempt.",
  "Without failure, growth would be impossible.",
  "The only way to truly fail is to give up.",
  "Failure is a reminder that you're pushing boundaries.",
  "Use failure as a tool, not a trap.",
  "Failing is just proof that you're trying new things.",
  "Even the darkest failures have silver linings.",
  "Success and failure are just different chapters of the same book.",
  "You can't change the past, but you can learn from it.",
  "Growth comes from discomfort and failure.",
  "Failure is the best personal trainer.",
  "Each failure is a brick in the foundation of success.",
  "Failure is a test of perseverance.",
  "If you’ve never failed, you’ve never tried anything new.",
  "You grow the most from your biggest failures.",
  "Failure is a pause, not a stop.",
  "Learn from your failures, and they become victories.",
  "Failure strengthens those who refuse to quit.",
  "Failures are the blueprints of innovation.",
  "A life without failure is a life without growth.",
  "Failure is proof that you're striving for something better.",
  "The courage to fail is the courage to succeed.",
  "The bigger the failure, the bigger the comeback.",
  "Every setback is a setup for a greater leap forward.",
  "Failure is the tuition you pay for success.",
  "The only real mistake is the one from which we learn nothing.",
  "Failure is not the opposite of success; it’s a part of success.",
  "The key to success is to fail quickly and learn from it.",
  "Your failures are just experiments on the road to greatness.",
  "Every failure removes one wrong path from your journey.",
  "Failure is a bruise, not a tattoo.",
  "The lessons learned from failure last longer than the sting of defeat.",
  "Growth happens when you turn failure into wisdom.",
  "Failure is simply a detour on the road to achievement.",
  "Mistakes are proof that you’re making an effort.",
  "Failure gives you the experience that textbooks never can.",
  "The road to success is paved with well-learned failures.",
  "Fail often, fail forward, but never fail to learn.",
  "Great things come to those who are willing to fail and try again.",
  "The courage to fail is the first step toward greatness.",
  "The strongest people are built from their toughest failures.",
  "Failure refines, strengthens, and prepares you for success.",
  "If you're afraid to fail, you'll never reach your full potential.",
  "A lesson learned from failure is a step toward victory.",
  "Success is simply failure with a better plan.",
  "What you learn from failure is more valuable than the failure itself.",
  "Every failure is a new beginning, not the end.",
  "You never fail—you either succeed or you learn.",
  "Failure is only wasted if you refuse to learn from it.",
  "Small failures prepare you for big wins.",
  "Failure forces you to discover your true strengths.",
  "Don't let a stumble in the road end your journey.",
  "Failure is a test of how badly you want success.",
  "Each failure makes your next attempt stronger.",
  "Success is built by stacking failures into stepping stones.",
  "If you’ve never failed, you’ve never taken a risk worth taking.",
  "The road to mastery is paved with lessons from failure.",
  "A single failure doesn’t define you, but your response to it does.",
  "Failure isn’t about falling down; it’s about getting up stronger.",
  "Great inventions are born from the lessons of failure.",
  "A mistake is only a mistake if you don’t learn from it.",
  "You are not your failures—you are your resilience.",
  "Don’t fear failure—fear never trying at all.",
  "Failure is the universe’s way of pointing you toward a better path.",
  "The most successful people are those who failed the most.",
  "Failure is not losing; failure is refusing to learn.",
  "Without failure, progress would be impossible.",
  "Failure is the shadow that highlights success.",
  "Mistakes refine us, not define us.",
  "Turn your failures into the foundation of your success.",
  "Failure is an invitation to grow beyond your limits.",
  "Your greatest teacher is the failure you rise from.",
  "Failure is just the beginning of a new opportunity.",
  "Sometimes, failure is the push you need to find a better way.",
];

final List<String> learningImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled learning from failure quotes with random images.
final List<QuoteItem> learningQuotes = getShuffledQuotes(
  learningQuotesRaw,
  learningImages,
);
