import '../quotes_randomizer.dart';

/// **Living in the Present Quotes & Images**
final List<String> presentQuotesRaw = [
  "Live in the moment, for the moment is all we have.",
  "The past is gone, the future is uncertain, but today is a gift.",
  "Happiness is found in the here and now.",
  "Be where you are, not where you were or where you wish to be.",
  "Today is the only day that truly belongs to you.",
  "The present moment is where life truly happens.",
  "Don’t dwell on the past or stress about the future; embrace the now.",
  "Enjoy the little things, for one day you may look back and realize they were the big things.",
  "Life is happening now—don’t miss it by worrying about what’s next.",
  "Peace is found in the present, not in regret or anticipation.",
  "The secret to happiness is being fully engaged in the present moment.",
  "The best way to prepare for the future is to fully experience today.",
  "You don’t need to rush—just breathe and be.",
  "Every moment is a new beginning, a fresh start.",
  "Let go of what was, and embrace what is.",
  "Mindfulness is the key to unlocking the beauty of the present.",
  "Life is too short to spend it anywhere but here and now.",
  "The power of now is the greatest power you hold.",
  "Every second you spend worrying is a second you lose living.",
  "Give yourself the gift of the present moment.",
  "You can’t change the past, but you can shape the present.",
  "True joy is found in appreciating the moment.",
  "Don’t let tomorrow’s worries steal today’s peace.",
  "The more present you are, the more alive you feel.",
  "Stop chasing the future and start embracing the now.",
  "Each breath is a reminder to live fully in the moment.",
  "Right now is the only place life exists.",
  "Be present in all things, and happiness will follow.",
  "The beauty of life is in its fleeting moments—cherish them.",
  "You are not your past or your future; you are this moment.",
  "Take life one moment at a time.",
  "The present moment is your greatest opportunity.",
  "Life unfolds in the now, not in yesterday or tomorrow.",
  "Don’t let your mind wander too far from where you are.",
  "Focus on what you can do now, not on what you should have done.",
  "Presence is the foundation of a meaningful life.",
  "Now is the perfect time to be happy.",
  "Today is a new canvas—paint it with presence.",
  "Time is precious; don’t waste it dwelling elsewhere.",
  "Life isn’t in the past or future—it’s in the breath you take now.",
  "Live each day as if it’s your first and last.",
  "Moments make up a lifetime—don’t let them slip away unnoticed.",
  "Regret and worry are thieves of the present.",
  "Enjoy the journey, not just the destination.",
  "Find joy in the simplicity of the present moment.",
  "The present is the only moment you can truly control.",
  "When you live fully in the now, you live fully in joy.",
  "Presence is the greatest present you can give yourself.",
  "Live in such a way that each moment is meaningful.",
  "What you do now shapes who you become.",
  "Every moment holds something to be grateful for.",
  "Don’t let life pass you by while you wait for the ‘perfect’ time.",
  "Life is not a race; enjoy each step of the way.",
  "Be present in your own story.",
  "The best memories are made when you are fully present.",
  "Living in the moment creates a richer, fuller life.",
  "Yesterday is history, tomorrow is a mystery, but today is a gift.",
  "Let today be enough.",
  "When you stop worrying about the future, you start living in the present.",
  "Every moment matters—make the most of it.",
  "Your real life is happening now.",
  "Savor the moment before it becomes a memory.",
  "Pause. Breathe. Enjoy the present.",
  "This moment is where happiness begins.",
  "The past has no power over the present unless you let it.",
  "When you focus on the now, you release the weight of the past.",
  "The most beautiful moments in life happen unexpectedly.",
  "What you do today determines your tomorrow.",
  "If you always live for tomorrow, you’ll miss today.",
  "The mind is at peace when it stays in the present.",
  "Embrace where you are, not where you wish you were.",
  "Make every moment a masterpiece.",
  "Live life like it’s your last day—but also your first.",
  "When you let go of distractions, you gain clarity.",
  "Gratitude grows when you focus on the present.",
  "Nothing is more valuable than your time—use it wisely.",
  "You deserve to enjoy the present, not just endure it.",
  "Life is a collection of moments—make them count.",
  "Stop waiting for the right time—now is the right time.",
  "The future is made of the choices you make now.",
  "Being present is the key to experiencing life deeply.",
  "Joy exists in the now, not in the ‘someday.’",
  "Stop searching for happiness and start living it.",
  "Live for today, plan for tomorrow, and learn from yesterday.",
  "The happiest people make the most of every moment.",
  "Right now is a miracle—don’t overlook it.",
  "Love and laughter are best shared in the present.",
  "Be present in your relationships; they are life’s true treasures.",
  "Your future self will thank you for living fully today.",
  "Tomorrow’s peace starts with today’s presence.",
  "The more you enjoy today, the better your tomorrows become.",
  "Life’s greatest moments happen when you least expect them.",
  "Find stillness in the present, and you’ll find peace.",
  "No amount of regret can change the past; no amount of anxiety can change the future.",
  "Enjoy today, because yesterday is gone and tomorrow isn’t promised.",
  "What if today was the best day of your life?",
  "Presence turns ordinary moments into extraordinary ones.",
  "Your greatest power is in the choices you make right now.",
  "Don’t rush through life—slow down and savor each moment.",
  "Be where your feet are.",
  "Living in the now frees you from the weight of time.",
  "Presence brings clarity, joy, and peace.",
  "You are not behind; you are exactly where you need to be.",
  "Your most precious memories will be made in the present.",
  "Now is the only time that truly belongs to you.",
  "Your time is your life—spend it wisely.",
  "The best way to live is to love the moment you’re in.",
  "Be fully awake to the gift of today.",
  "Time is fleeting—live each second with intention.",
  "You don’t find happiness; you create it in the present.",
  "Make the most of this moment—it will never come again.",
  "Now is the moment you’ve been waiting for.",
  "Stop and savor the moment before it becomes a memory.",
  "Each day is a fresh page—write your story with presence.",
  "You can’t relive the past or predict the future, but you can embrace now.",
  "Living in the moment makes the simplest things feel extraordinary.",
  "Let go of the past, breathe in the present, and step into the now.",
  "Your peace lives in the present, not in regrets or worries.",
  "Slow down and let today unfold in its own time.",
  "Be present with people, not just physically but emotionally.",
  "Life happens between the plans—enjoy the in-between moments.",
  "True happiness is not a destination, but a state of being in the now.",
  "Right now is where your power lies.",
  "You don’t need a perfect moment; you just need to be present in it.",
  "Live your life, not your worries.",
  "Be so focused on the moment that time feels irrelevant.",
  "The sun shines in the present, not in the memories of yesterday.",
  "Today is a chance to start again—make it count.",
  "There is no joy in reliving the past, but endless joy in experiencing the now.",
  "Presence is the antidote to regret.",
  "Worrying about the future won’t change it—being present will shape it.",
  "Stop chasing time; start embracing now.",
  "The more present you are, the richer life becomes.",
  "A mindful life is a meaningful life.",
  "The magic of life is found in the moments we fully experience.",
  "Your best self exists in this very moment.",
  "Every second you live in the present is a victory over time.",
  "Give your mind a break—just be here, now.",
  "Find wonder in the ordinary, and every moment becomes extraordinary.",
  "The best use of time is to truly live in it.",
  "Let today be enough, just as it is.",
  "The present moment is a gift—open it with gratitude.",
  "Your happiness is waiting for you in the now.",
  "Be mindful of your steps, for they create the journey.",
  "The now is where your soul dances freely.",
  "Appreciate what’s in front of you before it becomes what you miss.",
  "Right now is the only time that truly belongs to you.",
  "Wherever you are, be fully there.",
  "Living in the moment means embracing life as it unfolds.",
  "Don’t just go through life—experience it.",
  "What you have today is more than enough if you truly see it.",
  "Let go of the ‘what ifs’ and embrace ‘what is.’",
  "You won’t find happiness in the past or future, only in the present.",
  "This moment is precious; don’t trade it for distractions.",
  "Your breath is a reminder to live in the now.",
  "When you stop waiting for the right moment, you realize every moment is right.",
  "You don’t need to know what’s next to enjoy what’s now.",
  "Notice the beauty that exists in this moment.",
  "The simplest joys are found in being fully present.",
  "Don’t let the rush of life steal the peace of the present.",
  "The best things happen when you stop waiting and start living.",
  "Life is happening in this second—don’t miss it.",
  "The key to happiness is to love where you are, as you are.",
  "The past is a lesson, the future is a dream, but today is a reality.",
  "Be where your feet are, and your heart will follow.",
  "Make today so amazing that yesterday gets jealous.",
  "Presence is the path to true fulfillment.",
  "Breathe deeply, live presently, love fully.",
  "Every moment is an opportunity to be fully alive.",
  "Forget about yesterday and stop worrying about tomorrow—today needs you.",
  "You are most powerful when you are fully in the present.",
  "Enjoy the moment before it turns into a memory.",
  "The only time you can truly experience is now.",
  "When you’re truly present, even the ordinary feels magical.",
  "A life lived in the present is a life truly lived.",
  "Give your heart to the present, and joy will follow.",
  "Tomorrow is shaped by how you live today.",
  "You don’t need to rush to the next thing—this moment is enough.",
  "Appreciate the now before it becomes a then.",
  "Don’t just exist—be truly alive in the moment.",
  "Let go of distractions and focus on what matters right now.",
  "Happiness grows where presence is planted.",
  "Every second you live mindfully is a second well spent.",
  "Pause. Smile. Absorb this moment.",
  "Living in the present is the secret to a life well-lived.",
  "Life slows down when you focus on the now.",
  "Don’t wait for happiness—find it in this very breath.",
  "Right now is the most important moment of your life.",
  "The moment you truly live is the moment you truly feel.",
  "Worry steals today’s joy and gives nothing in return.",
  "Time is best spent being present, not being busy.",
  "The present is where life’s true treasures are found.",
  "Joy doesn’t come from planning the future, but from living the present.",
  "Instead of counting days, make the days count.",
  "The present is the only place where love, peace, and happiness exist.",
  "Every moment lived with presence adds depth to life.",
  "Your mind finds peace when it stays in the now.",
  "Being present turns routine moments into sacred ones.",
  "A fulfilling life is built on fully lived moments.",
];

final List<String> presentImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled living in the present quotes with random images.
final List<QuoteItem> presentQuotes = getShuffledQuotes(
  presentQuotesRaw,
  presentImages,
);
