import '../quotes_randomizer.dart';

/// **the art of teaching Quotes & Images**
final List<String> teachingQuotesRaw = [
  "Teaching is not about information. It's about inspiration.",
  "A good teacher can inspire hope, ignite imagination, and instill a love for learning.",
  "The best teachers teach from the heart, not from the book.",
  "Education is not the filling of a pail, but the lighting of a fire.",
  "Teachers plant the seeds of knowledge that grow forever.",
  "A teacher affects eternity; they can never tell where their influence stops.",
  "To teach is to touch a life forever.",
  "The best teachers are those who show you where to look but don’t tell you what to see.",
  "Teaching is the greatest act of optimism.",
  "A great teacher takes a hand, opens a mind, and touches a heart.",
  "Good teaching is more a giving of right questions than a giving of right answers.",
  "The art of teaching is the art of assisting discovery.",
  "The influence of a great teacher can never be erased.",
  "A teacher's purpose is not to create students in their own image, but to develop students who can create their own.",
  "Great teachers don’t just teach, they make learning an adventure.",
  "The best teachers are those who help their students become their best selves.",
  "Teaching is the profession that teaches all other professions.",
  "Teaching is about creating an environment where curiosity can flourish.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "Every teacher is a student, and every student is a teacher.",
  "A teacher’s job is to take a bunch of live wires and make sure they are well-grounded.",
  "A good teacher knows how to bring out the best in students.",
  "Education is not preparation for life; education is life itself.",
  "Good teachers introduce new ideas; great teachers empower students to create their own.",
  "The greatest teachers are those who can turn mistakes into lessons and lessons into opportunities.",
  "Teaching is more than imparting knowledge; it is inspiring change.",
  "A truly great teacher makes learning irresistible.",
  "The art of teaching is understanding that every student learns differently.",
  "A great teacher does not teach facts, they teach how to think.",
  "Effective teaching is about listening as much as it is about speaking.",
  "Teachers don’t just instruct; they inspire a love for learning.",
  "The beauty of teaching is that every day is a chance to make a difference.",
  "Teaching is not about telling; it’s about guiding.",
  "Students may not remember what you taught them, but they will always remember how you made them feel.",
  "A good teacher sees the potential in every student, even when they don’t see it themselves.",
  "A great teacher turns obstacles into stepping stones.",
  "Learning flourishes in a space where teachers encourage curiosity and creativity.",
  "Education is the key to unlocking the world, and a teacher holds that key.",
  "Teaching is not just a profession; it’s a calling.",
  "The most powerful tool a teacher has is their ability to inspire.",
  "A patient teacher is a wise teacher.",
  "Teaching is the gentle art of shaping the future.",
  "A teacher is a compass that activates the magnets of curiosity, knowledge, and wisdom.",
  "The most important lessons are often the ones not found in textbooks.",
  "Good teachers don’t give answers; they help students find them.",
  "The best teachers leave a piece of themselves in every student they teach.",
  "Teaching is about guiding, not controlling.",
  "A great teacher listens as much as they speak.",
  "Teachers don’t just teach subjects, they teach students.",
  "A teacher’s influence is measured not in grades but in lives changed.",
  "A great teacher brings learning to life.",
  "Every student is a book waiting to be opened by a teacher.",
  "Great teaching is about more than lessons; it’s about shaping lives.",
  "The best teachers make learning feel effortless.",
  "Education is a gift that lasts a lifetime, and teachers are the ones who give it.",
  "Teaching is the art of turning mirrors into windows.",
  "A good teacher doesn’t teach to the test but teaches for life.",
  "Great teaching is about making the ordinary extraordinary.",
  "Teaching is lighting a candle, not filling a bucket.",
  "A teacher’s encouragement lasts a lifetime.",
  "Good teaching is about knowing when to talk and when to listen.",
  "A teacher’s impact goes far beyond the classroom.",
  "Great teachers inspire their students to surpass them.",
  "Teaching is about bringing out the best in others.",
  "A teacher’s kindness is remembered long after the lesson is forgotten.",
  "The best teachers make learning contagious.",
  "The secret to great teaching is making students feel capable.",
  "Teaching is a journey of learning alongside students.",
  "A great teacher leaves footprints on the hearts of their students.",
  "The art of teaching is understanding how students learn best.",
  "A good teacher sees mistakes as stepping stones to success.",
  "Teachers don’t just teach lessons; they shape futures.",
  "A teacher’s belief in a student can change their life forever.",
  "The best teachers create environments where students feel safe to be themselves.",
  "A great teacher makes difficult concepts feel simple.",
  "Teaching is planting seeds of knowledge that will bloom over time.",
  "Great teachers know that every child learns in their own way.",
  "A teacher’s role is to make learning exciting, not exhausting.",
  "Teaching is about sparking curiosity, not just delivering facts.",
  "Good teaching creates lifelong learners, not just good students.",
  "A great teacher brings out the genius in every student.",
  "A teacher’s greatest reward is seeing their students succeed.",
  "Education is a journey, and teachers are the guides.",
  "The best teachers make students feel capable of anything.",
  "A teacher’s encouragement can change the course of a student’s life.",
  "Teaching is about seeing potential where others see obstacles.",
  "A teacher’s greatest strength is patience.",
  "Teaching is the act of making the impossible seem possible.",
  "A good teacher builds a bridge between learning and understanding.",
  "Teaching is about helping students write their own success stories.",
  "The best teachers make learning feel like an adventure.",
  "Teachers don’t just teach facts, they teach resilience and courage.",
  "A teacher’s true success is measured in the lives they inspire.",
  "Good teachers create students who are eager to learn, not just eager to pass.",
  "Teaching is the ultimate act of optimism.",
  "The best teachers don’t just explain; they inspire curiosity.",
  "A great teacher empowers students to teach themselves.",
  "Every student is capable of greatness, and a good teacher helps them see it.",
  "Teachers shape minds, but they also shape hearts.",
  "A teacher’s enthusiasm for learning is contagious.",
  "The best teachers turn challenges into opportunities for growth.",
  "Teaching is the one profession that creates all other professions.",
  "A good teacher is like a candle—it consumes itself to light the way for others.",
  "The best teachers are those who never stop being students.",
  "Teaching is a work of heart.",
  "A teacher’s true legacy is not in their lesson plans but in the lives they touch.",
  "Teachers open the door, but students must enter by themselves.",
  "The best teachers show students where to look but don’t tell them what to see.",
  "Education begins with curiosity, and teachers are its guides.",
  "The art of teaching is the art of awakening joy in creative expression and knowledge.",
  "Teaching is the art of helping others discover their own potential.",
  "Teachers don’t just instruct; they inspire.",
  "Great teachers turn walls into doors.",
  "A teacher's impact lasts far beyond the classroom.",
  "The greatest gift a teacher can give is a love for learning.",
  "A teacher’s job is to take a hand, open a mind, and touch a heart.",
  "Teaching is the art of nurturing curiosity and turning it into knowledge.",
  "A great teacher doesn’t just prepare students for exams, but for life.",
  "The best teachers make difficult things simple and simple things interesting.",
  "Good teachers create students who can think for themselves.",
  "A teacher is a gardener of minds, cultivating wisdom and knowledge.",
  "Learning is a journey, and a great teacher is the compass.",
  "The classroom is not just a place for learning—it’s a space for growth.",
  "Teaching is the bridge between knowledge and wisdom.",
  "Great teachers don’t just teach, they inspire confidence.",
  "Every student is a story waiting to be written, and teachers are the authors.",
  "The best teachers lead by example, not by instruction alone.",
  "Education is about lighting a spark, not just filling a bucket.",
  "Teachers don’t just prepare students for tests; they prepare them for challenges.",
  "A teacher's guidance can turn a small spark of interest into a burning passion.",
  "Teaching is not about giving answers, but about inspiring questions.",
  "A good teacher makes learning exciting and engaging.",
  "The best educators encourage students to be lifelong learners.",
  "Teaching is not just about facts; it's about shaping minds and values.",
  "The greatest teachers bring knowledge to life.",
  "A teacher’s belief in a student can inspire them to achieve the impossible.",
  "Great teaching is about connection, not just instruction.",
  "A teacher’s words can echo in a student’s heart for a lifetime.",
  "Good teachers don’t just cover material; they uncover potential.",
  "Every lesson taught is a seed planted in the mind of a student.",
  "A great teacher makes learning feel effortless and fun.",
  "Teaching is the key that unlocks a world of possibilities.",
  "A good teacher doesn’t just teach; they transform lives.",
  "The best teachers never give up on their students.",
  "Teachers don’t just teach subjects, they teach resilience and determination.",
  "A great teacher encourages students to dream bigger than they thought possible.",
  "Teaching is about creating a passion for discovery.",
  "A teacher’s kindness is often the most memorable lesson.",
  "Good teachers don’t just share knowledge; they awaken curiosity.",
  "A teacher’s patience can change a struggling student’s life.",
  "The best educators don’t just pass on knowledge; they create thinkers.",
  "Teaching is about making learning an adventure.",
  "Every student is unique, and a great teacher recognizes that.",
  "Teaching is more than a profession; it’s a lifelong mission.",
  "A teacher’s energy and passion are contagious.",
  "The best teachers challenge students to push beyond their limits.",
  "Great teachers encourage students to question everything.",
  "Education is about transformation, and teachers are the architects.",
  "A teacher’s impact extends far beyond the classroom walls.",
  "Teaching is about giving students the tools to build their own future.",
  "Good teaching is about inspiring, not dictating.",
  "A teacher’s greatest reward is seeing a student succeed.",
  "Teaching is about instilling a love for knowledge, not just delivering information.",
  "A great teacher helps students see the magic in learning.",
  "A teacher’s enthusiasm can make any subject come alive.",
  "Good teachers create an environment where students feel safe to explore and grow.",
  "Teaching is about making every student feel seen and valued.",
  "The best teachers make their students feel capable of achieving greatness.",
  "Teaching is not just a job; it’s a commitment to shaping the future.",
  "A teacher’s passion for learning inspires students to strive for more.",
  "Great teachers turn problems into opportunities for learning.",
  "A good teacher sees the potential in every student, even when they don’t see it themselves.",
  "The best teachers understand that learning is about curiosity, not just memorization.",
  "A teacher’s patience can change a struggling student’s story.",
  "Teaching is the art of guiding students to discover their strengths.",
  "A great teacher helps students see failure as a stepping stone to success.",
  "The best educators foster creativity and critical thinking.",
  "Teaching is about helping students unlock their full potential.",
  "A teacher’s words can shape a student’s future.",
  "The best teachers make their students believe in themselves.",
  "Teaching is not about control; it’s about empowerment.",
  "A great teacher teaches with passion, not just with words.",
  "Good teachers don’t just provide answers; they teach how to find them.",
  "A teacher’s encouragement can turn doubt into confidence.",
  "Great teachers inspire a hunger for learning that lasts a lifetime.",
  "A teacher’s dedication makes a world of difference.",
  "Every student deserves a teacher who believes in their potential.",
  "Teaching is not about perfection but about progress.",
  "A great teacher teaches students how to think, not what to think.",
  "The best teachers make students feel capable of achieving anything.",
  "A teacher’s greatest success is seeing a student surpass them.",
  "Teaching is about creating a spark of curiosity that never fades.",
  "A teacher’s passion for knowledge is the greatest lesson of all.",
  "The best educators don’t just teach facts; they teach perspective.",
  "A teacher’s job is not to be the center of attention, but to empower students to shine.",
  "Great teaching turns ordinary moments into extraordinary lessons.",
  "A good teacher doesn’t just teach a subject, they teach a way of thinking.",
  "The best teachers teach not just with words, but with example.",
];

final List<String> teachingImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled teaching quotes with random images.
final List<QuoteItem> teachingQuotes = getShuffledQuotes(
  teachingQuotesRaw,
  teachingImages,
);
