import '../quotes_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> bouncebackQuotesRaw = [
  "Failure is not the opposite of success; it’s part of success.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "The comeback is always stronger than the setback.",
  "Every failure is a lesson. If you are not willing to fail, you are not ready to succeed.",
  "When life knocks you down, roll over and look at the stars.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Difficulties in life are intended to make us better, not bitter.",
  "The road to success is dotted with many tempting parking spaces.",
  "The only real mistake is the one from which we learn nothing.",
  "Rock bottom became the solid foundation on which I rebuilt my life.",
  "Do not be embarrassed by your failures, learn from them and start again.",
  "The phoenix must burn to emerge.",
  "It always seems impossible until it’s done.",
  "Failure is the condiment that gives success its flavor.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "Tough times never last, but tough people do.",
  "Failure is the tuition you pay for success.",
  "He who is not courageous enough to take risks will accomplish nothing in life.",
  "Turn your wounds into wisdom.",
  "If you fell down yesterday, stand up today.",
  "Only those who dare to fail greatly can ever achieve greatly.",
  "Do not judge me by my successes, judge me by how many times I fell down and got back up again.",
  "Failure is an event, not a person. Yesterday ended last night.",
  "Don’t let the fear of losing be greater than the excitement of winning.",
  "The difference between average people and achieving people is their perception of and response to failure.",
  "One who conquers the sea today is ready to conquer the ocean tomorrow.",
  "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
  "Winners are not afraid of losing. But losers are. Failure is part of the process of success.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "In order to succeed, we must first believe that we can.",
  "Your setback is just a setup for your comeback.",
  "Don’t be afraid to give up the good to go for the great.",
  "The biggest risk is not taking any risk.",
  "Never let success get to your head and never let failure get to your heart.",
  "Sometimes you win, sometimes you learn.",
  "Rise above the storm and you will find the sunshine.",
  "Don’t be discouraged. It’s often the last key in the bunch that opens the lock.",
  "Don’t let yesterday take up too much of today.",
  "When we give ourselves permission to fail, we, at the same time, give ourselves permission to excel.",
  "Success is most often achieved by those who don’t know that failure is inevitable.",
  "It’s fine to celebrate success, but it is more important to heed the lessons of failure.",
  "You may have to fight a battle more than once to win it.",
  "When you come out of the storm, you won’t be the same person who walked in. That’s what the storm is all about.",
  "Failure should be our teacher, not our undertaker. Failure is delay, not defeat. It is a temporary detour, not a dead end.",
  "A bend in the road is not the end of the road… unless you fail to make the turn.",
  "Champions keep playing until they get it right.",
  "Embrace failure. Missteps and roadblocks are inevitable but are ultimately a sign of progress.",
  "Perseverance is failing 19 times and succeeding the 20th.",
  "Fall seven times, stand up eight.",
  "No pressure, no diamonds.",
  "If plan A doesn’t work, the alphabet has 25 more letters.",
  "Courage doesn’t always roar. Sometimes it’s the quiet voice at the end of the day saying, ‘I will try again tomorrow.’",
  "Losers quit when they fail. Winners fail until they succeed.",
  "Defeat is simply a signal to press onward.",
  "The master has failed more times than the beginner has even tried.",
  "A stumble may prevent a fall.",
  "Doubt kills more dreams than failure ever will.",
  "Great works are performed not by strength, but by perseverance.",
  "You just can’t beat the person who never gives up.",
  "Most great people have attained their greatest success just one step beyond their greatest failure.",
  "Failure is a bruise, not a tattoo.",
  "Storms make trees take deeper roots.",
  "Failure is simply success in progress.",
  "Pain is temporary. Quitting lasts forever.",
  "When nothing goes right, go left.",
  "Success is how high you bounce when you hit bottom.",
  "Tough times test you, but they also reveal your true strength.",
  "The harder the struggle, the more glorious the triumph.",
  "No failure, no growth.",
  "If you want to succeed, double your failure rate.",
  "Your limitation—it’s only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Dream it. Wish it. Do it.",
  "Difficult roads often lead to beautiful destinations.",
  "Be proud of how far you’ve come.",
  "Stay focused and never give up.",
  "Fear is only temporary. Regret lasts forever.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "You never know how strong you are until being strong is your only choice.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Keep going. Everything you need will come to you at the right time.",
  "Turn obstacles into stepping stones.",
  "Your past does not determine your future.",
  "Success grows from perseverance.",
  "Keep rising, keep fighting, keep dreaming.",
  "Failure leads to innovation and progress.",
  "Adapt. Overcome. Conquer.",
  "Don’t fear failure. Fear being in the same place next year.",
  "There is no failure except in no longer trying.",
  "Resilience is the secret ingredient to success.",
  "Tough moments define strong people.",
  "The past cannot be changed, but the future is in your power.",
  "Focus on progress, not perfection.",
  "Everything is difficult before it is easy.",
  "Storms make people stronger and never last forever.",
  "Rise, fall, and rise again.",
  "Even the darkest night will end, and the sun will rise.",
  "Nothing worth having comes easy.",
  "Fear kills more dreams than failure ever will.",
  "Struggle today for strength tomorrow.",
  "Every champion was once a contender that refused to give up.",
  "Failure is the foundation of success.",
  "Your story isn’t over yet; keep going.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "The road to success runs through failure street.",
  "Grit is not giving up when you face resistance.",
  "If you never fail, you’re not pushing yourself hard enough.",
  "Every day is a new opportunity to change your life.",
  "Obstacles are just opportunities in disguise.",
  "Your resilience will take you places talent cannot.",
  "The comeback is always greater than the setback.",
  "Keep showing up, even on your worst days.",
  "Mistakes are proof that you are trying.",
  "Learn from the past, but don’t live in it.",
  "Dream big, fail often, and succeed wildly.",
  "When you feel like quitting, remember why you started.",
  "Resilience turns adversity into strength.",
  "Never stop believing in yourself.",
  "Sometimes failure is just redirection.",
  "No matter how hard it gets, never give up.",
  "Your best days are ahead of you.",
  "Failure is just the beginning of something great.",
  "Failure is not falling down but refusing to get up.",
  "A comeback is a setback that got back up.",
  "What defines us is how well we rise after falling.",
  "It’s never too late for a new beginning.",
  "Life is tough, but so are you.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Small steps every day lead to big achievements.",
  "Believe in yourself, even when no one else does.",
  "The struggle you’re in today is developing the strength you need tomorrow.",
  "If you get tired, learn to rest, not to quit.",
  "Never be afraid of a scar; it simply means you were stronger than whatever tried to hurt you.",
  "Setbacks are just setups for comebacks.",
  "When one door closes, another opens. Keep knocking.",
  "You were given this life because you are strong enough to live it.",
  "Fall down seven times, get up eight.",
  "One step at a time is still moving forward.",
  "Strength grows in the moments when you think you can’t go on but keep going anyway.",
  "No storm lasts forever; keep pushing through.",
  "The only way to fail is to stop trying.",
  "Pain today will be power tomorrow.",
  "Adversity introduces a person to themselves.",
  "Let your scars tell a story of strength.",
  "Nothing is over until you stop trying.",
  "When life gives you lemons, make lemonade.",
  "The best way out is always through.",
  "Your hardest times often lead to the greatest moments of your life.",
  "Some of the greatest things in life come after failure.",
  "Tough situations build strong people.",
  "Champions keep playing until they get it right.",
  "Strength doesn’t come from winning; it comes from struggles.",
  "Never let a stumble be the end of your journey.",
  "Push through the pain; it’s only temporary.",
  "You don’t drown by falling in water; you drown by staying there.",
  "It’s always too early to quit.",
  "A minor setback paves the way for a major comeback.",
  "There is no growth without struggle.",
  "Even a broken crayon still colors.",
  "Your dreams don’t expire; keep chasing them.",
  "Don’t be afraid to start over. This time, you’re not starting from scratch; you’re starting from experience.",
  "Rise up. Start fresh. See the bright opportunity in each new day.",
  "The pain you feel today is the strength you feel tomorrow.",
  "Keep your head up. Your time is coming.",
  "Difficulties prepare ordinary people for extraordinary success.",
  "Trust the process, even when it doesn’t make sense.",
  "Never doubt yourself. You’re stronger than you think.",
  "The only time you fail is when you stop trying.",
  "What you overcome today will make you stronger tomorrow.",
  "You can start over at any time. Remember that.",
  "The secret to success is to never give up.",
  "Every champion was once a contender who refused to give up.",
  "Turn your wounds into wisdom.",
  "Every great success story has chapters of failure.",
  "The road to success is paved with challenges; walk it with confidence.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Rise every time you fall.",
  "Every setback is an opportunity for a stronger comeback.",
  "Success is just failure turned inside out.",
  "Make peace with your past so it won’t mess up your future.",
  "You didn’t come this far to only come this far.",
  "A difficult past makes for a powerful future.",
  "A warrior’s strength is measured by how many times they get back up.",
  "One day, your story will inspire someone else to keep going.",
  "Don’t look back; you’re not going that way.",
  "Let failure refine you, not define you.",
  "Keep moving forward, even when the path isn’t clear.",
  "Turn obstacles into opportunities.",
  "The greatest victory is rising after defeat.",
  "A detour is just another route to your destination.",
  "You can rise up from anything. You can completely recreate yourself.",
  "No matter how hard it gets, you are capable of overcoming it.",
  "You are not your past. You are the person who survived it.",
  "Keep pushing. Keep believing. Keep growing.",
  "Every time you fall, you’re learning how to rise better.",
  "Your struggle is proof that you haven’t given up.",
  "The fire inside you is greater than the storm outside.",
  "Every challenge you face today makes you stronger for tomorrow.",
  "Sometimes, rock bottom is the best foundation to build on.",
  "Strength isn’t about never breaking; it’s about putting the pieces back together.",
  "Don’t wait for opportunity. Create it.",
  "A mistake is just another step toward success.",
  "The greatest comeback starts with the smallest step forward.",
  "Where you are now is not where you’ll always be.",
  "Do not let the past hold you back; let it propel you forward.",
  "The climb may be tough, but the view is worth it.",
  "You’re closer than you think. Don’t stop now.",
  "When you feel like giving up, remember why you started.",
  "You don’t have to be perfect, just keep going.",
  "The only thing stronger than fear is hope.",
  "Your next chapter is waiting. Keep turning the pages.",
  "With the right mindset, anything is possible.",
  "The strongest people rise from the hardest falls.",
  "You are not a failure; you are a fighter.",
  "Even in darkness, you have the power to shine.",
  "Your persistence will pay off. Keep going.",
  "Your bounce back will be greater than your setback.",
  "What seems like the end is often a new beginning.",
  "You are limitless. Prove it to yourself.",
  "Rise up. You’ve got this.",
];

final List<String> bouncebackImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<QuoteItem> bouncebackQuotes = getShuffledQuotes(
  bouncebackQuotesRaw,
  bouncebackImages,
);
