import '../quotes_randomizer.dart';

/// **Embracing Change Quotes & Images**
final List<String> changeQuotesRaw = [
  "Embrace change like an old friend, for it brings new beginnings.",
  "Every change is a chance to rewrite your story.",
  "Sometimes, change is the best gift life can give you.",
  "The more you embrace change, the less it controls you.",
  "Change is a stepping stone, not a stumbling block.",
  "Your willingness to adapt determines your success.",
  "Change your mindset, and the world around you will follow.",
  "Let go of the past; make room for the future.",
  "Fear fades when you step into change with confidence.",
  "New doors open when you close old ones.",
  "Change is the catalyst for personal evolution.",
  "Don’t fear uncertainty; embrace its possibilities.",
  "If you resist change, you resist growth.",
  "A new beginning starts with a single brave step.",
  "The past is a lesson, not a life sentence.",
  "You have to let go of who you were to become who you’re meant to be.",
  "Without change, we would never discover our full potential.",
  "Transformation happens when you stop resisting change.",
  "Change is not a burden; it's an invitation.",
  "The unknown is where adventure begins.",
  "The secret to thriving is embracing the unexpected.",
  "If nothing ever changed, life would be boring.",
  "Change is a reminder that life is full of possibilities.",
  "The more adaptable you are, the stronger you become.",
  "Let go of control and let life unfold.",
  "When you embrace change, you embrace growth.",
  "The best journeys begin with a leap of faith.",
  "Change forces you to see the world differently.",
  "The magic of change is that it reveals your true strength.",
  "Life’s greatest lessons come from its biggest changes.",
  "Change is like a river—flow with it, don’t fight it.",
  "Find joy in the unexpected.",
  "Don’t fear the winds of change; they bring new opportunities.",
  "Every challenge is a disguised opportunity for growth.",
  "With change comes the possibility of something better.",
  "Evolve with life, don’t resist it.",
  "The key to happiness is accepting change with an open heart.",
  "Your greatest potential lies just beyond your comfort zone.",
  "Adaptation is the key to survival.",
  "Change isn’t meant to be easy; it’s meant to be worth it.",
  "Stop waiting for the perfect moment—embrace change now.",
  "Old ways won’t open new doors.",
  "You don’t grow when things stay the same.",
  "A shifting path often leads to a brighter destination.",
  "Even the seasons teach us to embrace change.",
  "You are never too old or too young to start fresh.",
  "Small changes lead to big transformations.",
  "Sometimes, change is just a fresh start in disguise.",
  "A new version of you is waiting on the other side of change.",
  "Be the wave that embraces the shore, not the rock that resists it.",
  "Nothing blooms without change.",
  "Embracing change means embracing life itself.",
  "Everything you’ve ever wanted is waiting on the other side of change.",
  "Life is not about avoiding change, but about mastering it.",
  "Change is the bridge between dreams and reality.",
  "You have the power to rewrite your story at any time.",
  "The more you grow, the more change becomes your friend.",
  "Uncertainty isn’t scary; it’s exciting when you welcome it.",
  "You can’t control change, but you can control how you respond to it.",
  "Trust that every change is leading you somewhere beautiful.",
  "One small shift today can change your entire future.",
  "Progress is impossible without change.",
  "The only way forward is through change.",
  "Change is a doorway to limitless possibilities.",
  "Every sunrise is proof that change is beautiful.",
  "Change is a reminder that you’re alive and evolving.",
  "Welcome change with an open heart, and life will surprise you.",
  "Stop resisting change—start shaping it.",
  "Life rewards those who embrace its unpredictability.",
  "You are stronger than any change life throws at you.",
  "Change isn’t scary; it’s just unfamiliar.",
  "Each change brings a new lesson to learn.",
  "Your story isn’t over—it’s just turning the page.",
  "You don’t need to have it all figured out to take the next step.",
  "The only thing worse than change is stagnation.",
  "The best view comes after the hardest climb.",
  "Sometimes, change is the universe’s way of guiding you.",
  "Everything changes, but that’s what makes life exciting.",
  "The only limits in life are the ones you refuse to change.",
  "Life is about learning to dance in the rain, not waiting for the storm to pass.",
  "If life stays the same, it stops being life.",
  "Your next chapter is waiting—turn the page.",
  "Don’t be afraid of endings; they are just new beginnings.",
  "Change is proof that life is always moving forward.",
  "Let go of what holds you back so you can embrace what lies ahead.",
  "Accept what is, let go of what was, and have faith in what will be.",
  "Every change holds a hidden opportunity.",
  "Resistance to change is resistance to progress.",
  "A comfort zone is the enemy of growth.",
  "Be the author of your own transformation.",
  "Change isn’t happening to you, it’s happening for you.",
  "The moment you embrace change, you gain control over it.",
  "A small shift in perspective can change everything.",
  "Growth only happens when you stop clinging to the past.",
  "New paths lead to new adventures—walk forward with courage.",
  "Fear of change is just fear of the unknown—trust yourself.",
  "If you never change, you’ll never know what you’re truly capable of.",
  "Welcome change, because it means you’re still moving forward.",
  "Your story is still being written—don’t be afraid to turn the page.",
  "Life doesn’t wait—so embrace change and move with it.",
  "Change is the law of life.",
  "Embrace uncertainty. Some of the most beautiful chapters in our lives won’t have a title until much later.",
  "Without change, there is no growth.",
  "The secret of change is to focus all your energy not on fighting the old but on building the new.",
  "Change is hard at first, messy in the middle, and gorgeous at the end.",
  "Growth and comfort do not coexist.",
  "If you don’t like something, change it. If you can’t change it, change your attitude.",
  "Change begins at the end of your comfort zone.",
  "Every new beginning comes from some other beginning’s end.",
  "To improve is to change; to be perfect is to change often.",
  "Change is inevitable. Growth is optional.",
  "Sometimes good things fall apart so better things can fall together.",
  "Your life does not get better by chance; it gets better by change.",
  "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
  "Embrace the uncertainty. Enjoy the beauty of becoming.",
  "Change brings opportunity.",
  "You can’t start the next chapter of your life if you keep re-reading the last one.",
  "Let go of what was, embrace what is, and trust what will be.",
  "New beginnings are often disguised as painful endings.",
  "Don't resist change; use it to shape the future.",
  "Adapting to change is like riding a wave. You can either be crushed by it or learn to surf.",
  "Change is painful, but nothing is as painful as staying stuck somewhere you don’t belong.",
  "Your willingness to look at your darkest moments is what empowers you to change.",
  "The winds of change are always blowing, but you have to raise the sails.",
  "Nothing changes unless you do.",
  "Don’t be afraid of change. Be afraid of not changing.",
  "Turn the page. It’s time for the next chapter.",
  "What you are afraid to let go of is exactly what will set you free.",
  "Let change refine you, not define you.",
  "The best way to predict the future is to create it.",
  "A comfort zone is a beautiful place, but nothing ever grows there.",
  "Change can be scary, but you know what’s scarier? Allowing fear to stop you from growing.",
  "Change before you have to.",
  "Every change brings a new opportunity.",
  "If you change the way you look at things, the things you look at change.",
  "Change is the essence of life. Be willing to surrender what you are for what you could become.",
  "Those who cannot change their minds cannot change anything.",
  "Be the change you wish to see in the world.",
  "The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
  "Change is a part of life; accept it and evolve.",
  "Life is about change. Sometimes it’s painful, sometimes it’s beautiful, but most of the time, it’s both.",
  "People change, seasons change, and so must you.",
  "Every exit is an entry somewhere else.",
  "The art of life is a constant readjustment to our surroundings.",
  "When we are no longer able to change a situation, we are challenged to change ourselves.",
  "Don’t fear change. Fear being in the same place next year.",
  "You are one decision away from a totally different life.",
  "A year from now, you will wish you had started today.",
  "Be open to change; it’s the only constant.",
  "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
  "The butterfly was once a caterpillar that embraced change.",
  "Life isn’t about finding yourself. It’s about creating yourself.",
  "Great things never come from comfort zones.",
  "Change always comes bearing gifts.",
  "Sometimes the smallest step in the right direction ends up being the biggest step of your life.",
  "If you do not change direction, you may end up where you are heading.",
  "You cannot grow unless you embrace change.",
  "Adaptability is about the powerful difference between adapting to cope and adapting to win.",
  "Every storm runs out of rain.",
  "Success is not about avoiding change but learning how to navigate it.",
  "Small shifts lead to big results.",
  "If nothing ever changed, there would be no butterflies.",
  "When the winds of change blow, some people build walls, others build windmills.",
  "You grow through what you go through.",
  "Life is about evolving, not staying the same.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "The only real mistake is the one from which we learn nothing.",
  "There is no innovation and creativity without change.",
  "To exist is to change, to change is to mature, to mature is to go on creating oneself endlessly.",
  "All great changes are preceded by chaos.",
  "Everything you’ve ever wanted is on the other side of change.",
  "Embracing change is the key to happiness.",
  "What seems like a setback is often a setup for a breakthrough.",
  "Changing your mind is a strength, not a weakness.",
  "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
  "If you wait until you’re ready, you’ll be waiting the rest of your life.",
  "Change is scary at first but beautiful at the end.",
  "Life moves on, and so should we.",
  "Sometimes, change is what we need most.",
  "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don’t belong.",
  "Transformation begins where comfort ends.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Change your thoughts, and you change your world.",
  "Never be afraid of change. You may lose something good, but you may gain something even better.",
  "You can't go back and change the beginning, but you can start where you are and change the ending.",
  "Every change makes you better than before.",
  "Change your story, change your life.",
  "Dream big, start small, but most importantly, start.",
  "You don’t have to have it all figured out to move forward.",
  "A new day is a new beginning.",
  "Fear of change is fear of growth.",
  "The greatest gift of life is the opportunity to change.",
  "Move with the flow of life, not against it.",
  "Change is the only way to move forward.",
  "If you resist change, you resist life.",
  "Dare to reinvent yourself.",
  "Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. Let reality be reality.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.",
  "Only when we let go of what we are, can we become what we might be.",
  "What if everything you are going through is preparing you for what you asked for?",
  "You have the power to say, 'This is not how my story will end.'",
  "Every day brings new choices.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Change is not an enemy, it is a friend guiding you to something greater.",
];

final List<String> changeImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled change quotes with random images.
final List<QuoteItem> changeQuotes = getShuffledQuotes(
  changeQuotesRaw,
  changeImages,
);
