import '../quotes_randomizer.dart';

/// **Courage and Strength Quotes & Images**

final List<String> courageQuotesRaw = [
  "Courage is not the absence of fear, but the triumph over it.",
  "Strength doesn’t come from what you can do; it comes from overcoming the things you once thought you couldn’t.",
  "Be strong enough to stand alone, but wise enough to ask for help when needed.",
  "Fear is temporary, but courage lasts forever.",
  "Bravery is not about being fearless, but about facing your fears head-on.",
  "Strength is not in never falling, but in rising every time you fall.",
  "You were given this life because you are strong enough to live it.",
  "The strongest people are not those who show strength in front of us, but those who fight battles we know nothing about.",
  "Courage is the power to let go of the familiar.",
  "It takes courage to grow up and become who you truly are.",
  "Difficulties in life are meant to make us better, not bitter.",
  "Courage is contagious. When one brave soul stands up, others follow.",
  "Strength grows in the moments when you think you can’t go on but keep going anyway.",
  "A strong person is not one who never cries, but one who sheds tears for a moment and then picks up the sword again.",
  "Do not pray for an easy life; pray for the strength to endure a difficult one.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Sometimes courage is just the quiet voice that says, ‘I will try again tomorrow.’",
  "The only way to truly fail is to give up.",
  "Life doesn’t get easier; you just get stronger.",
  "Bravery is when you face your fears even when your hands are shaking.",
  "You have survived 100% of your worst days. Keep going.",
  "Tough times never last, but tough people do.",
  "Strength isn’t just about how much you can handle before you break, but how much you can endure after you’ve been broken.",
  "Have the courage to stand alone and the wisdom to know when you need support.",
  "Even in the darkest moments, strength is found in hope.",
  "A storm may bend you, but it will never break you.",
  "Your greatest strength is within you, waiting to be unleashed.",
  "Fear is just a test of how much courage you have.",
  "Courage is being scared to death but saddling up anyway.",
  "When you feel like quitting, remember why you started.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Strength is built in the moments where you refuse to give up.",
  "The bravest thing you can do is to believe in yourself.",
  "A heart full of courage can never be conquered.",
  "No matter how hard it gets, keep pushing forward.",
  "You don’t always need a plan, sometimes you just need courage.",
  "Strength is not a matter of muscles, but of mind and spirit.",
  "Great strength comes from great struggles.",
  "Let your courage light the path when darkness surrounds you.",
  "The strongest people aren’t those who never struggle, but those who refuse to be defeated by it.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Life’s battles don’t always go to the strongest, but to those who refuse to give up.",
  "Sometimes, courage is simply taking the next step forward.",
  "Stand strong in the face of adversity and watch yourself grow.",
  "Fear will try to stop you; courage will push you forward.",
  "Strength is when you have every reason to give up, but choose not to.",
  "A warrior is not one who always wins but one who never surrenders.",
  "Never let fear decide your future.",
  "You don’t know how strong you are until being strong is the only choice you have.",
  "Courage doesn’t always roar; sometimes it’s the quiet voice saying, ‘Try again tomorrow.’",
  "The world belongs to those who dare.",
  "Your struggles are shaping you into something greater.",
  "Fear knocked, courage answered, and no one was there.",
  "Being strong doesn’t mean you never get hurt; it means you keep fighting even when you are.",
  "Adversity introduces us to our true selves.",
  "No challenge is too big when your courage is bigger.",
  "Strength is when you keep going, even when your mind tells you to stop.",
  "Real bravery is stepping forward even when you feel like stepping back.",
  "Storms make trees take deeper roots.",
  "Your strength today was once a weakness you overcame.",
  "You don’t have to be fearless; you just have to be brave enough to take the first step.",
  "Fall seven times, stand up eight.",
  "Heroes aren’t fearless; they just take action despite their fears.",
  "The strongest hearts have the deepest scars.",
  "Every setback is a setup for a stronger comeback.",
  "Life is tough, but so are you.",
  "Don’t wait for the storm to pass; learn to dance in the rain.",
  "Bravery is daring to stand up when the world tries to push you down.",
  "You are not defined by your struggles, but by how you rise above them.",
  "A true warrior knows that strength comes from within.",
  "Fear fades when faced with courage.",
  "True strength is facing your fears with an unshaken heart.",
  "Rise above the fear and watch your strength grow.",
  "The pain you feel today is the strength you’ll cherish tomorrow.",
  "You don’t need permission to be strong—just believe in yourself.",
  "Brave souls rewrite the rules of life.",
  "True strength is knowing when to fight and when to let go.",
  "No fear is greater than the power of courage within you.",
  "It’s not about how hard you hit, but how hard you can get hit and keep moving forward.",
  "Courage is daring to take a leap of faith when you can’t see the ground.",
  "Tough situations build tougher people.",
  "When fear whispers, let courage roar.",
  "Real strength is silent; real courage is unshakable.",
  "A brave heart beats louder than a thousand voices of doubt.",
  "Strength is the foundation, but courage is the key.",
  "The road to success is paved with courage and persistence.",
  "Be strong enough to walk alone, but wise enough to find the right companions.",
  "The strongest warriors fight their battles in silence.",
  "Even the smallest spark of courage can ignite a fire within.",
  "Fear makes the wolf bigger than it is—stand strong.",
  "Your spirit is stronger than any obstacle in your way.",
  "Courage means taking action, even when fear tries to stop you.",
  "Strength is not measured by victories, but by perseverance.",
  "You have survived every challenge so far—trust your strength to face the next one."
      "Courage is found in the moments when fear is loudest.",
  "Strength is built in silence but seen in storms.",
  "You don’t need to see the whole staircase, just take the first step.",
  "Fear is a reaction; courage is a decision.",
  "The strongest people are those who fight battles no one sees.",
  "With courage, even the smallest step is progress.",
  "A warrior does not complain about the battle; they fight it.",
  "Fear and doubt are powerless when faced with determination.",
  "Your strength is greater than your struggles.",
  "Let your faith be bigger than your fear.",
  "Strength is knowing you can, even when everything says you can't.",
  "Being brave means taking the first step even when you’re afraid.",
  "Strength isn’t about muscles; it’s about mindset.",
  "Do what you fear, and watch your courage grow.",
  "Every storm you endure makes you stronger.",
  "Fear is only as strong as you allow it to be.",
  "Courage means standing tall even when the ground shakes.",
  "You have been through worse. You will get through this too.",
  "Real strength is found in the depths of struggle.",
  "No matter how many times you fall, stand up one more time.",
  "A heart full of courage is unstoppable.",
  "Courage means going on even when you have no strength left.",
  "Your fears are liars; your courage is real.",
  "A small act of courage can change everything.",
  "The bravest thing you can do is believe in yourself.",
  "Fear tells you to stop; courage tells you to keep going.",
  "The strongest battles are fought within.",
  "It takes courage to walk a path no one else does.",
  "Even in fear, move forward with faith.",
  "Strength is built in the quiet moments of struggle.",
  "Bravery is not about not being scared, but about acting despite it.",
  "Your scars are proof of your courage.",
  "Stand strong; your struggles will turn into strength.",
  "Courage is refusing to quit when times get tough.",
  "Face your fears, or they will forever chase you.",
  "Strength means never letting your fear decide your fate.",
  "You are powerful beyond what you believe.",
  "No fear is greater than the power of a determined heart.",
  "Each hardship you overcome is a lesson in strength.",
  "True warriors are made, not born.",
  "The storm will pass, but your strength will remain.",
  "Even when afraid, take the leap.",
  "Strong minds don’t fear challenges; they embrace them.",
  "You have more courage than you know.",
  "Keep standing tall—your strength is inspiring.",
  "Bravery is facing tomorrow, no matter how hard today was.",
  "Courage means daring to dream when others doubt.",
  "You are braver than you think and stronger than you know.",
  "A warrior’s heart never backs down.",
  "Fear fades when faced with unshaken determination.",
  "Pain shapes strength, and strength fuels courage.",
  "You are capable of withstanding more than you believe.",
  "Strength is what you build after a fall.",
  "Even the darkest night can’t defeat a heart full of courage.",
  "Have the courage to be different.",
  "Strength means daring to fail and trying again.",
  "The only real defeat is in giving up.",
  "Difficulties are stepping stones to strength.",
  "Your fear doesn’t define you; your courage does.",
  "Face your challenges head-on; they won’t last forever.",
  "You don’t need to feel brave to act brave.",
  "Life rewards those who have the courage to go on.",
  "Strength is pushing through the hard days.",
  "What seems impossible now will be part of your strength later.",
  "Dare to take the risks others fear.",
  "With every challenge, you grow stronger.",
  "You don’t need permission to be strong.",
  "Courage is fighting for your dreams even when no one believes in you.",
  "The moment you refuse to give up, you win.",
  "Believe in yourself, even when no one else does.",
  "A strong soul shines even in the darkest times.",
  "Courage is getting back up when you’ve been knocked down.",
  "Bravery is standing alone when necessary.",
  "Fear is just the beginning of courage.",
  "Strength means never giving in to doubts.",
  "Rise like a phoenix from the ashes of defeat.",
  "You were made to do hard things.",
  "Strength is not about being unbreakable; it’s about never staying broken.",
  "A brave person is one who faces fear, not one who has none.",
  "Your journey is shaping your strength.",
  "Courage means standing tall in the storm.",
  "Fear whispers, but courage roars.",
  "The strongest souls emerge from the toughest battles.",
  "Great things come to those who dare.",
  "Even when you feel weak, your spirit remains unshaken.",
  "Fear is temporary; strength lasts forever.",
  "The road to success is built on courage.",
  "You are stronger than your pain.",
  "Fear is loud, but courage speaks louder.",
  "Strength is found in the moments you refuse to quit.",
  "Your struggles are preparing you for something greater.",
  "Dare to take the first step, and courage will follow.",
  "Bravery is built with every step into the unknown.",
  "Even the smallest act of courage can change your life.",
  "Life rewards those who refuse to give up.",
  "Strength means standing even when everything tells you to fall.",
  "Be the person who never quits, no matter what.",
  "Your power lies in your resilience.",
  "Fear may slow you down, but it will never stop you if you have courage.",
];

final List<String> courageImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled courage quotes with random images.
// Notice this name vvvvvvvvvvvvvvvvvvvvv this you have to put in here
final List<QuoteItem> courageQuotes = getShuffledQuotes(
  courageQuotesRaw, //TODO: Notice this name
  courageImages,
);
