import '../quotes_randomizer.dart';

/// **Overcoming Challenges Quotes & Images**
final List<String> overcomingQuotesRaw = [
  "Difficulties in life are intended to make us better, not bitter.",
  "Strength grows in the moments when you think you can’t go on but keep going anyway.",
  "Every challenge you overcome makes you stronger than before.",
  "The greater the challenge, the greater the triumph.",
  "Obstacles are opportunities in disguise.",
  "Tough times don’t last, but tough people do.",
  "The moment you refuse to quit is the moment you overcome.",
  "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
  "A smooth sea never made a skilled sailor.",
  "You are stronger than your struggles.",
  "With every challenge, you grow wiser and braver.",
  "Turn your obstacles into stepping stones.",
  "You were given this challenge because you are strong enough to handle it.",
  "A setback is just a setup for a comeback.",
  "The only way out is through.",
  "Every difficulty carries the seed of equal or greater success.",
  "Storms make trees take deeper roots.",
  "Life’s challenges are not meant to paralyze you, but to help you discover who you are.",
  "You can’t control the waves, but you can learn to surf.",
  "Your struggles develop your strengths.",
  "Courage is not having the strength to go on, but going on when you have no strength.",
  "If you’re going through hell, keep going.",
  "Challenges test us, but they also reveal our true strength.",
  "What seems impossible today will be your strength tomorrow.",
  "Overcoming challenges is the key to unlocking your full potential.",
  "Let challenges shape you, not break you.",
  "A warrior sees every challenge as a chance to grow.",
  "Pain is temporary, but quitting lasts forever.",
  "When faced with a mountain, climb it, go around it, or find a new path.",
  "Fear thrives on avoidance, but courage grows with action.",
  "The harder the challenge, the greater the reward.",
  "Resilience is built through struggle.",
  "Every failure is a step closer to success.",
  "Embrace challenges as part of your journey to greatness.",
  "Turn adversity into an advantage.",
  "The struggle you're in today is building the strength you need for tomorrow.",
  "Life is tough, but so are you.",
  "Keep pushing; your breakthrough is near.",
  "You grow through what you go through.",
  "Great victories come from great battles.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Face your challenges boldly, and they will shrink before you.",
  "Every storm runs out of rain.",
  "You don’t have to be fearless, just determined.",
  "Don’t let the struggle define you; let it refine you.",
  "You can rise above any challenge with perseverance and belief.",
  "Your past struggles are proof of your present strength.",
  "Stay patient and trust the process.",
  "You were built to endure, to fight, and to overcome.",
  "Defeat is only final if you stop trying.",
  "The road to success is always under construction.",
  "See challenges as stepping stones, not stumbling blocks.",
  "Believe in your ability to overcome anything.",
  "You can overcome anything if you refuse to stop trying.",
  "Difficult roads often lead to beautiful destinations.",
  "Persistence is the key to conquering any obstacle.",
  "Nothing is impossible for the one who is willing to keep trying.",
  "Small steps every day lead to great victories.",
  "The only way to overcome a challenge is to face it head-on.",
  "Struggles make success taste sweeter.",
  "In the middle of difficulty lies opportunity.",
  "What doesn’t kill you makes you stronger.",
  "Challenges force us to find our hidden strengths.",
  "Adversity reveals the warrior within.",
  "You become unstoppable when you stop fearing failure.",
  "The fire of adversity forges the strongest steel.",
  "When life knocks you down, get up stronger.",
  "Don’t let fear dictate your future.",
  "Success is built on the foundation of failures overcome.",
  "Resilience is refusing to let failure define you.",
  "Great things never come from comfort zones.",
  "A challenge is only as big as you allow it to be.",
  "Never let a setback be the end of your story.",
  "Your struggles prepare you for something greater.",
  "You are capable of more than you know.",
  "One day, your struggles will be someone else’s inspiration.",
  "Rough seas bring the best sailors to shore.",
  "Take one step at a time; progress is still progress.",
  "No challenge is greater than the power of perseverance.",
  "Victory belongs to those who never give up.",
  "The bravest souls rise from the hardest struggles.",
  "Every challenge carries the potential for greatness.",
  "Success is born from struggle.",
  "Keep going; you are closer than you think.",
  "Challenges make your success story worth telling.",
  "Your hardest times often lead to your greatest moments.",
  "Behind every challenge lies an opportunity.",
  "A strong mindset turns obstacles into growth.",
  "When the path is tough, remember why you started.",
  "You’ve conquered hardships before; you’ll do it again.",
  "Let go of fear and embrace the challenge.",
  "Fear is the lock; courage is the key.",
  "No matter how many times you fall, rise one more time.",
  "The greatest warriors are forged in battle.",
  "Adversity teaches lessons that comfort never can.",
  "You don’t find strength; you create it through challenges.",
  "Never underestimate your ability to rise again.",
  "Strength is not given; it is earned through struggles.",
  "The best view comes after the hardest climb.",
  "Take pride in how far you’ve come and keep going.",
  "Success is simply resilience in motion.",
  "When you stand firm, no storm can break you.",
  "You’re stronger than your struggles, braver than your fears.",
  "The darkest night always leads to the brightest dawn.",
  "Hardships are the training grounds for champions.",
  "Overcoming challenges is proof of your unstoppable spirit.",
  "Challenges shape character and build resilience.",
  "No storm lasts forever; keep moving forward.",
  "Where there’s a will, there’s always a way.",
  "Your challenges are just stepping stones to success.",
  "You never lose; you either win or learn.",
  "Stay strong; your efforts will be rewarded.",
  "Sometimes the hardest paths lead to the most beautiful destinations.",
  "Keep pushing; you’re capable of amazing things.",
  "Life’s difficulties are just opportunities to prove your strength.",
  "Rise above the struggle, and you will shine.",
  "Every mountain you climb makes you a stronger hiker.",
  "Obstacles exist to be overcome.",
  "Failure is not the opposite of success; it’s part of the journey.",
  "With determination, nothing is out of reach.",
  "Your toughest times prepare you for your greatest moments.",
  "Remember, the caterpillar must struggle before it can fly.",
  "No matter how tough the road, keep walking.",
  "Courage is facing the challenge, even when afraid.",
  "A positive mindset turns challenges into triumphs.",
  "Stand tall in the face of adversity; you were born to rise.",
  "The world belongs to those who refuse to quit."
      "Challenges are what make life exciting, overcoming them is what makes it meaningful.",
  "Don’t be discouraged by challenges; be empowered by them.",
  "When life gives you obstacles, build a staircase.",
  "Every challenge you face is an opportunity to rise higher.",
  "Struggles refine you; they don’t define you.",
  "What you overcome today will be your strength tomorrow.",
  "You can’t control the storm, but you can learn to dance in the rain.",
  "Adversity introduces you to your inner strength.",
  "The struggle is real, but so is your ability to conquer it.",
  "Rise every time you fall, and soon you’ll learn to fly.",
  "Growth and comfort do not coexist.",
  "You don’t need an easy life, just a resilient mindset.",
  "Difficult moments are the teachers of wisdom.",
  "Challenges push you to discover your true potential.",
  "Victory belongs to those who never surrender to difficulty.",
  "What you survive today will inspire others tomorrow.",
  "Your toughest battles reveal your greatest strengths.",
  "Life’s greatest lessons come from the hardest challenges.",
  "Endure the storm, and you’ll enjoy the sunshine.",
  "Every challenge is an invitation to evolve.",
  "Tough times shape the toughest people.",
  "Pain shapes purpose if you allow it.",
  "You were born to rise above the struggle.",
  "No challenge is too big when your will is unbreakable.",
  "Your perseverance will lead you to the peak of success.",
  "Find power in your pain, strength in your struggles.",
  "Behind every struggle lies a hidden strength.",
  "The path to greatness is paved with obstacles.",
  "Adversity is not a stop sign; it's a detour to something greater.",
  "Nothing worth achieving ever comes easy.",
  "Your struggles are proof that you are progressing.",
  "If it doesn’t challenge you, it won’t change you.",
  "Great challenges lead to great rewards.",
  "Hard times build unshakable character.",
  "Do not fear challenges; they are opportunities in disguise.",
  "Battles today prepare you for victories tomorrow.",
  "Let every challenge fuel your hunger for success.",
  "The road may be tough, but you are tougher.",
  "The obstacle in your way is the way forward.",
  "Rise like the sun after the darkest night.",
  "A warrior is not one who never faces defeat, but one who rises after every fall.",
  "Each difficulty is a stepping stone toward success.",
  "Keep moving forward; setbacks are just setups for comebacks.",
  "Your struggles today are stories of triumph tomorrow.",
  "The only thing standing between you and success is persistence.",
  "You are built for resilience, not retreat.",
  "Storms in life are there to test your foundation.",
  "Even in darkness, the strongest stars shine the brightest.",
  "Overcoming difficulties makes success even sweeter.",
  "You have survived 100% of your worst days. Keep going.",
  "The fight you’re in today strengthens you for tomorrow.",
  "Never be afraid of failure; be afraid of not trying.",
  "Every great achievement was once considered impossible.",
  "You don’t fail until you stop trying.",
  "There is no growth without challenge.",
  "A setback is just a setup for a major comeback.",
  "Adversity builds courage, endurance, and wisdom.",
  "You weren’t made to break; you were made to rise.",
  "A river cuts through rock not by strength, but by persistence.",
  "You don’t climb mountains by wishing; you climb by doing.",
  "There is strength in every struggle you endure.",
  "Difficulties make victory even more satisfying.",
  "The harder the battle, the sweeter the victory.",
  "No challenge lasts forever, but your strength will.",
  "Your ability to rise again defines you more than your failures.",
  "Pain is just another word for progress.",
  "Every problem has a solution; you just have to find it.",
  "You are braver than your fears and stronger than your struggles.",
  "Never stop believing in your ability to overcome.",
  "Great journeys begin with difficult first steps.",
  "Each hardship carries a lesson that makes you wiser.",
  "Stay strong—your breakthrough is closer than you think.",
  "You don’t have to be fearless; you just have to be brave enough to take the next step.",
  "Keep moving forward, even if you have to crawl.",
  "Your struggles are just stepping stones to greatness.",
  "Don’t let a moment of difficulty define your destiny.",
  "Every setback prepares you for a greater comeback.",
  "Courage and perseverance will always defeat obstacles.",
  "Challenges strengthen the heart of a warrior.",
  "Your hardships today will be your strengths tomorrow.",
  "You may stumble, but you will not fall.",
  "The path to success is always through adversity.",
  "Fear has no power over a determined mind.",
  "Never let doubt keep you from overcoming challenges.",
  "When everything feels impossible, remember why you started.",
  "Rise stronger with every setback.",
  "Your struggles are the foundation of your future success.",
  "Defeat only exists when you stop trying.",
  "Don’t let obstacles discourage you; let them drive you.",
  "Every problem has a lesson hidden inside.",
  "Strength isn’t measured by ease, but by endurance.",
  "If you refuse to quit, you can never truly fail.",
  "The best way to overcome challenges is to embrace them.",
  "There’s always a way forward if you’re willing to find it.",
  "Adversity sharpens your strength and wisdom.",
  "Difficulties are just preparation for greater things.",
  "No storm lasts forever; endure and rise again.",
  "The more obstacles you face, the stronger you become.",
  "When times are tough, you grow tougher.",
  "Your endurance will write the story of your success.",
  "Through perseverance, even the impossible becomes possible.",
];

final List<String> overcomingImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled overcoming challenges quotes with random images.
final List<QuoteItem> overcomingQuotes = getShuffledQuotes(
  overcomingQuotesRaw,
  overcomingImages,
);
