import '../quotes_randomizer.dart';

/// **The Power of Perseverance Quotes & Images**
final List<String> perseveranceQuotesRaw = [
  "Perseverance is the fuel that drives success.",
  "A dream doesn't become reality through magic; it takes sweat, determination, and hard work.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Perseverance conquers all things.",
  "Never let temporary defeat keep you from permanent success.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "Every champion was once a contender that refused to give up.",
  "Work hard in silence, let your perseverance make the noise.",
  "Perseverance is the act of believing in yourself when no one else does.",
  "The path to success is filled with failures, but those who persevere never truly fail.",
  "When life knocks you down, roll over and look at the stars.",
  "If you want to achieve greatness, stop asking for permission and start persisting.",
  "Stay patient and trust the journey.",
  "Resilience is the art of never giving up, no matter how many times you fall.",
  "Behind every success story is someone who refused to quit.",
  "Your struggles develop your strengths.",
  "If you give up on your dreams, what’s left?",
  "Perseverance is the ability to transform obstacles into opportunities.",
  "Push yourself, because no one else is going to do it for you.",
  "Your biggest challenge isn’t someone else—it’s the voice inside your head.",
  "You were given this life because you are strong enough to live it.",
  "Do what is right, not what is easy, and success will follow.",
  "Perseverance is the ability to keep going when everything seems impossible.",
  "Don’t let a bad day make you think you have a bad life.",
  "It’s not over until you win.",
  "Tough situations build strong people.",
  "The harder you fall, the stronger you rise.",
  "The only way to fail is to quit trying.",
  "The mountain of success is climbed one step at a time.",
  "Difficult roads lead to beautiful destinations.",
  "Those who persist through challenges reach heights others only dream of.",
  "Great things never come from comfort zones.",
  "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
  "Your growth begins the moment you decide not to quit.",
  "Grit is sticking with your future day in and day out.",
  "Let perseverance be your compass when the road gets rough.",
  "You don’t need to see the whole staircase, just take the first step.",
  "Success comes to those who keep moving forward.",
  "The longer the struggle, the sweeter the victory.",
  "Genius is 1% talent and 99% perseverance.",
  "You don’t have to be fast, you just have to keep going.",
  "Victory belongs to the most tenacious.",
  "Rise up stronger every time you fall.",
  "Your determination today shapes your success tomorrow.",
  "Your dreams are worth the fight.",
  "You are one step away from changing your life—keep moving forward.",
  "The best view comes after the hardest climb.",
  "Your perseverance today is your success story tomorrow.",
  "Small steps every day lead to big achievements.",
  "Stay dedicated to your path, no matter how difficult it seems.",
  "There is no failure, only lessons that lead to success.",
  "The greatest battles are won by those who refuse to surrender.",
  "To win without struggle is to triumph without glory.",
  "The strongest steel is forged in the hottest fires.",
  "Every setback is a setup for a comeback.",
  "Your resilience will outshine any obstacle.",
  "Take every challenge as an opportunity to prove your perseverance.",
  "Do not stop when you are tired, stop when you are done.",
  "Life is tough, but so are you.",
  "The secret of success is persistence through failure.",
  "Your hard work will be rewarded in ways you never imagined.",
  "A little more effort, a little more patience, and what seemed hopeless may turn into a glorious success.",
  "Refuse to be discouraged; greatness takes time.",
  "Success isn’t just about talent—it’s about never giving up.",
  "Every failure carries with it the seed of equal or greater success.",
  "If you believe in it, fight for it.",
  "Your greatest achievement is just beyond your greatest struggle.",
  "Perseverance is the courage to keep going even when the path is unclear.",
  "You don’t have to be the best; you just have to be relentless.",
  "Even the darkest night will end, and the sun will rise.",
  "Sometimes the best thing you can do is not give up.",
  "Stay focused, stay persistent, and success will follow.",
  "Strength grows when you refuse to give up.",
  "Never stop believing in yourself.",
  "Your future self will thank you for your perseverance today.",
  "It always seems impossible until it’s done.",
  "You don’t find willpower; you create it through perseverance.",
  "Obstacles are just stepping stones to success.",
  "Patience, persistence, and perspiration make an unbeatable combination.",
  "Success comes to those who dare to stick with it.",
  "One day, your story will inspire others to keep going.",
  "Tough people last; tough times don’t.",
  "Success belongs to those who never stop moving forward.",
  "The real test is not whether you avoid failure, but whether you learn from it and keep going.",
  "Your struggles today are the foundation of your strength tomorrow.",
  "Courage and perseverance have a magical talisman before which difficulties disappear.",
  "A stumble is not a fall; it's a step toward success.",
  "Storms may shake you, but they won’t break you if you keep moving forward.",
  "Keep going, because consistency is the mother of mastery.",
  "One foot in front of the other, even on the hardest days.",
  "The only thing standing between you and success is perseverance.",
  "Your journey is not over until you win.",
  "No matter how slow you go, you're still lapping everyone who stopped.",
  "Success is a marathon, not a sprint—keep running.",
  "A bend in the road is not the end unless you fail to turn.",
  "Whatever you do, never stop believing in yourself.",
  "Don't count the days—make the days count with perseverance.",
  "Perseverance is not a long race; it is many short races one after another.",
  "Keep pushing forward, even when the road seems impossible.",
  "Success is built on a foundation of determination and effort.",
  "A river cuts through rock not because of its power, but because of its persistence.",
  "Perseverance is failing 19 times and succeeding the 20th.",
  "Small daily improvements are the key to long-term success.",
  "When nothing seems to be going right, keep going.",
  "Your journey is defined by how many times you get back up.",
  "Patience, persistence, and perspiration make success possible.",
  "You haven’t come this far to only come this far.",
  "Never let failure be the end of your story.",
  "Champions keep playing until they get it right.",
  "A little progress each day adds up to big results.",
  "Nothing worth having comes easy—keep working for it.",
  "The only way to truly fail is to give up.",
  "Perseverance turns stumbling blocks into stepping stones.",
  "Success is 90% persistence and 10% talent.",
  "You are stronger than the challenges you face.",
  "One small step every day leads to great destinations.",
  "The best things come to those who refuse to quit.",
  "Doubt kills more dreams than failure ever will.",
  "The key to success is to focus on progress, not perfection.",
  "Hard work and perseverance will take you where luck never could.",
  "Setbacks are just setups for comebacks.",
  "Endurance is the ability to keep going when everything tells you to stop.",
  "Success is for those who are willing to keep trying.",
  "Difficulties in life are there to test how badly you want success.",
  "Your ability to persist will determine your ability to succeed.",
  "What seems impossible today will one day be your warm-up.",
  "Perseverance is the path to greatness.",
  "Winners are not those who never fail, but those who never quit.",
  "Strength doesn’t come from winning; it comes from struggles.",
  "Keep your eyes on the goal and never lose focus.",
  "Your effort will pay off, just give it time.",
  "You grow stronger with every challenge you overcome.",
  "Those who keep moving forward reach places others only dream of.",
  "Success demands patience, determination, and grit.",
  "Everything you want is on the other side of perseverance.",
  "There is no substitute for consistent hard work.",
  "The moment you want to quit is the moment you need to push harder.",
  "Stay committed, even when the results take time.",
  "Nothing can stop the person who never gives up.",
  "Dreams are achieved by those who refuse to give up.",
  "You are capable of more than you believe.",
  "Every great success story begins with perseverance.",
  "The key to unlocking your potential is persistence.",
  "Failure is not the opposite of success; it’s part of the journey.",
  "If you stumble, make it part of your dance.",
  "Resilience is built through the storms of life.",
  "Tough times create stronger people.",
  "The harder you work, the greater your results.",
  "Obstacles are opportunities in disguise.",
  "Success is not for the fastest, but for those who keep going.",
  "Your breakthrough is waiting beyond your struggles.",
  "Perseverance is the silent power behind all great achievements.",
  "You don’t have to be perfect—just persistent.",
  "When the world says 'give up,' hope whispers 'try one more time.'",
  "Difficulties strengthen the mind just as labor strengthens the body.",
  "The more you push, the closer you get to success.",
  "Your efforts will be rewarded in due time.",
  "Turn your failures into motivation to succeed.",
  "Greatness comes from never losing faith in yourself.",
  "Keep moving forward, even when progress is slow.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Trust the process and embrace the journey.",
  "Perseverance transforms ordinary people into extraordinary achievers.",
  "Keep fighting for your dreams—they are worth it.",
  "Never stop believing in what you are capable of.",
  "Consistency beats talent when talent doesn’t work hard.",
  "Your story isn’t over yet—keep writing it.",
  "There is no elevator to success; you have to take the stairs.",
  "Growth happens outside of your comfort zone.",
  "Success doesn’t happen overnight; it happens over time.",
  "The best things in life come to those who work for them.",
  "No challenge is too big when you refuse to quit.",
  "Hardships are just stepping stones to something greater.",
  "Never let difficulties define your future.",
  "Persistence is the secret ingredient of every success story.",
  "When you feel like quitting, remember why you started.",
  "The biggest victories come after the hardest battles.",
  "A strong mindset fuels unstoppable perseverance.",
  "Your potential is limitless—never stop pushing forward.",
  "The climb may be tough, but the view is worth it.",
  "Everything gets better when you don’t give up.",
  "Fear fades when you take action.",
  "Grit is the ability to keep going despite uncertainty.",
  "The fire inside you is greater than any challenge ahead.",
  "One day, your struggle will be someone’s inspiration.",
  "Stay strong, stay focused, and success will follow.",
  "Your persistence today creates a better tomorrow.",
  "Behind every success is someone who didn’t quit.",
  "Your efforts will never go unnoticed—keep pushing forward.",
  "Courage and perseverance go hand in hand.",
  "Nothing can break you unless you let it.",
  "Every failure is just a lesson in disguise.",
  "You hold the power to shape your own destiny.",
  "With enough perseverance, even the impossible becomes possible.",
];

final List<String> perseveranceImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled perseverance quotes with random images.
final List<QuoteItem> perseveranceQuotes = getShuffledQuotes(
  perseveranceQuotesRaw,
  perseveranceImages,
);
