import '../quotes_randomizer.dart';

/// **finding purpose in life Quotes & Images**
final List<String> purposeQuotesRaw = [
  "Your purpose in life is to find your purpose and give your whole heart and soul to it.",
  "The meaning of life is to find your gift. The purpose of life is to give it away.",
  "Life is never made unbearable by circumstances, but only by lack of meaning and purpose.",
  "Your work is to discover your world and then with all your heart give yourself to it.",
  "The purpose of our lives is to be happy.",
  "You were born with a purpose; your journey is to uncover it.",
  "When you follow your passion, your purpose will reveal itself.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "Purpose is the reason you journey. Passion is the fire that lights the way.",
  "Your purpose is not something you find; it’s something you build.",
  "A life without purpose is like a ship without a rudder.",
  "What you do today matters because you are exchanging a day of your life for it.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "Finding your purpose is not about you. It’s about how you impact the world.",
  "Passion and purpose go hand in hand. When you discover your passion, you find your purpose.",
  "The secret to success is discovering your purpose and aligning your actions with it.",
  "Fulfillment comes when you live a life driven by purpose, not just ambition.",
  "You weren’t created just to make a living; you were created to make a difference.",
  "Live your life with intention and purpose, and happiness will follow.",
  "Don’t wait for permission to live your purpose—start today.",
  "Every experience, good or bad, is shaping you for something greater.",
  "Find what sets your soul on fire and pursue it relentlessly.",
  "Your dreams are whispers of your true purpose.",
  "True success is living a life aligned with your deepest values and passions.",
  "If you have a strong enough why, you will find the how.",
  "The meaning of life is not to accumulate things, but to contribute something meaningful.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Your life purpose is waiting to be discovered in your greatest passion.",
  "Your uniqueness is your power—embrace it and use it for good.",
  "A fulfilled life is one spent in service of something greater than yourself.",
  "When you love what you do, it never feels like work.",
  "Purpose is not found in comfort zones but in taking risks and following your heart.",
  "Align your actions with your values, and your purpose will become clear.",
  "A meaningful life is one that adds value to others.",
  "Every person is born with a mission—find yours and live it fully.",
  "The greatest tragedy is not death but a life without purpose.",
  "Stop chasing success and start chasing purpose.",
  "True happiness comes from finding and living your life’s mission.",
  "A life filled with purpose is a life filled with joy.",
  "Don’t let fear keep you from your calling.",
  "When you follow your calling, the universe aligns to help you succeed.",
  "Purpose is the bridge between goals and meaning.",
  "Your story matters—live it with purpose.",
  "The things you are passionate about are not random; they are your calling.",
  "Do what makes your soul shine.",
  "Clarity of purpose gives meaning to each step you take.",
  "A meaningful life is about making a difference, not just making a living.",
  "Every day is an opportunity to step closer to your purpose.",
  "Living with purpose turns the ordinary into the extraordinary.",
  "You are never too old or too young to find your true calling.",
  "Your passion is the fuel that ignites your purpose.",
  "Chase purpose, not perfection.",
  "True fulfillment is found in serving something greater than yourself.",
  "Your purpose is the legacy you leave behind.",
  "Find what you love and let it guide you.",
  "When you live with purpose, life becomes an adventure.",
  "Listen to your inner voice—it knows the way.",
  "Stop searching for purpose and start creating it.",
  "A strong purpose gives you the strength to overcome any obstacle.",
  "The best way to predict your future is to create it.",
  "If you don’t design your life’s purpose, someone else will do it for you.",
  "Dream big, but let purpose guide your steps.",
  "Your purpose isn’t a destination; it’s a way of life.",
  "Find your purpose, and you’ll find your peace.",
  "Passion is temporary; purpose lasts forever.",
  "Once you find your purpose, everything else falls into place.",
  "Live every day as if it’s part of your bigger mission.",
  "Your talents are clues to your purpose—use them wisely.",
  "Purpose is not found in what you achieve, but in who you become.",
  "To find your purpose, start with what you love to do.",
  "Helping others is the fastest way to find meaning in life.",
  "Follow your curiosity, and you’ll find your purpose.",
  "Your purpose is bigger than any fear that holds you back.",
  "A purpose-driven life is a powerful life.",
  "Don’t just exist—live with intention and passion.",
  "Your purpose is the compass that guides your journey.",
  "Life’s purpose is not about getting more but giving more.",
  "Find your why, and everything else will make sense.",
  "True wealth is found in a meaningful life, not material things.",
  "The path to your purpose begins with self-discovery.",
  "What you do for others will define your legacy.",
  "Finding purpose is not a one-time event but a lifelong journey.",
  "Live for something greater than yourself.",
  "Your mission in life is where your passion and talent intersect.",
  "You don’t need to have all the answers—just take the first step.",
  "Be brave enough to follow your purpose even when the road is uncertain.",
  "A fulfilled life is lived on purpose, not by accident.",
  "Your purpose should scare you a little and excite you a lot.",
  "Leave the world better than you found it—that is purpose.",
  "What would you do if you weren’t afraid? That’s your purpose calling.",
  "You are here for a reason—make it count.",
  "Every moment spent living your purpose is a moment well spent.",
  "The happiest people are those who live with purpose and intention.",
  "Purpose fuels perseverance, even in the toughest times.",
  "Find the intersection of what you love, what you're good at, and what the world needs.",
  "Live your purpose loudly, unapologetically, and passionately.",
  "Each of us has a unique role to play in the world—find yours and embrace it.",
  "A heart filled with purpose beats with joy.",
  "Follow your dreams, but let purpose be your guide.",
  "You are meant for greatness—walk boldly in your purpose."
      "Purpose is not something you find overnight; it's something you discover through life’s journey.",
  "Your life’s purpose is the key to unlocking your full potential.",
  "You exist for a reason—find it and live it fully.",
  "When you walk in your purpose, you inspire others to find theirs.",
  "Your life has meaning beyond what you can see right now.",
  "Follow your curiosity—it will lead you to your purpose.",
  "A meaningful life is built on passion, service, and intention.",
  "Your purpose is the light that guides you through the darkest times.",
  "Each day is a new opportunity to step closer to your life’s purpose.",
  "Success without purpose is an empty victory.",
  "Purpose-driven people don’t need motivation; their passion fuels them.",
  "Your purpose is the sum of your passions, values, and dreams.",
  "The more you serve others, the clearer your purpose becomes.",
  "A fulfilled life is one where you align your actions with your calling.",
  "True happiness comes when you align your work with your purpose.",
  "Living with purpose turns even the smallest tasks into something meaningful.",
  "Discovering your purpose is a journey, not a destination.",
  "Your struggles are shaping you for the purpose you were meant to fulfill.",
  "Don’t just work for a paycheck; work for a purpose.",
  "Passion fades, but purpose sustains you through the highs and lows.",
  "Live with intention, and your purpose will reveal itself.",
  "Your talents are not random—they are the roadmap to your purpose.",
  "If you feel lost, focus on what excites you—that’s where purpose lies.",
  "A strong sense of purpose fuels perseverance through adversity.",
  "Let go of fear, and step into your purpose with confidence.",
  "Your mission in life is to make the world better, even in small ways.",
  "To find your purpose, follow what makes you feel alive.",
  "Your unique perspective is needed in the world—embrace it.",
  "When you find your why, you can endure any how.",
  "Don’t compare your journey to others—your purpose is uniquely yours.",
  "The greatest tragedy is living without discovering your purpose.",
  "Live for something greater than yourself, and life will become meaningful.",
  "You were created with intention—your purpose is waiting to be discovered.",
  "Each of us has a story to tell and a purpose to fulfill.",
  "Align your choices with your values, and your purpose will shine through.",
  "Your purpose is hidden in the things you love to do effortlessly.",
  "Finding your purpose is about serving, not just achieving.",
  "A life of purpose is a life well lived.",
  "The more you give, the more purpose you will find.",
  "The key to purpose is in the things that bring you deep joy.",
  "Purpose makes even the toughest days worthwhile.",
  "When you know your purpose, obstacles become stepping stones.",
  "Your impact on others is the true measure of your purpose.",
  "You were born to do something amazing—go and find it.",
  "Discovering purpose requires patience, curiosity, and courage.",
  "When you live with purpose, even failures become meaningful.",
  "Your true purpose is found in the things that excite and challenge you.",
  "If you chase meaning, success will follow.",
  "Your life’s purpose is not a job title; it’s how you show up in the world.",
  "You were not created to just exist—you were made to thrive.",
  "Your gifts and passions hold clues to your life’s mission.",
  "What excites you? That’s where your purpose begins.",
  "Live with purpose, and life will reward you with meaning.",
  "Life is too short to live without purpose—find it and pursue it relentlessly.",
  "Your existence is not an accident; there is a reason you are here.",
  "The things you love are not coincidences—they are part of your life’s mission.",
  "Your calling is waiting for you to answer it.",
  "If you don’t know your purpose yet, keep searching—never settle.",
  "Living with purpose gives life a deeper sense of fulfillment.",
  "The more you help others, the clearer your purpose becomes.",
  "You are most powerful when you live in alignment with your purpose.",
  "Your dreams are whispers of your soul’s true calling.",
  "A purpose-driven life is the most rewarding kind of life.",
  "Success is temporary, but purpose lasts a lifetime.",
  "Find your purpose, and everything else will fall into place.",
  "You were designed for greatness—step into your purpose.",
  "Clarity of purpose gives you the energy to push forward.",
  "When you find your why, the how becomes easier.",
  "Your greatest impact will come when you live with purpose.",
  "The search for purpose is a journey worth taking.",
  "Even the smallest actions can serve a greater purpose.",
  "Your purpose is not just about you; it’s about the lives you touch.",
  "True contentment comes from living a purpose-filled life.",
  "Your purpose is calling—are you ready to answer?",
  "The moment you embrace your purpose, your life changes forever.",
  "Each challenge you overcome prepares you for your higher calling.",
  "Your purpose is waiting—it’s up to you to uncover it.",
  "Living in your purpose makes you unstoppable.",
  "The world needs what you have to offer—don’t hold back.",
  "A strong purpose leads to a strong life.",
  "Your best life is one lived with clarity, passion, and purpose.",
  "You were meant to do extraordinary things—believe it.",
  "When you align your life with your purpose, everything makes sense.",
  "Your story has meaning—share it and inspire others.",
  "Your future self is waiting for you to embrace your purpose.",
  "A purpose-filled life is one of joy, growth, and fulfillment.",
  "Find the intersection of what you love and what serves others—that is your purpose.",
  "If your purpose doesn’t scare you a little, dream bigger.",
  "Your journey is unique—don’t let anyone define your purpose for you.",
  "Your potential is limitless when you live with purpose.",
  "You don’t need permission to follow your purpose—just start.",
  "Don’t just make a living—make a difference.",
  "Purpose is the foundation of a truly successful life.",
  "Your best work will come when you are aligned with your purpose.",
  "A meaningful life is one where passion and purpose meet.",
  "Find your purpose, and you will find your inner peace.",
  "Purpose transforms ordinary days into extraordinary experiences.",
  "You were created to create, inspire, and lead—embrace it.",
  "There is no greater adventure than living a purpose-driven life.",
];

final List<String> purposeImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled purpose quotes with random images.
final List<QuoteItem> purposeQuotes = getShuffledQuotes(
  purposeQuotesRaw,
  purposeImages,
);
