name: aarav
description: "Wellness Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  salomon_bottom_bar: ^3.3.2
  audioplayers: ^5.2.1
  page_transition: ^2.2.1
  fab_circular_menu_plus: ^0.0.3
  circular_menu: 
    path: ./packages/circular_menu-4.0.0
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.2.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  record: ^5.2.1
  flutter_sound_record: ^3.3.2
  audio_waveforms: ^1.2.0
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.4


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/test_bg.png
    - assets/images/logo_a.png
    - assets/images/sphere.png
    - assets/images/lips.png
    - assets/images/breathing.png
    - assets/sounds/rhythm-of-life-301382.mp3
    - assets/images/sound.gif
    - assets/images/wp.jpg
    - assets/images/mood_tracker/tired.png
    - assets/images/mood_tracker/sad.png
    - assets/images/mood_tracker/loving.png
    - assets/images/mood_tracker/happy.png
    - assets/images/mood_tracker/good.png
    - assets/images/mood_tracker/average.png
    - assets/images/mood_tracker/annoyed.png
    - assets/images/mood_tracker/angry.png
    # SAVE THIS FILE (press ctrl+s) everytime you add a new image to breathing to refelect changes
    - assets/images/breathing/
    - assets/images/breathing/box_breathing-removebg-preview.png
    - assets/images/breathing/calm.png
    - assets/images/breathing/energy.png
    - assets/images/breathing/health.png


    - assets/images/breathing/night_time-removebg-preview.png
    - assets/images/breathing/box 300/balanced Control Breath.png
    - assets/images/breathing/box 300/Calm and Steady Breath.png
    - assets/images/breathing/box 300/Classic Box Breath.png
    - assets/images/breathing/box 300/Deep Focus Breath.png
    - assets/images/breathing/box 300/Endurance Box Breath.png
    - assets/images/breathing/box 300/Grounding Breath.png
    - assets/images/breathing/box 300/Mental Reset Breath.png
    - assets/images/breathing/box 300/Powerful Presence Breath.png
    - assets/images/breathing/box 300/Stress Relief Box.png

    - assets/images/breathing/calm 300/balance flow.png
    - assets/images/breathing/calm 300/deep stilness.png
    - assets/images/breathing/calm 300/gentle calm.png
    - assets/images/breathing/calm 300/harmony.png
    - assets/images/breathing/calm 300/peaceful mind.png
    - assets/images/breathing/calm 300/quite focus.png
    - assets/images/breathing/calm 300/serene rhythm.png
    - assets/images/breathing/calm 300/stillness.png
    - assets/images/breathing/calm 300/Tranquil mind.png

    - assets/images/breathing/energy 300/Awakening Breath.png
    - assets/images/breathing/energy 300/Dynamic Flow.png
    - assets/images/breathing/energy 300/Energizing Wave.png
    - assets/images/breathing/energy 300/Fire Up Breath.png
    - assets/images/breathing/energy 300/Invigorating Rhythm.png
    - assets/images/breathing/energy 300/Morning Charge.png
    - assets/images/breathing/energy 300/Power Breath.png
    - assets/images/breathing/energy 300/Quick Refresh.png
    - assets/images/breathing/energy 300/Vitality Boost.png

    - assets/images/breathing/health 300/Balanced Wellness Breath.png
    - assets/images/breathing/health 300/Circulation Booster.png
    - assets/images/breathing/health 300/Deep Healing Breath.png
    - assets/images/breathing/health 300/Detox Breath.png
    - assets/images/breathing/health 300/Immune Boost.png
    - assets/images/breathing/health 300/Lung Strengthening Breath.png
    - assets/images/breathing/health 300/Refreshing Breath.png
    - assets/images/breathing/health 300/Rejuvenation Breath.png
    - assets/images/breathing/health 300/Vital Flow Breath.png

    - assets/images/breathing/night 300/calm night.png
    - assets/images/breathing/night 300/deep sleep.png
    - assets/images/breathing/night 300/dream state.png
    - assets/images/breathing/night 300/free mind.png
    - assets/images/breathing/night 300/night relax.png
    - assets/images/breathing/night 300/peaceful rest.png
    - assets/images/breathing/night 300/serene sleep.png
    - assets/images/breathing/night 300/silent night.png
    - assets/images/breathing/night 300/tranquil night.png

    - assets/images/breathing/peformance 300/Endurance Flow.png
    - assets/images/breathing/peformance 300/Flow State Breath.png
    - assets/images/breathing/peformance 300/Focus Booster.png
    - assets/images/breathing/peformance 300/mental clarity breath.png
    - assets/images/breathing/peformance 300/Peak Performance.png
    - assets/images/breathing/peformance 300/Power Rhythm.png
    - assets/images/breathing/peformance 300/Sharpen Focus Breath.png
    - assets/images/breathing/peformance 300/Steady Mind Breath.png
    - assets/images/breathing/peformance 300/precision breath.png

    - assets/images/quotes/Quotes icons/
    - assets/images/quotes/bg/
    - assets/images/sound icons/
    - assets/images/affermations icons/

    - assets/sounds/sound audio/

    - assets/sounds/sound audio/Awake calm music.mp3
    - assets/sounds/sound audio/bird-singing.mp3
    - assets/sounds/sound audio/Gentle River Flow.mp3
    - assets/sounds/sound audio/nature_thunder.mp3
    - assets/sounds/sound audio/Rainfall.mp3
    - assets/sounds/sound audio/Soothing Ocean Waves.mp3
    - assets/sounds/sound audio/thoughtful piano instrumenta (attribution ).mp3
    - assets/sounds/sound audio/WATERFALL.mp3





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package




flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_a.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo_a.png"  # Foreground image
  adaptive_icon_background: "#000000"  # Solid black background

  
     
    