import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> believeinpotentialAffirmationRaw = [
  "I have unlimited potential within me.",
  "I believe in my abilities to achieve greatness.",
  "I am capable of achieving anything I set my mind to.",
  "I trust in my journey and my progress.",
  "I am worthy of success and happiness.",
  "I embrace my strengths and talents fully.",
  "I have the power to shape my own future.",
  "I believe in myself and my dreams.",
  "I am confident in my ability to grow and learn.",
  "I am meant to do amazing things in life.",
  "I have the skills and talent to succeed.",
  "I trust in my inner wisdom to guide me.",
  "I am capable of handling any challenge that comes my way.",
  "I believe that my potential is limitless.",
  "I am strong, capable, and intelligent.",
  "I am on the right path to achieving my dreams.",
  "I choose to see possibilities instead of obstacles.",
  "I believe that I can overcome any setback.",
  "I am constantly growing and improving.",
  "I have everything I need within me to succeed.",
  "I am worthy of all the good things life has to offer.",
  "I trust in my ability to make the best decisions for myself.",
  "I am proud of how far I have come.",
  "I am destined for greatness.",
  "I believe in my ability to turn my dreams into reality.",
  "I am not limited by my past; I am empowered by my future.",
  "I am worthy of all the opportunities that come my way.",
  "I trust myself to take the right steps toward success.",
  "I am full of potential, and I embrace it completely.",
  "I am talented, intelligent, and creative.",
  "I believe in my ability to make a difference in the world.",
  "I am capable of achieving my highest goals.",
  "I trust that my hard work and dedication will pay off.",
  "I am open to learning and growing every day.",
  "I choose to focus on my strengths and abilities.",
  "I am confident in my power to create change.",
  "I am enough just as I am.",
  "I am proud of the progress I make each day.",
  "I believe in my ability to rise above challenges.",
  "I am filled with endless possibilities.",
  "I have the courage to follow my dreams.",
  "I trust in my own unique path to success.",
  "I choose to step into my full potential.",
  "I am worthy of achieving my biggest dreams.",
  "I have the ability to achieve greatness.",
  "I am constantly unlocking new levels of my potential.",
  "I am focused, determined, and ready for success.",
  "I believe that I am destined for something great.",
  "I am grateful for my skills and talents.",
  "I trust that I have what it takes to succeed.",
  "I am capable of incredible things.",
  "I choose to believe in myself every single day.",
  "I am open to all the success that is coming my way.",
  "I am fearless in the pursuit of my goals.",
  "I embrace challenges as opportunities to grow.",
  "I trust in my ability to create a fulfilling life.",
  "I am proud of the person I am becoming.",
  "I allow myself to dream big and aim high.",
  "I am confident in my power to succeed.",
  "I am becoming the best version of myself every day.",
  "I am resilient, strong, and capable of anything.",
  "I choose to move forward with confidence.",
  "I am constantly discovering new strengths within me.",
  "I trust in my unique journey to success.",
  "I am worthy of the life I dream of.",
  "I am a powerful force for success and happiness.",
  "I am limitless in my ability to achieve my goals.",
  "I believe in my unique gifts and talents.",
  "I am open to new possibilities and opportunities.",
  "I trust in my capacity to make a positive impact.",
  "I am strong, smart, and unstoppable.",
  "I allow myself to believe in my highest potential.",
  "I embrace my journey with excitement and confidence.",
  "I am worthy of recognition and success.",
  "I trust that I am on the right path.",
  "I am constantly improving and growing stronger.",
  "I am a magnet for success and abundance.",
  "I believe in my ability to adapt and thrive.",
  "I am surrounded by opportunities for growth and success.",
  "I am capable of making my dreams a reality.",
  "I am fearless in the face of challenges.",
  "I choose to celebrate my progress, no matter how small.",
  "I trust that I am capable of achieving greatness.",
  "I believe in my ability to learn from my experiences.",
  "I allow myself to shine brightly and confidently.",
  "I embrace my personal growth with excitement.",
  "I am deserving of all the success coming my way.",
  "I choose to focus on my strengths and abilities.",
  "I am brave enough to step into my full potential.",
  "I trust that my hard work will lead to success.",
  "I am worthy of my biggest and boldest dreams.",
  "I have the strength and courage to go after what I want.",
  "I am excited about my future and all its possibilities.",
  "I believe that my efforts will bring amazing results.",
  "I am open to all the success coming my way.",
  "I trust in myself and my ability to succeed.",
  "I am committed to reaching my full potential.",
  "I embrace my journey with confidence and joy.",
  "I am unstoppable in the pursuit of my dreams.",
  "I am filled with potential and purpose.",
  "I trust in my ability to achieve my dreams.",
  "I believe in myself and my unique strengths.",
  "I am capable of greatness in all areas of my life.",
  "I am confident in my ability to succeed.",
  "I have the power to create a bright future.",
  "I am worthy of success and happiness.",
  "I have unlimited potential waiting to be explored.",
  "I am strong, intelligent, and capable.",
  "I believe in my ability to overcome obstacles.",
  "I trust my instincts and decisions.",
  "I am resilient and adaptable to change.",
  "I have the courage to step into my greatness.",
  "I am constantly growing and improving.",
  "I am capable of achieving whatever I set my mind to.",
  "I am proud of who I am and who I am becoming.",
  "I embrace challenges as opportunities for growth.",
  "I am open to new possibilities and experiences.",
  "I am confident in my unique path.",
  "I believe in my ability to make a difference.",
  "I am worthy of the life I desire.",
  "I am capable of achieving excellence in all I do.",
  "I trust in my own power to create change.",
  "I am enough, just as I am.",
  "I have the strength to face any challenge.",
  "I believe in my ideas and dreams.",
  "I am proud of my progress, no matter how small.",
  "I trust that I am on the right path.",
  "I embrace my unique talents and abilities.",
  "I am excited about my future and my growth.",
  "I have the power to shape my destiny.",
  "I am constantly learning and evolving.",
  "I am worthy of love, success, and abundance.",
  "I choose to see the best in myself.",
  "I am bold, brave, and unstoppable.",
  "I trust myself to make the right choices.",
  "I am in control of my success and happiness.",
  "I believe in my ability to overcome self-doubt.",
  "I am a powerful force for positive change.",
  "I am grateful for my unique journey.",
  "I trust that my hard work will pay off.",
  "I am capable of turning my dreams into reality.",
  "I embrace my full potential with confidence.",
  "I believe in my ability to rise above challenges.",
  "I am strong enough to handle anything that comes my way.",
  "I am proud of the person I am becoming.",
  "I trust myself to take the next step forward.",
  "I am worthy of every opportunity that comes my way.",
  "I have the courage to follow my dreams.",
  "I am capable of doing incredible things.",
  "I believe in my ability to make things happen.",
  "I am focused, driven, and determined to succeed.",
  "I embrace my journey with confidence and excitement.",
  "I am constantly unlocking new levels of my potential.",
  "I am resilient and capable of achieving greatness.",
  "I trust in my own wisdom and abilities.",
  "I have the strength to push beyond my limits.",
  "I am capable of transforming my life for the better.",
  "I am open to success and new opportunities.",
  "I am a creator of my own success story.",
  "I am brave enough to step out of my comfort zone.",
  "I trust that I am capable of handling anything.",
  "I am constantly proving my potential to myself.",
  "I believe that I have what it takes to succeed.",
  "I choose to focus on my progress, not my fears.",
  "I am surrounded by endless possibilities.",
  "I am excited to see how far I can go.",
  "I am becoming stronger and more capable every day.",
  "I have everything within me to achieve my dreams.",
  "I am capable of learning and growing each day.",
  "I trust in my ability to create a fulfilling life.",
  "I embrace my own path with confidence.",
  "I believe in my ability to inspire others.",
  "I am powerful beyond measure.",
  "I have the talent and skills to reach my goals.",
  "I am worthy of all my achievements.",
  "I trust in the timing of my success.",
  "I am unstoppable when I believe in myself.",
  "I choose to believe in my strengths and abilities.",
  "I am in control of my thoughts and actions.",
  "I am committed to unlocking my full potential.",
  "I am deserving of the success that comes my way.",
  "I am confident in my power to achieve great things.",
  "I am constantly growing into the best version of myself.",
  "I have the potential to do extraordinary things.",
  "I am ready to embrace my full power.",
  "I believe in my ability to accomplish anything.",
  "I am proud of the progress I make every day.",
  "I am strong enough to keep moving forward.",
  "I choose to believe in myself no matter what.",
  "I am open to the limitless opportunities around me.",
  "I trust in my power to create the life I want.",
  "I am determined to succeed and grow.",
  "I am becoming more confident with each passing day.",
  "I have all the skills I need to succeed.",
  "I embrace challenges as stepping stones to greatness.",
  "I am committed to believing in my potential daily.",
  "I am capable of creating an extraordinary future.",
  "I choose to trust my abilities and intuition.",
];

final List<String> believeinpotentialImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> believeinpotentialAffirmation =
    getShuffledaffirmations(
      believeinpotentialAffirmationRaw,
      believeinpotentialImages,
    );
