import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> embracingStrengthsAffirmationRaw = [
  "I am strong, capable, and resilient.",
  "My strengths make me unique and powerful.",
  "I embrace my talents with confidence.",
  "I trust in my abilities to overcome any challenge.",
  "I am worthy of success and happiness.",
  "I celebrate my skills and talents every day.",
  "I grow stronger with each obstacle I overcome.",
  "I have the power to create positive change in my life.",
  "My confidence grows with every step I take.",
  "I am proud of who I am and what I can do.",
  "I believe in myself and my potential.",
  "My strengths shine through in all that I do.",
  "I have the courage to follow my dreams.",
  "I embrace my journey and all the lessons it brings.",
  "I am limitless in my potential and growth.",
  "I turn challenges into opportunities for growth.",
  "I trust myself to make the best decisions for my life.",
  "I radiate confidence and inner strength.",
  "My passion and determination drive me forward.",
  "I have everything I need within me to succeed.",
  "I am resilient in the face of adversity.",
  "I am proud of my progress and achievements.",
  "I am becoming the best version of myself every day.",
  "I have the power to achieve greatness.",
  "I honor and appreciate my unique gifts.",
  "My confidence is unshakable.",
  "I learn and grow from every experience.",
  "I am intelligent, capable, and strong.",
  "My potential is limitless.",
  "I trust myself to handle whatever comes my way.",
  "I believe in my ability to succeed.",
  "I am worthy of my dreams and aspirations.",
  "I am enough just as I am.",
  "My perseverance leads me to success.",
  "I embrace my individuality and celebrate my strengths.",
  "I have the ability to make a difference in the world.",
  "I acknowledge my worth and value.",
  "I am fearless in pursuing my goals.",
  "My talents and abilities are valuable.",
  "I rise above self-doubt and embrace confidence.",
  "I am unstoppable when I believe in myself.",
  "I trust the process of my personal growth.",
  "I am brave, bold, and brilliant.",
  "I acknowledge my achievements and celebrate them.",
  "I am worthy of recognition and success.",
  "I have a strong and resilient mind.",
  "I am the author of my own success story.",
  "I am powerful beyond measure.",
  "I am a force for positivity and change.",
  "I honor my journey and all I have accomplished.",
  "My inner strength guides me through any challenge.",
  "I am confident in my decisions and actions.",
  "I grow stronger with every challenge I face.",
  "I radiate confidence, courage, and inner peace.",
  "I embrace my strengths and use them to uplift others.",
  "I am proud of the person I am becoming.",
  "I am a source of inspiration to those around me.",
  "I am grateful for my strengths and abilities.",
  "I trust myself to make the right choices.",
  "My confidence shines from within.",
  "I embrace my journey, knowing I am on the right path.",
  "I am determined, focused, and strong-willed.",
  "I have the power to shape my own destiny.",
  "I choose to believe in myself every day.",
  "My hard work and dedication lead me to success.",
  "I am a masterpiece in progress.",
  "I embrace my uniqueness with confidence.",
  "I have the courage to stand up for myself.",
  "My voice matters, and I use it with confidence.",
  "I am capable of achieving greatness.",
  "I trust in my ability to create the life I desire.",
  "I am worthy of love, success, and happiness.",
  "I am resilient and capable of handling life's challenges.",
  "I believe in my abilities and trust my intuition.",
  "I have the power to accomplish my goals.",
  "My self-worth is not defined by others' opinions.",
  "I embrace challenges as opportunities to grow.",
  "I am proud of how far I have come.",
  "I am confident in my unique strengths and abilities.",
  "I am deserving of all the good things coming my way.",
  "I am capable of achieving anything I set my mind to.",
  "I let go of self-doubt and embrace my confidence.",
  "I am in control of my own success.",
  "I embrace my imperfections as part of my strengths.",
  "I use my strengths to create a positive impact.",
  "I am a powerhouse of potential and success.",
  "I have the ability to rise above any challenge.",
  "I am always growing, learning, and evolving.",
  "I acknowledge my worth and embrace my greatness.",
  "I am fearless in chasing my dreams.",
  "I have a strong mind and a determined heart.",
  "I turn my dreams into reality with my strengths.",
  "I am capable, confident, and courageous.",
  "My strengths make me extraordinary.",
  "I trust myself to handle any situation.",
  "I am proud of who I am and who I am becoming.",
  "I am bold, brave, and brilliant.",
  "I embrace my strengths and share them with the world.",
  "I am unstoppable, determined, and powerful.",
  "I am proud of the person I am today.",
  "I am a shining example of strength and resilience.",
  "I love and appreciate myself for who I am.",
  "I am the creator of my own success story.",
  "I am confident in my unique abilities.",
  "Every day, I grow stronger and wiser.",
  "My inner strength empowers me to succeed.",
  "I trust my instincts and follow my dreams.",
  "I celebrate my achievements, big and small.",
  "I have the courage to stand in my power.",
  "I am capable of handling anything that comes my way.",
  "My strength lies in my perseverance.",
  "I welcome challenges as opportunities to grow.",
  "I am proud of the skills I have developed.",
  "I believe in myself wholeheartedly.",
  "I turn obstacles into stepping stones.",
  "I am resilient, adaptable, and strong.",
  "I embrace my talents and use them with confidence.",
  "I have the ability to make a difference.",
  "I appreciate my unique strengths and gifts.",
  "I have the power to create my own success.",
  "I am strong, inside and out.",
  "I trust in my ability to make good decisions.",
  "I am courageous in the face of uncertainty.",
  "I recognize my own worth and value.",
  "I have limitless potential within me.",
  "I radiate self-assurance and determination.",
  "I am resourceful and find solutions with ease.",
  "I deserve to take up space and be heard.",
  "I am bold in pursuing my passions.",
  "My persistence leads me to success.",
  "I am a warrior of strength and resilience.",
  "I accept myself as I am, with all my strengths.",
  "I am the architect of my own destiny.",
  "I push past fear and embrace confidence.",
  "I am powerful beyond measure.",
  "My journey is mine to shape and define.",
  "I thrive in every challenge I face.",
  "I bring valuable skills and ideas to the table.",
  "I believe in my ability to rise above setbacks.",
  "I am strong enough to handle anything life brings.",
  "I am constantly improving and evolving.",
  "I am unshakable in my confidence.",
  "I let go of doubt and embrace my abilities.",
  "My hard work and dedication make me unstoppable.",
  "I am a beacon of strength and positivity.",
  "I stand tall, knowing my worth.",
  "I am fearless in striving for greatness.",
  "I am talented, capable, and worthy.",
  "I trust myself to handle any situation.",
  "My challenges only make me stronger.",
  "I embrace my power and use it wisely.",
  "I am enough, just as I am.",
  "I am limitless in what I can achieve.",
  "I honor my strengths and use them wisely.",
  "My success is a reflection of my hard work.",
  "I have everything I need to thrive.",
  "I have the power to shape my reality.",
  "My unique talents add value to the world.",
  "I am an unstoppable force of determination.",
  "I choose to believe in my abilities.",
  "I am confident in my potential to succeed.",
  "I trust in my ability to achieve greatness.",
  "I embrace my uniqueness with pride.",
  "I let go of self-doubt and step into my power.",
  "I am motivated, focused, and determined.",
  "I attract success through my strength and courage.",
  "I am a leader, and my strengths guide me.",
  "I acknowledge and appreciate my own talents.",
  "I am always learning and growing.",
  "I use my strengths to lift others up.",
  "I am in charge of my own destiny.",
  "I overcome obstacles with grace and ease.",
  "I am worthy of all the good in my life.",
  "I trust myself to rise above any challenge.",
  "My confidence grows with each passing day.",
  "I have the strength to face any difficulty.",
  "I embrace my imperfections as part of my greatness.",
  "I am a powerhouse of potential and growth.",
  "I celebrate my strengths without comparison.",
  "I am the best version of myself today.",
  "I stand in my power and embrace my gifts.",
  "I create my own opportunities with confidence.",
  "I let go of fear and step into my greatness.",
  "I am strong in both mind and body.",
  "I have a purpose, and I fulfill it boldly.",
  "I am worthy of success and happiness.",
  "I see my own potential and trust in it.",
  "I am skilled, competent, and talented.",
  "I embrace my growth and trust the process.",
  "My confidence is unwavering.",
  "I trust my inner wisdom and intuition.",
  "I am open to new opportunities for success.",
  "I have a powerful voice that deserves to be heard.",
  "I am grateful for the strength within me.",
  "My past does not define me—my strength does.",
  "I am an example of resilience and determination.",
  "I am courageous in creating the life I want.",
  "I use my strengths to navigate life with ease.",
  "I appreciate my uniqueness and embrace my power.",
  "I celebrate my journey and my progress.",
  "I am meant to do incredible things.",
  "My inner strength is my greatest asset.",
  "I am here to shine, succeed, and thrive.",
];

final List<String> bouncebackImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> embracingStrengthsAffirmation =
    getShuffledaffirmations(embracingStrengthsAffirmationRaw, bouncebackImages);
