import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> overcomedoubtAffirmationRaw = [
  "I trust myself and my abilities.",
  "I am capable and strong.",
  "I release all doubts and embrace confidence.",
  "I am worthy of success and happiness.",
  "I believe in myself and my potential.",
  "I choose to replace fear with faith in myself.",
  "I have everything I need within me to succeed.",
  "I am enough, just as I am.",
  "I let go of negative self-talk and embrace positivity.",
  "I am capable of achieving my dreams.",
  "I believe in my ability to handle challenges.",
  "I deserve to be happy and confident.",
  "I release fear and welcome self-assurance.",
  "I trust the journey of my life.",
  "I am proud of how far I have come.",
  "I am growing, learning, and evolving every day.",
  "I trust myself to make the right choices.",
  "I embrace my uniqueness and celebrate it.",
  "I am resilient and can handle any challenge.",
  "I refuse to let self-doubt hold me back.",
  "I believe in my power to change my life.",
  "I release perfectionism and embrace progress.",
  "I have faith in my ability to succeed.",
  "I am courageous in the face of uncertainty.",
  "I accept myself fully and completely.",
  "I acknowledge my fears but do not let them control me.",
  "I am constantly improving and becoming my best self.",
  "I replace doubt with determination.",
  "I choose to believe in myself every day.",
  "I am more than my mistakes.",
  "I am allowed to take up space and use my voice.",
  "I am a work in progress, and that is okay.",
  "I welcome new opportunities with confidence.",
  "I am grateful for my strengths and abilities.",
  "I am stronger than my doubts.",
  "I am worthy of my dreams and goals.",
  "I embrace challenges as opportunities for growth.",
  "I trust myself to figure things out.",
  "I deserve to feel confident in myself.",
  "I let go of limiting beliefs that hold me back.",
  "I am capable of creating the life I want.",
  "I am learning to love and trust myself more each day.",
  "I speak to myself with kindness and encouragement.",
  "I deserve to be confident and self-assured.",
  "I let go of comparisons and embrace my uniqueness.",
  "I am proud of myself and my progress.",
  "I trust in my ability to overcome any obstacle.",
  "I have the strength to face my fears.",
  "I am not defined by my past mistakes.",
  "I am constantly evolving into a better version of myself.",
  "I am stronger than my insecurities.",
  "I trust in my intuition and decisions.",
  "I am worthy of all the good things in my life.",
  "I choose to focus on my strengths, not my weaknesses.",
  "I release doubt and welcome self-trust.",
  "I trust in my own wisdom and choices.",
  "I am stronger than my fears and doubts.",
  "I let go of self-judgment and embrace self-love.",
  "I am confident in my ability to succeed.",
  "I believe in myself and my unique talents.",
  "I refuse to let doubt control my decisions.",
  "I am worthy of achieving my dreams.",
  "I release all negativity and welcome positivity.",
  "I am proud of who I am and who I am becoming.",
  "I have the strength to overcome any challenge.",
  "I trust myself to take the right steps forward.",
  "I let go of self-doubt and embrace confidence.",
  "I deserve happiness, success, and love.",
  "I am capable of handling whatever comes my way.",
  "I am enough just as I am.",
  "I have everything I need within me to thrive.",
  "I am learning to trust myself more each day.",
  "I acknowledge my fears but refuse to be controlled by them.",
  "I believe in my ability to grow and improve.",
  "I am resilient, strong, and capable.",
  "I trust that I am on the right path.",
  "I am proud of my progress, no matter how small.",
  "I am deserving of love, respect, and kindness.",
  "I am free from self-doubt and full of self-trust.",
  "I can and will overcome any obstacles.",
  "I am powerful beyond measure.",
  "I am courageous and willing to step outside my comfort zone.",
  "I am proud of myself for trying.",
  "I accept myself fully and completely.",
  "I am capable of making great decisions.",
  "I trust in my ability to create the life I desire.",
  "I am worthy of every opportunity that comes my way.",
  "I embrace uncertainty as part of my journey.",
  "I am more than my fears and insecurities.",
  "I deserve success and happiness.",
  "I am confident in my ability to learn and grow.",
  "I release perfectionism and embrace progress.",
  "I am learning to believe in myself more each day.",
  "I am enough, exactly as I am.",
  "I have the power to rewrite my story.",
  "I trust the process of my personal growth.",
  "I am fearless in the pursuit of my dreams.",
  "I replace doubt with confidence and courage.",
  "I let go of limiting beliefs and embrace possibilities.",
  "I am grateful for my strengths and talents.",
  "I deserve to take up space and be heard.",
  "I trust that I am capable of achieving greatness.",
  "I welcome challenges as opportunities for growth.",
  "I am proud of my journey and progress.",
  "I let go of comparisons and embrace my uniqueness.",
  "I am in control of my thoughts and beliefs.",
  "I believe in myself even when things get tough.",
  "I am open to new opportunities and experiences.",
  "I release fear and step forward with confidence.",
  "I am courageous and brave in all that I do.",
  "I celebrate my achievements, no matter how small.",
  "I am strong enough to overcome self-doubt.",
  "I trust my instincts and intuition.",
  "I deserve to believe in myself fully.",
  "I choose confidence over fear.",
  "I am unstoppable in achieving my goals.",
  "I embrace failure as a learning opportunity.",
  "I am in charge of my own happiness and success.",
  "I am grateful for my growth and resilience.",
  "I have a powerful voice that deserves to be heard.",
  "I let go of past mistakes and move forward.",
  "I am constantly evolving into the best version of myself.",
  "I allow myself to be proud of who I am.",
  "I trust myself to make the best choices for my life.",
  "I am brave, strong, and capable.",
  "I believe in my power to change my life.",
  "I embrace my potential and step into my greatness.",
  "I release doubt and step into confidence.",
  "I know that I am worthy of success and happiness.",
  "I choose to see challenges as stepping stones.",
  "I honor my progress and personal growth.",
  "I am confident in my unique abilities.",
  "I radiate self-assurance and inner strength.",
  "I am free from self-doubt and full of self-belief.",
  "I choose to be kind and encouraging to myself.",
  "I trust that I am capable of amazing things.",
  "I am not my past mistakes; I am my potential.",
  "I am enough, just as I am, in this moment.",
  "I believe in my ability to create the life I desire.",
  "I deserve success and fulfillment in all areas of life.",
  "I have the strength to push past my fears.",
  "I allow myself to take risks and grow.",
  "I am courageous, confident, and strong.",
  "I am grateful for the person I am becoming.",
  "I am limitless in my potential and power.",
  "I trust that I am on the right path for me.",
  "I let go of fear and embrace faith in myself.",
  "I speak to myself with kindness and encouragement.",
  "I am proud of my resilience and determination.",
  "I am worthy of all the good that comes my way.",
  "I believe in my talents, skills, and intelligence.",
  "I step forward with confidence and courage.",
  "I am fearless in the face of uncertainty.",
  "I trust that everything is unfolding as it should.",
  "I replace self-doubt with self-belief every day.",
  "I choose to believe in myself wholeheartedly.",
  "I am capable of great things, and I trust in my abilities.",
];

final List<String> overcomingdoubtImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> overcomedoubtAffirmation = getShuffledaffirmations(
  overcomedoubtAffirmationRaw,
  overcomingdoubtImages,
);
