import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> radiateassuranceAffirmationRaw = [
  "I radiate confidence and assurance in all that I do.",
  "I trust in my abilities and my unique talents.",
  "I am secure in who I am and what I stand for.",
  "I move through life with certainty and grace.",
  "I exude self-assurance in every situation.",
  "I believe in my decisions and trust my judgment.",
  "I am comfortable in my own skin and embrace my authenticity.",
  "I am a beacon of strength and confidence.",
  "I carry myself with poise and self-respect.",
  "I trust in my ability to handle anything that comes my way.",
  "I radiate positivity and self-belief.",
  "I am proud of who I am and what I have achieved.",
  "I attract success and opportunities through my assurance.",
  "I speak with clarity, confidence, and conviction.",
  "I trust in my own wisdom and intuition.",
  "I am a source of inspiration and strength to others.",
  "I carry myself with dignity and self-assurance.",
  "I walk into every room knowing I belong.",
  "I am certain of my worth and my value.",
  "I deserve all the success that comes my way.",
  "I project confidence in my body language and voice.",
  "I stand tall, knowing my presence is powerful.",
  "I embrace challenges with a fearless heart.",
  "I trust my inner voice to guide me in the right direction.",
  "I handle every situation with calmness and poise.",
  "I radiate assurance in my words and actions.",
  "I have a strong and unshakable belief in myself.",
  "I am certain of my strengths and abilities.",
  "I trust in my power to create the life I desire.",
  "I inspire others with my confidence and certainty.",
  "I am at peace with myself and my journey.",
  "I am secure in the knowledge that I am enough.",
  "I carry myself with ease, grace, and assurance.",
  "I have unshakable confidence in my potential.",
  "I trust myself to navigate any situation.",
  "I make decisions with clarity and conviction.",
  "I am fully capable of achieving my goals.",
  "I handle uncertainty with confidence and trust.",
  "I trust in my skills and expertise.",
  "I embrace my uniqueness with pride and confidence.",
  "I am powerful, capable, and self-assured.",
  "I radiate assurance in every interaction.",
  "I know my presence makes an impact.",
  "I am unafraid to take up space and be heard.",
  "I am confident in my voice and my message.",
  "I trust myself to rise to any challenge.",
  "I am a leader, and I carry myself as such.",
  "I radiate assurance and inspire confidence in others.",
  "I own my strengths and stand tall in them.",
  "I believe in my worth and act accordingly.",
  "I am the embodiment of self-assurance.",
  "I trust in the power of my presence.",
  "I project unwavering confidence in every step I take.",
  "I am comfortable being seen and heard.",
  "I embrace my personal power with certainty.",
  "I know I am worthy of respect and admiration.",
  "I exude strength, assurance, and resilience.",
  "I have absolute faith in my path and my choices.",
  "I handle criticism with confidence and grace.",
  "I am certain of my talents and abilities.",
  "I walk with purpose and radiate assurance.",
  "I know I have something valuable to offer the world.",
  "I embrace my inner strength and let it shine.",
  "I trust in my ability to succeed in any endeavor.",
  "I am unshakable in my belief in myself.",
  "I project certainty in my thoughts, words, and actions.",
  "I am fearless in the face of challenges.",
  "I radiate a powerful energy of assurance and self-belief.",
  "I believe in my own greatness and act accordingly.",
  "I navigate life with confidence and certainty.",
  "I embrace my journey with trust and assurance.",
  "I am grounded, composed, and self-assured.",
  "I am proud of my progress and trust in my path.",
  "I radiate assurance and positive energy wherever I go.",
  "I trust myself to handle anything that comes my way.",
  "I am a magnet for success because of my confidence.",
  "I know my value and never settle for less.",
  "I make decisions with a strong sense of certainty.",
  "I approach every challenge with a confident mindset.",
  "I embrace my authenticity and let my light shine.",
  "I am worthy of recognition, respect, and admiration.",
  "I am unafraid to step into the spotlight.",
  "I trust in my ability to grow and adapt.",
  "I carry myself with elegance, assurance, and pride.",
  "I know my worth and never doubt my capabilities.",
  "I move with confidence and certainty in my actions.",
  "I am fearless in the pursuit of my dreams.",
  "I embrace change with an open heart and a confident mind.",
  "I radiate assurance in everything I do.",
  "I am in control of my own success and happiness.",
  "I trust in my ability to make the best choices for myself.",
  "I embody self-assurance in all aspects of my life.",
  "I am confident in my ability to inspire and lead.",
  "I attract positive outcomes through my self-belief.",
  "I am the definition of grace, confidence, and assurance.",
  "I let go of fear and embrace my full potential.",
  "I radiate certainty, even in uncertain times.",
  "I have a natural presence that commands respect.",
  "I am at peace with who I am and where I am going.",
  "I am worthy of all the success and happiness I desire.",
  "I am certain of my dreams and take steps toward them daily.",
  "I project inner strength and unwavering confidence.",
  "I trust my ability to learn, adapt, and succeed.",
  "I am comfortable in my own power.",
  "I embrace my uniqueness and let it shine brightly.",
  "I radiate assurance through my actions and words.",
  "I am sure of myself, my choices, and my path.",
  "I trust the process of my life with confidence.",
  "I know I have what it takes to succeed.",
  "I am unshaken by challenges, for I am strong and capable.",
  "I handle setbacks with resilience and assurance.",
  "I trust in my vision and take steps toward it daily.",
  "I deserve all the good that comes into my life.",
  "I am proud of the person I am becoming.",
  "I am powerful beyond measure and embrace it fully.",
  "I radiate assurance effortlessly and naturally.",
  "I trust my journey and know that I am on the right path.",
  "I walk with confidence, knowing I belong.",
  "I exude self-belief in all that I do.",
  "I stand firm in my convictions and values.",
  "I know I am capable of greatness and act accordingly.",
  "I trust in my ability to turn my dreams into reality.",
  "I embrace my self-assurance and let it shine.",
  "I believe in my voice and the impact it can make.",
  "I am a force of confidence and resilience.",
  "I step forward in life with courage and conviction.",
  "I radiate an unstoppable energy of self-belief.",
  "I trust in my ability to thrive and succeed.",
  "I am unshakable, confident, and assured in all I do.",
  "I radiate confidence effortlessly.",
  "I trust myself and my decisions.",
  "I carry myself with strength and grace.",
  "I exude assurance in all that I do.",
  "My presence commands respect and admiration.",
  "I am confident in my abilities.",
  "I walk into every room with poise and certainty.",
  "I believe in myself without hesitation.",
  "I trust my intuition and inner wisdom.",
  "I speak with clarity and conviction.",
  "I am proud of who I am becoming.",
  "I am fearless in expressing my true self.",
  "I embrace my uniqueness with confidence.",
  "I stand tall, knowing my worth.",
  "I radiate a powerful energy of assurance.",
  "I handle challenges with courage and confidence.",
  "I trust my journey and the path ahead.",
  "I am self-assured in my actions and choices.",
  "I attract positive outcomes through my confidence.",
  "I believe in my skills and expertise.",
  "I project certainty in everything I do.",
  "I am unshakable in my belief in myself.",
  "I move forward with strength and conviction.",
  "I let go of doubt and embrace self-trust.",
  "I am a beacon of confidence and inspiration.",
  "I trust in my ability to overcome obstacles.",
  "I radiate assurance in my voice and body language.",
  "I am worthy of success and happiness.",
  "I inspire others with my confidence.",
  "I trust my instincts and follow my heart.",
  "I am calm, composed, and self-assured.",
  "I know I have what it takes to succeed.",
  "I carry myself with elegance and certainty.",
  "I embrace life’s challenges with confidence.",
  "I am in control of my thoughts and emotions.",
  "I trust in my ability to adapt and grow.",
  "I exude positivity and self-belief.",
  "I am a natural leader, confident in my abilities.",
  "I approach every situation with assurance.",
  "I trust in my power to create my own reality.",
  "I hold my head high and speak with authority.",
  "I am fearless in the face of uncertainty.",
  "I am comfortable taking up space and being heard.",
  "I trust in my unique path and purpose.",
  "I radiate a magnetic energy of self-assurance.",
  "I am powerful, capable, and full of confidence.",
  "I know my value and never question it.",
  "I am proud of my journey and all I have achieved.",
  "I am resilient, strong, and unwavering.",
  "I make decisions with confidence and ease.",
  "I radiate assurance and self-respect.",
  "I own my strengths and trust in my potential.",
  "I embrace every opportunity with courage.",
  "I project strength, wisdom, and self-belief.",
  "I am unshaken by challenges or criticism.",
  "I trust myself to always find a way forward.",
  "I carry myself like a person who belongs.",
  "I know my presence makes an impact.",
  "I am fearless in my pursuit of success.",
  "I let go of fear and embrace self-confidence.",
  "I trust my ability to navigate any situation.",
  "I radiate certainty, even in difficult times.",
  "I am secure in who I am and what I offer.",
  "I believe in my ability to achieve greatness.",
  "I step into each day with courage and confidence.",
  "I am bold, brave, and unapologetically myself.",
  "I walk with confidence and a strong sense of self.",
  "I trust in my ability to make the right choices.",
  "I have a presence that commands attention.",
  "I am comfortable in my own power.",
  "I trust in my own journey and timing.",
  "I express myself with confidence and ease.",
  "I trust that I am always on the right path.",
  "I embrace my personal power and use it wisely.",
  "I have unshakable faith in myself.",
  "I carry myself with unwavering self-belief.",
  "I am at peace with who I am.",
  "I project a powerful aura of self-assurance.",
  "I attract success by believing in myself.",
  "I trust in my ability to handle any challenge.",
  "I am confident in my talents and strengths.",
  "I step into new experiences with certainty.",
  "I radiate assurance in all areas of my life.",
  "I am worthy of recognition and appreciation.",
  "I approach life with unwavering self-trust.",
  "I let go of self-doubt and embrace confidence.",
  "I radiate a calm and assured presence.",
  "I trust my voice, my choices, and my power.",
  "I believe in myself wholeheartedly.",
  "I carry myself with assurance and elegance.",
];

final List<String> radiateassuranceImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> radiateassuranceAffirmation =
    getShuffledaffirmations(
      radiateassuranceAffirmationRaw,
      radiateassuranceImages,
    );
