import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> speakconfidentlyAffirmationRaw = [
  "I speak with confidence and clarity.",
  "My words are powerful and impactful.",
  "I express myself with ease and assurance.",
  "I trust my voice and my message.",
  "I communicate my thoughts clearly and effectively.",
  "My voice deserves to be heard.",
  "I am confident in the way I express myself.",
  "I speak my truth with kindness and strength.",
  "I am articulate and well-spoken.",
  "My words inspire and uplift others.",
  "I am calm and composed when I speak.",
  "I express my thoughts with confidence and ease.",
  "I trust myself to say the right words at the right time.",
  "I am fearless in sharing my ideas.",
  "I speak with clarity and conviction.",
  "My voice is strong and steady.",
  "I am a confident and persuasive speaker.",
  "I embrace every opportunity to speak with confidence.",
  "I am comfortable speaking in any situation.",
  "I have the power to communicate effectively.",
  "My words are valuable and meaningful.",
  "I speak from my heart with authenticity.",
  "I articulate my thoughts with confidence and grace.",
  "I speak with passion and purpose.",
  "I believe in the power of my words.",
  "I express my ideas clearly and persuasively.",
  "I trust my ability to communicate effectively.",
  "I speak with enthusiasm and conviction.",
  "I am fearless when expressing my thoughts.",
  "I am in control of my voice and my message.",
  "My voice matters, and I use it wisely.",
  "I am a confident and charismatic speaker.",
  "I share my thoughts boldly and openly.",
  "I express myself with self-assurance.",
  "I am calm, composed, and articulate.",
  "I am confident in my ability to speak in public.",
  "I am a powerful communicator.",
  "I speak with authority and assurance.",
  "I project confidence in every conversation.",
  "My words flow effortlessly and clearly.",
  "I am proud of my voice and the way I communicate.",
  "I speak with poise and clarity.",
  "I welcome the opportunity to express myself.",
  "I trust my instincts when speaking.",
  "I am comfortable speaking in front of others.",
  "I am naturally charismatic and engaging.",
  "I express my opinions with confidence.",
  "I am a skilled and persuasive speaker.",
  "I am always improving my communication skills.",
  "I am articulate and expressive.",
  "I speak with warmth and sincerity.",
  "I confidently express my thoughts and emotions.",
  "I am fearless in stating my beliefs.",
  "I am in tune with my voice and its power.",
  "I communicate with clarity and purpose.",
  "I speak with strength and certainty.",
  "I am at ease speaking my mind.",
  "I speak with confidence, no matter the situation.",
  "I trust my ability to speak eloquently.",
  "I am always calm and collected when I speak.",
  "I enjoy speaking and sharing my ideas.",
  "I am always prepared to speak with confidence.",
  "I have a natural ability to captivate my audience.",
  "I express myself boldly and unapologetically.",
  "My voice is a reflection of my confidence.",
  "I radiate confidence through my words.",
  "I speak with clarity and purpose.",
  "I have the ability to make a lasting impact through my words.",
  "I communicate in a way that is clear and engaging.",
  "I am proud of my ability to articulate my thoughts.",
  "I welcome opportunities to speak and share my ideas.",
  "I trust my voice to convey my message effectively.",
  "I embrace public speaking with confidence and enthusiasm.",
  "I remain poised and confident in all conversations.",
  "I am always in control of my words and tone.",
  "I choose words that empower and uplift others.",
  "I express myself with joy and confidence.",
  "I am a strong and influential speaker.",
  "I am bold and assertive in my communication.",
  "I speak up and stand by my words.",
  "I am comfortable speaking in any setting.",
  "I trust my knowledge and express it confidently.",
  "I enjoy communicating my thoughts with others.",
  "My words are clear, concise, and meaningful.",
  "I am capable of handling any speaking situation.",
  "I am respected and valued for my communication skills.",
  "I speak with intelligence and assurance.",
  "I enjoy sharing my ideas with confidence.",
  "I engage my audience with confidence and authenticity.",
  "I speak with warmth and charisma.",
  "I use my voice to inspire and motivate others.",
  "I express myself in a way that is powerful and engaging.",
  "I communicate with ease, even in challenging situations.",
  "I am always learning and improving my speaking skills.",
  "I am confident in every conversation I have.",
  "I articulate my message with confidence and passion.",
  "I trust my ability to handle difficult conversations.",
  "I am a natural and confident speaker.",
  "I embrace my unique voice and speaking style.",
  "I speak from a place of confidence and knowledge.",
  "I love using my voice to share my thoughts and ideas.",
  "I speak with courage and clarity.",
  "My voice is strong, steady, and powerful.",
  "I trust my ability to communicate effectively.",
  "I am always calm and collected when I speak.",
  "I express my thoughts with confidence and conviction.",
  "My words flow effortlessly and clearly.",
  "I speak with authority and assurance.",
  "My voice is important, and I use it wisely.",
  "I communicate with confidence in all situations.",
  "I am a natural and engaging speaker.",
  "I trust my intuition when speaking.",
  "I embrace every opportunity to express myself.",
  "I speak with purpose and confidence.",
  "My voice commands attention and respect.",
  "I am always improving my speaking skills.",
  "I articulate my words with clarity and precision.",
  "I share my thoughts boldly and authentically.",
  "I speak with warmth and sincerity.",
  "I enjoy speaking and sharing my ideas with others.",
  "I am fearless in expressing my opinions.",
  "My voice carries power, strength, and clarity.",
  "I communicate assertively and effectively.",
  "I am proud of my ability to articulate my thoughts.",
  "I use my words to inspire and empower others.",
  "I speak from the heart with confidence and ease.",
  "I choose my words carefully and communicate clearly.",
  "I express myself in a way that is engaging and effective.",
  "I am comfortable speaking in front of any audience.",
  "I have a natural ability to captivate listeners.",
  "I radiate confidence through my words.",
  "I remain calm and confident in all conversations.",
  "I express myself freely and fearlessly.",
  "I am articulate and well-spoken.",
  "I project confidence in every conversation.",
  "I am skilled at communicating my thoughts clearly.",
  "I trust my ability to speak effectively.",
  "I am always in control of my voice and message.",
  "I welcome the opportunity to speak my mind.",
  "I am a confident and charismatic communicator.",
  "I listen attentively and respond thoughtfully.",
  "I have the courage to speak up and be heard.",
  "I express myself with ease and self-assurance.",
  "My words are valuable, and I use them wisely.",
  "I am comfortable speaking in any situation.",
  "I share my ideas with excitement and clarity.",
  "I am a powerful and influential speaker.",
  "I confidently share my knowledge and insights.",
  "I use my voice to create positive change.",
  "I speak up for myself and what I believe in.",
  "I communicate with grace, confidence, and poise.",
  "I embrace public speaking with enthusiasm and confidence.",
  "I trust my ability to deliver a clear message.",
  "I am fearless in conversations and discussions.",
  "I speak with energy and conviction.",
  "I enjoy expressing my ideas with clarity and confidence.",
  "I have the skills and knowledge to communicate effectively.",
  "I engage my audience with authenticity and confidence.",
  "I remain composed and articulate under pressure.",
  "I express my emotions openly and honestly.",
  "I project positivity through my words and tone.",
  "I enjoy speaking in front of others and sharing my thoughts.",
  "I am proud of the way I express myself.",
  "I trust that my words have impact and meaning.",
  "I speak with wisdom and purpose.",
  "I am calm, composed, and clear in my speech.",
  "I have the confidence to say what needs to be said.",
  "I express my needs and desires clearly and assertively.",
  "I am comfortable and relaxed when speaking.",
  "I am worthy of being heard and respected.",
  "I communicate with passion and purpose.",
  "I allow my voice to shine in every conversation.",
  "I am eloquent and persuasive in my speech.",
  "I trust my instincts when choosing my words.",
  "I welcome constructive discussions with confidence.",
  "I stand by my words and speak my truth.",
  "I embrace my voice and speak my mind freely.",
  "I am always prepared to communicate my thoughts clearly.",
  "I use my voice to connect and inspire others.",
  "I trust my ability to engage people with my words.",
  "I am fearless in expressing my creativity and ideas.",
  "I communicate with enthusiasm and authenticity.",
  "I have the courage to speak in any situation.",
  "I confidently deliver my message in a meaningful way.",
  "I remain strong and confident in debates and discussions.",
  "I am clear, concise, and compelling when I speak.",
  "I express myself with passion and clarity.",
  "I believe in my ability to communicate powerfully.",
  "I am always learning and improving my speaking skills.",
  "I make a positive impact with my words.",
  "I am relaxed and self-assured in all conversations.",
  "I trust my ability to communicate my needs and desires.",
  "I have the courage to voice my thoughts without fear.",
  "I speak with self-respect and confidence.",
  "I allow my authentic voice to shine through.",
  "I am articulate, persuasive, and engaging.",
  "I express myself without hesitation or doubt.",
  "I am a confident and effective communicator.",
  "I trust that my words make a difference.",
  "I communicate my ideas with strength and passion.",
  "I am at ease when speaking to any audience.",
  "I inspire others with my words and confidence.",
  "I love the sound of my voice when I speak confidently.",
];

final List<String> speakconfidentlyImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> speakconfidentlyAffirmation =
    getShuffledaffirmations(
      speakconfidentlyAffirmationRaw,
      speakconfidentlyImages,
    );
