import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> trustdecisionsAffirmationRaw = [
  "I trust myself to make the right choices.",
  "My decisions are guided by wisdom and intuition.",
  "I am confident in my ability to choose wisely.",
  "I release doubt and embrace trust in my decisions.",
  "I honor my inner voice and trust its guidance.",
  "I make decisions with clarity and confidence.",
  "Every choice I make aligns with my highest good.",
  "I trust the process of my life unfolding.",
  "I am capable of making the best decisions for myself.",
  "I let go of fear and trust in my own judgment.",
  "I believe in the choices I make every day.",
  "My instincts lead me in the right direction.",
  "I trust that every decision I make serves my growth.",
  "I listen to my heart and follow its wisdom.",
  "I am empowered to make decisions with confidence.",
  "I make choices that align with my goals and values.",
  "I trust in my ability to navigate challenges.",
  "Every decision I make is an opportunity to learn and grow.",
  "I am wise, thoughtful, and capable of making great choices.",
  "I trust that the universe supports my decisions.",
  "My choices reflect my true self and desires.",
  "I am free from self-doubt and second-guessing.",
  "I embrace change and trust my ability to adapt.",
  "I make decisions that bring me peace and happiness.",
  "I confidently move forward, knowing I am on the right path.",
  "My choices are made with love and intention.",
  "I trust my journey and the direction I am headed.",
  "I have the power to make decisions that shape my future.",
  "I am at peace with the choices I make.",
  "I trust my ability to handle whatever comes my way.",
  "I confidently make decisions that align with my purpose.",
  "I release the need for external validation and trust myself.",
  "My decisions are a reflection of my wisdom and experience.",
  "I am in control of my choices and my life.",
  "I let go of overthinking and trust my instincts.",
  "I trust that everything is unfolding for my highest good.",
  "I am decisive and take action with confidence.",
  "My intuition is a powerful guide in my decision-making.",
  "I make choices based on love, not fear.",
  "I honor my needs and trust my ability to fulfill them.",
  "I have the courage to make bold and confident decisions.",
  "I listen to my inner wisdom and trust its guidance.",
  "I make decisions that support my well-being and happiness.",
  "I trust my past decisions and the lessons they have taught me.",
  "I am free from regret because I trust my choices.",
  "I trust that I am always on the right path.",
  "Every decision I make brings me closer to my goals.",
  "I embrace uncertainty with trust in my abilities.",
  "I make choices that lead me to success and fulfillment.",
  "I am strong and capable of making the best decisions.",
  "I trust myself even when faced with difficult choices.",
  "I make decisions that bring balance and harmony to my life.",
  "I release the fear of making mistakes and trust my growth.",
  "I confidently follow my dreams and make choices that support them.",
  "I trust that I am always learning and evolving.",
  "I am worthy of making decisions that serve me.",
  "I am grateful for my ability to choose what’s best for me.",
  "I make empowered decisions that align with my vision.",
  "I have faith in my ability to make sound choices.",
  "I embrace the power of decision-making in my life.",
  "I trust that the right opportunities come from the decisions I make.",
  "I make thoughtful and mindful decisions.",
  "I give myself permission to make decisions without fear.",
  "I trust that my choices lead me to abundance and happiness.",
  "I am at peace with the path I have chosen.",
  "I choose to move forward with faith and confidence.",
  "I am the best person to make decisions for my life.",
  "I honor my journey and trust the steps I take.",
  "I trust in the lessons that come with every decision.",
  "I am fearless in making decisions that align with my truth.",
  "I make choices that support my highest potential.",
  "I am confident in my ability to handle the outcomes of my decisions.",
  "I embrace responsibility for my choices with confidence.",
  "I trust my ability to create the life I desire.",
  "I am grateful for the wisdom that guides my choices.",
  "I am a capable decision-maker, and I trust myself completely.",
  "I make decisions that are right for me, regardless of others' opinions.",
  "I choose to be decisive and trust the process.",
  "I am at peace with the choices I have made.",
  "I make powerful decisions that shape my success.",
  "I trust that I always make the best choice available to me.",
  "I am courageous in making decisions that serve my happiness.",
  "I trust that every decision I make aligns with my purpose.",
  "I listen to my heart and follow my inner guidance.",
  "I have faith in my ability to create the future I want.",
  "I make decisions that empower and uplift me.",
  "I let go of uncertainty and embrace trust in myself.",
  "I am always in alignment with my highest wisdom.",
  "I trust my past, present, and future decisions.",
  "I choose to believe in my ability to make great choices.",
  "I trust the timing of my decisions and their impact on my journey.",
  "I release hesitation and embrace bold decision-making.",
  "I am confident in my ability to handle any consequences.",
  "I trust that my choices bring me closer to my dreams.",
  "I make decisions from a place of strength and clarity.",
  "I am grateful for the ability to make choices for myself.",
  "I know that my decisions shape my success, and I trust them.",
  "I trust in my ability to make wise and empowering decisions.",
  "I move forward with confidence, trusting every step I take.",
  "I make decisions with confidence and clarity.",
  "My choices are a reflection of my wisdom and experience.",
  "I trust myself to choose what is best for me.",
  "I am guided by intuition and inner wisdom.",
  "Every decision I make helps me grow and evolve.",
  "I release fear and trust my instincts.",
  "I honor my choices and stand by them with confidence.",
  "I am always learning, and my decisions reflect my growth.",
  "I trust myself to make the right choices at the right time.",
  "My decisions shape my success and happiness.",
  "I have the power to make choices that align with my highest self.",
  "I embrace uncertainty and trust my ability to navigate it.",
  "I am fully capable of making decisions that benefit me.",
  "I listen to my heart and make choices that feel right.",
  "I believe in my ability to make smart and informed decisions.",
  "I am confident in my ability to solve problems effectively.",
  "I make decisions with courage and strength.",
  "I trust the process and know that I am on the right path.",
  "I am free from the need to second-guess my choices.",
  "My choices are a reflection of my strength and resilience.",
  "I release self-doubt and embrace my decision-making power.",
  "I choose to trust myself in all situations.",
  "I am calm and confident in my choices.",
  "I listen to my inner voice and honor its guidance.",
  "I am in control of my life and my decisions.",
  "I trust that every choice I make is leading me to success.",
  "I allow myself to make decisions without overthinking.",
  "My past choices have brought me to where I am meant to be.",
  "I accept and trust the decisions I make.",
  "I make decisions that align with my goals and aspirations.",
  "I am proud of the choices I make every day.",
  "I trust my ability to make decisions that support my well-being.",
  "I have everything I need to make the right decisions.",
  "I move forward with faith in my decisions.",
  "I trust myself even when I don’t have all the answers.",
  "I am at peace with the choices I have made.",
  "I am worthy of making decisions that bring me happiness.",
  "I make bold and decisive choices with ease.",
  "I trust that my decisions are leading me toward fulfillment.",
  "I have faith in my ability to handle any outcome.",
  "I trust the timing of my decisions and my journey.",
  "I let go of the past and focus on the present choices I make.",
  "I am responsible for my choices, and I own them with confidence.",
  "I release hesitation and embrace my decision-making power.",
  "I make choices that align with my values and beliefs.",
  "I am courageous in making decisions that support my dreams.",
  "I am capable of handling whatever comes from my choices.",
  "I embrace my decision-making skills with gratitude.",
  "I trust that my choices are divinely guided.",
  "I make choices from a place of love and trust.",
  "I welcome the freedom that comes with making decisions.",
  "I let go of fear and move forward with trust in my choices.",
  "I am confident in my ability to create a life I love.",
  "I choose to trust myself fully in all situations.",
  "My decisions are in alignment with my highest good.",
  "I trust that everything is unfolding as it should.",
  "I am learning to trust myself more each day.",
  "I trust that my choices lead me to the right opportunities.",
  "I believe in my ability to choose what is best for me.",
  "I let go of worry and embrace trust in my journey.",
  "I know that I am capable of making great decisions.",
  "I make decisions with a clear mind and an open heart.",
  "I release the fear of making mistakes and embrace learning.",
  "I am at peace with my past decisions and embrace my future.",
  "I trust myself to make decisions that bring me joy.",
  "My choices are a reflection of my confidence and trust in myself.",
  "I trust my journey, even when I can’t see the full path.",
  "I believe in the power of my own choices.",
  "I give myself permission to trust my gut feelings.",
  "I have the wisdom to make the best decisions for my life.",
  "I trust in the lessons that come with every choice.",
  "I am fearless in making decisions that align with my purpose.",
  "I embrace the unknown with trust and excitement.",
  "I release anxiety and replace it with trust in my choices.",
  "I trust my ability to recognize the best path for me.",
  "I make decisions with confidence, knowing I am capable.",
  "I listen to my inner guidance and trust its wisdom.",
  "I make choices that align with my soul’s purpose.",
  "I choose trust over fear in all decision-making.",
  "I am the best person to decide what is right for me.",
  "I embrace my power to choose my own path.",
  "I trust that the right opportunities will come from my choices.",
  "I make decisions with confidence and determination.",
  "I am at peace with the choices I make.",
  "I have faith in my ability to create a fulfilling life.",
  "I trust my strengths and skills in decision-making.",
  "I am brave enough to make the decisions that serve me best.",
  "I am in harmony with my choices and my journey.",
  "I embrace trust and let go of self-doubt.",
  "I release the need for approval and trust my inner voice.",
  "I allow myself to be decisive and trust my own path.",
  "I trust my experiences to guide me in making great decisions.",
  "I choose to make empowered and confident decisions.",
  "I am in tune with my inner wisdom and trust my intuition.",
  "I trust the flow of life and my place within it.",
  "I embrace trust as a daily practice in my life.",
  "I trust that my decisions are shaping a brighter future for me.",
];

final List<String> trustdecisionsImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> trustdecisionsAffirmation = getShuffledaffirmations(
  trustdecisionsAffirmationRaw,
  trustdecisionsImages,
);
