import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> balancedlivingAffirmationRaw = [
  "I nourish my mind with positive and peaceful thoughts.",
  "I allow myself to take breaks when needed.",
  "I am in control of my thoughts and emotions.",
  "I choose to focus on what truly matters in my life.",
  "I make time for self-reflection and inner peace.",
  "I am grateful for the balance I cultivate in my life.",
  "I release all worries and embrace peace.",
  "I create space for both work and rest in my life.",
  "I trust in my ability to handle life's ups and downs.",
  "I prioritize my mental well-being daily.",
  "I embrace mindfulness and stay present in the moment.",
  "I am free from the pressure to be perfect.",
  "I allow myself to slow down and enjoy life.",
  "I release stress and invite calmness into my mind.",
  "I choose thoughts that bring me peace and clarity.",
  "I let go of distractions and focus on what serves me.",
  "I cultivate a mindset of balance and harmony.",
  "I find joy in the simple moments of life.",
  "I trust in the flow of life and embrace its rhythm.",
  "I accept myself as I am, while striving to grow.",
  "I allow myself to feel and express my emotions freely.",
  "I am kind to myself, even on difficult days.",
  "I practice self-compassion and self-love.",
  "I embrace both my strengths and my imperfections.",
  "I am patient with myself and my emotions.",
  "I release negative emotions and welcome positivity.",
  "I am emotionally strong and resilient.",
  "I find balance between my emotions and rationality.",
  "I allow joy and love to fill my heart daily.",
  "I nurture my emotional well-being with kindness.",
  "I accept change as a natural part of life.",
  "I trust my emotions to guide me, not control me.",
  "I set healthy boundaries to protect my emotional energy.",
  "I welcome happiness and fulfillment into my life.",
  "I allow myself to rest and recharge emotionally.",
  "I handle life's challenges with grace and wisdom.",
  "I am surrounded by love and support.",
  "I express gratitude for my emotions, as they guide me.",
  "I am at peace with my past, present, and future.",
  "I embrace balance in my relationships and emotions.",
  "I listen to my body and honor its needs.",
  "I nourish my body with healthy and energizing foods.",
  "I allow my body the rest it deserves.",
  "I make time for movement that brings me joy.",
  "I choose to respect and care for my body daily.",
  "I embrace physical activity as a way to recharge.",
  "I maintain a balance between activity and relaxation.",
  "I treat my body as a temple of health and strength.",
  "I am in tune with my body's signals and needs.",
  "I give myself permission to slow down when needed.",
  "I am grateful for my body and all it allows me to do.",
  "I take deep breaths and allow relaxation to fill me.",
  "I balance effort with rest, knowing both are important.",
  "I hydrate my body and keep it refreshed.",
  "I prioritize sleep and recovery as part of self-care.",
  "I move with energy and embrace an active lifestyle.",
  "I trust my body's wisdom and take care of it daily.",
  "I maintain a healthy balance between work and play.",
  "I appreciate my body and treat it with love and care.",
  "I find joy in keeping my body active and strong.",
  "I set boundaries that support my well-being.",
  "I make time for both productivity and relaxation.",
  "I value my time and use it wisely.",
  "I allow myself to step away from work when needed.",
  "I create a work-life balance that feels right for me.",
  "I find fulfillment in both work and personal life.",
  "I prioritize rest without feeling guilty.",
  "I am productive without compromising my peace.",
  "I manage my time with balance and intention.",
  "I trust that I am doing enough each day.",
  "I enjoy my work while making time for joy and play.",
  "I release guilt about taking time for myself.",
  "I embrace moments of stillness and presence.",
  "I allow myself to unplug and recharge.",
  "I am focused during work and relaxed during rest.",
  "I find joy in small moments throughout the day.",
  "I separate work and personal life to maintain balance.",
  "I celebrate progress, not just productivity.",
  "I allow balance to guide my daily schedule.",
  "I am creating a life where both work and play matter.",
  "I connect with my inner peace every day.",
  "I trust in the journey and timing of my life.",
  "I am aligned with my purpose and passion.",
  "I make time for quiet reflection and self-discovery.",
  "I am deeply connected to my higher self.",
  "I surrender control and trust the universe.",
  "I embrace life with an open heart and open mind.",
  "I trust that everything is unfolding as it should.",
  "I am guided by my intuition and inner wisdom.",
  "I find meaning and fulfillment in every moment.",
  "I welcome peace and harmony into my life.",
  "I am open to the lessons that life has to offer.",
  "I find joy in the journey, not just the destination.",
  "I cultivate a sense of gratitude and presence.",
  "I accept that balance is a continuous journey.",
  "I release what no longer serves me and embrace growth.",
  "I allow stillness to bring me clarity and peace.",
  "I trust that I am exactly where I need to be.",
  "I embrace balance in mind, body, and soul.",
  "I am at peace with the present and excited for the future.",
  "I nurture relationships that bring me joy and balance.",
  "I give and receive love freely.",
  "I communicate openly and honestly in my relationships.",
  "I surround myself with people who uplift and inspire me.",
  "I maintain a balance between socializing and solitude.",
  "I allow myself to enjoy meaningful connections.",
  "I choose relationships that support my well-being.",
  "I give myself permission to say no when needed.",
  "I create space for quality time with loved ones.",
  "I maintain a balance between giving and receiving.",
  "I welcome healthy, supportive relationships into my life.",
  "I let go of toxic relationships that drain my energy.",
  "I make time for deep and meaningful conversations.",
  "I appreciate the people who bring joy into my life.",
  "I respect my own needs while supporting others.",
  "I trust that the right people will enter my life.",
  "I enjoy time with others while honoring my alone time.",
  "I set boundaries that protect my energy and peace.",
  "I create space for love, laughter, and connection.",
  "I balance my social life with my personal well-being.",
  "I create balance in my thoughts and emotions.",
  "I trust myself to handle challenges with grace.",
  "I am present in each moment and embrace life fully.",
  "I release the need for perfection and embrace progress.",
  "I allow myself to pause and reset when needed.",
  "I let go of what I cannot control and focus on peace.",
  "I create time for both productivity and relaxation.",
  "I honor my limits and respect my energy levels.",
  "I choose thoughts that nourish and empower me.",
  "I give myself permission to slow down and breathe.",
  "I acknowledge my emotions and respond with kindness.",
  "I embrace challenges as opportunities for growth.",
  "I give myself the love and support I need.",
  "I release self-judgment and allow self-compassion.",
  "I am in harmony with my emotions and my inner world.",
  "I set boundaries that protect my emotional well-being.",
  "I trust my emotions to guide me in a healthy way.",
  "I am patient with myself as I cultivate balance.",
  "I respect my body's need for both activity and rest.",
  "I make choices that support my physical well-being.",
  "I nourish my body with healthy and energizing food.",
  "I move my body in ways that bring me joy.",
  "I listen to my body and give it what it needs.",
  "I embrace a lifestyle that supports my well-being.",
  "I prioritize rest and relaxation without guilt.",
  "I hydrate and fuel my body with love and care.",
  "I release tension and invite relaxation into my body.",
  "I honor my body's need for movement and stillness.",
  "I maintain a healthy balance between work and play.",
  "I give myself permission to rest and recharge.",
  "I am productive, yet I prioritize self-care.",
  "I create boundaries that allow me to enjoy life fully.",
  "I make space for joy, creativity, and relaxation.",
  "I am not defined by my work alone.",
  "I deserve time for both success and serenity.",
  "I balance ambition with self-care and rest.",
  "I respect my own time and energy.",
  "I trust myself to manage my responsibilities with ease.",
  "I am in tune with my inner peace and purpose.",
  "I embrace stillness and allow clarity to guide me.",
  "I release worries and trust in the flow of life.",
  "I allow myself to connect with my deeper self.",
  "I make time for reflection and spiritual growth.",
  "I trust in the timing of my journey.",
  "I let go of what no longer serves me.",
  "I surrender control and embrace faith in my path.",
  "I cultivate inner harmony and balance.",
  "I am deeply connected to my intuition and wisdom.",
  "I nurture relationships that bring me peace and joy.",
  "I balance my social time with solitude and self-care.",
  "I surround myself with people who uplift me.",
  "I give and receive love freely and openly.",
  "I respect my energy levels when socializing.",
  "I communicate my needs and boundaries with love.",
  "I make time for meaningful connections.",
  "I enjoy socializing without overextending myself.",
  "I prioritize relationships that align with my values.",
  "I am grateful for the love and support in my life.",
  "I balance work, rest, and play with ease.",
  "I prioritize what truly matters in my daily life.",
  "I create time for joy and relaxation every day.",
  "I handle responsibilities without feeling overwhelmed.",
  "I take things one step at a time.",
  "I make time for both adventure and quiet moments.",
  "I trust that I am doing enough each day.",
  "I create a lifestyle that supports balance and harmony.",
  "I allow myself to enjoy the present moment.",
  "I choose to live with ease and flow.",
  "I release stress and invite calmness into my life.",
  "I trust that I can handle whatever comes my way.",
  "I respond to stress with clarity and composure.",
  "I am centered, grounded, and at peace.",
  "I let go of unnecessary worries and focus on peace.",
  "I create space for deep relaxation and renewal.",
  "I release the urge to rush and embrace the present.",
  "I breathe deeply and allow stress to melt away.",
  "I choose to approach challenges with a calm mind.",
  "I find balance even in the busiest moments.",
  "I honor my needs and prioritize self-care.",
  "I listen to my heart and follow what feels right.",
  "I am kind and compassionate toward myself.",
  "I embrace self-care as an essential part of my life.",
  "I trust that taking care of myself is productive.",
  "I let go of guilt for putting myself first.",
  "I choose self-love in every moment.",
  "I create time for activities that nourish my soul.",
  "I deserve rest, joy, and fulfillment.",
  "I allow myself to relax without feeling guilty.",
  "I embrace balance in all aspects of my life.",
  "I welcome peace and harmony into my day.",
  "I trust myself to make choices that support balance.",
  "I approach each day with a sense of calm and ease.",
  "I am committed to creating a balanced life.",
  "I invite balance into my thoughts, actions, and habits.",
  "I choose to live in a way that supports my well-being.",
  "I honor the rhythm of my life and trust its flow.",
  "I find joy in the balance I create for myself.",
  "I am in alignment with a life of balance and fulfillment.",
];

final List<String> balancedlivingImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> balancedlivingAffirmation = getShuffledaffirmations(
  balancedlivingAffirmationRaw,
  balancedlivingImages,
);
