import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> liveharmonyAffirmationRaw = [
  "I choose to live in peace and harmony.",
  "I am in sync with the natural rhythm of life.",
  "I cultivate harmony within myself and my surroundings.",
  "I radiate peace and kindness wherever I go.",
  "I choose love, compassion, and understanding.",
  "I embrace the balance of life with gratitude.",
  "I am connected to the harmony of the universe.",
  "I find joy in the simple moments of life.",
  "I honor my inner peace above all else.",
  "I am calm, centered, and grounded.",
  "I let go of negativity and invite harmony into my life.",
  "I welcome balance in all aspects of my life.",
  "I live in alignment with my values and beliefs.",
  "I respect and honor the differences in others.",
  "I choose to respond with love and patience.",
  "I am at peace with myself and the world.",
  "I create harmonious relationships with ease.",
  "I choose thoughts that bring peace and clarity.",
  "I accept and embrace life as it unfolds.",
  "I live in the present moment with gratitude.",
  "I listen with an open heart and mind.",
  "I am in harmony with the energy around me.",
  "I release all resistance and flow with life.",
  "I radiate calmness and serenity in every situation.",
  "I allow myself to live peacefully and freely.",
  "I choose harmony over conflict.",
  "I respect my own needs and the needs of others.",
  "I create a peaceful environment wherever I go.",
  "I honor the beauty of nature and my connection to it.",
  "I communicate with kindness and understanding.",
  "I trust the journey of my life.",
  "I forgive myself and others, allowing peace to flow.",
  "I embrace the ebb and flow of life with ease.",
  "I focus on the good in myself and those around me.",
  "I find harmony in the balance between work and rest.",
  "I breathe in calmness and exhale stress.",
  "I choose to see the best in every situation.",
  "I am grateful for the harmony in my life.",
  "I let go of expectations and trust the process.",
  "I cultivate mindfulness in my daily life.",
  "I seek solutions that bring peace and unity.",
  "I am surrounded by peaceful and positive energy.",
  "I create harmony through my words and actions.",
  "I respect and nurture the relationships in my life.",
  "I choose to live with kindness and patience.",
  "I release tension and welcome relaxation.",
  "I welcome calmness and tranquility into my life.",
  "I am open to giving and receiving love freely.",
  "I flow with the rhythm of life effortlessly.",
  "I see beauty and harmony in everything around me.",
  "I embrace change with a peaceful heart.",
  "I trust in the divine timing of the universe.",
  "I let go of control and allow life to unfold.",
  "I am connected to a deep sense of inner peace.",
  "I attract peace and serenity into my life.",
  "I am aligned with the harmony of the universe.",
  "I release all fear and welcome love.",
  "I appreciate the peace and balance in my life.",
  "I live each moment with grace and ease.",
  "I am free from unnecessary worries and fears.",
  "I treat myself and others with love and respect.",
  "I am a beacon of peace in a chaotic world.",
  "I choose to focus on harmony and positivity.",
  "I am grateful for the love and peace within me.",
  "I create a life filled with joy, balance, and peace.",
  "I am in harmony with the people around me.",
  "I trust that everything is working for my highest good.",
  "I am open to new perspectives and peaceful solutions.",
  "I choose to be a source of peace and love.",
  "I balance my needs with the needs of others.",
  "I release stress and welcome tranquility.",
  "I welcome peace into my heart, mind, and soul.",
  "I create harmony in my thoughts and actions.",
  "I choose words that uplift and inspire.",
  "I am grateful for the peace that surrounds me.",
  "I honor the sacred balance of life.",
  "I attract loving and peaceful relationships.",
  "I embrace life's challenges with a calm mind.",
  "I am surrounded by harmony and positivity.",
  "I trust in the power of kindness and compassion.",
  "I embrace stillness and silence as a source of strength.",
  "I create balance between my heart and mind.",
  "I see love and peace in all beings.",
  "I choose patience and understanding in all situations.",
  "I live in harmony with my true self.",
  "I trust that inner peace brings outer harmony.",
  "I embrace life's flow with ease and grace.",
  "I find joy in simplicity and balance.",
  "I am deeply connected to the peace within me.",
  "I trust the universe to guide me toward peace.",
  "I release past hurts and invite peace into my heart.",
  "I am at home in the stillness of my soul.",
  "I honor and respect the energy of those around me.",
  "I choose inner harmony over external chaos.",
  "I allow myself to rest and recharge in peace.",
  "I let go of the need to control everything.",
  "I make space for harmony in my daily life.",
  "I seek peace within before seeking it externally.",
  "I cherish the moments of peace in my life.",
  "I create a sanctuary of peace within my mind.",
  "I choose to live in love and harmony every day.",
  "I am in perfect balance with myself and the world.",
  "I trust that my inner peace influences my outer world.",
  "I cultivate an attitude of gratitude and serenity.",
  "I find harmony by accepting myself fully.",
  "I allow peace to flow through me effortlessly.",
  "I embrace life’s natural cycles with understanding.",
  "I appreciate the gift of each peaceful moment.",
  "I am patient, kind, and compassionate with myself.",
  "I attract people and experiences that bring peace.",
  "I trust in the divine balance of the universe.",
  "I breathe deeply and release all tension.",
  "I live each day with a heart full of peace.",
  "I create a life of joy, love, and balance.",
  "I celebrate the harmony that exists within and around me.",
  "I make choices that align with my inner peace.",
  "I am worthy of a peaceful and harmonious life.",
  "I choose to be a source of light and harmony.",
  "I bring balance to my relationships and interactions.",
  "I am present, peaceful, and deeply content.",
  "I am grateful for the harmony in my life today and always.",
  "I accept and embrace peace as my natural state.",
  "I trust that everything is unfolding perfectly.",
  "I release all distractions and focus on inner harmony.",
  "I choose to see peace in every situation.",
  "I align myself with the frequency of harmony.",
  "I live with an open heart and a peaceful mind.",
  "I walk my path with grace and serenity.",
  "I choose to live in peace and harmony every day.",
  "I am at peace with myself and the world around me.",
  "I release all negativity and welcome balance.",
  "I am aligned with the natural flow of life.",
  "I create a peaceful space within and around me.",
  "I embrace stillness and serenity in my life.",
  "I radiate love, kindness, and harmony.",
  "I listen to my inner wisdom and trust my path.",
  "I respect and honor the energy of others.",
  "I cultivate harmony through mindful living.",
  "I am in balance with my thoughts, emotions, and actions.",
  "I choose kindness and understanding in all interactions.",
  "I create unity and peace in my relationships.",
  "I flow with the rhythm of life effortlessly.",
  "I am surrounded by positive and peaceful energy.",
  "I let go of stress and embrace calmness.",
  "I am grateful for the harmony in my life.",
  "I live in alignment with my highest good.",
  "I trust the natural order of the universe.",
  "I welcome balance and tranquility into my life.",
  "I communicate with love and patience.",
  "I am in tune with the peace within me.",
  "I choose to see beauty and harmony everywhere.",
  "I am a source of peace and positivity.",
  "I let go of conflict and embrace unity.",
  "I treat others with respect and compassion.",
  "I find joy in the simple moments of life.",
  "I create harmony in my home and surroundings.",
  "I am at peace with where I am in life.",
  "I accept myself and others without judgment.",
  "I breathe in peace and exhale tension.",
  "I trust in the timing of my life's journey.",
  "I choose to forgive and release all negativity.",
  "I am patient and understanding in all situations.",
  "I allow peace to fill my heart and soul.",
  "I find balance between work, rest, and play.",
  "I embrace harmony in all areas of my life.",
  "I seek peaceful solutions to all challenges.",
  "I welcome love, peace, and serenity into my life.",
  "I am grounded, centered, and calm.",
  "I approach life with ease and grace.",
  "I honor my needs while respecting others.",
  "I find strength in my inner peace.",
  "I trust that everything is unfolding perfectly.",
  "I am a beacon of light and harmony.",
  "I live each day with gratitude and mindfulness.",
  "I cultivate an environment of peace and love.",
  "I release the need for control and trust the process.",
  "I embrace the present moment with peace and joy.",
  "I see the good in myself and others.",
  "I bring harmony to my thoughts, words, and actions.",
  "I create peace through conscious choices.",
  "I respect differences and celebrate unity.",
  "I am open to giving and receiving love.",
  "I choose to live in harmony with nature.",
  "I express myself with clarity and kindness.",
  "I honor the ebb and flow of life.",
  "I remain calm in the face of challenges.",
  "I allow peace to guide my decisions.",
  "I cherish moments of stillness and reflection.",
  "I am deeply connected to the harmony of the universe.",
  "I choose to let go of resentment and embrace love.",
  "I trust the wisdom of my heart and mind.",
  "I make space for joy and balance in my life.",
  "I am free from worry and stress.",
  "I nurture my mind, body, and spirit with love.",
  "I respect and honor the journey of others.",
  "I live each moment with awareness and grace.",
  "I release fear and embrace peace.",
  "I create a world of peace through my thoughts and actions.",
  "I radiate serenity and attract peaceful experiences.",
  "I welcome each new day with a calm heart.",
  "I choose positivity and harmony in every moment.",
  "I am in harmony with the cycles of nature.",
  "I see challenges as opportunities for growth.",
  "I send love and light to those around me.",
  "I am grateful for the balance in my life.",
  "I find peace in acceptance and surrender.",
  "I embrace life's uncertainties with trust and ease.",
  "I create a life filled with joy and balance.",
  "I cultivate peace within, which reflects in my outer world.",
  "I honor my boundaries and respect others' boundaries.",
  "I choose to be a source of harmony and love.",
  "I trust that peace and joy are my natural state.",
  "I find beauty in the diversity of life.",
  "I release what no longer serves me and embrace peace.",
  "I let go of resistance and flow with life.",
  "I choose to respond with love and understanding.",
  "I am one with the peaceful energy of the universe.",
  "I breathe deeply and welcome calmness.",
  "I am at ease with myself and my surroundings.",
  "I release the past and embrace the present with peace.",
  "I seek to bring harmony to all situations.",
  "I allow my heart to be light and free.",
  "I align myself with the highest vibration of love.",
  "I am grateful for the harmony that surrounds me.",
  "I am a channel for peace, love, and unity.",
  "I am in tune with my inner wisdom and guidance.",
];

final List<String> liveharmonyImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> liveharmonyAffirmation = getShuffledaffirmations(
  liveharmonyAffirmationRaw,
  liveharmonyImages,
);
