import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> overcomestressAffirmationRaw = [
  "I am calm, centered, and in control of my emotions.",
  "I release all tension and welcome peace into my life.",
  "I am stronger than any stress that comes my way.",
  "I inhale peace and exhale stress.",
  "I allow myself to relax and let go of worry.",
  "I choose to focus on what I can control.",
  "I trust that everything is unfolding as it should.",
  "I have the power to remain calm in stressful situations.",
  "I deserve peace and tranquility in my life.",
  "I let go of what I cannot change and embrace serenity.",
  "My mind is clear, and my heart is at ease.",
  "I choose to respond to challenges with patience and grace.",
  "I am resilient, strong, and capable of handling anything.",
  "Every breath I take fills me with calm and relaxation.",
  "I trust myself to navigate life's ups and downs.",
  "I release all unnecessary worries and fears.",
  "I am safe, supported, and at peace.",
  "I replace stress with inner peace and confidence.",
  "I allow myself to rest and recharge.",
  "I am in control of my thoughts, and I choose positivity.",
  "I welcome relaxation into my body and mind.",
  "I am present in this moment, and I feel at ease.",
  "I am surrounded by love, support, and positivity.",
  "I choose to let go of stress and embrace joy.",
  "I am capable of handling life's challenges with grace.",
  "My mind is at peace, and my heart is light.",
  "I release tension from my body and invite calmness.",
  "I focus on what brings me peace and happiness.",
  "I trust the process of life and remain calm.",
  "I am grateful for the peace that surrounds me.",
  "My thoughts are peaceful, and my body is relaxed.",
  "I am free from stress and full of positive energy.",
  "I embrace each moment with ease and gratitude.",
  "I choose to approach life with calm and clarity.",
  "I am patient, peaceful, and present.",
  "I acknowledge my stress and gently let it go.",
  "I am resilient and can overcome any challenge.",
  "I nourish my body, mind, and soul with positivity.",
  "I deserve to take breaks and prioritize my well-being.",
  "I trust that all will work out as it should.",
  "I am calm and composed in all situations.",
  "I allow myself to slow down and breathe deeply.",
  "I release all worry and welcome joy into my life.",
  "I am peaceful, relaxed, and filled with gratitude.",
  "I find joy in the little things and let go of stress.",
  "I am bigger than my stress, and I choose peace.",
  "My body and mind are in perfect harmony.",
  "I am safe and at peace in the present moment.",
  "I let go of perfection and embrace progress.",
  "I release stress and embrace relaxation.",
  "I allow myself to pause, breathe, and reset.",
  "I am resilient and trust myself to handle challenges.",
  "I prioritize my peace and well-being.",
  "I trust that I am exactly where I need to be.",
  "I am in control of my emotions and reactions.",
  "I find peace within, no matter the circumstances.",
  "I am worthy of peace, happiness, and self-care.",
  "I trust in my ability to manage life's challenges.",
  "I focus on what uplifts me and release negativity.",
  "I am grateful for the calm moments in my life.",
  "I allow my mind to rest and find clarity.",
  "I am gentle with myself and honor my feelings.",
  "I let go of tension and allow peace to flow in.",
  "I am patient with myself and my journey.",
  "I embrace relaxation as an essential part of my life.",
  "I choose thoughts that bring me peace and ease.",
  "I give myself permission to rest without guilt.",
  "I trust that I am doing my best, and that is enough.",
  "I replace stress with calm and confidence.",
  "I am capable, strong, and in control of my emotions.",
  "I breathe in positivity and exhale all tension.",
  "I am free from the burden of unnecessary worries.",
  "I have everything I need to feel peaceful and calm.",
  "I welcome inner peace and let go of inner chaos.",
  "I am grounded, centered, and at ease.",
  "I choose to navigate stress with wisdom and grace.",
  "I am grateful for each peaceful moment in my life.",
  "I honor my emotions and allow them to flow freely.",
  "I am at ease with myself and my surroundings.",
  "I trust my ability to overcome stressful moments.",
  "I am resilient and find strength in every challenge.",
  "I release fear and embrace the present moment.",
  "I choose to see stress as an opportunity for growth.",
  "I am kind to myself and patient with my progress.",
  "I am surrounded by peace, love, and positivity.",
  "I am strong enough to handle whatever comes my way.",
  "I trust in my journey and let go of worry.",
  "I cultivate a peaceful mindset in all situations.",
  "I prioritize my mental and emotional well-being.",
  "I breathe deeply and allow my body to relax.",
  "I am grateful for the lessons each challenge brings.",
  "I choose to focus on the present and release worry.",
  "I am in charge of my emotions and reactions.",
  "I acknowledge stress but do not let it control me.",
  "I choose to stay calm and confident in all situations.",
  "I am at peace with where I am in life.",
  "I embrace change with a calm and open heart.",
  "I allow myself to take breaks and recharge.",
  "I deserve to feel relaxed, happy, and peaceful.",
  "I trust in the universe's plan for me.",
  "I let go of stress and embrace inner harmony.",
  "I am calm, collected, and in control.",
  "I face challenges with grace and composure.",
  "I choose peace over anxiety and joy over stress.",
  "I am grateful for the peaceful moments in my day.",
  "I trust in the process of life and remain calm.",
  "I let go of tension and embrace relaxation.",
  "I have the strength to overcome any stress.",
  "I nourish my mind with positive and peaceful thoughts.",
  "I am patient and kind to myself.",
  "I choose serenity over stress every time.",
  "I allow myself to breathe deeply and relax.",
  "I am grateful for every moment of peace.",
  "I am free from the weight of stress and worry.",
  "I welcome tranquility into my daily life.",
  "I trust that I can handle anything with grace.",
  "I choose happiness, balance, and peace.",
  "I focus on solutions rather than stressors.",
  "I allow myself to rest and recharge as needed.",
  "I am safe, strong, and resilient.",
  "I embrace each day with a peaceful mind.",
  "I choose to prioritize my well-being above all.",
  "I trust my ability to remain calm under pressure.",
  "I am grateful for the calmness within me.",
  "I have everything I need to feel at peace.",
  "I let go of worries and focus on the present moment.",
  "I am bigger than my stress and worries.",
  "I choose to feel calm and centered in this moment.",
  "My mind is peaceful, and my body is relaxed.",
  "I let go of stress and embrace tranquility.",
  "I trust myself to handle any challenges with ease.",
  "I am in control of my thoughts and emotions.",
  "I release what I cannot control and focus on peace.",
  "I am surrounded by calmness and positivity.",
  "I breathe in peace and exhale stress.",
  "I allow myself to rest and recharge.",
  "I trust that everything will work out in the best way possible.",
  "I am capable of handling any situation with grace.",
  "I deserve to live a life free from stress and anxiety.",
  "I choose relaxation over tension.",
  "I am patient with myself as I navigate challenges.",
  "I prioritize my well-being and peace of mind.",
  "I release all tension from my body and mind.",
  "I allow myself to take things one step at a time.",
  "I am resilient and can overcome any obstacle.",
  "I replace stress with calm and clarity.",
  "I am at peace with the present moment.",
  "I allow myself to relax and let go of worries.",
  "I am in charge of how I react to life's challenges.",
  "I give myself permission to pause and breathe.",
  "I am grateful for the moments of peace in my life.",
  "I choose to focus on what uplifts and empowers me.",
  "I release any negativity that does not serve me.",
  "I am strong, balanced, and at ease.",
  "I trust that everything is unfolding as it should.",
  "I prioritize self-care and emotional well-being.",
  "I let go of overwhelm and embrace simplicity.",
  "I deserve to feel calm, happy, and free.",
  "I choose to replace worry with hope and trust.",
  "I am grounded, centered, and secure.",
  "I embrace uncertainty with a peaceful heart.",
  "I am grateful for my ability to remain calm.",
  "I choose to see stress as an opportunity for growth.",
  "I nourish my mind, body, and soul with positive energy.",
  "I am calm and composed in all situations.",
  "I am stronger than any stress that comes my way.",
  "I trust that solutions will come to me at the right time.",
  "I take deep breaths and allow tension to melt away.",
  "I have everything I need to feel at peace.",
  "I find strength in moments of stillness.",
  "I am safe, loved, and supported.",
  "I welcome joy and relaxation into my life.",
  "I choose to focus on the good in every situation.",
  "I release resistance and embrace flow.",
  "I am at ease with myself and my surroundings.",
  "I take breaks when I need them and honor my limits.",
  "I trust the timing of my life.",
  "I acknowledge my feelings and allow them to pass.",
  "I am worthy of peace and relaxation.",
  "I choose to respond to stress with a calm mind.",
  "I allow myself to let go and trust the process.",
  "I find peace in the little things around me.",
  "I replace overthinking with mindfulness.",
  "I am capable of handling stressful situations gracefully.",
  "I give myself permission to relax fully.",
  "I focus on what brings me joy and fulfillment.",
  "I am learning to release stress more easily each day.",
  "I am in harmony with the flow of life.",
  "I welcome each new day with a peaceful mind.",
  "I let go of worry and focus on the present moment.",
  "I choose kindness and patience, especially with myself.",
  "I allow myself to embrace calmness in all situations.",
  "I am free from the grip of stress and tension.",
  "I create space for peace in my daily life.",
  "I trust that I am on the right path.",
  "I am grateful for the lessons that come with challenges.",
  "I am in control of my inner world.",
  "I release fear and embrace trust.",
  "I allow myself to slow down and appreciate life.",
  "I am enough, and I am doing my best.",
  "I choose to prioritize rest and self-care.",
  "I am resilient, adaptable, and strong.",
  "I replace stress with a sense of ease and confidence.",
  "I trust that life is working in my favor.",
  "I am at peace with where I am right now.",
  "I welcome calm and clarity into my mind.",
  "I give myself permission to step away from stress.",
  "I cultivate inner peace with every breath I take.",
  "I choose to focus on what brings me happiness.",
  "I release any need for perfection and embrace growth.",
  "I honor my body’s need for rest and renewal.",
  "I am a magnet for peace, joy, and relaxation.",
  "I am grateful for my ability to remain calm under pressure.",
  "I focus on solutions rather than problems.",
  "I allow myself to breathe deeply and let go.",
  "I am surrounded by positive energy and love.",
  "I am at peace with the present moment.",
  "I trust that everything will unfold at the perfect time.",
  "I embrace challenges with a calm and open heart.",
  "I release all tension and allow peace to flow through me.",
  "I choose to create balance and harmony in my life.",
  "I am capable of maintaining a peaceful state of mind.",
  "I am grateful for every opportunity to relax and recharge.",
  "I am free from stress and filled with inner peace.",
];

final List<String> overcomestressImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> overcomestressAffirmation = getShuffledaffirmations(
  overcomestressAffirmationRaw,
  overcomestressImages,
);
