import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> practicemindfulnessAffirmationRaw = [
  "I am fully present in this moment.",
  "I embrace the here and now with gratitude.",
  "I choose to focus on the beauty around me.",
  "I breathe in calmness and exhale stress.",
  "I am aware of my thoughts without judgment.",
  "I trust the process of life as it unfolds.",
  "I allow myself to experience life as it is.",
  "I acknowledge my emotions with kindness.",
  "I am grounded, calm, and centered.",
  "I choose peace over worry.",
  "I find joy in the present moment.",
  "I release what I cannot control.",
  "I observe my thoughts and let them pass like clouds.",
  "I listen to my body and honor its needs.",
  "I am in tune with the rhythm of life.",
  "I cultivate patience and understanding.",
  "I embrace each moment with curiosity.",
  "I am at peace with what is.",
  "I choose to respond with love and awareness.",
  "I let go of past regrets and future worries.",
  "I accept myself exactly as I am.",
  "I am grateful for the little moments of life.",
  "I allow myself to slow down and breathe.",
  "I find stillness within me.",
  "I am open to the present experience.",
  "I honor my journey with mindfulness.",
  "I appreciate the simple joys of life.",
  "I let go of distractions and focus on now.",
  "I trust my intuition and inner wisdom.",
  "I am connected to my breath, my body, and my mind.",
  "I welcome peace into my heart.",
  "I find balance in my thoughts and actions.",
  "I am conscious of my thoughts, words, and actions.",
  "I allow myself to fully experience life’s beauty.",
  "I practice awareness in all that I do.",
  "I accept life’s flow without resistance.",
  "I let go of judgment and embrace acceptance.",
  "I choose to be gentle with myself today.",
  "I release stress with each mindful breath.",
  "I am grateful for this moment.",
  "I am aware of the sensations in my body.",
  "I appreciate the present as a gift.",
  "I find joy in the simplest things.",
  "I allow my thoughts to come and go like waves.",
  "I let go of negativity and welcome peace.",
  "I observe my emotions without attachment.",
  "I inhale peace and exhale tension.",
  "I choose to see beauty in everyday life.",
  "I am aware of the energy I bring to each moment.",
  "I honor the space between stimulus and response.",
  "I trust the wisdom of the present moment.",
  "I choose to focus on what truly matters.",
  "I surrender to the present and let go of worry.",
  "I nourish my mind with stillness and peace.",
  "I embrace mindfulness as a way of living.",
  "I allow myself to rest in awareness.",
  "I am in harmony with my surroundings.",
  "I am grateful for the breath that sustains me.",
  "I choose to cultivate inner peace.",
  "I trust in the natural rhythm of life.",
  "I observe my thoughts with compassion.",
  "I am mindful of the love and joy in my life.",
  "I embrace the journey, not just the destination.",
  "I release the need to rush and embrace patience.",
  "I appreciate the richness of the present moment.",
  "I accept things as they are with an open heart.",
  "I am a witness to my own life experience.",
  "I bring awareness to every action I take.",
  "I let go of distractions and return to my breath.",
  "I appreciate each breath as a new beginning.",
  "I cultivate stillness and inner peace.",
  "I am grateful for my senses and their gifts.",
  "I welcome each moment with an open mind.",
  "I trust in the natural unfolding of life.",
  "I am fully engaged in whatever I do.",
  "I let go of expectations and embrace what is.",
  "I am conscious of the present without judgment.",
  "I create space for mindfulness in my day.",
  "I embrace uncertainty with grace and awareness.",
  "I find joy in small moments of clarity.",
  "I slow down and appreciate life’s details.",
  "I am at peace with my thoughts and emotions.",
  "I observe the world with a sense of wonder.",
  "I am open to the wisdom of each moment.",
  "I allow mindfulness to guide my actions.",
  "I experience life deeply and intentionally.",
  "I welcome the present with an open heart.",
  "I choose to respond, not react.",
  "I find freedom in the now.",
  "I breathe deeply and embrace serenity.",
  "I practice gratitude in every moment.",
  "I honor my presence in this world.",
  "I surrender to the present and trust life’s flow.",
  "I am in tune with the rhythm of nature.",
  "I choose mindfulness over mindlessness.",
  "I experience the present fully and wholeheartedly.",
  "I cultivate gratitude through mindfulness.",
  "I let go of the past and live in the now.",
  "I allow my awareness to deepen each day.",
  "I choose presence over distraction.",
  "I am at peace with the unfolding of life.",
  "I nurture my soul with stillness and breath.",
  "I trust in the power of mindfulness to transform me.",
  "I focus on what is within my control.",
  "I embrace the power of now.",
  "I welcome clarity and awareness into my day.",
  "I breathe deeply and let go of stress.",
  "I create moments of stillness in my daily life.",
  "I honor my body and mind through mindfulness.",
  "I am grateful for the lessons in every moment.",
  "I allow life to be as it is without resistance.",
  "I bring my full attention to the present.",
  "I choose to see life through a lens of gratitude.",
  "I accept myself and my emotions with love.",
  "I cherish each moment as a gift.",
  "I bring peace into every interaction.",
  "I observe, accept, and release thoughts with ease.",
  "I am patient with myself as I practice mindfulness.",
  "I trust in the unfolding of each day.",
  "I find joy in simply being.",
  "I align myself with the present moment.",
  "I embrace the now with an open heart.",
  "I allow my thoughts to pass without attachment.",
  "I am grateful for the breath that connects me to life.",
  "I approach life with mindfulness and love.",
  "I breathe deeply, feeling grounded and at peace.",
  "I am fully immersed in the beauty of the present.",
  "I cultivate mindfulness with every breath I take.",
  "I am mindful of the energy I bring to the world.",
  "I surrender to the flow of the present moment.",
  "I embrace each breath as a gift of life.",
  "I choose to be mindful in all that I do.",
  "I am present, awake, and aware.",
  "I find deep peace in mindful living.",
  "I am grateful for the stillness within me.",
  "I bring a spirit of mindfulness to my daily life.",
  "I let go of distractions and focus on the now.",
  "I am fully present in this moment.",
  "I choose to slow down and enjoy life.",
  "Each breath I take fills me with calm and peace.",
  "I observe my thoughts without judgment.",
  "I release distractions and embrace stillness.",
  "I trust in the flow of life and let go of control.",
  "I find beauty in the simple moments.",
  "I welcome peace into my mind and body.",
  "I am aware of my thoughts and emotions.",
  "I breathe deeply and center myself in the now.",
  "I choose to respond with mindfulness, not react impulsively.",
  "I appreciate the present moment as a gift.",
  "I am grateful for this moment, exactly as it is.",
  "I listen to my body and honor its needs.",
  "I trust the wisdom of my inner self.",
  "I observe my emotions with love and compassion.",
  "I allow thoughts to come and go without attachment.",
  "I embrace each moment with an open heart.",
  "I release worry and welcome clarity.",
  "I find joy in the rhythm of my breath.",
  "I am rooted in the present, free from regret or fear.",
  "I surrender to the present and find peace.",
  "I choose awareness over autopilot.",
  "I experience life as it unfolds, moment by moment.",
  "I let go of judgment and accept things as they are.",
  "I am kind to myself in every moment.",
  "I welcome stillness and clarity into my life.",
  "I focus on what I can control and release the rest.",
  "I nourish my soul by being present.",
  "I choose to be fully engaged in life.",
  "I embrace mindfulness in all that I do.",
  "I am at peace with myself and my surroundings.",
  "I bring love and awareness to my actions.",
  "I accept myself and my emotions with kindness.",
  "I let go of past worries and future anxieties.",
  "I allow myself to pause and just be.",
  "I appreciate the sounds, sights, and sensations around me.",
  "I observe my thoughts like clouds passing in the sky.",
  "I create space for peace in my heart and mind.",
  "I am a witness to my own experience.",
  "I approach each day with mindfulness and gratitude.",
  "I inhale positivity and exhale stress.",
  "I welcome calmness and serenity into my life.",
  "I trust the natural rhythm of my breath.",
  "I am grateful for each moment as it comes.",
  "I embrace the journey of mindful living.",
  "I accept all experiences as part of my growth.",
  "I choose peace over worry.",
  "I let go of distractions and focus on now.",
  "I practice gratitude in every moment.",
  "I appreciate the present without clinging to the past.",
  "I slow down and enjoy the richness of life.",
  "I am connected to the present through my breath.",
  "I trust in the unfolding of each day.",
  "I am aware of the sensations in my body.",
  "I allow life to be as it is without resistance.",
  "I respond to challenges with awareness and calmness.",
  "I find joy in the stillness of the present.",
  "I release the need to control everything.",
  "I am enough, just as I am in this moment.",
  "I trust my intuition to guide me wisely.",
  "I bring mindfulness to my daily routines.",
  "I allow myself to be present with ease and joy.",
  "I listen deeply to myself and others.",
  "I choose peace over perfection.",
  "I find freedom in being fully present.",
  "I align with the present and embrace its gifts.",
  "I let go of what no longer serves me.",
  "I observe my surroundings with a sense of wonder.",
  "I trust that I am exactly where I need to be.",
  "I am mindful of my energy and where I focus it.",
  "I choose presence over distraction.",
  "I find beauty in the ordinary moments of life.",
  "I honor my needs by staying present with myself.",
  "I take mindful steps toward my goals.",
  "I accept change with grace and openness.",
  "I embrace the now with love and gratitude.",
  "I allow space for stillness in my life.",
  "I experience life fully, with all my senses.",
  "I approach each day with curiosity and awareness.",
  "I find joy in simply being.",
  "I embrace the present moment without resistance.",
  "I welcome awareness as my guide.",
  "I am at peace with what is, right now.",
  "I see every moment as an opportunity for growth.",
  "I allow myself to be present without judgment.",
  "I am grateful for the moments of stillness in my day.",
  "I nurture mindfulness in all areas of my life.",
  "I bring my full attention to the present.",
  "I let go of distractions and return to myself.",
  "I honor each breath as a gift of life.",
  "I trust in the wisdom of the present moment.",
  "I create space for mindfulness every day.",
  "I embrace the now and trust that it is enough.",
  "I am fully present in everything I do.",
  "I cultivate mindfulness with love and patience.",
  "I honor my journey by living with awareness.",
];

final List<String> practicemindfulnessImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> practicemindfulnessAffirmation =
    getShuffledaffirmations(
      practicemindfulnessAffirmationRaw,
      practicemindfulnessImages,
    );
