name: circular_menu_example
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  circular_menu: ^4.0.0
  

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
