import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> achievegoalsAffirmationRaw = [
  "I am committed to achieving my goals.",
  "Every day, I am getting closer to my dreams.",
  "I have the discipline to accomplish anything I set my mind to.",
  "I believe in my ability to reach my goals.",
  "I am focused, determined, and unstoppable.",
  "I have a clear vision of my goals and take steps daily to achieve them.",
  "Success is within my reach, and I claim it now.",
  "I turn my dreams into reality through consistent action.",
  "I am capable of achieving greatness.",
  "I trust the process and stay dedicated to my journey.",
  "I have everything I need to succeed.",
  "Each step I take brings me closer to my goals.",
  "I am resilient and push through obstacles with confidence.",
  "I am focused on my goals and nothing can distract me.",
  "I have the power to shape my future.",
  "I attract success with my hard work and dedication.",
  "I am disciplined, consistent, and committed to my goals.",
  "I celebrate my progress and keep moving forward.",
  "I take massive action to achieve my dreams.",
  "I am in control of my success.",
  "I embrace challenges as stepping stones to my goals.",
  "My mind is set on success, and I do what it takes to achieve it.",
  "I am worthy of achieving my biggest dreams.",
  "I stay motivated and inspired to reach my goals.",
  "I am persistent, patient, and powerful.",
  "I trust myself to take the right steps toward my goals.",
  "I believe in my vision and pursue it with passion.",
  "I take responsibility for my future and create my own success.",
  "I remain focused and never give up.",
  "I overcome every challenge with courage and determination.",
  "I am committed to my personal and professional growth.",
  "I am constantly improving and moving forward.",
  "I attract opportunities that help me achieve my goals.",
  "I believe in my ability to make things happen.",
  "I am proactive and take control of my success.",
  "I have a success mindset that drives me forward.",
  "I learn from my failures and use them to grow.",
  "I am the creator of my destiny.",
  "I stay focused on my goals despite distractions.",
  "I trust that my hard work will pay off.",
  "I am determined to make my dreams a reality.",
  "I embrace the journey and trust in the process.",
  "I am surrounded by opportunities for success.",
  "I take bold steps toward my future.",
  "I turn setbacks into setups for success.",
  "I wake up motivated and ready to achieve my goals.",
  "I set clear intentions and take purposeful action.",
  "I am patient and trust in the timing of my success.",
  "I take action every day to achieve my dreams.",
  "I am confident in my ability to succeed.",
  "I remain focused, even in the face of challenges.",
  "I push beyond my comfort zone to achieve greatness.",
  "I celebrate small wins on my journey to success.",
  "I stay dedicated and consistent with my efforts.",
  "I attract success by working hard and believing in myself.",
  "I am disciplined in my actions and committed to my goals.",
  "I have an unstoppable drive to achieve what I want.",
  "I remain positive and trust in my journey.",
  "I am capable of accomplishing everything I desire.",
  "I believe in my power to turn my vision into reality.",
  "I take inspired action toward my goals.",
  "I use my time wisely to reach my objectives.",
  "I visualize my success and take action to achieve it.",
  "I am focused and determined to achieve my dreams.",
  "I wake up each day with purpose and motivation.",
  "I am consistent in my efforts and refuse to quit.",
  "I have the strength to persevere through any challenge.",
  "I trust in my abilities to succeed.",
  "I am confident in my path and progress.",
  "I take charge of my success and work diligently toward it.",
  "I am willing to do what it takes to reach my goals.",
  "I stay committed to my vision, no matter what.",
  "I attract opportunities that align with my ambitions.",
  "I am determined to succeed beyond my expectations.",
  "I remain focused, resilient, and driven.",
  "I overcome fear and self-doubt with courage and action.",
  "I keep my eyes on my goals and work toward them daily.",
  "I am destined for success and prosperity.",
  "I develop habits that support my success.",
  "I am persistent and never give up on my goals.",
  "I take action with confidence and faith in myself.",
  "I am ready to achieve my full potential.",
  "I have a growth mindset that leads me to success.",
  "I am focused on progress, not perfection.",
  "I move forward with clarity and purpose.",
  "I am a magnet for success and achievement.",
  "I take one step at a time toward my dreams.",
  "I transform my dreams into reality through action.",
  "I wake up every day excited to move closer to my goals.",
  "I trust my journey and embrace the lessons along the way.",
  "I break big goals into smaller, achievable steps.",
  "I am committed to self-discipline and personal growth.",
  "I am focused, fearless, and fully dedicated.",
  "I am worthy of achieving my highest aspirations.",
  "I am an achiever, and success is my reality.",
  "I believe in my dreams and work hard to achieve them.",
  "I am unstoppable in the pursuit of my goals.",
  "I am capable of extraordinary achievements.",
  "I make decisions that support my long-term success.",
  "I am surrounded by positivity and possibility.",
  "I embrace persistence as the key to my success.",
  "I use every setback as a stepping stone to victory.",
  "I align my actions with my goals and values.",
  "I create my own opportunities and seize them fearlessly.",
  "I am confident in my ability to achieve everything I desire.",
  "I am strong, determined, and destined for greatness.",
  "I take action without hesitation or fear.",
  "I stay motivated and take bold steps toward success.",
  "I wake up each day ready to conquer my goals.",
  "I am constantly improving and moving forward in life.",
  "I work hard, stay consistent, and trust the process.",
  "I am grateful for my progress and excited for my future.",
  "I visualize my success and make it happen.",
  "I turn challenges into opportunities for growth.",
  "I am committed to achieving my personal and professional goals.",
  "I refuse to let fear or doubt hold me back.",
  "I believe in my ability to accomplish great things.",
  "I am laser-focused on what I want to achieve.",
  "I embrace the effort it takes to reach my dreams.",
  "I create success through my thoughts and actions.",
  "I am limitless in what I can accomplish.",
  "I take action daily to bring my goals to life.",
  "I am proud of my persistence and dedication.",
  "I know I am capable of turning my vision into reality.",
  "I trust that I am on the right path.",
  "I celebrate every milestone I achieve.",
  "I never stop believing in myself and my dreams.",
  "I am fully capable of achieving my goals.",
  "I have the power to turn my dreams into reality.",
  "Every step I take brings me closer to success.",
  "I am disciplined and dedicated to my goals.",
  "I attract the right opportunities to achieve my goals.",
  "I believe in my ability to succeed.",
  "I stay focused and never lose sight of my dreams.",
  "I take consistent action towards my goals.",
  "I am unstoppable in my pursuit of success.",
  "I trust the journey, knowing success is inevitable.",
  "I am committed to growth and self-improvement.",
  "I am resilient and rise above challenges.",
  "I set clear goals and work hard to achieve them.",
  "My determination leads me to great achievements.",
  "I make progress every single day.",
  "I am capable of overcoming any obstacle.",
  "I am dedicated to becoming the best version of myself.",
  "I believe in my ability to accomplish great things.",
  "I attract success through hard work and perseverance.",
  "I am patient and trust the process of achieving my dreams.",
  "I stay motivated and inspired to reach my goals.",
  "I take action daily to move closer to my dreams.",
  "I am laser-focused on achieving my ambitions.",
  "I push past fear and embrace new opportunities.",
  "I am capable, confident, and driven to succeed.",
  "I embrace the journey and celebrate small victories.",
  "I am strong enough to overcome any challenge.",
  "I trust myself to make the right choices for success.",
  "I take responsibility for my dreams and goals.",
  "I am constantly improving and evolving.",
  "I remain positive, even in difficult times.",
  "I use setbacks as fuel to push me forward.",
  "I am grateful for my progress and continue moving ahead.",
  "I am surrounded by success and inspiration.",
  "I create the life I desire with focus and dedication.",
  "I am determined to achieve everything I set my mind to.",
  "I trust my skills and talents to lead me to success.",
  "I welcome challenges as opportunities to grow.",
  "I am a go-getter who refuses to quit.",
  "I stay consistent and keep showing up for my dreams.",
  "I am worthy of achieving my biggest goals.",
  "I embrace hard work and discipline with enthusiasm.",
  "I transform my vision into reality through action.",
  "I wake up every day ready to conquer my goals.",
  "I am focused on progress, not perfection.",
  "I am the creator of my own success.",
  "I take bold steps toward my future every day.",
  "I am persistent and never give up on my dreams.",
  "I stay committed, even when things get tough.",
  "I trust my inner wisdom to guide me to success.",
  "I take control of my destiny with confidence.",
  "I refuse to let doubt or fear hold me back.",
  "I am on the right path to achieving my goals.",
  "I am an achiever, and nothing can stop me.",
  "I use every failure as a lesson for future success.",
  "I am constantly learning and growing.",
  "I have a clear vision and work towards it daily.",
  "I am disciplined and committed to my success.",
  "I attract the right people and opportunities into my life.",
  "I am worthy of all the success coming my way.",
  "I stay focused and block out distractions.",
  "I believe in myself and my ability to make things happen.",
  "I am courageous enough to chase my biggest dreams.",
  "I take one step at a time towards success.",
  "I have the power to create the life I desire.",
  "I celebrate my achievements, big and small.",
  "I embrace patience and trust the process.",
  "I am motivated, ambitious, and driven.",
  "I am capable of turning my aspirations into reality.",
  "I take inspired action towards my dreams.",
  "I am passionate about my goals and excited about my future.",
  "I attract success because I work hard for it.",
  "I remain confident even when challenges arise.",
  "I am constantly improving and moving forward.",
  "I make smart choices that support my success.",
  "I am worthy of achieving greatness in life.",
  "I put in the effort, and success follows.",
  "I am dedicated to turning my dreams into accomplishments.",
  "I am powerful, persistent, and prepared for success.",
  "I have what it takes to accomplish anything I desire.",
  "I am destined to achieve amazing things.",
  "I am proud of my progress and continue to push forward.",
];

final List<String> achievegoalsImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> achievegoalsAffirmation = getShuffledaffirmations(
  achievegoalsAffirmationRaw,
  achievegoalsImages,
);
