import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> adaptabilityAffirmationRaw = [
  "I embrace change with an open mind.",
  "I adapt easily to new situations and challenges.",
  "I am flexible and resilient in all aspects of life.",
  "I trust myself to navigate life's twists and turns.",
  "I welcome uncertainty as an opportunity for growth.",
  "I am capable of adjusting to any situation with ease.",
  "I remain calm and centered in times of change.",
  "I thrive in new environments and embrace challenges.",
  "I see every obstacle as a chance to evolve.",
  "I am open to learning and growing every day.",
  "I adjust to new circumstances with confidence and grace.",
  "I am resourceful and creative in problem-solving.",
  "I welcome new perspectives and ideas with an open heart.",
  "I trust in my ability to handle whatever comes my way.",
  "I find solutions even in the most uncertain situations.",
  "I let go of what no longer serves me and welcome the new.",
  "I am strong, adaptable, and capable of overcoming anything.",
  "I embrace life’s changes with courage and optimism.",
  "I am flexible and flow with the rhythms of life.",
  "I trust that change brings new opportunities for success.",
  "I adjust my mindset to thrive in any situation.",
  "I am fearless in the face of the unknown.",
  "I see challenges as chances to grow stronger and wiser.",
  "I welcome transformation and progress in my life.",
  "I am open to unexpected opportunities and blessings.",
  "I release resistance and embrace the beauty of change.",
  "I navigate life’s transitions with wisdom and grace.",
  "I trust in my ability to reinvent myself when needed.",
  "I turn challenges into stepping stones for success.",
  "I am at peace with change and flow effortlessly with it.",
  "I am resilient and adapt to any situation with ease.",
  "I am open to new experiences and embrace them fully.",
  "I thrive in uncertainty because I trust myself completely.",
  "I welcome new beginnings with excitement and confidence.",
  "I trust that every change leads me to something better.",
  "I am quick to adjust and respond to life’s surprises.",
  "I am strong enough to handle any transformation in my life.",
  "I am capable of handling sudden changes with clarity and strength.",
  "I trust the process and embrace the unknown with faith.",
  "I am open to different paths that lead to success.",
  "I stay positive and make the most of every situation.",
  "I evolve with every new challenge and become wiser.",
  "I let go of fear and step into the new with confidence.",
  "I am creative in finding new ways to succeed.",
  "I embrace life’s detours as part of my journey.",
  "I trust in my ability to learn and adapt quickly.",
  "I move forward with courage even when things change.",
  "I am flexible, strong, and open to new ideas.",
  "I remain calm and composed when faced with change.",
  "I find peace in knowing that change brings growth.",
  "I embrace uncertainty as an adventure, not a fear.",
  "I choose to adapt and grow rather than resist change.",
  "I am open to the lessons each change brings.",
  "I remain confident in my ability to adjust and succeed.",
  "I am capable of shifting my mindset when needed.",
  "I welcome new possibilities and embrace them with joy.",
  "I trust that I will always find my way.",
  "I move forward with resilience and a positive attitude.",
  "I am strong enough to rise above any challenge.",
  "I see every change as an opportunity to reinvent myself.",
  "I flow effortlessly with the natural changes of life.",
  "I remain adaptable in both success and challenges.",
  "I am comfortable with change because I trust my journey.",
  "I am constantly growing, evolving, and improving.",
  "I learn from every experience and use it to move forward.",
  "I let go of what no longer serves me with ease.",
  "I embrace discomfort as a sign of growth and expansion.",
  "I am fearless in adjusting to new circumstances.",
  "I trust that my ability to adapt makes me stronger.",
  "I am always learning, evolving, and thriving.",
  "I welcome the unknown and see it as an adventure.",
  "I remain positive and flexible through life’s changes.",
  "I adjust to life’s changes with strength and wisdom.",
  "I make the best of every situation, no matter what.",
  "I trust that every challenge is leading me to something better.",
  "I find new ways to grow and succeed every day.",
  "I welcome the new with enthusiasm and courage.",
  "I release resistance and embrace the flow of life.",
  "I am adaptable and always find solutions.",
  "I trust in my resilience and ability to overcome anything.",
  "I see opportunities where others see obstacles.",
  "I thrive in the face of change and uncertainty.",
  "I am open to fresh perspectives and new ways of thinking.",
  "I have the ability to pivot and succeed in any situation.",
  "I remain hopeful and optimistic, no matter the circumstances.",
  "I am constantly evolving into the best version of myself.",
  "I see life’s unexpected changes as stepping stones to success.",
  "I let go of fear and embrace the endless possibilities ahead.",
  "I am prepared for change and welcome it with confidence.",
  "I release doubt and embrace the adventure of life.",
  "I am comfortable with uncertainty because I trust myself.",
  "I accept that change is a part of life and I make the best of it.",
  "I approach challenges with curiosity and confidence.",
  "I choose to focus on what I can control and let go of the rest.",
  "I remain strong and courageous through life’s transformations.",
  "I am open-minded and welcome new perspectives.",
  "I am excited about the changes that lie ahead.",
  "I find balance in times of transition.",
  "I allow myself to grow through every life experience.",
  "I am always open to learning something new.",
  "I trust myself to handle whatever comes my way.",
  "I move through challenges with grace and wisdom.",
  "I adapt effortlessly to life’s shifts and surprises.",
  "I use every change as an opportunity for self-improvement.",
  "I welcome transformation as a natural part of my journey.",
  "I am always evolving, learning, and thriving.",
  "I make adjustments as needed to continue my growth.",
  "I have the inner strength to adapt and succeed.",
  "I choose to embrace change rather than fear it.",
  "I rise above difficulties with ease and confidence.",
  "I face every transition with courage and grace.",
  "I welcome each new chapter of my life with joy.",
  "I am comfortable with change because I trust in my journey.",
  "I am open to new experiences and embrace them fully.",
  "I thrive in uncertainty and find opportunities in every change.",
  "I am fearless in embracing the unknown.",
  "I release old patterns and welcome fresh opportunities.",
  "I remain optimistic in the face of uncertainty.",
  "I am a master of adaptation and transformation.",
  "I embrace change as a path to growth.",
  "I am flexible and open to new experiences.",
  "I adapt easily to unexpected situations.",
  "I trust myself to handle life's changes with ease.",
  "I thrive in evolving circumstances.",
  "I welcome change as an opportunity for success.",
  "I remain calm and focused in uncertain times.",
  "I am resourceful in overcoming obstacles.",
  "I adjust to new challenges with confidence.",
  "I trust my ability to navigate life's twists and turns.",
  "I learn and grow from every experience.",
  "I embrace new possibilities with an open heart.",
  "I see every transition as a stepping stone to greatness.",
  "I move forward fearlessly, no matter the circumstances.",
  "I find creative solutions in changing situations.",
  "I let go of fear and embrace the unknown.",
  "I trust that change brings new opportunities.",
  "I release resistance and accept life’s natural flow.",
  "I am strong and resilient in the face of challenges.",
  "I adapt to life’s surprises with a positive mindset.",
  "I remain centered and balanced in shifting situations.",
  "I embrace flexibility as a source of strength.",
  "I turn challenges into opportunities for success.",
  "I adjust with grace and wisdom to new circumstances.",
  "I welcome unexpected changes with curiosity and courage.",
  "I am confident in my ability to thrive in any environment.",
  "I am comfortable stepping out of my comfort zone.",
  "I approach transitions with optimism and enthusiasm.",
  "I trust in my ability to find solutions quickly.",
  "I see opportunities in every new situation.",
  "I am open to learning and evolving every day.",
  "I embrace uncertainty as part of my journey.",
  "I transform obstacles into stepping stones.",
  "I welcome change and make the most of it.",
  "I remain strong and adaptable in any situation.",
  "I accept change as an essential part of life.",
  "I flow effortlessly with life's ups and downs.",
  "I confidently embrace the unknown.",
  "I adjust to new challenges with ease and positivity.",
  "I am fearless in facing new experiences.",
  "I am always evolving into the best version of myself.",
  "I trust my instincts when adapting to new situations.",
  "I embrace innovation and new ways of thinking.",
  "I remain flexible and find joy in transformation.",
  "I release what no longer serves me and welcome the new.",
  "I am quick to learn and adjust in any situation.",
  "I welcome life’s changes as exciting new beginnings.",
  "I have the ability to handle anything that comes my way.",
  "I adapt to different environments with confidence.",
  "I trust in my resilience and inner strength.",
  "I am always ready to embrace the next adventure.",
  "I approach changes with an open and eager mind.",
  "I shift my mindset to align with new possibilities.",
  "I am prepared for and embrace unexpected changes.",
  "I am creative and flexible in problem-solving.",
  "I grow stronger with every challenge I face.",
  "I welcome fresh perspectives and new ideas.",
  "I trust that every change leads to greater success.",
  "I am at peace with the ever-changing nature of life.",
  "I learn from every experience and keep moving forward.",
  "I am fluid and adaptable, just like nature.",
  "I accept life’s changes with a grateful heart.",
  "I navigate transitions with ease and grace.",
  "I choose to see change as a chance for growth.",
  "I am willing to step outside my comfort zone.",
  "I am open-minded and embrace new perspectives.",
  "I create opportunities through my adaptability.",
  "I let go of fear and welcome change with confidence.",
  "I trust the process of life’s constant evolution.",
  "I find excitement in exploring the unknown.",
  "I am capable of handling life’s uncertainties.",
  "I turn setbacks into stepping stones for success.",
  "I adjust effortlessly to new circumstances.",
  "I rise to the occasion in any situation.",
  "I see every change as a chance to reinvent myself.",
  "I trust that adaptability makes me stronger.",
  "I move with the flow of life instead of resisting it.",
  "I remain positive, no matter what changes arise.",
  "I embrace life’s shifts as part of my personal growth.",
];

final List<String> adaptabilitygoalsImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> adaptabilityAffirmation = getShuffledaffirmations(
  adaptabilityAffirmationRaw,
  adaptabilitygoalsImages,
);
