import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> dreamactAffirmationRaw = [
  "I dare to dream big and take bold action.",
  "My dreams are valid, and I am capable of achieving them.",
  "I turn my dreams into reality through consistent effort.",
  "I believe in my ability to make things happen.",
  "Every step I take brings me closer to my dreams.",
  "I am committed to both dreaming and doing.",
  "I take inspired action towards my goals daily.",
  "My dreams are worth the effort I put in.",
  "I have the courage to follow my dreams.",
  "I act with confidence, knowing success is within reach.",
  "I trust the process of growth and progress.",
  "I create the life of my dreams through my actions.",
  "I am not afraid to take risks for my dreams.",
  "I choose to take action instead of waiting for the perfect moment.",
  "I have the power to bring my dreams to life.",
  "Each action I take builds momentum towards success.",
  "I am fully capable of achieving greatness.",
  "I am motivated to work towards my biggest goals.",
  "I embrace challenges as stepping stones to my dreams.",
  "I act with purpose and determination.",
  "I stay focused on what truly matters to me.",
  "I am willing to step outside my comfort zone.",
  "I believe in my potential to create the future I desire.",
  "I act with faith, knowing my dreams are achievable.",
  "I take responsibility for making my dreams come true.",
  "I am proactive and dedicated to my success.",
  "My dreams fuel my passion and drive.",
  "I take one step at a time towards my vision.",
  "I have the strength to overcome obstacles on my path.",
  "I am a doer, not just a dreamer.",
  "I turn my ideas into tangible results.",
  "I am in control of my future and take action accordingly.",
  "I trust in my ability to manifest my desires.",
  "I believe that my hard work will pay off.",
  "I embrace discipline as a tool for success.",
  "I have all the resources I need to achieve my dreams.",
  "I am excited about what I am creating for my life.",
  "I am determined to bring my vision to life.",
  "I make decisions that align with my goals.",
  "I choose progress over perfection.",
  "I wake up every day with purpose and determination.",
  "I turn fear into motivation to take action.",
  "I am capable of achieving anything I desire.",
  "I take action even when I feel uncertain.",
  "My actions today shape my future success.",
  "I let go of doubt and embrace possibility.",
  "I am patient, persistent, and powerful.",
  "I take meaningful steps towards my vision daily.",
  "I believe in my dreams, and I make them happen.",
  "I am responsible for creating my own success.",
  "I celebrate progress, no matter how small.",
  "I am disciplined in my pursuit of excellence.",
  "I focus on solutions rather than obstacles.",
  "I am resilient and adaptable in my journey.",
  "I follow through on my commitments to myself.",
  "I take bold steps toward the life I envision.",
  "I trust myself to figure things out.",
  "I am a creator, a doer, and a visionary.",
  "My actions today bring my dreams closer to reality.",
  "I take action with confidence and clarity.",
  "I am building my dream life with every choice I make.",
  "I am the architect of my destiny.",
  "I make the most of every opportunity.",
  "I take responsibility for my progress and success.",
  "I am in alignment with my highest purpose.",
  "I am unstoppable when I take action towards my goals.",
  "I welcome challenges as opportunities to grow.",
  "I have the power to change my life for the better.",
  "I follow my dreams fearlessly and passionately.",
  "I act on my ideas with confidence and belief.",
  "I trust that my efforts will lead to success.",
  "I keep going, even when things get tough.",
  "I am constantly improving and evolving.",
  "I refuse to let fear hold me back.",
  "I turn my aspirations into reality through action.",
  "I move forward with clarity and determination.",
  "I take action with enthusiasm and courage.",
  "I believe in my ability to achieve the extraordinary.",
  "I am dedicated to making my dreams come true.",
  "I stay committed to my vision, no matter what.",
  "I trust in my ability to navigate challenges.",
  "I take action that aligns with my purpose.",
  "I choose to believe in myself and my abilities.",
  "I am passionate about pursuing my dreams.",
  "I make progress every single day.",
  "I have faith in my ability to succeed.",
  "I am grateful for every step of my journey.",
  "I am energized by the actions I take.",
  "I make things happen with dedication and effort.",
  "I choose action over excuses.",
  "I embrace the journey as much as the destination.",
  "I am strong, capable, and ready for success.",
  "I am constantly turning my dreams into reality.",
  "I let go of doubt and move forward with courage.",
  "I see opportunities where others see obstacles.",
  "I trust myself to handle whatever comes my way.",
  "I act with confidence and clarity.",
  "I am persistent in the face of challenges.",
  "I take consistent action towards my dreams.",
  "I let my vision guide my actions.",
  "I am committed to making my dreams a reality.",
  "I have a powerful vision for my future.",
  "I am determined to make my dreams come true.",
  "I am taking steps every day towards my goals.",
  "I believe in my potential to create an amazing life.",
  "I embrace failure as a lesson on the road to success.",
  "I act with passion and purpose.",
  "I focus on solutions and take action with confidence.",
  "I stay committed to my dreams, no matter what.",
  "I have the courage to pursue my dreams fully.",
  "I am the hero of my own story.",
  "I embrace the process of growth and learning.",
  "I make things happen with intention and effort.",
  "I am disciplined in my pursuit of success.",
  "I am ready to take bold action toward my dreams.",
  "I welcome change as an opportunity for growth.",
  "I am focused on achieving my biggest aspirations.",
  "I am aligned with my highest potential.",
  "I act decisively to create the life I desire.",
  "I take ownership of my success and happiness.",
  "I move with purpose and direction.",
  "I trust in my ability to accomplish anything.",
  "I am committed to turning my dreams into reality.",
  "I am constantly improving my skills and mindset.",
  "I am powerful, determined, and unstoppable.",
  "I act with courage, faith, and conviction.",
  "I embrace my dreams with enthusiasm and dedication.",
  "I know that taking action is the key to success.",
  "I have the power to bring my dreams to life.",
  "I make decisions that move me toward my dreams.",
  "I am inspired, motivated, and driven to succeed.",
  "I create opportunities through action.",
  "I embrace each day as a new chance to progress.",
  "I take responsibility for my growth and success.",
  "I am fully committed to my goals and vision.",
  "I follow my heart and take action with confidence.",
  "I believe in my ability to make a difference.",
  "I have the power to turn my dreams into reality.",
  "Every step I take brings me closer to my goals.",
  "I trust the journey as I pursue my dreams.",
  "I take inspired action toward my vision.",
  "I am bold and fearless in chasing my dreams.",
  "I turn my ideas into actions every day.",
  "I am capable of making my dreams come true.",
  "I choose progress over perfection.",
  "I believe in my ability to create a successful future.",
  "I make things happen through determination and action.",
  "I take the first step, even when I feel uncertain.",
  "I am committed to my dreams, no matter what.",
  "My actions today shape the future I desire.",
  "I follow my dreams with passion and persistence.",
  "I am resilient in the face of obstacles.",
  "I act with confidence and courage.",
  "I embrace challenges as opportunities for growth.",
  "I am constantly learning and evolving.",
  "I take responsibility for turning my dreams into reality.",
  "I act with intention and focus.",
  "I am disciplined in my pursuit of success.",
  "I wake up every day motivated to take action.",
  "I let go of fear and move forward with confidence.",
  "I am a creator, a visionary, and a doer.",
  "I am focused on achieving my biggest goals.",
  "I take control of my future with decisive action.",
  "I embrace uncertainty and take action anyway.",
  "I choose to be proactive rather than passive.",
  "I welcome new opportunities and seize them boldly.",
  "I know that success comes from consistent effort.",
  "I believe in my dreams and back them up with action.",
  "I use my creativity to make my dreams a reality.",
  "I act with purpose and clarity.",
  "I am constantly working towards my ideal life.",
  "I turn inspiration into action without hesitation.",
  "I am committed to growth, progress, and success.",
  "I have everything I need to achieve my dreams.",
  "I am determined to overcome any obstacles in my way.",
  "I take one step at a time toward success.",
  "I am brave enough to take action on my dreams.",
  "I know that my efforts will be rewarded.",
  "I refuse to let doubt stop me from taking action.",
  "I am driven, focused, and unstoppable.",
  "I take daily action toward my aspirations.",
  "I move forward with confidence and optimism.",
  "I believe in my ability to make a difference.",
  "I have faith in my journey and my potential.",
  "I take risks that align with my dreams.",
  "I trust that everything is unfolding for my highest good.",
  "I use challenges as fuel to push me forward.",
  "I take inspired action and trust the results.",
  "I welcome success into my life through my actions.",
  "I act despite fear and uncertainty.",
  "I make the most of every opportunity that comes my way.",
  "I create my future through my actions today.",
  "I am ready to do whatever it takes to succeed.",
  "I choose courage over comfort.",
  "I am persistent and patient in my pursuit of greatness.",
  "I trust my instincts and follow my passions.",
  "I put in the work, and success follows.",
  "I believe that I am capable of extraordinary things.",
  "I make decisions that bring me closer to my dreams.",
  "I take action with enthusiasm and excitement.",
  "I embrace the journey and enjoy the process.",
  "I am consistent, committed, and courageous.",
  "I attract opportunities through my dedication and focus.",
  "I trust in my ability to accomplish great things.",
  "I turn dreams into plans and plans into action.",
  "I am empowered to create the life I want.",
  "I step outside my comfort zone to reach my dreams.",
  "I am willing to do what it takes to succeed.",
  "I take action without fear of failure.",
  "I embrace change as a necessary part of growth.",
  "I use my skills and talents to build my dream life.",
  "I take calculated risks that align with my vision.",
  "I know that effort and action lead to success.",
  "I am determined to make an impact in the world.",
  "I believe in myself and in my ability to succeed.",
];

final List<String> dreamactgoalsImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> dreamactAffirmation = getShuffledaffirmations(
  dreamactAffirmationRaw,
  dreamactgoalsImages,
);
