import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> growthcommitmentAffirmationRaw = [
  "I am committed to my personal growth every day.",
  "I embrace change as an opportunity to grow.",
  "I am dedicated to becoming the best version of myself.",
  "I trust the process of learning and evolving.",
  "I am open to new experiences that help me grow.",
  "I believe in my ability to improve and evolve.",
  "I am willing to step outside my comfort zone.",
  "I welcome challenges as a path to growth.",
  "I am constantly learning and developing new skills.",
  "I am committed to my lifelong journey of self-improvement.",
  "I embrace setbacks as stepping stones to success.",
  "I am capable of adapting and growing through every experience.",
  "I commit to being better than I was yesterday.",
  "I am willing to invest time and effort into my growth.",
  "I trust that each challenge is helping me grow stronger.",
  "I am open to constructive feedback and use it to improve.",
  "I believe in my ability to learn from every situation.",
  "I welcome personal development with excitement and joy.",
  "I am patient with myself as I grow and evolve.",
  "I trust in my ability to transform my life.",
  "I am focused on progress, not perfection.",
  "I embrace failure as a lesson for future success.",
  "I am always expanding my knowledge and skills.",
  "I am dedicated to becoming wiser and more experienced.",
  "I choose to see obstacles as opportunities for growth.",
  "I am committed to my dreams and aspirations.",
  "I push myself to grow beyond my current limits.",
  "I have the discipline to keep moving forward.",
  "I value consistency in my self-improvement journey.",
  "I am always improving, learning, and evolving.",
  "I am grateful for the lessons I learn every day.",
  "I am willing to put in the effort to grow.",
  "I take responsibility for my own growth and success.",
  "I am disciplined and focused on my goals.",
  "I am determined to reach my highest potential.",
  "I embrace challenges as tools for self-improvement.",
  "I am dedicated to pushing myself beyond my fears.",
  "I have the courage to face difficulties head-on.",
  "I trust my ability to overcome obstacles and grow stronger.",
  "I am committed to lifelong learning and self-development.",
  "I believe in my capacity to expand my abilities.",
  "I prioritize my personal growth every single day.",
  "I welcome new experiences that broaden my perspective.",
  "I am resilient and adaptable in my journey of growth.",
  "I believe in my ability to create positive change.",
  "I celebrate every small step I take toward growth.",
  "I am excited about the opportunities for personal expansion.",
  "I learn from my mistakes and grow wiser.",
  "I am committed to constant self-improvement.",
  "I embrace the process of evolving into my best self.",
  "I take action toward my goals with dedication.",
  "I am patient with myself as I evolve and transform.",
  "I am motivated to expand my skills and talents.",
  "I challenge myself to grow in new ways.",
  "I am open to exploring new paths for self-improvement.",
  "I see every experience as a chance to learn.",
  "I am determined to keep progressing no matter what.",
  "I am grateful for the growth that comes with each challenge.",
  "I take small steps every day toward self-betterment.",
  "I am proud of the progress I make every day.",
  "I trust in my ability to create a brighter future.",
  "I allow myself to grow at my own pace.",
  "I invest time in activities that promote personal growth.",
  "I believe in my ability to build the life I want.",
  "I am open to learning from everyone around me.",
  "I recognize that growth is a lifelong journey.",
  "I embrace change as a powerful catalyst for progress.",
  "I trust in my inner strength to keep growing.",
  "I seek knowledge and experiences that enhance my life.",
  "I am committed to my growth even when it's difficult.",
  "I choose growth over fear every time.",
  "I challenge myself to step outside my comfort zone.",
  "I embrace the unknown as part of my journey.",
  "I am persistent in my pursuit of self-improvement.",
  "I take bold steps toward my dreams every day.",
  "I welcome opportunities that push me to grow.",
  "I take control of my own self-development.",
  "I believe in the power of continuous growth.",
  "I use my challenges as fuel for transformation.",
  "I commit to being a lifelong learner.",
  "I am excited about how much I am evolving.",
  "I am always learning, adapting, and improving.",
  "I have the power to shape my own destiny.",
  "I trust myself to keep moving forward.",
  "I surround myself with people who encourage growth.",
  "I focus on learning rather than worrying about mistakes.",
  "I am proud of how far I have come.",
  "I am committed to breaking old patterns and growing new ones.",
  "I believe that every challenge helps me grow stronger.",
  "I am grateful for every opportunity to learn something new.",
  "I take responsibility for my personal development.",
  "I push myself to reach new levels of success.",
  "I trust the timing of my personal growth.",
  "I give myself permission to evolve at my own pace.",
  "I embrace the journey of self-improvement wholeheartedly.",
  "I focus on becoming the best version of myself daily.",
  "I am always one step closer to my goals.",
  "I welcome growth with enthusiasm and optimism.",
  "I am patient with myself as I improve each day.",
  "I choose to see struggles as stepping stones.",
  "I trust in my journey of continuous improvement.",
  "I am willing to learn from every experience.",
  "I am always leveling up in every aspect of life.",
  "I acknowledge and celebrate my personal progress.",
  "I am eager to grow in mind, body, and spirit.",
  "I choose habits that support my personal growth.",
  "I am committed to improving my mindset daily.",
  "I am excited about the progress I make each day.",
  "I let go of self-doubt and embrace my potential.",
  "I believe in my ability to transform my life.",
  "I take full responsibility for my self-growth.",
  "I am dedicated to learning something new every day.",
  "I welcome each day as an opportunity to grow.",
  "I recognize that growth takes time, and I am patient.",
  "I am courageous enough to embrace change and growth.",
  "I am always evolving into a stronger, wiser person.",
  "I challenge myself to become a better version of myself.",
  "I trust in my ability to rise and grow beyond limits.",
  "I am committed to developing a positive mindset.",
  "I am proud of myself for striving for growth daily.",
  "I welcome self-improvement as a joyful journey.",
  "I embrace discomfort as a necessary part of growth.",
  "I am always seeking ways to better myself.",
  "I trust that I am growing in the right direction.",
  "I am worthy of the growth and success I seek.",
  "I release all fear and doubt holding me back.",
  "I commit to becoming the best version of myself.",
  "I honor my commitment to lifelong growth.",
  "I am committed to my personal and professional growth.",
  "Every day, I choose to grow and evolve.",
  "I embrace change as a powerful tool for transformation.",
  "I trust that my efforts will lead to meaningful growth.",
  "I am willing to learn from every experience.",
  "Growth is a lifelong journey, and I am dedicated to it.",
  "I allow myself to grow at my own pace.",
  "I am capable of continuous self-improvement.",
  "I invest in my personal development every single day.",
  "I embrace new challenges as opportunities for learning.",
  "I believe in my ability to expand my skills and knowledge.",
  "I am dedicated to becoming a better version of myself.",
  "I celebrate my small victories on the path of growth.",
  "I trust that my journey of growth is unfolding perfectly.",
  "I release self-doubt and commit to personal expansion.",
  "I seek out opportunities that help me grow.",
  "I am constantly evolving into a stronger and wiser person.",
  "I am open to constructive feedback and use it to improve.",
  "I am willing to step outside my comfort zone.",
  "I prioritize my growth and well-being.",
  "I am always striving to learn and grow.",
  "I choose to see obstacles as stepping stones to success.",
  "I embrace discomfort as a sign of growth.",
  "I trust in the process of my personal development.",
  "I take consistent action toward my growth goals.",
  "I am resilient and adaptable in my growth journey.",
  "I recognize that growth requires patience and effort.",
  "I am open to learning new perspectives and ideas.",
  "I take responsibility for my own success and growth.",
  "I believe in my ability to overcome challenges.",
  "I am excited about the person I am becoming.",
  "I trust myself to make decisions that support my growth.",
  "I am committed to developing a growth mindset.",
  "I welcome new experiences that help me evolve.",
  "I let go of limiting beliefs and embrace my potential.",
  "I believe in my ability to shape my future.",
  "I take inspired action toward my goals every day.",
  "I use failures as lessons for future success.",
  "I push myself beyond my perceived limits.",
  "I am grateful for the opportunities to grow.",
  "I am focused on progress, not perfection.",
  "I surround myself with people who encourage my growth.",
  "I embrace lifelong learning with enthusiasm.",
  "I step forward in faith, knowing growth takes time.",
  "I am patient with myself as I improve every day.",
  "I cultivate habits that support my growth and success.",
  "I am becoming wiser and stronger with each challenge.",
  "I trust that each lesson is shaping me for the better.",
  "I am always learning, adapting, and improving.",
  "I embrace new possibilities with an open heart and mind.",
  "I challenge myself to reach new heights.",
  "I am committed to reaching my full potential.",
  "I invest in my skills and talents to achieve greatness.",
  "I allow myself to grow through my mistakes.",
  "I see setbacks as opportunities for growth and reflection.",
  "I am determined to keep growing no matter what.",
  "I honor my journey by embracing growth every day.",
  "I give myself permission to evolve and expand.",
  "I trust in my resilience and ability to adapt.",
  "I recognize that growth is a process, not a destination.",
  "I choose to cultivate a positive and growth-focused mindset.",
  "I seek wisdom and guidance to enhance my growth journey.",
  "I am excited about new learning opportunities.",
  "I challenge my fears and step into my potential.",
  "I am grateful for every lesson life teaches me.",
  "I commit to becoming the best version of myself.",
  "I am proud of how much I have grown already.",
  "I give myself grace as I navigate my growth journey.",
  "I focus on becoming stronger, smarter, and more confident.",
  "I am resilient, and I rise stronger after every setback.",
  "I welcome self-reflection as a tool for personal evolution.",
  "I trust that growth takes time, and I remain patient.",
  "I believe in my ability to make a lasting impact.",
  "I am constantly working to improve myself and my skills.",
  "I honor my progress, no matter how small.",
  "I take every opportunity to learn something new.",
  "I am committed to unlocking my full potential.",
  "I stay open-minded and adaptable in my growth journey.",
  "I believe in my capacity to grow into my dreams.",
  "I take each step forward with courage and determination.",
];

final List<String> growthcommitmentImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> growthcommitmentAffirmation =
    getShuffledaffirmations(
      growthcommitmentAffirmationRaw,
      growthcommitmentImages,
    );
