import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> learnfromfailureAffirmationRaw = [
  "Failure is just a lesson, not a defeat.",
  "Every failure is a stepping stone to success.",
  "I embrace failure as part of my growth journey.",
  "Mistakes help me learn and improve.",
  "I am resilient and rise after every fall.",
  "Failure is proof that I am trying.",
  "I grow stronger with every setback.",
  "Every challenge is an opportunity in disguise.",
  "I turn failures into valuable lessons.",
  "My past failures do not define my future.",
  "I welcome mistakes as part of progress.",
  "I am learning and evolving every day.",
  "I use failure as motivation to keep going.",
  "I trust in my ability to bounce back.",
  "Every experience makes me wiser and stronger.",
  "I see setbacks as setups for comebacks.",
  "I choose to learn instead of giving up.",
  "My failures make my success story even greater.",
  "I am capable of overcoming any setback.",
  "Every mistake brings me closer to mastery.",
  "I let go of the fear of failure.",
  "Failure is just a temporary detour.",
  "I am always learning, growing, and improving.",
  "I celebrate progress, no matter how small.",
  "I am stronger than my failures.",
  "Failure teaches me resilience and adaptability.",
  "I find solutions instead of focusing on setbacks.",
  "I am open to learning from every situation.",
  "My failures are my greatest teachers.",
  "I move forward with courage and confidence.",
  "I am proud of my ability to keep going.",
  "I am not afraid to fail because I always learn.",
  "I embrace challenges with an open mind.",
  "I am getting better every day.",
  "I see failure as feedback, not finality.",
  "I believe in my ability to turn setbacks into success.",
  "I am more than my mistakes.",
  "Every failure is an opportunity for growth.",
  "I trust that every failure leads to a breakthrough.",
  "I use my failures to fuel my determination.",
  "I am patient with my learning process.",
  "I trust that everything happens for a reason.",
  "Failure does not define me; my perseverance does.",
  "I choose to see obstacles as opportunities.",
  "I am always moving forward, no matter what.",
  "I bounce back stronger after every setback.",
  "I release self-doubt and embrace self-growth.",
  "I accept failure as part of the journey to success.",
  "I give myself permission to fail and learn.",
  "I have the courage to keep going despite setbacks.",
  "Failure helps me refine my skills and strategy.",
  "I focus on progress, not perfection.",
  "I have the strength to overcome any obstacle.",
  "I am proud of how far I have come.",
  "I embrace failure with a positive attitude.",
  "I rise above my failures and move forward.",
  "I trust the process of learning and growth.",
  "I am capable of turning failures into opportunities.",
  "I accept failure with grace and determination.",
  "Every setback is preparing me for success.",
  "I face failure with confidence and optimism.",
  "I am fearless in the face of challenges.",
  "I see setbacks as a chance to reassess and grow.",
  "I am always evolving through my experiences.",
  "My mistakes do not make me a failure.",
  "I focus on what I can learn from my failures.",
  "I choose persistence over giving up.",
  "I am grateful for the lessons failure teaches me.",
  "I believe that every failure brings me closer to success.",
  "I never lose; I either win or learn.",
  "I embrace imperfection as part of the journey.",
  "I am patient with myself as I learn and grow.",
  "Failure is an invitation to grow and improve.",
  "I am flexible and adapt to any challenge.",
  "I trust myself to learn from every mistake.",
  "I am committed to continuous improvement.",
  "I let go of regret and focus on learning.",
  "I turn failures into valuable life lessons.",
  "I choose to find wisdom in my mistakes.",
  "I believe that setbacks make me stronger.",
  "I am stronger than any failure I face.",
  "Failure is just a chapter, not my entire story.",
  "I keep moving forward despite setbacks.",
  "I allow myself to try, fail, and try again.",
  "I know that failure is part of every success story.",
  "I replace fear of failure with curiosity.",
  "I am proud of my efforts, regardless of the outcome.",
  "I use failure as a stepping stone to greatness.",
  "I forgive myself for past mistakes and move forward.",
  "I am not afraid to take risks and learn.",
  "I see failure as a teacher, not an enemy.",
  "I am confident in my ability to recover from failure.",
  "I trust that failure leads to new opportunities.",
  "I learn, adapt, and move forward with strength.",
  "I embrace the journey, including the failures.",
  "Failure makes me wiser, stronger, and better.",
  "I focus on growth rather than perfection.",
  "I am patient with my journey of learning.",
  "I choose resilience over self-doubt.",
  "I accept setbacks as part of success.",
  "I believe in my ability to keep improving.",
  "Failure is a sign that I am pushing my limits.",
  "I find strength in my struggles.",
  "I am brave enough to try again.",
  "I see every setback as a comeback in progress.",
  "I am capable of achieving success despite obstacles.",
  "I believe in my ability to succeed, no matter what.",
  "Every failed attempt brings me closer to victory.",
  "I am determined to turn failures into strengths.",
  "I am not afraid to fail because I always get back up.",
  "I am a work in progress, and that is okay.",
  "I trust myself to make adjustments and keep going.",
  "I celebrate learning from failure.",
  "I turn obstacles into opportunities for success.",
  "I am grateful for the wisdom failure brings.",
  "I learn valuable lessons from every challenge.",
  "Failure fuels my motivation to do better.",
  "I release fear and welcome growth.",
  "I believe that persistence leads to success.",
  "I grow stronger with every failure I face.",
  "I allow myself to take risks and learn.",
  "Failure does not define me; my response does.",
  "I am focused on progress, not setbacks.",
  "I choose to find meaning in my failures.",
  "I am learning valuable skills through my mistakes.",
  "I see challenges as stepping stones, not roadblocks.",
  "I trust that failure is leading me to something greater.",
  "Every failure is a lesson in disguise.",
  "I let go of perfection and embrace progress.",
  "Failure reminds me that I am trying something new.",
  "I learn from my experiences and keep improving.",
  "I am always moving toward success, no matter what.",
  "I am strong enough to overcome any failure.",
  "I trust that my struggles will make me stronger.",
  "I believe that success is built on lessons from failure.",
  "Failure is my greatest teacher.",
  "I grow wiser with every mistake I make.",
  "Each setback is a setup for a comeback.",
  "I turn obstacles into stepping stones for success.",
  "Every failure brings me closer to my goals.",
  "I embrace failure as a natural part of growth.",
  "I learn from my mistakes and move forward.",
  "I am resilient, strong, and capable of overcoming challenges.",
  "I let go of self-judgment and embrace self-improvement.",
  "Failure is just a redirection toward something better.",
  "I trust in my ability to rise after every fall.",
  "I choose to see failure as a stepping stone to success.",
  "I learn valuable lessons from every setback.",
  "I accept mistakes as part of my journey.",
  "I believe in my ability to adapt and grow.",
  "Every experience makes me a better version of myself.",
  "I embrace challenges with confidence and determination.",
  "I am not afraid to fail because I always learn.",
  "I turn failures into motivation for success.",
  "I am not defined by my mistakes; I am defined by my persistence.",
  "Every failure is an opportunity to start again, wiser than before.",
  "I choose growth over fear.",
  "I allow myself to try, fail, and try again.",
  "I have the strength to overcome any setback.",
  "Failure teaches me patience and resilience.",
  "I use failure as fuel to keep going.",
  "I embrace my imperfections and keep learning.",
  "Every mistake is a lesson in disguise.",
  "I focus on progress, not perfection.",
  "I turn every setback into a comeback.",
  "I trust the process of learning and growth.",
  "I celebrate every attempt, even if I fail.",
  "I use failure as an opportunity to improve.",
  "I am grateful for the lessons failure teaches me.",
  "I welcome new challenges, knowing they make me stronger.",
  "Failure does not break me; it builds me.",
  "I am patient with my progress and trust the journey.",
  "I am proud of myself for pushing forward despite challenges.",
  "I am open to learning from every situation.",
  "I choose persistence over fear.",
  "I replace self-doubt with self-belief.",
  "I trust that failure is part of my success story.",
  "I have the courage to keep trying, no matter what.",
  "I embrace failure as part of my journey to greatness.",
  "I learn from my past and create a better future.",
  "I allow failure to shape me, not stop me.",
  "I am stronger because of the challenges I have faced.",
  "I see setbacks as opportunities to grow.",
  "I refuse to let failure hold me back.",
  "I rise above my failures with courage and determination.",
  "Every failure is a stepping stone toward success.",
  "I focus on solutions instead of dwelling on mistakes.",
  "I let go of regrets and focus on progress.",
  "I trust that my efforts will lead to success.",
  "I am not afraid to fail because I know I will rise again.",
  "Failure helps me discover new paths to success.",
  "I choose to learn, grow, and move forward.",
  "I am worthy of success, even after failure.",
  "I take risks, knowing failure is part of learning.",
  "I welcome failure as proof of my effort.",
  "I see every failure as a lesson, not a loss.",
  "I trust my ability to turn setbacks into success.",
  "I let go of perfectionism and embrace progress.",
  "I am patient with myself as I learn and improve.",
  "I believe that my failures will lead to breakthroughs.",
  "I see failure as feedback, not failure.",
  "I am capable of overcoming any challenge that comes my way.",
  "I choose resilience over regret.",
  "I grow stronger with each lesson learned.",
  "I embrace my journey, including its ups and downs.",
  "I am always improving, no matter the outcome.",
  "I use my failures as stepping stones to success.",
  "I trust that my hard work will pay off.",
  "I am grateful for every learning opportunity.",
  "I forgive myself for past mistakes and move forward.",
  "I know that failure is part of the road to success.",
  "I learn, grow, and keep pushing forward.",
  "I welcome every experience as a chance to improve.",
  "I am always evolving through my experiences.",
  "I believe that every mistake makes me better.",
  "I trust in my ability to turn failure into wisdom.",
  "I am fearless in the face of challenges.",
  "I embrace every setback as a chance to rise higher.",
];

final List<String> learnfromfailureImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> learnfromfailureAffirmation =
    getShuffledaffirmations(
      learnfromfailureAffirmationRaw,
      learnfromfailureImages,
    );
