import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> opportunitymagnetAffirmationRaw = [
  "I attract endless opportunities into my life.",
  "I am a magnet for success and abundance.",
  "New and exciting opportunities flow to me effortlessly.",
  "I am open to receiving incredible opportunities every day.",
  "Doors of success open for me at the right time.",
  "The universe aligns everything for my greatest good.",
  "I recognize and seize golden opportunities.",
  "I am ready for the opportunities that are meant for me.",
  "Every challenge I face leads to new possibilities.",
  "I am always in the right place at the right time.",
  "My energy attracts valuable connections and opportunities.",
  "I confidently step into new possibilities.",
  "I believe in my ability to create opportunities.",
  "I welcome unexpected blessings into my life.",
  "I see opportunities where others see obstacles.",
  "I am grateful for the opportunities that come my way.",
  "I take inspired action towards my goals.",
  "Every day brings new opportunities for success.",
  "My mindset attracts endless possibilities.",
  "I am open to learning and growing from every opportunity.",
  "I manifest opportunities that align with my purpose.",
  "I trust the universe to guide me toward amazing opportunities.",
  "I attract people and experiences that bring me success.",
  "I am worthy of life-changing opportunities.",
  "I am constantly discovering new paths to success.",
  "My potential opens doors to incredible opportunities.",
  "I attract career growth and financial success effortlessly.",
  "I trust that new opportunities will always find me.",
  "I am prepared and ready for my next big break.",
  "I create opportunities through my hard work and determination.",
  "I am surrounded by endless possibilities.",
  "I embrace every opportunity with gratitude and enthusiasm.",
  "I am a magnet for once-in-a-lifetime opportunities.",
  "I allow success and prosperity to flow freely to me.",
  "I make the most of every opportunity that comes my way.",
  "I am excited about the new doors opening in my life.",
  "I attract opportunities that align with my highest good.",
  "My positive energy draws in incredible possibilities.",
  "I am always one step closer to my dreams.",
  "Every moment holds the potential for something great.",
  "I attract the perfect opportunities for my growth.",
  "I have the courage to take bold chances.",
  "I am confident in my ability to recognize valuable opportunities.",
  "Opportunities are all around me, and I choose to see them.",
  "My passion and purpose attract success effortlessly.",
  "I attract wealth, success, and happiness with ease.",
  "I am ready to embrace all the success coming my way.",
  "I am aligned with the flow of abundance.",
  "My dreams and desires attract the perfect opportunities.",
  "I say yes to new possibilities with confidence.",
  "I trust my instincts to guide me toward success.",
  "I am a beacon for opportunity and prosperity.",
  "I take risks knowing that great opportunities await me.",
  "I am open to unexpected opportunities and blessings.",
  "My enthusiasm attracts incredible possibilities.",
  "I am constantly expanding my network and attracting new opportunities.",
  "I believe in my ability to create the life I desire.",
  "Every day presents new doors for me to walk through.",
  "I turn obstacles into stepping stones for new opportunities.",
  "I am always ready for my next adventure.",
  "I trust that my hard work will bring amazing opportunities.",
  "I attract success in every area of my life.",
  "My thoughts create endless opportunities for growth.",
  "I welcome career, financial, and personal growth opportunities.",
  "I am capable of making the most out of every situation.",
  "I attract the right people who support my growth.",
  "My creativity leads me to exciting opportunities.",
  "I am destined for greatness, and opportunities come naturally to me.",
  "I make choices that align with my highest potential.",
  "I recognize the power of taking action on new opportunities.",
  "I radiate confidence, attracting limitless possibilities.",
  "I welcome change because it brings me closer to my goals.",
  "I am open to new possibilities in all areas of my life.",
  "I have a mindset that attracts abundance and success.",
  "I trust that I am on the right path to incredible opportunities.",
  "The more I grow, the more opportunities I attract.",
  "I am always prepared to take advantage of the opportunities around me.",
  "I allow my intuition to guide me to the best choices.",
  "Every interaction I have leads to new possibilities.",
  "I am a natural attractor of success and happiness.",
  "I welcome exciting challenges that bring new opportunities.",
  "I take bold steps toward my dreams every day.",
  "My skills and talents bring me endless opportunities.",
  "I am surrounded by success, prosperity, and abundance.",
  "Every experience brings me closer to new opportunities.",
  "I embrace life’s surprises and trust that they lead to something great.",
  "I have the ability to turn dreams into reality.",
  "I step outside my comfort zone to unlock new opportunities.",
  "I trust in the timing of my success.",
  "My energy is magnetic, drawing in unlimited possibilities.",
  "I am confident that I am attracting the perfect opportunities for me.",
  "I have everything I need to take advantage of my opportunities.",
  "Every decision I make leads me to a new opportunity.",
  "I am a powerful creator of my own success.",
  "I trust in my journey and the opportunities it brings.",
  "I am in alignment with my highest potential.",
  "My openness to learning attracts success.",
  "I am constantly creating opportunities for myself and others.",
  "I take decisive action toward my dreams.",
  "I am always ready for my next great opportunity.",
  "I am fearless in the pursuit of my dreams.",
  "I am an opportunity magnet, and success is inevitable.",
  "I remain positive, knowing the best is yet to come.",
  "I create a life filled with purpose and success.",
  "The universe brings me unlimited opportunities every day.",
  "I confidently attract financial and career breakthroughs.",
  "My optimism brings me closer to my dreams.",
  "Every new day is filled with limitless possibilities.",
  "I am worthy of every incredible opportunity that comes my way.",
  "I am grateful for the abundance of opportunities in my life.",
  "I make the most of every situation by seeing its potential.",
  "I see endless opportunities to grow and succeed.",
  "I embrace every opportunity with enthusiasm and passion.",
  "I am a powerful force of attraction for success.",
  "My dreams are supported by infinite opportunities.",
  "I take action on new opportunities with confidence and clarity.",
  "The right opportunities always find their way to me.",
  "I welcome abundance, prosperity, and success into my life.",
  "I am unstoppable in my pursuit of new opportunities.",
  "I trust in my ability to make the right choices.",
  "I am guided toward the best opportunities for my growth.",
  "The universe is always working in my favor.",
  "I am courageous enough to step into new possibilities.",
  "I believe in my power to create the life I desire.",
  "I embrace the unknown because it leads to endless opportunities.",
  "I am always attracting something amazing into my life.",
  "My success story is unfolding beautifully every day.",
  "I am open to infinite opportunities that come my way.",
  "I effortlessly attract success and abundance.",
  "Opportunities flow to me in perfect timing.",
  "Every challenge I face leads to new possibilities.",
  "I am a magnet for prosperity and growth.",
  "The universe constantly brings amazing opportunities to me.",
  "I see opportunities where others see obstacles.",
  "I am always in the right place at the right time.",
  "Doors of success are opening for me now.",
  "I welcome new opportunities with confidence and excitement.",
  "My energy attracts the right people and circumstances.",
  "Every day, I attract golden opportunities into my life.",
  "I trust the process and know that opportunities are endless.",
  "My skills and talents make me an opportunity magnet.",
  "I seize every opportunity that aligns with my goals.",
  "I am always prepared to embrace new possibilities.",
  "I am worthy of limitless opportunities.",
  "I take bold steps toward my dreams and attract success.",
  "Opportunities present themselves to me effortlessly.",
  "I am constantly expanding and welcoming new experiences.",
  "I recognize and act on opportunities that serve me best.",
  "The universe supports me in creating my dream life.",
  "My positive mindset attracts prosperity and success.",
  "I embrace change because it leads to new opportunities.",
  "I trust that my journey is unfolding in perfect harmony.",
  "I am always learning and growing from the opportunities I receive.",
  "I attract career, financial, and personal growth opportunities.",
  "I am a powerful creator of my own success.",
  "I trust that the universe will guide me to amazing opportunities.",
  "I say yes to new possibilities and trust in my path.",
  "Every day is filled with new chances to grow and succeed.",
  "I make decisions that lead me toward incredible opportunities.",
  "My confidence attracts life-changing opportunities.",
  "I am destined to achieve greatness.",
  "My openness invites opportunities into my life.",
  "I attract mentors and resources that help me grow.",
  "I trust my intuition to lead me to the right opportunities.",
  "I am surrounded by endless possibilities.",
  "I am aligned with the energy of success.",
  "I recognize golden opportunities and act on them.",
  "The universe provides me with everything I need to succeed.",
  "I attract opportunities that bring me joy and fulfillment.",
  "I create my own opportunities through passion and dedication.",
  "My enthusiasm and energy attract success effortlessly.",
  "I am ready for the next big opportunity in my life.",
  "My potential is limitless, and so are my opportunities.",
  "I allow myself to step into new possibilities fearlessly.",
  "I am a natural magnet for prosperity and abundance.",
  "Every step I take brings me closer to new opportunities.",
  "I radiate confidence, attracting limitless possibilities.",
  "I am worthy of every incredible opportunity that comes my way.",
  "I embrace each opportunity with excitement and gratitude.",
  "Success is drawn to me because I am ready for it.",
  "I make the most of every opportunity that presents itself.",
  "I am bold, confident, and ready to seize every opportunity.",
  "I am always discovering new paths to success.",
  "Every interaction brings new opportunities into my life.",
  "My passion and hard work open doors for me.",
  "I attract the perfect opportunities for my growth.",
  "I recognize the power of taking action on new opportunities.",
  "I am always one step closer to my goals.",
  "I welcome exciting surprises and unexpected opportunities.",
  "I believe in my power to manifest amazing opportunities.",
  "I turn every challenge into an opportunity for success.",
  "I am courageous enough to embrace new possibilities.",
  "I attract abundance in all forms effortlessly.",
  "I step outside my comfort zone to unlock new opportunities.",
  "My thoughts are aligned with success and prosperity.",
  "I am open to new ideas and innovations that bring success.",
  "I see every situation as an opportunity to grow.",
  "I trust that every opportunity I need will come to me.",
  "I attract opportunities that align with my purpose.",
  "I am destined for greatness, and opportunities come easily to me.",
  "I take inspired action to bring my dreams to life.",
  "My optimism attracts endless opportunities into my life.",
  "I radiate success, and people love to work with me.",
  "The right opportunities always find me at the perfect time.",
  "I am grateful for the abundance of opportunities in my life.",
];

final List<String> opportunitymagnetImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> opportunitymagnetAffirmation =
    getShuffledaffirmations(
      opportunitymagnetAffirmationRaw,
      opportunitymagnetImages,
    );
