import '../quotes_randomizer.dart';

/// **Leadership and Influence Quotes & Images**
final List<String> leadershipQuotesRaw = [
  "A leader is one who knows the way, goes the way, and shows the way.",
  "Leadership is not about being in charge. It is about taking care of those in your charge.",
  "The greatest leader is not necessarily the one who does the greatest things but the one who gets people to do the greatest things.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Leadership is the capacity to translate vision into reality.",
  "The function of leadership is to produce more leaders, not more followers.",
  "A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others.",
  "Leadership is not about titles, positions, or flowcharts. It is about one life influencing another.",
  "People don’t follow leaders who seek followers. They follow leaders who create more leaders.",
  "The task of the leader is to get their people from where they are to where they have not been.",
  "If your actions inspire others to dream more, learn more, do more, and become more, you are a leader.",
  "True leadership is about creating a vision that others can see, believe in, and strive to achieve.",
  "Great leaders are willing to sacrifice their own personal interests for the good of the team.",
  "A leader takes people where they want to go. A great leader takes people where they ought to be.",
  "Leadership is not about control but about service.",
  "Leaders don’t force people to follow; they invite them on a journey.",
  "Your influence is determined by how abundantly you place other people’s interests first.",
  "The best way to lead people is by showing them the way, not by pushing them from behind.",
  "Good leaders create a vision, articulate the vision, and passionately own the vision.",
  "True leadership is serving others, not serving yourself.",
  "A great leader is not the one who has the most followers, but the one who creates the most leaders.",
  "Leaders are made, not born. They are made by hard effort and perseverance.",
  "The best leaders are those most interested in surrounding themselves with assistants and associates smarter than they are.",
  "The key to successful leadership is influence, not authority.",
  "The most powerful leadership tool you have is your own personal example.",
  "Leadership is the ability to empower others to do great things.",
  "A leader should not only guide but also inspire and uplift.",
  "Integrity is the most valuable and respected quality of leadership.",
  "Leadership is an action, not a position.",
  "A leader is someone who sees possibilities where others see obstacles.",
  "Great leaders don’t set out to be a leader; they set out to make a difference.",
  "Leaders don’t create followers; they create more leaders.",
  "A leader must be able to see the invisible to achieve the impossible.",
  "True leaders listen more than they speak.",
  "Leadership is about making others better as a result of your presence.",
  "Leaders think and talk about the solutions, not the problems.",
  "True leadership is not about words but about actions.",
  "Great leaders inspire others to take action, not just follow orders.",
  "A great leader is someone who turns their vision into reality through passion and perseverance.",
  "Leadership is unlocking people's potential to become better.",
  "The best leaders are those who understand that leadership is about people, not power.",
  "Leaders cultivate a culture of trust and collaboration.",
  "To lead others, one must first lead themselves.",
  "Leadership is about taking responsibility, not making excuses.",
  "Leadership is an opportunity to serve, not to rule.",
  "A great leader is one who builds bridges rather than walls.",
  "The best leaders don’t create followers; they create change-makers.",
  "A good leader leads with heart and wisdom, not just intellect.",
  "Leadership means seeing beyond the moment and guiding others towards a brighter future.",
  "The role of a leader is not to have all the answers but to inspire the right questions.",
  "Great leaders invest in their people and help them grow.",
  "A leader’s job is to bring out the best in those they serve.",
  "Leadership is about lighting the path, not standing in the spotlight.",
  "True leadership is about inspiring and empowering others to be their best.",
  "Leaders don’t create excuses; they create solutions.",
  "Good leaders don’t just direct; they connect.",
  "Leadership is about courage, integrity, and creating positive change.",
  "The best leaders build leaders, not just followers.",
  "Great leaders understand that their success depends on the success of their team.",
  "Leadership is about making a difference, not making a point.",
  "A real leader is someone who doesn’t seek praise but earns respect.",
  "Leadership is about bringing out the best in people, not just telling them what to do.",
  "Great leaders don’t just inspire; they empower and elevate.",
  "The measure of a true leader is how they lift others up.",
  "Leadership is about enabling others to succeed and grow.",
  "The best leaders leave a legacy of inspiration, not just instructions.",
  "Leadership is knowing when to lead and when to listen.",
  "Good leaders take responsibility when things go wrong and give credit when things go right.",
  "Leadership is about action, not position.",
  "A great leader doesn’t command respect; they earn it through their actions.",
  "The best leaders create a culture of encouragement and empowerment.",
  "Leadership is about bringing vision to life and inspiring others to do the same.",
  "The true test of leadership is how well you inspire others to be their best selves.",
  "A leader’s greatest tool is their ability to listen and learn.",
  "Leadership is about turning obstacles into opportunities.",
  "Great leaders lead with passion, wisdom, and authenticity.",
  "Leadership is about leading with purpose and serving with heart.",
  "A great leader fosters a culture of trust and innovation.",
  "Leadership is about creating a shared vision and guiding others toward it.",
  "True leadership is about inspiring and serving others.",
  "Great leaders lift others as they climb.",
  "The strength of a leader is not in their power but in their influence.",
  "A true leader builds bridges, not walls.",
  "Leaders don’t demand respect; they earn it through their actions.",
  "Leadership is about turning ideas into reality and dreams into action.",
  "The best leaders create a culture of growth and learning.",
  "A leader’s greatest asset is their ability to inspire others to greatness.",
  "Leadership is about making the world better, one decision at a time.",
  "A great leader’s power is measured by how they empower others.",
  "Leadership is about being brave enough to take the first step.",
  "Great leaders lead with both their heart and mind.",
  "The best leaders create an environment where others can thrive.",
  "True leadership is about lifting others up, not standing above them.",
  "A leader’s success is measured by the success of their team.",
  "Leadership is about creating ripples of positive change.",
  "The mark of a great leader is their ability to inspire and motivate others.",
  "Great leaders build strong relationships and inspire trust.",
  "Leadership is not about being the best. It is about making others better.",
  "True leaders create a culture where people feel empowered to thrive.",
  "A leader’s job is not to be the smartest in the room but to bring out the intelligence in others.",
  "Leadership is about inspiring belief in a better future.",
  "A good leader is like a candle – they consume themselves to light the way for others.",
  "Great leadership starts with self-leadership.",
  "The most effective leaders lead by example, not by words alone.",
  "True leadership is lifting others up, not standing above them.",
  "Good leaders don’t tell you what to do. They show you how it’s done.",
  "A real leader nurtures talent, develops potential, and celebrates progress.",
  "Leadership is about creating an environment where people want to succeed.",
  "A leader’s influence is measured by the lives they inspire.",
  "Leadership is not about controlling others but empowering them.",
  "The best leaders are those who inspire others to become leaders themselves.",
  "To lead is to serve, to inspire, and to create opportunities for others.",
  "Leadership is about seeing the possibilities and helping others believe in them too.",
  "Great leaders are not afraid of change; they embrace and drive it.",
  "A true leader values people more than power.",
  "A great leader’s strength lies in their ability to listen and understand.",
  "Leadership is the art of motivating others to achieve what they thought was impossible.",
  "True leaders empower, encourage, and elevate those around them.",
  "Leaders don’t create followers. They create more leaders.",
  "Leadership is about action and results, not just speeches and promises.",
  "A leader must have a vision and the courage to follow it.",
  "A great leader’s success is reflected in the success of their people.",
  "The power of leadership is not in authority but in influence.",
  "A true leader invests in others and helps them unlock their potential.",
  "Leadership is not about making yourself important, but making others important.",
  "A real leader doesn’t demand respect – they earn it through their actions.",
  "Leadership is the bridge between vision and reality.",
  "A great leader doesn’t shine alone; they light up others too.",
  "A leader creates more hope than fear.",
  "The best leaders build teams, not just empires.",
  "Leadership is about making tough decisions with kindness and integrity.",
  "Good leaders bring out the best in people, even when they don’t see it themselves.",
  "A leader’s real power is in their ability to inspire action in others.",
  "Leadership is about creating opportunities for others, not just for yourself.",
  "Leaders are not those who say, ‘Go.’ They say, ‘Let’s go together.’",
  "Great leaders inspire confidence, not fear.",
  "A great leader sees potential where others see problems.",
  "Leaders create a path where there was none before.",
  "The essence of leadership is not authority, but trust.",
  "A true leader is one who turns obstacles into opportunities.",
  "The greatest leaders uplift others rather than elevate themselves.",
  "Leadership is about vision, courage, and unwavering belief in success.",
  "The measure of a great leader is how they handle failure.",
  "The best leaders don’t have all the answers, but they ask the right questions.",
  "A real leader builds people, not just projects.",
  "Leaders make a difference not by force, but by example.",
  "Leadership is about responsibility, not privilege.",
  "A leader’s legacy is measured in the lives they’ve touched.",
  "Great leaders adapt, grow, and learn continuously.",
  "Leadership is not about being fearless, but about taking action despite fear.",
  "A leader is not defined by their title but by their ability to inspire.",
  "Leaders create a culture of growth, encouragement, and support.",
  "Great leaders lead with heart, mind, and integrity.",
  "The best leaders remain students of life and learning.",
  "Leadership is about making things better, not just making things happen.",
  "Good leaders don’t micromanage; they empower and trust their teams.",
  "The true leader is one who helps others climb, rather than watching from the top.",
  "Leaders are visionaries who bring people together for a greater purpose.",
  "Great leaders don’t build walls; they build bridges.",
  "The best leaders invest in people, not just profits.",
  "Leadership is about leaving a legacy that outlives you.",
  "The strongest leaders uplift others rather than seek the spotlight.",
  "A leader’s wisdom lies in listening as much as in speaking.",
  "Leadership is about embracing change and guiding others through it.",
  "The mark of a great leader is humility in success and grace in failure.",
  "A great leader is one who makes those around them shine.",
  "Leadership is about bringing people together to accomplish something bigger than themselves.",
  "Great leaders balance confidence with humility.",
  "Leadership is not about creating fear, but fostering courage.",
  "A true leader remains calm in the face of chaos.",
  "The best leaders make decisions based on values, not popularity.",
  "Leadership is about clarity, not control.",
  "A great leader focuses on solutions, not just problems.",
  "True leadership is about being willing to do what you ask of others.",
  "Leadership is about recognizing the strengths in others and helping them grow.",
  "A great leader earns respect through authenticity and empathy.",
  "The best leaders encourage others to be their best selves.",
  "Leaders take responsibility when things go wrong and share success when things go right.",
  "Leadership is about encouraging innovation, not just following tradition.",
  "A leader’s most important trait is integrity.",
  "The greatest leaders are those who never stop learning and evolving.",
  "Leadership is about uniting people under a shared purpose.",
  "The best leaders know when to speak and when to listen.",
  "A true leader understands that leadership is a journey, not a destination.",
  "Leaders must first believe in themselves before others can believe in them.",
  "Leadership is about doing what’s right, even when it’s hard.",
  "A great leader doesn’t just direct; they empower others to take charge.",
  "Leadership is about turning inspiration into action.",
  "Leaders create cultures, not just companies.",
  "The best leaders never stop inspiring and never stop learning.",
  "Leadership is about staying true to your principles while adapting to change.",
  "A true leader doesn’t seek recognition; they seek impact.",
  "Great leaders lift others up, not themselves.",
  "Leadership is about seeing a better future and guiding others toward it.",
  "A great leader has the ability to see the unseen and make it possible.",
  "Leadership is about bringing out the best in those you lead.",
  "A leader’s strength is measured by the success of those they support.",
  "The best leaders inspire people to believe in their own potential.",
  "Leadership is the courage to take the first step, even when no one follows.",
  "A true leader puts purpose before power.",
  "Leadership is about leaving things better than you found them.",
  "The best leaders are not afraid of change – they create it.",
  "Great leaders are driven by passion, not ego.",
  "Leadership is about creating momentum for positive change.",
  "A leader’s true power lies in the trust they earn, not the authority they hold.",
  "The best leaders turn setbacks into stepping stones.",
  "Leadership is about creating opportunities where none exist.",
  "Great leaders guide, inspire, and uplift others to greatness.",
];

final List<String> leadershipImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled leadership and influence quotes with random images.
final List<QuoteItem> leadershipQuotes = getShuffledQuotes(
  leadershipQuotesRaw,
  leadershipImages,
);
