import '../quotes_randomizer.dart';

/// **Motivation for Hard Work Quotes & Images**
final List<String> motivationQuotesRaw = [
  "Success is the sum of small efforts, repeated day in and day out.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Dream big, work hard, stay focused, and surround yourself with good people.",
  "Opportunities don’t happen. You create them through hard work.",
  "Push yourself, because no one else is going to do it for you.",
  "There is no substitute for hard work. It is the price of success.",
  "Great things come to those who work tirelessly for them.",
  "Discipline is choosing between what you want now and what you want most.",
  "Your only limit is the amount of effort you’re willing to put in.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Work hard in silence, let success make the noise.",
  "The difference between ordinary and extraordinary is that little extra effort.",
  "Hard work spotlights the character of people: some turn up their sleeves, some turn up their noses, and some don’t turn up at all.",
  "Success doesn’t just find you. You have to go out and get it.",
  "You are rewarded in public for what you practice in private.",
  "Don’t wish for it. Work for it.",
  "Winners embrace hard work. They love the discipline of it.",
  "What you get by achieving your goals is not as important as what you become by achieving them.",
  "The harder you work, the luckier you get.",
  "If you’re not willing to work for it, don’t complain about not having it.",
  "Hustle until your haters ask if you’re hiring.",
  "Every accomplishment starts with the decision to try.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Success is earned. Never given.",
  "The price of success is hard work, dedication, and determination.",
  "Hard work turns dreams into reality.",
  "When you feel like quitting, remember why you started.",
  "Strive for progress, not perfection.",
  "Effort only fully releases its reward after a person refuses to quit.",
  "The road to success is paved with hard work and determination.",
  "If it were easy, everyone would do it.",
  "Hard work pays off in the future, laziness pays off now.",
  "Behind every successful person is years of hard work.",
  "Your success is determined by your daily habits.",
  "Small steps every day lead to big results over time.",
  "You won’t achieve anything if you don’t try.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Hard work builds character, discipline, and resilience.",
  "Success is not for the lazy.",
  "Your future is created by what you do today, not tomorrow.",
  "There are no shortcuts to success—just hard work and consistency.",
  "Don’t let anyone outwork you.",
  "You never know how strong you are until being strong is your only choice.",
  "Never give up on something you can’t go a day without thinking about.",
  "Pain is temporary. Quitting lasts forever.",
  "The pain of hard work is temporary, but the pride lasts forever.",
  "Put in the work now, and reap the rewards later.",
  "Action is the foundational key to all success.",
  "Be willing to put in the work that others won’t.",
  "Nobody cares about your excuses. Just get it done.",
  "Hard work will take you farther than natural talent ever could.",
  "Success isn’t given. It’s earned through hard work and perseverance.",
  "The grind never stops, and neither should you.",
  "The dream is free, but the hustle is sold separately.",
  "Don’t downgrade your dream to fit your reality. Upgrade your work ethic to match your vision.",
  "Your hustle determines your success.",
  "Work hard, stay consistent, and be patient. The results will come.",
  "Hard work is an investment in your future self.",
  "Your work ethic determines your success.",
  "The secret to success? Work harder than everyone else.",
  "Be unstoppable. Be relentless. Keep grinding.",
  "A little progress each day adds up to big results.",
  "Hard work is the key that unlocks doors of opportunity.",
  "Do what others won’t, so you can do what others can’t.",
  "Don’t be afraid of hard work. Be afraid of a life without purpose.",
  "Work hard, stay humble, and never stop learning.",
  "You are capable of more than you think.",
  "Effort, patience, and consistency will lead you to success.",
  "Make your dreams so big that working hard every day becomes a necessity.",
  "Excuses don’t build empires. Hard work does.",
  "Do today what others won’t, so tomorrow you can do what others can’t.",
  "Make yourself proud. Put in the work.",
  "Success doesn’t come from what you do occasionally, but from what you do consistently.",
  "Show up. Do the work. Stay consistent. Success will follow.",
  "Results happen over time, not overnight. Work hard and stay consistent.",
  "You didn’t come this far to only come this far.",
  "Your work ethic will separate you from the competition.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Success demands discipline and consistency.",
  "Hard work doesn’t guarantee success, but without it, failure is certain.",
  "Believe in yourself and put in the effort. The results will speak for themselves.",
  "The only thing standing between you and success is the work you’re willing to put in.",
  "Be so busy improving yourself that you have no time to criticize others.",
  "Dreams don’t work unless you do.",
  "If you stay consistent, success is inevitable.",
  "Don’t talk about it. Be about it.",
  "Your grind determines your greatness.",
  "Success is not about luck. It’s about hard work, persistence, and resilience.",
  "You don’t find willpower, you create it through hard work.",
  "Success is built on a foundation of hard work and sacrifice.",
  "Your biggest competition is yourself. Push harder every day.",
  "The best investment you can make is in your own work ethic.",
  "Without hard work, talent is nothing.",
  "Be willing to pay the price of success through dedication and effort.",
  "If you put in the effort, the results will come.",
  "Some people dream of success while others wake up and work for it.",
  "Stay patient, stay persistent, and keep grinding.",
  "The key to success is to start before you’re ready.",
  "Hard work and consistency always beat luck.",
  "What you do today determines your success tomorrow.",
  "Hustle in silence and let your success be your noise.",
  "There is no elevator to success—you have to take the stairs.",
  "Your potential is endless, but only if you work for it.",
  "Sweat now so you can shine later.",
  "Fall in love with the process, and the results will come.",
  "Great things never come from comfort zones. Work for it!",
  "Excuses will never build the future you want.",
  "The hustle brings the muscle.",
  "Success loves preparation. Keep grinding.",
  "Keep pushing, keep working, and never give up.",
  "Do what it takes, not what is easy.",
  "Your results are a reflection of your work ethic.",
  "Success starts with self-discipline.",
  "Work until you no longer have to introduce yourself.",
  "Your success tomorrow begins with your hustle today.",
  "Every step you take brings you closer to your goal.",
  "The harder the struggle, the sweeter the victory.",
  "Hard work doesn’t go unnoticed; the universe always rewards effort.",
  "Talent is nothing without dedication and discipline.",
  "You can have results or excuses, but not both.",
  "Success is built on consistency, not convenience.",
  "The best preparation for tomorrow is doing your best today.",
  "Success favors those who refuse to give up.",
  "Outwork your past self every single day.",
  "Your work ethic is your signature.",
  "Make today so productive that your future self thanks you.",
  "A strong work ethic beats luck every time.",
  "Hard work is the foundation of every great achievement.",
  "Nothing grows without effort—including you.",
  "You don’t always have to feel motivated; you just have to be disciplined.",
  "Your habits define your success.",
  "If it doesn’t challenge you, it won’t change you.",
  "Hard work is the currency of success.",
  "Small progress is still progress.",
  "The real grind is doing what you said you’d do, long after the mood you said it in has left.",
  "Success isn’t for the chosen few, but for those who choose to work for it.",
  "Be the hardest worker in the room, and success will follow.",
  "Hard work is a muscle—the more you use it, the stronger it gets.",
  "Wake up with determination, go to bed with satisfaction.",
  "The pain of today’s effort is the power behind tomorrow’s success.",
  "If you’re going through hell, keep going.",
  "A dream doesn’t become reality through magic; it takes sweat, determination, and hard work.",
  "Discipline is doing what needs to be done, even when you don’t feel like doing it.",
  "You are only confined by the limits you refuse to break.",
  "Winners don’t wait for chances, they take them.",
  "Success is 1% inspiration and 99% perspiration.",
  "Keep grinding until your idols become your rivals.",
  "The only limit to your impact is your imagination and commitment.",
  "Push past your comfort zone—it’s where growth happens.",
  "Hard work is a staircase; take one step at a time until you reach the top.",
  "Stop waiting. Start doing.",
  "The road to success is always under construction.",
  "Hustle with purpose, not desperation.",
  "Hard work is the bridge between goals and accomplishments.",
  "Your dedication today writes your success story tomorrow.",
  "Struggle now, shine later.",
  "Work hard, be kind, and amazing things will happen.",
  "Consistency creates confidence.",
  "Success is not about luck—it’s about how much you’re willing to sacrifice.",
  "A little progress each day leads to massive results.",
  "Your struggle is your strength in disguise.",
  "The future belongs to those who work hard for it today.",
  "Hard work is an investment that always pays off.",
  "The only thing that stands between you and your goals is effort.",
  "Get comfortable being uncomfortable—that’s where success lives.",
  "Your level of success is determined by your level of discipline and perseverance.",
  "Every master was once a beginner who never gave up.",
  "The best way to predict the future is to create it.",
  "Champions don’t show up to get everything they want; they show up to give everything they have.",
  "The best way to appreciate success is to work hard for it.",
  "Success doesn’t come to you; you go to it.",
  "Hustle in silence and let success do the talking.",
  "If you want different results, you have to do things differently.",
  "Hard work is the engine of achievement.",
  "Effort is never wasted; it’s just stored for the right time.",
  "The only way to do great work is to love what you do and work hard at it.",
  "Turn obstacles into opportunities through relentless effort.",
  "The key to success is a relentless work ethic.",
  "You can’t have a million-dollar dream with a minimum-wage work ethic.",
  "Believe in the process, trust the work, and success will follow.",
  "What comes easy won’t last, and what lasts won’t come easy.",
  "Make sweat your best investment.",
  "Success isn’t always about greatness. It’s about consistency. Hard work leads to success.",
  "The grind never lies. It will always show your true effort.",
  "Work hard, believe in yourself, and watch what happens.",
  "Be proud of how hard you’re working—even if the results aren’t visible yet.",
  "Work for a cause, not for applause.",
  "Success is made in the effort, not just the outcome.",
  "The best way to build confidence is through hard work.",
  "You get what you work for, not what you wish for.",
  "Stop doubting and start doing.",
  "Hard work is never wasted; it’s just stored up for a future reward.",
  "There are no shortcuts—just dedication and persistence.",
  "Progress takes patience and hard work.",
  "Hard work is what turns dreams into plans and plans into reality.",
  "Don’t stop grinding; your future self is counting on you.",
  "The only thing standing between you and success is the effort you’re willing to put in.",
  "Success is a journey, not a destination—so keep walking.",
  "Even the smallest effort moves you forward.",
  "Work for what you want, not for what you wish.",
  "Grit, grind, and greatness go hand in hand.",
  "Nothing will work unless you do.",
  "You may have to fight a battle more than once to win it.",
  "Big things have small beginnings. Work hard on the small things.",
  "Nothing worth having comes easy.",
  "Your effort today defines your success tomorrow.",
  "Hard work + patience = results.",
  "What’s easy won’t make you better. Work hard, and you will be stronger.",
  "Success happens one step at a time—just keep taking the next step.",
];

final List<String> motivationImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled motivation quotes with random images.
final List<QuoteItem> motivationQuotes = getShuffledQuotes(
  motivationQuotesRaw,
  motivationImages,
);
