import '../quotes_randomizer.dart';

/// **Overcoming Procrastination Quotes & Images**
final List<String> procrastinationQuotesRaw = [
  "The secret to getting ahead is getting started.",
  "Do it now. Sometimes ‘later’ becomes ‘never’.",
  "Action is the foundational key to all success.",
  "A year from now, you will wish you had started today.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Procrastination makes easy things hard and hard things harder.",
  "Small deeds done are better than great deeds planned.",
  "Start where you are. Use what you have. Do what you can.",
  "Your future is created by what you do today, not tomorrow.",
  "The best way to predict your future is to create it.",
  "Don’t let perfectionism become procrastination.",
  "Dream big, start small, act now.",
  "Take the first step. You don’t have to see the whole staircase.",
  "Someday is not a day of the week.",
  "Losers make promises; winners make commitments.",
  "An ounce of action is worth a ton of theory.",
  "Success is not about luck; it’s about discipline and hard work.",
  "Don’t wait for inspiration. It comes after starting.",
  "Your dreams don’t work unless you do.",
  "Success begins at the end of your comfort zone.",
  "The sooner you start, the sooner you finish.",
  "Waiting for the perfect time? It doesn’t exist.",
  "There are seven days in the week, and ‘someday’ isn’t one of them.",
  "Decide. Commit. Act. Succeed.",
  "The hardest thing about getting started is getting started.",
  "Don’t put off for tomorrow what you can do today.",
  "The cost of procrastination is the life you could have lived.",
  "If you spend too much time thinking, you’ll never do it.",
  "Procrastination is like a credit card: it’s fun until you get the bill.",
  "You may delay, but time will not.",
  "Quit talking. Begin doing.",
  "Done is better than perfect.",
  "The best way to get something done is to begin.",
  "A goal without action is just a wish.",
  "Your time is now. Stop waiting.",
  "Today’s effort is tomorrow’s success.",
  "The earlier you start, the more time you have to improve.",
  "What you do today will determine your tomorrow.",
  "Your dreams are waiting for you to take action.",
  "You don’t need more time, you need to act.",
  "If it’s important, you’ll find a way. If not, you’ll find an excuse.",
  "Opportunities multiply as you seize them.",
  "There’s no better time than now.",
  "Don’t let your fear of failure stop you from starting.",
  "Progress, not perfection.",
  "Do it now or regret it later.",
  "Time wasted is opportunity lost.",
  "The pain of discipline is better than the pain of regret.",
  "Take action and correct course along the way.",
  "The hardest part of any task is starting.",
  "Be stronger than your excuses.",
  "The habit of procrastination steals your success.",
  "Someday is just an excuse.",
  "Stop wishing, start doing.",
  "Your potential is wasted when you delay action.",
  "A small step today is better than waiting for the perfect moment.",
  "The difference between success and failure is action.",
  "Success loves speed.",
  "If you wait until you’re ready, you’ll be waiting forever.",
  "Do something today that your future self will thank you for.",
  "Excuses will always be there. Opportunities won’t.",
  "What you start today builds momentum for tomorrow.",
  "When you delay, you’re telling yourself your goal isn’t important.",
  "Procrastination kills more dreams than failure ever will.",
  "The sooner you finish, the sooner you can relax.",
  "Stop waiting for motivation. Take action and motivation will follow.",
  "Decide. Take action. Move forward.",
  "The best time to plant a tree was 20 years ago. The second-best time is now.",
  "Action beats anxiety every time.",
  "Stop overthinking and start doing.",
  "Start before you’re ready.",
  "You can’t reach your dreams without moving toward them.",
  "Waiting is a trap. Take action now.",
  "If you wait for perfect conditions, you’ll never get anything done.",
  "One hour of action is worth a lifetime of excuses.",
  "Results come from action, not intention.",
  "Your biggest enemy is the delay you allow.",
  "Commit to your goals and take daily steps.",
  "Every second you wait is time lost forever.",
  "Act as if your dreams depend on today’s effort—because they do.",
  "Let today be the day you take action.",
  "You can’t build a reputation on what you’re going to do.",
  "Discipline will take you where motivation won’t.",
  "Overcome procrastination one step at a time.",
  "Your time is precious—don’t waste it hesitating.",
  "The key to success is taking consistent action.",
  "If you keep waiting for the right time, it’ll never come.",
  "Action is the antidote to doubt.",
  "Procrastination makes simple things difficult.",
  "Success starts with a decision to move forward.",
  "Don't talk about what you’re going to do—just do it.",
  "Nothing changes unless you do.",
  "Think less. Do more.",
  "Stop delaying, start doing, and never look back.",
  "Don’t let fear paralyze you—take action now.",
  "Every journey begins with a single step.",
  "If it’s worth doing, it’s worth doing now.",
  "You can’t fail if you don’t quit.",
  "Avoiding work won’t make it go away.",
  "Each small effort adds up to great success.",
  "Success is built on tiny, daily actions.",
  "You have the power to change your habits today.",
  "Make today count—you won’t get it back.",
  "The difference between winners and losers is action.",
  "Act as if failure is impossible.",
  "Start now. The longer you wait, the harder it gets.",
  "Procrastination is the grave in which opportunity is buried.",
  "Your time is too valuable to waste.",
  "You are in control of your future—start shaping it today.",
  "Waiting won’t get you closer to your goals.",
  "Success is a result of doing, not waiting.",
  "Everything you want is on the other side of action.",
  "Don't let procrastination steal your dreams.",
  "Fear and doubt disappear with action.",
  "Start small, but start now.",
  "Work hard now so you can enjoy later.",
  "Doing something today is better than doing nothing at all.",
  "Think of where you’ll be in a year if you start today.",
  "If it’s worth achieving, it’s worth starting now.",
  "Don't let tomorrow be a repeat of today’s hesitation.",
  "Your goals deserve immediate attention.",
  "Turn procrastination into productivity.",
  "Take charge of your time and own your success.",
  "Procrastination only delays your happiness.",
  "Hard work today leads to freedom tomorrow.",
  "A task begun is a task half done.",
  "The best time to start was yesterday. The next best time is now.",
  "Push yourself, because no one else is going to do it for you.",
  "If you want to make an easy job seem hard, just keep putting it off.",
  "Procrastination is the thief of time.",
  "The only way to do great work is to love what you do and do it now.",
  "Inspiration exists, but it has to find you working.",
  "Winners focus on progress, not excuses.",
  "Doubt kills more dreams than failure ever will.",
  "The secret of getting things done is to act!",
  "It always seems impossible until it’s done.",
  "There are two kinds of pain in life: the pain of discipline and the pain of regret.",
  "Act now. Later is never guaranteed.",
  "You don’t find willpower, you create it with action.",
  "Take one step forward, and the path will reveal itself.",
  "One step at a time is all it takes to get there.",
  "Success is the sum of small efforts repeated day in and day out.",
  "A minute of action is better than an hour of planning.",
  "Start messy, improve later.",
  "The longer you wait, the heavier the burden.",
  "The bridge between dreams and reality is action.",
  "Your success depends on your ability to act consistently.",
  "You can’t improve something you never start.",
  "Regret weighs more than effort.",
  "You don’t drown by falling in water; you drown by staying there.",
  "Fear of failure should never be greater than the fear of not trying.",
  "Life rewards those who take action, not those who wait.",
  "Be a doer, not just a dreamer.",
  "Excuses are the lies we tell ourselves to delay success.",
  "Your dreams won’t chase you. You have to chase them.",
  "The time you waste now is the success you delay later.",
  "Every expert was once a beginner who didn’t quit.",
  "Don’t put off for tomorrow what you can conquer today.",
  "Great achievements begin with the courage to take the first step.",
  "Be addicted to progress, not procrastination.",
  "A small step forward is better than standing still.",
  "Discipline will get you what motivation won’t.",
  "Waiting for the right moment is an illusion.",
  "Replace ‘I should’ with ‘I must’ and watch your life change.",
  "Nothing worthwhile comes from hesitation.",
  "A slow start is still a start.",
  "Time waits for no one, so act now.",
  "You don’t have to be perfect, just start moving.",
  "Your goals don’t need excuses; they need effort.",
  "Focus on progress, not perfection.",
  "One hour of focused work beats a whole day of delay.",
  "Fear fades with action.",
  "Your potential is wasted when you keep waiting.",
  "Procrastination is a habit, and habits can be changed.",
  "Your future self is waiting for you to take action today.",
  "Stop thinking about it and just do it.",
  "There’s no such thing as the perfect time, only a perfect excuse.",
  "Your excuses don’t build your dreams, action does.",
  "You are stronger than your doubts.",
  "The best things in life come to those who take action.",
  "Start before you’re ready.",
  "A step forward is progress, no matter how small.",
  "Don’t wait for motivation, let discipline guide you.",
  "Don’t be afraid of failure; be afraid of not starting.",
  "The road to success is paved with effort, not intention.",
  "Decide what you want and make it happen.",
  "You will never regret taking action.",
  "A day wasted is a dream delayed.",
  "Your time is too valuable to waste on waiting.",
  "Your life won’t change until you start moving.",
  "You don’t have to do everything, just do something.",
  "Each step you take makes the next one easier.",
  "The hardest part of anything is just beginning.",
  "A little progress each day adds up to big results.",
  "Your mind will always look for the easy way out. Ignore it and act.",
  "Don’t let uncertainty keep you from taking the first step.",
  "If you’re tired of starting over, stop quitting.",
  "There’s no such thing as the ‘perfect’ time, only now.",
  "The best ideas in the world are useless without execution.",
  "Success doesn’t come to those who wait; it comes to those who act.",
  "A year from now, you’ll wish you had started today.",
  "Stop watching others succeed and start working on your own success.",
  "Every delay is an opportunity lost.",
  "Turn your ‘one day’ into ‘day one’.",
  "If you can dream it, you can start it.",
  "Action turns your dreams into reality.",
  "Success doesn’t wait for those who hesitate.",
  "No one ever accomplished great things by waiting.",
  "The more you do, the more confident you become.",
  "The longer you delay, the harder it gets.",
  "Avoiding the task makes it seem harder than it is.",
  "Act now; your future self will thank you.",
  "You don’t have to finish, but you have to start.",
  "Every action you take builds momentum.",
  "Perfection is the enemy of progress—just start!",
  "Your success is hidden in your daily habits.",
  "No one who waited for the perfect time ever achieved greatness.",
  "If you don’t take action, nothing changes.",
  "Start today, not tomorrow.",
  "Don’t sit and wait. Get up and create.",
  "Your potential means nothing without execution.",
  "Winners don’t wait for chances, they take them.",
  "Don’t let procrastination rob you of success.",
];

final List<String> procrastinationImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled overcoming procrastination quotes with random images.
final List<QuoteItem> procrastinationQuotes = getShuffledQuotes(
  procrastinationQuotesRaw,
  procrastinationImages,
);
