import '../quotes_randomizer.dart';

/// **Success & Failure Quotes & Images**

final List<String> successQuotesRaw = [
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "The only real failure is the failure to try.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be afraid to fail. Be afraid not to try.",
  "Mistakes are proof that you are trying.",
  "A person who never made a mistake never tried anything new.",
  "The road to success is paved with failures.",
  "Every failure brings with it the seed of an equivalent success.",
  "Failure is not the opposite of success; it’s part of success.",
  "The difference between successful people and others is how long they spend feeling sorry for themselves.",
  "Success is achieved and maintained by those who try and keep trying.",
  "Only those who dare to fail greatly can ever achieve greatly.",
  "Fall seven times, stand up eight.",
  "Success is not about winning all the time; it's about learning from your losses.",
  "Failure is not the end; it's the beginning of a new learning curve.",
  "Don't fear failure. Fear being in the same place next year.",
  "Success is going from failure to failure without losing your enthusiasm.",
  "Your failure does not define you. Your determination does.",
  "Great success is built on great failures.",
  "The only thing standing between you and success is continuous effort.",
  "Every successful person was once a beginner who failed multiple times.",
  "Your failures are your stepping stones to success.",
  "It is hard to fail, but it is worse never to have tried to succeed.",
  "Losers quit when they fail. Winners fail until they succeed.",
  "Do not be embarrassed by your failures; learn from them and start again.",
  "Failure is a detour, not a dead-end street.",
  "Success isn't given, it’s earned with hard work and persistence.",
  "Doubt kills more dreams than failure ever will.",
  "If you are not failing, you are not trying hard enough.",
  "Behind every success story, there is a tale of failure and perseverance.",
  "Failure is only a temporary stop on the journey to success.",
  "Don't let failure discourage you; let it teach you.",
  "Failure is proof that you are learning and growing.",
  "The key to success is learning how to fail gracefully.",
  "Success is a journey of overcoming failures, one step at a time.",
  "Failure builds character; success builds reputation.",
  "Your response to failure determines your path to success.",
  "If you never try, you’ll never fail; but you’ll also never succeed.",
  "Failure should be our teacher, not our undertaker.",
  "The only limit to your success is the fear of failure.",
  "Failure prepares you for success in ways success never can.",
  "A person who never failed never tried something new.",
  "No one succeeds without failure along the way.",
  "The more you fail, the more you learn, and the closer you are to success.",
  "A setback is just a setup for a comeback.",
  "Failure is the tuition you pay for success.",
  "Failure is a bruise, not a tattoo.",
  "Success comes to those who refuse to quit.",
  "Don't let a single failure define your entire journey.",
  "The only real mistake is the one from which we learn nothing.",
  "Success is the sum of small efforts repeated daily.",
  "Your failures should be motivation, not discouragement.",
  "The secret to success is learning from failure without getting discouraged.",
  "Failure is the price you pay for growth.",
  "Success and failure are two sides of the same coin; embrace both.",
  "No great success was ever achieved without some failures.",
  "Mistakes are the portals of discovery.",
  "You learn more from failure than from success.",
  "Failure is a stepping stone, not a stumbling block.",
  "The secret to success is not avoiding failure but overcoming it.",
  "There is no success without first experiencing failure.",
  "You can’t have success without taking risks and facing failures.",
  "Success is built on a foundation of past failures.",
  "Every failure brings you closer to success if you learn from it.",
  "The only thing more painful than failure is regret.",
  "Don't fear failure, fear being too afraid to try.",
  "Success doesn't come without its share of failures.",
  "Every master was once a disaster.",
  "If you learn from defeat, you haven’t really lost.",
  "Success is the result of perseverance despite failures.",
  "Don't let failure be your identity; let it be your teacher.",
  "One failure is just a step toward your next success.",
  "Fail forward, not backward.",
  "Every success story has failure chapters.",
  "It’s not how many times you fall, but how many times you get back up.",
  "Success is built by those who refuse to stop after failing.",
  "If you want to increase your success rate, double your failure rate.",
  "The first step to success is trying, even if you fail.",
  "Failure is the foundation upon which great achievements are built.",
  "A winner is just a loser who tried one more time.",
  "To succeed, you must first be willing to experience failure.",
  "The only failure in life is the failure to try.",
  "Success doesn’t come to those who fear failure.",
  "The road to success is never a straight path; it’s full of twists, turns, and setbacks.",
  "Every expert was once a beginner who failed many times.",
  "You must expect failure, but you must never accept it.",
  "The harder the struggle, the greater the success.",
  "You don’t fail until you stop trying.",
  "The biggest risk is not taking one.",
  "Failure is the forge that shapes success.",
  "Fail smart, fail fast, and fail forward.",
  "Success grows out of struggles and failures.",
  "Success starts when you stop fearing failure.",
  "Your failures are not fatal unless you refuse to learn from them.",
  "Small failures lead to big victories.",
  "Failures refine you, success defines you.",
  "Learn, adapt, and keep moving forward.",
  "Success is for those who keep showing up despite failures.",
  "The difference between success and failure is persistence.",
  "Failure is nothing but postponed success.",
  "Never give up. Today’s failure is tomorrow’s success story.",
  "With every failure, you gain valuable experience.",
  "Each failure brings new lessons that push you toward success.",
  "Every failure teaches you something that success cannot.",
  "Don't let failure break you; let it make you stronger.",
  "Failure is a bend in the road, not the end of the road.",
  "The only true failure is quitting when things get hard.",
  "Success happens when you turn failures into stepping stones.",
  "The fear of failure should never be greater than the desire to succeed.",
  "Your failures make your successes even sweeter.",
  "It’s not over until you decide to quit.",
  "Failure makes you stronger, smarter, and more resilient.",
  "Success is the art of rising every time you fall.",
  "Those who dare to fail greatly can achieve greatly.",
  "One step closer after failure is one step closer to success.",
  "The biggest failures often lead to the greatest successes.",
  "Your dreams are worth failing for—again and again.",
  "Failure is proof that you are striving for something greater.",
  "You only truly fail when you stop trying.",
  "Success and failure are both teachers; learn from them equally.",
  "Success is born out of perseverance through repeated failures.",
  "Your failure today is the foundation of your success tomorrow.",
  "Failing is not falling down; it’s staying down that makes it failure.",
  "A champion is defined not by their wins, but by how they recover from failures.",
  "The road to success is paved with obstacles; your failures are stepping stones.",
  "Failure is simply the raw material from which success is built.",
  "Great things never come from comfort zones, nor from fear of failure.",
  "You are not your failures; you are your ability to overcome them.",
  "Don't let success make you arrogant, and don't let failure break you.",
  "The greatest successes often come after the hardest failures.",
  "Failure is the test that success must pass through.",
  "Success and failure are both lessons; the wise learn from both.",
  "The surest way to fail is never to try.",
  "Success is about persistence, not perfection.",
  "If you fear failure, you'll never taste the sweetness of success.",
  "Your failures should fuel your determination, not weaken it.",
  "The greatest failure is not trying at all.",
  "Success belongs to those who can stand up one more time than they fall.",
  "A single failure doesn't define you; quitting does.",
  "Mistakes are the price of progress.",
  "Success is not luck; it is persistence through failure.",
  "Failure is the universe redirecting you to something greater.",
  "Don't let failure be your excuse; let it be your motivation.",
  "If you never fail, you’ve never pushed yourself enough.",
  "Success is measured by how high you bounce after hitting rock bottom.",
  "A river cuts through rock not because of its power, but because of its persistence.",
  "Fail until you succeed; it's the only way forward.",
  "Don't measure success by wins alone—measure it by lessons learned from failure.",
  "Failure is like training; it makes you stronger for the next challenge.",
  "If success was easy, it wouldn’t be valued as much.",
  "The scars of failure are what make success so rewarding.",
  "Even the most successful people have failed more times than they can count.",
  "Your failures today are building blocks for future success.",
  "Success is built by those who embrace failure, not fear it.",
  "Failure is an event, not a person.",
  "The only way to avoid failure is to do nothing—then, you fail by default.",
  "Behind every successful person is a trail of failures they learned from.",
  "Every expert started as a beginner who failed repeatedly.",
  "The only failure that matters is the failure to learn from past mistakes.",
  "Each failure is a necessary step toward your greatest victory.",
  "You don’t need to avoid failure—you need to embrace it as part of the journey.",
  "The strongest people are the ones who have failed the most and kept going.",
  "Fear of failure is the greatest enemy of success.",
  "The best way to ensure success is to increase your willingness to fail.",
  "Greatness comes not from avoiding failure, but from learning how to rise above it.",
  "The greater the failure, the sweeter the success that follows.",
  "Success is earned through resilience, not perfection.",
  "Your failures are not your weaknesses—they are proof of your determination.",
  "Failure refines you, but it does not define you.",
  "Behind every breakthrough is a long list of failures.",
  "Don't let one failure convince you that you are incapable of success.",
  "You will fail your way to success—embrace the process.",
  "Failure is a temporary inconvenience, not a permanent status.",
  "Success is learning to turn failures into stepping stones.",
  "The harder the struggle, the greater the triumph.",
  "You cannot climb the ladder of success with the fear of falling.",
  "Successful people see failure as feedback, not as defeat.",
  "Every failure brings you closer to the knowledge that leads to success.",
  "Failure is simply success in progress.",
  "You cannot truly succeed until you have failed enough to appreciate success.",
  "Failure is nothing but a detour on the way to success.",
  "Fail small, fail fast, and learn big.",
  "It’s not about avoiding failure, but about failing smart.",
  "The only way to master success is by mastering failure.",
  "Success does not come to those who wish for it, but to those who work through failures for it.",
  "Your willingness to persist despite failure is what defines your potential for success.",
  "If failure is not an option, success is just an illusion.",
  "The key to success is embracing failure as a mentor, not an enemy.",
  "When you feel like giving up, remember that success might just be one failure away.",
  "Failure is the investment you make in your own learning.",
  "Success is built upon the rubble of repeated failures.",
  "Failing is not losing; it's proof that you’re trying.",
  "No failure is final unless you allow it to be.",
  "The biggest difference between winners and losers is how they handle failure.",
  "To succeed spectacularly, you must first fail spectacularly.",
  "Failure is the seed from which success grows.",
  "Even a failed attempt moves you one step forward.",
  "Success isn’t about getting it right the first time—it’s about not giving up when you don’t.",
  "Failures are milestones on the road to achievement.",
  "Your biggest failures often lead to your biggest breakthroughs.",
  "Failure is a powerful teacher—listen to its lessons.",
  "Those who fear failure also fear success.",
  "Without failure, success would have no meaning.",
  "Don't be afraid of failing; be afraid of never trying.",
  "Failure tests your resolve; success rewards your persistence.",
  "If you learn from failure, it becomes success in disguise.",
  "The greatest people in history were the ones who failed most—until they succeeded.",
  "Success is just failure turned inside out.",
  "Behind every failure is an untold lesson waiting to be learned.",
  "Every successful person was once a dreamer who failed multiple times.",
  "If you don’t fail, you’re not pushing yourself hard enough.",
  "Successful people don’t fear failure; they embrace it as part of the journey.",
  "The only way to completely fail is to give up entirely.",
  "Success is built one failure at a time.",
  "Failure is just an unfinished chapter in the book of success.",
  "If you fail today, it only means you are one step closer to success tomorrow.",
];

final List<String> successImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled success & failure quotes with random images.
final List<QuoteItem> successQuotes = getShuffledQuotes(
  successQuotesRaw,
  successImages,
);
