import '../quotes_randomizer.dart';

/// **Time Management Wisdom Quotes & Images**
final List<String> timeQuotesRaw = [
  "Time is what we want most, but what we use worst.",
  "You may delay, but time will not.",
  "The bad news is time flies. The good news is you're the pilot.",
  "Don’t spend time beating on a wall, hoping to transform it into a door.",
  "Lost time is never found again.",
  "Time is a created thing. To say ‘I don’t have time’ is like saying ‘I don’t want to.’",
  "A year from now, you may wish you had started today.",
  "Time isn’t the main thing, it’s the only thing.",
  "Time is the school in which we learn, time is the fire in which we burn.",
  "To do two things at once is to do neither.",
  "Focus on being productive instead of busy.",
  "The way we spend our time defines who we are.",
  "Do not squander time, for that’s the stuff life is made of.",
  "Lack of direction, not lack of time, is the problem. We all have 24-hour days.",
  "The secret to your future is hidden in your daily routine.",
  "Your future is created by what you do today, not tomorrow.",
  "Small daily improvements over time lead to stunning results.",
  "Time management is really a misnomer—the challenge is not to manage time, but to manage ourselves.",
  "Ordinary people think merely of spending time; great people think of using it.",
  "Until we can manage time, we can manage nothing else.",
  "Most of us spend too much time on what is urgent and not enough time on what is important.",
  "The key is in not spending time, but in investing it.",
  "Plan your work and work your plan.",
  "A goal without a plan is just a wish.",
  "You can do anything, but not everything.",
  "If you fail to plan, you are planning to fail.",
  "Your priorities are your character.",
  "Decide what you want, decide what you are willing to exchange for it. Establish your priorities and go to work.",
  "It is not enough to be busy… The question is: what are we busy about?",
  "Dost thou love life? Then do not squander time, for that’s the stuff life is made of.",
  "Successful people are simply those with successful habits.",
  "Don’t wait. The time will never be just right.",
  "The best way to predict the future is to create it.",
  "What gets scheduled gets done.",
  "An inch of time is an inch of gold, but you can't buy that inch of time with an inch of gold.",
  "There’s never enough time to do it right, but there’s always enough time to do it over.",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "Start where you are. Use what you have. Do what you can.",
  "Time management is life management.",
  "Balance is not something you find, it’s something you create.",
  "You will never find time for anything. If you want time, you must make it.",
  "Time spent on hiring is time well spent.",
  "No one is too busy; it’s just a matter of priorities.",
  "To be successful, you must decide exactly what you want to accomplish, then resolve to pay the price to get it.",
  "Time is the wisest counselor of all.",
  "The more you chase time, the more it runs away.",
  "Time is non-refundable. Use it with intention.",
  "A wise person does at once what a fool does at last.",
  "The habit of managing time wisely is the foundation of success.",
  "Every second you spend is an investment in your future.",
  "Productivity is never an accident. It is always the result of a commitment to excellence and smart planning.",
  "If something takes less than two minutes, do it now.",
  "You can’t make up for lost time, but you can stop losing more.",
  "Successful people don’t find time, they make time.",
  "Stop being busy and start being effective.",
  "Work expands so as to fill the time available for its completion.",
  "Time management is the art of arranging, organizing, and scheduling your time to get things done.",
  "The most important investment you can make is in yourself and how you use your time.",
  "What you do today matters. What you do consistently defines you.",
  "Success is determined by how you use your time when no one is watching.",
  "Every wasted moment subtracts from the time you have to make a difference.",
  "If you don’t prioritize your life, someone else will.",
  "The way to get started is to quit talking and begin doing.",
  "A minute of planning saves 10 minutes of execution.",
  "You must master your time rather than becoming a slave to the constant flow of events and demands.",
  "Make every second count. Your future self will thank you.",
  "Each day is a blank canvas. How you use your time paints the picture of your life.",
  "Respect your time. Others will follow your example.",
  "Time is not money; it is much more valuable than money.",
  "Don’t measure time, make time count.",
  "Work smarter, not harder.",
  "The successful person has the habit of doing what failures don’t like to do.",
  "Saying ‘no’ is a powerful time management tool.",
  "Tomorrow is never promised. Start today.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "The clock is ticking. Are you becoming the person you want to be?",
  "Don't let yesterday take up too much of today.",
  "It’s not about having time, it’s about making time.",
  "Every action has a price in time. Choose wisely.",
  "Make a schedule that reflects your values, not just your tasks.",
  "Discipline is the bridge between goals and accomplishment.",
  "Instead of saying ‘I don’t have time,’ try saying ‘It’s not a priority,’ and see how it feels.",
  "Every day is an opportunity to invest in yourself.",
  "Success begins with a well-managed calendar.",
  "Avoid time thieves: distractions, procrastination, and multitasking.",
  "You own the time you don’t waste.",
  "Deadlines exist for a reason—respect them.",
  "Your mindset about time determines how you use it.",
  "Wasting time is stealing from yourself.",
  "Do the most important thing first each day.",
  "A productive day starts the night before.",
  "Be ruthless with your time. It’s the most valuable thing you own.",
  "The key to efficiency is eliminating distractions.",
  "Master your minutes, and you will master your days.",
  "If it’s important, schedule it.",
  "Your habits determine how well you manage time.",
  "What you do in your free time determines your future.",
  "Do less, but do it better.",
  "The real secret of time management is self-discipline.",
  "The most successful people are the ones who respect their time the most."
      "Time is the most valuable thing a person can spend.",
  "You can’t manage time, but you can manage yourself.",
  "A well-spent day brings happy sleep.",
  "Time is the only commodity that can’t be saved; it can only be spent.",
  "Don’t watch the clock; do what it does—keep going.",
  "You have the same number of hours in a day as the most successful people in history.",
  "Time waits for no one, so use it wisely.",
  "Your ability to manage time is your ability to manage life.",
  "The best investment you can make is in how you use your time.",
  "Time is your most precious resource—spend it wisely.",
  "What you do today will define your tomorrow.",
  "You don’t find time, you create it.",
  "Take care of the minutes, and the hours will take care of themselves.",
  "The greatest gift you can give someone is your time.",
  "Plan your day, or your day will plan you.",
  "The way you spend your time defines your success.",
  "Time is a currency—spend it on things that matter.",
  "Your future self is watching. Make the right decisions today.",
  "The clock never stops, but you have the power to make every second count.",
  "To waste time is to waste life.",
  "Time is a non-renewable resource. Use it wisely.",
  "Your priorities are reflected in your calendar.",
  "What you do with your time today determines where you’ll be tomorrow.",
  "Time spent planning is never wasted.",
  "Success is built on the small habits you repeat daily.",
  "You control your time, or your time controls you.",
  "The value of time increases as you run out of it.",
  "Time is not just money—it’s life.",
  "If you don’t have time for what matters, make time.",
  "Lost time is never recovered, so don’t waste it.",
  "The secret to success is in your daily routine.",
  "Every moment is a fresh beginning.",
  "Your schedule should reflect your goals, not just your tasks.",
  "If you prioritize everything, you prioritize nothing.",
  "Time is a gift—use it to build something meaningful.",
  "Small actions over time lead to big results.",
  "Eliminate time-wasters and focus on what matters.",
  "Your life is made up of time—use it intentionally.",
  "The most successful people master their minutes.",
  "Time is borrowed, not owned. Spend it wisely.",
  "What you repeatedly do determines your destiny.",
  "Your dreams deserve your time—make them a priority.",
  "Wasting time today is stealing from your future self.",
  "The way you manage time is a reflection of your self-discipline.",
  "A life well-managed is a life well-lived.",
  "You will never regret time spent wisely.",
  "Make today so productive that your future self thanks you.",
  "The secret to success is managing your time, not just your tasks.",
  "If you don’t control your time, others will.",
  "Each day is a new opportunity to be productive.",
  "Time doesn’t change things; action does.",
  "Great things are done by small things brought together over time.",
  "Stop saying you don’t have time and start making time.",
  "Time is the real wealth; spend it on things that matter.",
  "You can’t control time, but you can control how you use it.",
  "Being busy is not the same as being productive.",
  "Every second wasted is a second lost forever.",
  "Make every hour count towards your goals.",
  "Time management is really about self-management.",
  "Stop procrastinating; start executing.",
  "If you don’t respect your time, don’t expect others to.",
  "Focus on progress, not perfection.",
  "Productivity is about efficiency, not busyness.",
  "A disciplined mind leads to a disciplined schedule.",
  "Make time for what truly matters.",
  "Time flies, but you are the pilot.",
  "Effective time management is the key to success.",
  "Time well spent leads to a life well lived.",
  "What you do today defines who you become tomorrow.",
  "A minute wasted is a minute you can never get back.",
  "The best way to use time is to invest it in personal growth.",
  "A dream without a deadline is just a wish.",
  "The difference between success and failure is how you use your time.",
  "Prioritize your time, or it will be prioritized for you.",
  "Choose progress over perfection.",
  "The quality of your time determines the quality of your life.",
  "Take control of your time before it takes control of you.",
  "A well-organized life begins with well-managed time.",
  "Time is life. Don’t waste it on things that don’t matter.",
  "Your success is determined by how you manage your time.",
  "The best productivity tool is self-discipline.",
  "If you want more time, waste less of it.",
  "Time is the only thing you spend that you can’t earn back.",
  "The path to success is paved with time well spent.",
  "Use time wisely—it’s the one resource you can’t replenish.",
  "Being productive means doing more of what truly matters.",
  "There’s always time for what’s important if you make it a priority.",
  "Productivity is about working smarter, not just harder.",
  "Winners use their time wisely. Losers waste it.",
  "The best way to save time is to stop wasting it.",
  "How you spend your time determines how you spend your life.",
  "A well-used day is a successful day.",
  "If you don’t set priorities, life will set them for you.",
  "The future belongs to those who plan for it today.",
  "Your time is your most valuable asset. Protect it.",
  "Spend time on what makes you grow.",
  "If you wait for the perfect time, you’ll wait forever.",
  "You can always earn more money, but you can’t earn more time.",
  "The way you use your time determines the results you get.",
  "Small daily actions create massive long-term results.",
  "If you want to change your life, start by changing how you use your time.",
  "Every minute is a chance to move closer to your dreams.",
  "Plan your time, or your time will plan you.",
  "The best way to predict the future is to shape it today.",
  "Your time is limited—don’t waste it living someone else’s dream.",
];

final List<String> timeImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled time management wisdom quotes with random images.
final List<QuoteItem> timeQuotes = getShuffledQuotes(timeQuotesRaw, timeImages);
