import '../quotes_randomizer.dart';

/// **Workplace Ethics & Values Quotes & Images**
final List<String> workplaceQuotesRaw = [
  "Integrity is doing the right thing, even when no one is watching.",
  "Ethics is knowing the difference between what you have a right to do and what is right to do.",
  "A business that makes nothing but money is a poor business.",
  "Honesty and transparency make you different from the rest.",
  "A reputation for integrity is worth more than any paycheck.",
  "Your values shape your actions, and your actions define your character.",
  "Success without integrity is failure.",
  "Work hard in silence, let your ethics make the noise.",
  "Doing what is right may not always be easy, but it is always worth it.",
  "Ethics is the foundation of any successful organization.",
  "Respect in the workplace creates a culture of trust.",
  "Always choose character over convenience.",
  "Fairness and honesty will take you further than shortcuts ever will.",
  "Excellence is not a skill, it's an attitude.",
  "Responsibility is accepting that you are the cause and the solution of the matter.",
  "Integrity means following your moral compass even when it's hard.",
  "The strength of a team is built on trust and ethical behavior.",
  "Your work is your signature—make it something you’re proud of.",
  "The best way to earn trust is through consistent ethical behavior.",
  "The greatest test of integrity is when you are faced with temptation.",
  "Your character is your brand.",
  "Leaders who prioritize ethics create teams that thrive.",
  "Ethical decision-making builds long-term success.",
  "Trust is earned through ethical conduct and transparency.",
  "Professionalism starts with treating others with respect.",
  "Honesty is the first chapter in the book of wisdom.",
  "Accountability breeds responsibility.",
  "Success built on dishonesty is temporary.",
  "Hard work and ethics never go unnoticed.",
  "Integrity is choosing your thoughts and actions based on values, not personal gain.",
  "Ethics is the soul of a great workplace.",
  "Success without ethics is like a house built on sand.",
  "Leadership is about making others better through your presence and ethics.",
  "A workplace with ethics is a workplace with purpose.",
  "Respect is earned through ethical behavior, not demanded.",
  "Truth builds trust. Lies destroy it.",
  "Lead with integrity, and others will follow.",
  "Your values are your true north—never lose sight of them.",
  "A strong ethical foundation creates a thriving work culture.",
  "A clear conscience is the softest pillow.",
  "Professionalism is built on ethics and accountability.",
  "The ethical path may be difficult, but it leads to true success.",
  "What you do in private reflects who you are in public.",
  "Be someone people can count on to do the right thing.",
  "Short-term gains from unethical behavior lead to long-term losses.",
  "Doing good is good business.",
  "A leader’s integrity sets the tone for the entire workplace.",
  "The way you treat people in the workplace defines your leadership.",
  "Courage is standing up for what is right, even when you stand alone.",
  "True leadership is based on ethics, not authority.",
  "Workplace values determine the strength of an organization.",
  "Be ethical, not because you have to, but because you want to.",
  "An ethical workplace is a productive workplace.",
  "Doing the right thing is a habit, not a one-time decision.",
  "Ethical companies attract ethical employees.",
  "Small ethical decisions shape big workplace cultures.",
  "Honesty and integrity are the best policies for business success.",
  "Your ethics are tested the most when no one is watching.",
  "Leaders set the ethical tone of an organization.",
  "Accountability builds a culture of trust.",
  "A toxic workplace is built on unethical behavior.",
  "A team built on ethics will always outperform one built on deception.",
  "Ethics is not a part of business; it is the heart of business.",
  "A promise made must be a promise kept.",
  "Loyalty should never be at the cost of integrity.",
  "A great workplace starts with great values.",
  "Always act in a way that you would be proud of in the future.",
  "Business ethics is the bridge between personal values and corporate responsibility.",
  "A company’s true wealth is measured in trust, not profit.",
  "The true test of character is how you act when faced with ethical dilemmas.",
  "An ethical workplace attracts ethical clients.",
  "Leadership without ethics is manipulation.",
  "Your moral compass should guide your professional decisions.",
  "Unethical behavior is a short-term gain with long-term consequences.",
  "Employees who feel respected and valued perform better.",
  "You cannot separate ethics from success.",
  "A strong team is built on trust and shared values.",
  "Integrity is the foundation of lasting relationships.",
  "The best business strategy is honesty.",
  "A person’s character is revealed in their work ethic.",
  "Honesty and integrity are not optional in the workplace.",
  "The workplace thrives on trust, not fear.",
  "What you tolerate becomes your workplace culture.",
  "Quality work is built on a foundation of ethics.",
  "Trust grows where honesty and ethics are practiced.",
  "An ethical leader earns respect, not just obedience.",
  "Your values are your strongest assets in your career.",
  "A true leader chooses ethics over personal gain.",
  "The ethical path may not be the fastest, but it is the strongest.",
  "Reputation takes years to build and seconds to destroy.",
  "Trust is the currency of a strong organization.",
  "A workplace that values ethics creates leaders, not followers.",
  "Respect for colleagues fosters a positive work environment.",
  "A person’s values reflect in their work habits.",
  "You build credibility through ethical choices.",
  "Compromise on quality, not on ethics.",
  "A team built on integrity will always stand strong.",
  "The highest ethical standards lead to the best workplaces.",
  "Hard work and honesty create lasting success.",
  "Ethical behavior is an investment in your career.",
  "The right thing is rarely the easiest thing.",
  "Your word is your worth—keep it strong.",
  "Lies in the workplace create cracks in trust.",
  "Doing good work means doing honest work.",
  "Culture eats strategy for breakfast—build a culture of integrity.",
  "A leader’s true power lies in ethical leadership.",
  "Work ethics should be the backbone of every company.",
  "Your actions define your reputation—choose wisely.",
  "A workplace built on honesty fosters innovation.",
  "The golden rule applies in the office too—treat others as you wish to be treated.",
  "Strong ethics drive strong businesses.",
  "True success is measured in trust, not just profits.",
  "An ethical mindset ensures long-term success.",
  "Workplace ethics define the organization’s future.",
  "Lead with your values, and success will follow.",
  "A culture of ethics creates a culture of excellence.",
  "Without ethics, power is just exploitation.",
  "People work best in an environment of trust and respect.",
  "The best workplaces are built on a foundation of integrity.",
  "What you do when no one is looking defines you.",
  "A commitment to ethics is a commitment to success.",
  "The best leaders inspire ethical behavior.",
  "Success that compromises values is not real success.",
  "Choose ethics over expediency every time.",
  "Respect, honesty, and trust form the pillars of a great workplace.",
  "Acting with integrity is always the right choice."
      "Ethical leadership creates ethical teams.",
  "A strong work ethic is the foundation of success.",
  "Integrity is not just about being honest; it's about being consistent.",
  "Trust is built through ethical behavior and transparency.",
  "Your actions define your workplace values, not your words.",
  "Fair treatment of employees creates a loyal workforce.",
  "Doing the right thing means standing up for ethics, even when it's hard.",
  "Ethics should not be situational—it should be a standard.",
  "Workplace ethics is the silent force behind strong company culture.",
  "An ethical workplace values people over profit.",
  "Honest work creates a legacy of trust.",
  "Good ethics is good business.",
  "The ethical path may be tough, but it always leads to success.",
  "A culture of accountability ensures workplace integrity.",
  "An honest mistake is better than a dishonest success.",
  "Respect in the workplace fosters a culture of cooperation.",
  "Ethical employees make ethical companies.",
  "The golden rule applies to the workplace—treat others with respect.",
  "Short-term gains from unethical choices lead to long-term losses.",
  "Your integrity is your most valuable workplace asset.",
  "A workplace built on honesty attracts talent and success.",
  "Unethical behavior can damage a company faster than any competitor.",
  "Leaders should lead with values, not just vision.",
  "Respect, trust, and ethics make a great workplace.",
  "Employees who feel valued work harder and stay longer.",
  "The best workplaces make ethics their foundation.",
  "Success earned with integrity is success worth keeping.",
  "Your work reflects your values—make it count.",
  "People may forget what you said, but they will never forget how you treated them.",
  "Doing what’s right in the workplace is never the wrong choice.",
  "If you compromise ethics for profit, you will eventually lose both.",
  "An organization’s strength lies in the ethics of its employees.",
  "True leadership is about making ethical decisions, even when it’s difficult.",
  "Ethics in the workplace leads to respect from employees and customers alike.",
  "An ethical company attracts ethical clients.",
  "The best leaders don’t demand respect—they earn it through ethical behavior.",
  "A company’s reputation is built on the values it upholds.",
  "Employees follow the example set by their leaders.",
  "A business with strong ethics is built to last.",
  "When ethics are lost, so is trust.",
  "Fair treatment of employees results in a productive workforce.",
  "Without ethics, there can be no true success.",
  "A toxic work culture begins where ethics are ignored.",
  "Your reputation is built by the ethical choices you make every day.",
  "Ethical decisions create long-term prosperity.",
  "Respect and fairness should be at the heart of every workplace.",
  "The real test of integrity is what you do when no one is watching.",
  "A great workplace is one where ethics are non-negotiable.",
  "The most valuable thing in a workplace is trust.",
  "Leaders with integrity inspire teams with purpose.",
  "Good ethics build great teams.",
  "Your moral compass should guide your workplace behavior.",
  "When ethics are prioritized, success follows naturally.",
  "Integrity at work means keeping your promises and doing your best.",
  "Respect and kindness should never be compromised for profit.",
  "The strength of an organization is measured by its ethical standards.",
  "A workplace without ethics is a workplace without stability.",
  "Doing right is not always easy, but it is always necessary.",
  "Trust is built in small moments of ethical decision-making.",
  "The success of a business is measured by more than just profit—it’s about impact.",
  "Honesty in the workplace fosters innovation and collaboration.",
  "Being ethical is not just about following rules, but about doing what is right.",
  "Accountability is a sign of a strong work ethic.",
  "Ethical workplaces attract employees who are committed to excellence.",
  "An ethical company earns the trust of its employees and customers alike.",
  "True workplace success is built on respect, honesty, and fairness.",
  "Fairness should be the foundation of every company’s policies.",
  "A leader’s ethics determine the culture of their organization.",
  "People don’t leave bad jobs; they leave bad workplace cultures.",
  "Without honesty, no business can truly thrive.",
  "Good ethics makes for good business practices.",
  "Doing good work means doing it with integrity.",
  "Ethical employees contribute to a positive and sustainable workplace.",
  "Success without ethics is failure in disguise.",
  "What you do in your workplace defines your character.",
  "The companies that value ethics attract the best employees.",
  "Your values should guide your career, not just your personal life.",
  "The best way to gain respect is to act with integrity.",
  "True teamwork is built on ethical behavior and mutual respect.",
  "Fair wages, fair treatment, and fair policies create a great workplace.",
  "Integrity should never be sacrificed for short-term success.",
  "A healthy work environment starts with ethical leadership.",
  "Being ethical at work means treating colleagues with respect and fairness.",
  "Leadership is about making ethical choices even when they are difficult.",
  "A business without ethics is like a house without a foundation.",
  "A commitment to ethics creates a workplace people are proud to be a part of.",
  "True character is shown in the choices you make at work every day.",
  "A workplace based on ethics fosters loyalty and dedication.",
  "Honesty and integrity should never be compromised for a deadline or a profit.",
  "Strong values make a strong workplace culture.",
  "Without ethics, even the most profitable business will eventually fail.",
  "Treat employees with respect, and they will give you their best work.",
  "Every ethical choice you make adds to your professional reputation.",
  "A great workplace values honesty over deception.",
  "Employees who are treated fairly perform better and stay longer.",
  "Success comes and goes, but integrity lasts a lifetime.",
  "Fairness in the workplace leads to fairness in business.",
  "Workplace culture is shaped by the ethical choices of its employees.",
  "A commitment to integrity is a commitment to long-term success.",
  "Good ethics create a positive and inclusive workplace.",
  "A company’s brand is defined by the values it upholds.",
  "Every decision in the workplace should reflect a commitment to honesty and fairness.",
];

final List<String> workplaceImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled workplace ethics and values quotes with random images.
final List<QuoteItem> workplaceQuotes = getShuffledQuotes(
  workplaceQuotesRaw,
  workplaceImages,
);
