import '../quotes_randomizer.dart';

/// **Family Bonds Quotes & Images**
final List<String> familyQuotesRaw = [
  "Family is where life begins and love never ends.",
  "A happy family is but an earlier heaven.",
  "The love of a family is life’s greatest blessing.",
  "Family gives us roots to stand tall and strong.",
  "In the heart of every family is love and connection.",
  "Family means no one gets left behind or forgotten.",
  "Home is where love resides, memories are created, and family is forever.",
  "The strength of a family lies in its unity.",
  "A family’s love is the foundation of a fulfilling life.",
  "No wealth can replace the love of a close-knit family.",
  "A house is made of walls and beams, but a home is built with love and dreams.",
  "Families are like branches on a tree; we grow in different directions, yet our roots remain as one.",
  "The love between family members is the strongest bond on earth.",
  "Family is not just an important thing; it’s everything.",
  "A family that eats together, stays together.",
  "The best thing in life is the warmth of a loving family.",
  "A true family stands by you in every storm.",
  "Family is the heart of a happy life.",
  "A strong family is a shelter in life’s storms.",
  "Happiness is being surrounded by those who love you unconditionally.",
  "A family’s love is the glue that holds everything together.",
  "Nothing is more powerful than the love of family.",
  "Your family is your greatest treasure.",
  "Through every high and low, family remains your constant support.",
  "Family love is the purest form of unconditional love.",
  "Together, a family can overcome any obstacle.",
  "Love, laughter, and family—life’s greatest gifts.",
  "The love of a family is a gift that lasts forever.",
  "No distance can weaken the bond of a loving family.",
  "A family is a circle of love, strength, and trust.",
  "Home is not a place, it’s the people who love you.",
  "Family is the compass that guides us through life.",
  "The memories we create with our family are priceless.",
  "A family’s love is a beacon in times of darkness.",
  "Cherish your family, for they are your greatest blessing.",
  "A family is a masterpiece created with love.",
  "Strong family ties are the foundation of a happy life.",
  "The bond of family is stronger than anything else.",
  "Nothing compares to the laughter of a family together.",
  "Families build each other up, no matter what.",
  "A tight-knit family is a fortress of love and security.",
  "Every family has its ups and downs, but love always remains.",
  "Family is the first school of love and kindness.",
  "A family’s love grows stronger with time.",
  "You never outgrow the love of your family.",
  "Love is what makes a family, not blood.",
  "Family stands by you even when the world turns away.",
  "A home filled with love is a home filled with joy.",
  "Family is the key to a life full of happiness.",
  "Where there is family, there is warmth and belonging.",
  "A family’s love is like a candle—it shines brightest in the darkness.",
  "Family is the thread that weaves the fabric of our lives.",
  "Through thick and thin, family is always there.",
  "Loving families create a world full of kindness.",
  "The joy of family is the best kind of happiness.",
  "Every family has a story—make sure yours is full of love.",
  "Home is where the love of your family resides.",
  "Families teach us the meaning of love and sacrifice.",
  "Blood makes you related, but love makes you family.",
  "Family ties grow stronger with every shared memory.",
  "A united family can conquer any challenge.",
  "Love within a family is the foundation of a beautiful life.",
  "A family’s support is the wind beneath your wings.",
  "Family is a place where love knows no boundaries.",
  "Nothing is more comforting than a family’s embrace.",
  "A loving family is life’s greatest blessing.",
  "Happiness is multiplied when shared with family.",
  "Family is the source of our greatest strength.",
  "A strong family bond is an unbreakable force.",
  "Every family is unique, but love is always the common thread.",
  "Family means finding strength in one another.",
  "Home is where family gathers with love and laughter.",
  "Family makes ordinary moments extraordinary.",
  "A house may be built with bricks, but a home is built with love.",
  "The best inheritance a parent can give is love and guidance.",
  "A family’s love is the best foundation for a fulfilling life.",
  "Love, respect, and trust—keys to a happy family.",
  "The love of a family is a constant source of strength.",
  "Family is a safe haven in an unpredictable world.",
  "A close family is a treasure beyond measure.",
  "A supportive family is life’s greatest gift.",
  "A strong family is the best investment in life.",
  "True happiness starts with a loving family.",
  "The love of a family is the greatest kind of wealth.",
  "Family love is a language everyone understands.",
  "Cherish your family, for they are life’s greatest gift.",
  "A family’s embrace is the safest place on earth.",
  "In the end, family is all that truly matters.",
  "A loving home is built with laughter and care.",
  "Family teaches us the power of unconditional love.",
  "A family’s love is the secret ingredient to happiness.",
  "Home is where your family’s love is felt most deeply.",
  "No family is perfect, but love makes it whole.",
  "Family provides the roots that help us grow strong.",
  "The best memories are made with family by your side.",
  "A family’s love endures all seasons of life.",
  "Family is the anchor that keeps us grounded.",
  "True strength comes from the love of a family.",
  "The foundation of a great life is built on family love.",
  "No matter where life takes you, family remains in your heart.",
  "A family that supports each other is unstoppable.",
  "The most beautiful thing in life is a happy family.",
  "Family is a gift that lasts a lifetime.",
  "Loving families create a better world.",
  "Family gives us a place to belong and be ourselves.",
  "Nothing brings more joy than a family’s love.",
  "The best place in the world is in the arms of family.",
  "A family’s love is the glue that holds everything together.",
  "Family makes the journey of life more meaningful.",
  "A strong family is life’s greatest treasure.",
  "Love and laughter are the heart of every family.",
  "Family is where love grows and hearts are nurtured.",
  "A close family is a source of endless strength.",
  "The love of a family creates the best memories.",
  "A warm family is a life’s biggest blessing.",
  "Family is not about perfection; it’s about love.",
  "Family is the heartbeat of every home.",
  "A strong family foundation leads to a strong future."
      "Family is the heartbeat of our existence.",
  "A loving family is life’s most precious gift.",
  "No matter where you go, family is always home.",
  "The love of family is the foundation of happiness.",
  "Family is a garden where love blooms endlessly.",
  "Family is not just about blood, but about love and support.",
  "True family stands by you, even in the darkest times.",
  "Family is like music, some notes are high, some are low, but it’s always a beautiful song.",
  "A strong family creates a strong future.",
  "The joy of family is the light that never fades.",
  "In a world of change, family remains our constant.",
  "A close-knit family is a source of endless strength.",
  "Love is the glue that holds a family together.",
  "A family’s love is the bridge over troubled waters.",
  "A home filled with love is a home filled with joy.",
  "A happy family is a reflection of heaven on earth.",
  "A family is a safe harbor in the storms of life.",
  "Family gives us the courage to chase our dreams.",
  "Every family has a unique story, but love is always the common thread.",
  "The warmth of a family’s love is the best comfort.",
  "A home isn’t a place; it’s the people in it.",
  "The love of a family is like an unbreakable thread.",
  "A supportive family is life’s greatest security blanket.",
  "Time spent with family is time well spent.",
  "The foundation of a happy life is built on family love.",
  "Family members may argue, but love always wins in the end.",
  "Nothing compares to the love of a close family.",
  "A family’s laughter is the soundtrack of happiness.",
  "Family is the compass that keeps us on the right path.",
  "Every family has ups and downs, but love remains the anchor.",
  "A strong family bond is an unshakable force.",
  "Happiness is being surrounded by people who truly care.",
  "Family is where we learn the meaning of love and respect.",
  "The love of a family is the secret ingredient to a joyful life.",
  "A united family can overcome any challenge.",
  "No treasure is greater than a family’s love.",
  "A family’s love makes every burden lighter.",
  "Home is not about walls, but about hearts full of love.",
  "A family’s support is the wind beneath your wings.",
  "In the end, love is what makes a family strong.",
  "No matter how far you roam, family always welcomes you home.",
  "Family is the one thing that makes the world feel right.",
  "Cherish your family, for they are your true wealth.",
  "Family is the heart of every home.",
  "The beauty of life lies in the love of family.",
  "A home filled with laughter is a home filled with love.",
  "Family is like a quilt, stitched with love and memories.",
  "Where there is family, there is warmth and belonging.",
  "The love of a family is the greatest source of happiness.",
  "Family is a precious gift, cherish it always.",
  "The strength of a family lies in its unity and love.",
  "Family gives us the courage to face the world.",
  "A true family stands by you in every storm.",
  "The roots of a strong family grow deep in love.",
  "A loving family is life’s greatest blessing.",
  "A family’s love is the light that guides us home.",
  "The memories we make with family last a lifetime.",
  "Through thick and thin, family is always there.",
  "No matter what happens, family remains our foundation.",
  "The love within a family is the key to happiness.",
  "A close family is a gift that keeps on giving.",
  "Family love is the foundation of a fulfilling life.",
  "The best things in life aren’t things, they’re family moments.",
  "Nothing is stronger than the bond of a loving family.",
  "A loving home is built with patience, kindness, and understanding.",
  "Family means having someone to lean on, no matter what.",
  "A happy home is made with love, not bricks.",
  "A family’s love is the compass that guides us through life.",
  "Love within a family is what makes life beautiful.",
  "The greatest support system is a family that truly cares.",
  "Family is where life begins and love never ends.",
  "The best foundation for a strong future is a supportive family.",
  "Family is the safe place where we can be our true selves.",
  "A home filled with love is a home filled with peace.",
  "No wealth is greater than the love of family.",
  "A close family can turn any house into a home.",
  "Family is the light in the darkest times.",
  "A family’s love is the secret to lifelong happiness.",
  "Family is the mirror that reflects who we truly are.",
  "Strong families create strong individuals.",
  "A family’s love is the only wealth that truly matters.",
  "Family is the one thing you can always count on.",
  "A family’s love is like an eternal flame, burning bright through all seasons.",
  "Family is a sanctuary where love and trust grow.",
  "Home is where you are loved, no matter what.",
  "The love of a family is the greatest legacy.",
  "A family’s love stands the test of time.",
  "Through every chapter of life, family remains the constant.",
  "Family means celebrating joys and overcoming struggles together.",
  "No bond is stronger than that of a loving family.",
  "Family is the only thing that truly lasts forever.",
  "A family’s love is the best medicine for any heartache.",
  "Family gives us wings to fly and roots to come back.",
  "A house may be built with bricks, but a family is built with love.",
  "No matter how big or small, a family’s love makes all the difference.",
  "The love of a family is the light that never dims.",
  "Home is where love and family meet.",
  "Family means lifting each other up in times of need.",
  "The joy of a loving family is the essence of life.",
];

final List<String> familyImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled family quotes with random images.
final List<QuoteItem> familyQuotes = getShuffledQuotes(
  familyQuotesRaw,
  familyImages,
);
