import '../quotes_randomizer.dart';

/// **Forgiveness and Understanding Quotes & Images**
final List<String> forgivenessQuotesRaw = [
  "Forgiveness is the key that unlocks the door to peace.",
  "Understanding begins where judgment ends.",
  "The weak can never forgive. Forgiveness is the attribute of the strong. – Mahatma Gandhi",
  "Holding onto anger is like drinking poison and expecting the other person to die. – Buddha",
  "Forgiveness does not change the past, but it does enlarge the future. – Paul Boese",
  "To err is human, to forgive, divine. – Alexander Pope",
  "Forgiveness is giving up the hope that the past could have been any different. – Oprah Winfrey",
  "True forgiveness is when you can say, 'Thank you for that experience.' – Oprah Winfrey",
  "The practice of forgiveness is our most important contribution to the healing of the world. – Marianne Williamson",
  "Understanding is deeper than knowledge. Many people know you, but very few understand you.",
  "Forgive others, not because they deserve forgiveness, but because you deserve peace.",
  "When you forgive, you set a prisoner free. That prisoner is you. – Lewis B. Smedes",
  "Forgiveness does not excuse their behavior. Forgiveness prevents their behavior from destroying your heart.",
  "An eye for an eye makes the whole world blind. – Mahatma Gandhi",
  "Hate cannot drive out hate; only love can do that. – Martin Luther King Jr.",
  "Forgiveness is a gift you give yourself. – Suzanne Somers",
  "The first to apologize is the bravest. The first to forgive is the strongest. The first to forget is the happiest.",
  "You don't need to understand everything to have compassion and forgiveness.",
  "Understanding someone’s struggles leads to a heart filled with forgiveness.",
  "The beauty of life is found in understanding and forgiving each other.",
  "A mistake repeated is a choice, but understanding can help break the cycle.",
  "Forgiveness is the fragrance the violet sheds on the heel that has crushed it. – Mark Twain",
  "It takes a strong person to say sorry, and an even stronger person to forgive.",
  "Forgiving someone doesn’t mean forgetting. It means choosing peace over pain.",
  "We all make mistakes. Kindness and understanding turn them into lessons, not regrets.",
  "Forgiveness means letting go of the hope for a better past.",
  "Without forgiveness, life is governed by an endless cycle of resentment and retaliation. – Roberto Assagioli",
  "Understanding brings clarity, and clarity brings peace.",
  "Forgiveness liberates the soul. It removes fear. That is why it is such a powerful weapon. – Nelson Mandela",
  "Forgiveness is not about forgetting. It is about letting go of another person’s throat. – William Paul Young",
  "Understanding leads to compassion, and compassion leads to healing.",
  "Forgive others as quickly as you expect God to forgive you.",
  "Love and understanding are the true pillars of lasting peace.",
  "He who cannot forgive others breaks the bridge over which he himself must pass. – George Herbert",
  "Forgiveness is choosing to love. It is the first skill of self-giving love. – Mahatma Gandhi",
  "Mistakes are meant for learning, not for holding grudges.",
  "Peace is found when we choose understanding over judgment.",
  "Be kind, for everyone you meet is fighting a battle you know nothing about.",
  "A lack of understanding creates distance; forgiveness brings hearts closer.",
  "Forgiveness is a reflection of loving yourself enough to move on.",
  "Understanding is seeing with the heart, not just the eyes.",
  "Holding onto anger only burns the hand that refuses to let go.",
  "A heart filled with understanding has no room for hatred.",
  "Forgiveness is like a muscle—the more you use it, the stronger it gets.",
  "Letting go of resentment is like removing a weight from your soul.",
  "Compassion grows in the garden of forgiveness.",
  "Forgiveness is the final form of love. – Reinhold Niebuhr",
  "Understanding someone's past helps you forgive their present actions.",
  "Patience and understanding pave the way to forgiveness.",
  "Forgiveness isn't approval; it's freedom.",
  "Forgiveness turns wounds into wisdom.",
  "The greatest gift you can give yourself is forgiveness.",
  "We forgive not because they deserve it, but because we do.",
  "Forgiveness cleanses the heart of pain.",
  "Understanding someone's pain can turn anger into compassion.",
  "Forgiveness heals you more than the one you forgive.",
  "Grudges are heavy. Forgiveness makes the soul lighter.",
  "Forgiveness is not about them; it's about your peace.",
  "Understanding people’s intentions leads to a forgiving heart.",
  "Forgiving yourself is just as important as forgiving others.",
  "Not everyone will understand you, and that’s okay.",
  "Kindness and understanding are never wasted.",
  "The more we understand, the less we judge.",
  "Forgiveness isn't weakness—it's the strength to move forward.",
  "Forgiveness is the bridge to a peaceful heart.",
  "Don't let anger block the road to understanding.",
  "Choosing forgiveness over revenge is choosing happiness over pain.",
  "Forgiveness is a journey, not a destination.",
  "People grow when they feel understood, not judged.",
  "Understanding takes effort; forgiveness takes heart.",
  "When we understand each other, peace follows.",
  "No one is perfect; understanding that helps us forgive.",
  "Forgiveness is giving yourself permission to move forward.",
  "We all need a second chance, sometimes even a third or fourth.",
  "Understanding is the first step to true forgiveness.",
  "Forgiving doesn't change the past, but it changes the future.",
  "People may not remember what you said, but they'll remember how you made them feel.",
  "Judging a person does not define who they are, it defines who you are.",
  "Let go of bitterness; hold onto love.",
  "Understanding builds bridges where there were once walls.",
  "Forgiveness is the highest form of strength.",
  "No matter how deep the wound, forgiveness can heal it.",
  "Forgiveness is a promise to yourself to stop reliving the pain.",
  "Choose understanding over assumptions.",
  "The heart that understands is the heart that forgives.",
  "Resentment is like a poison you drink hoping someone else will suffer.",
  "Understanding someone's pain makes forgiveness easier.",
  "Let your heart be big enough to forgive even when it's hard.",
  "Forgiveness is a silent prayer for peace.",
  "What we see in others is often a reflection of what we hold inside.",
  "The most important forgiveness is the one you give yourself.",
  "Love, understanding, and forgiveness are the true pillars of happiness.",
  "Forgiveness softens even the hardest heart.",
  "Being wronged doesn’t mean we must carry the burden forever.",
  "Understanding others begins with understanding ourselves.",
  "Let your kindness be greater than your hurt.",
  "Forgiveness is letting go of the hope that the past can be different.",
  "A heart at peace is a heart that has learned to forgive.",
  "When you release resentment, you make room for joy.",
  "We all need forgiveness more than we realize.",
  "True strength lies in choosing understanding over anger.",
  "Compassion is the language of forgiveness.",
  "Choose peace. Choose love. Choose forgiveness.",
  "Forgiveness is not something we do for others. We do it for ourselves to get well and move on.",
  "Understanding means seeing with an open heart, not just open eyes.",
  "Forgive yourself for not knowing what you didn’t know before you learned it.",
  "Forgiveness is not a sign of weakness but a mark of immense strength.",
  "When you choose to forgive, you break the chains of bitterness holding you back.",
  "A heart full of understanding has no space for resentment.",
  "We all have chapters we’d rather not read out loud. Forgive and move forward.",
  "Sometimes, the hardest person to forgive is yourself.",
  "Forgiveness is the act of setting a prisoner free, only to realize that prisoner was you.",
  "When we let go of grudges, we create space for love and peace.",
  "Understanding comes from listening, not reacting.",
  "The past is a place of reference, not residence. Forgive and grow.",
  "Mistakes are proof that we are trying; understanding helps us learn from them.",
  "The best way to heal is to forgive.",
  "A moment of anger can ruin years of understanding.",
  "Forgiveness does not erase the past but gives you a brighter future.",
  "Happiness blooms where grudges cannot grow.",
  "The first step toward forgiveness is the decision to let go.",
  "Compassion makes forgiveness easier.",
  "Sometimes, the apology you never received is the one you need to give yourself.",
  "No one has ever regretted choosing forgiveness over resentment.",
  "Forgiving doesn't mean forgetting; it means choosing peace over pain.",
  "Your soul shines brighter when you remove the weight of hatred.",
  "To truly understand someone is the beginning of forgiveness.",
  "When you seek to understand, you open the door to true connection.",
  "Anger makes you small; forgiveness forces you to grow.",
  "We are all imperfect humans trying to find our way—understanding makes the journey easier.",
  "There is power in understanding and peace in forgiveness.",
  "Forgiveness is not for them, it is for you.",
  "The greatest test of love is forgiveness.",
  "To forgive is to free yourself from the past.",
  "Understanding is the foundation of true forgiveness.",
  "Grudges weigh you down; let them go and feel the freedom.",
  "Forgive, because life is too short for regrets.",
  "Kindness and understanding can heal even the deepest wounds.",
  "Forgiveness does not mean condoning wrongdoings; it means choosing yourself over resentment.",
  "A heart that understands is a heart that forgives.",
  "Forgiveness is an inner peace we grant ourselves.",
  "No matter how much it hurts, forgiveness is always worth it.",
  "Forgiveness is a process, not an event.",
  "Forgiving does not make you weak; it makes you free.",
  "If you want peace, understand. If you want happiness, forgive.",
  "True wisdom is knowing when to let go and move on.",
  "Holding onto anger is like carrying a heavy stone—you get tired first.",
  "Healing begins when we stop blaming and start understanding.",
  "Compassion turns anger into love and resentment into understanding.",
  "We all need forgiveness, just as we all need love.",
  "You don’t need closure to find peace; sometimes, forgiveness is enough.",
  "Time may not heal all wounds, but forgiveness does.",
  "A forgiving heart is a heart that truly lives.",
  "Forgiveness is the first step toward healing.",
  "There is strength in understanding and peace in letting go.",
  "Even if you never hear 'I'm sorry,' forgive anyway.",
  "Understanding creates bridges where walls once stood.",
  "Forgiveness is not earned; it is given freely.",
  "Your heart deserves peace—choose forgiveness.",
  "What you hold onto holds onto you; let go of resentment.",
  "The heart that forgives is the heart that understands.",
  "A wise soul chooses understanding over anger.",
  "Forgive as freely as you breathe.",
  "We all make mistakes—understanding brings us closer, not apart.",
  "Anger is heavy; forgiveness is light.",
  "Understanding means seeing past someone's flaws to their humanity.",
  "You don't need to fix everything to forgive. Sometimes, letting go is enough.",
  "Judgment creates division; understanding builds unity.",
  "To be understood is a gift; to be forgiven is a blessing.",
  "Resentment chains you to the past; forgiveness sets you free.",
  "Choosing to forgive is choosing happiness over pain.",
  "Compassion opens the door to understanding.",
  "Forgiveness is not about them; it’s about your peace of mind.",
  "There is no love without understanding, and no peace without forgiveness.",
  "Understanding is the art of listening with the heart.",
  "Forgiveness is a conscious choice, not an emotional reaction.",
  "To understand is to love in its purest form.",
  "A forgiving heart sees the best in people.",
  "Understanding starts when we replace judgment with curiosity.",
  "No one is perfect—grace is what holds us together.",
  "Forgiveness is not a weakness; it’s the ultimate strength.",
  "We cannot grow when we are chained to the past—let go and rise.",
  "Love flourishes where forgiveness lives.",
  "Anger destroys, but understanding rebuilds.",
  "Forgiveness is not a one-time act but a daily practice.",
  "Holding a grudge is like holding your breath—you only hurt yourself.",
  "Forgive others the way you wish to be forgiven.",
  "A single act of understanding can mend years of pain.",
  "Forgiveness does not make you forget; it helps you move forward.",
  "No peace exists where resentment lives.",
  "Understanding someone's pain does not justify their actions, but it explains them.",
  "Forgiveness means trading pain for freedom.",
  "Letting go of resentment allows love to enter.",
  "Even the deepest wounds can be healed with time and forgiveness.",
  "Empathy and understanding are the keys to healing.",
  "The burden of anger is heavier than the relief of forgiveness.",
  "Forgiveness is an act of self-care.",
  "Be kind, for we all have struggles unseen.",
  "Understanding removes the barriers that separate us.",
  "Forgive because your soul deserves rest.",
  "The world needs more love, understanding, and forgiveness.",
  "When you forgive, you don’t change the past—you change the future.",
  "Let love be greater than your pain.",
  "You don’t have to forget, but you do have to forgive to move on.",
  "Forgiveness is the foundation of true peace.",
  "Understand before you judge, forgive before you hold a grudge.",
  "Forgiveness opens the heart to love again.",
  "A peaceful heart is one that chooses to understand, forgive, and love.",
];

final List<String> forgivenessImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled forgiveness quotes with random images.
final List<QuoteItem> forgivenessQuotes = getShuffledQuotes(
  forgivenessQuotesRaw,
  forgivenessImages,
);
