import '../quotes_randomizer.dart';

/// **Friendship and Trust Quotes & Images**
final List<String> friendshipQuotesRaw = [
  "True friendship is built on trust, not just shared memories.",
  "A friend is someone who knows all about you and still loves you.",
  "Trust is the foundation of every strong friendship.",
  "Good friends are like stars; you don’t always see them, but you know they are there.",
  "Friendship is not about who you have known the longest, but who walked in and never left your side.",
  "A real friend is one who walks in when the rest of the world walks out.",
  "Trust takes years to build, seconds to break, and forever to repair.",
  "The best way to keep a friend is to be one.",
  "Friendship is not about being inseparable but about being separated and nothing changes.",
  "True friends are never apart, maybe in distance but never in heart.",
  "Loyal friends are worth more than gold.",
  "A good friend is like a four-leaf clover; hard to find and lucky to have.",
  "Honesty is the key ingredient in every strong friendship.",
  "Trust is like glass, once broken, it can never be the same again.",
  "A true friend accepts you for who you are but also helps you become who you should be.",
  "Genuine friendship is a sheltering tree.",
  "Friendship without trust is like a phone without a signal—useless.",
  "Good friends bring out the best in you.",
  "To be trusted is a greater compliment than to be loved.",
  "Friendship is the golden thread that ties the heart of all the world.",
  "The best mirror is an old friend.",
  "A single loyal friend is worth a thousand relatives.",
  "Friends don’t let friends face hardships alone.",
  "Trust and friendship go hand in hand; you can’t have one without the other.",
  "A friend’s trust is more valuable than gold.",
  "A friend is one of the nicest things you can have and one of the best things you can be.",
  "No distance can break the bond of true friendship.",
  "A faithful friend is a sturdy shelter; whoever finds one has found a treasure.",
  "Friendship means understanding, not agreement.",
  "Friends are the family we choose for ourselves.",
  "Trust is built with consistency.",
  "True friendship is when you walk in opposite directions, yet remain side by side.",
  "A friend’s loyalty is measured in moments of hardship, not in moments of joy.",
  "Good friends listen, great friends understand.",
  "Friendship is a two-way street built on trust and respect.",
  "Trust is not given; it is earned through actions.",
  "A friend is someone who gives you total freedom to be yourself.",
  "A true friend never gets in your way unless you happen to be going down.",
  "The only way to have a friend is to be one.",
  "Honest conversations strengthen friendships.",
  "A trusted friend is a gift from the universe.",
  "A best friend understands you even when you don’t say a word.",
  "A strong friendship doesn’t need daily conversation, as long as trust exists.",
  "True friends speak the truth, even when it hurts.",
  "A good friendship is like a beautiful song—lasting and unforgettable.",
  "Trust and honesty are the bricks that build the house of friendship.",
  "Great friendships withstand the test of time and distance.",
  "The best friendships are built on a solid foundation of trust and love.",
  "Without trust, a friendship is like a plant without water—it withers away.",
  "Friendship is the shadow of the evening, which increases with the setting sun of life.",
  "A true friend multiplies your joys and divides your sorrows.",
  "Friends are those rare people who ask how we are and then wait to hear the answer.",
  "Loyalty is what makes friendship stronger.",
  "Trust is earned, respect is given, and loyalty is demonstrated.",
  "Friendship is born when one person says to another, ‘What! You too? I thought I was the only one.’",
  "A friend is someone who can see the truth and pain in you, even when you’re fooling everyone else.",
  "Friendship is not about who is real to your face but who stays real behind your back.",
  "A friend knows the song in your heart and can sing it back to you when you forget the words.",
  "Trust in a friendship is like a bank account—every act of honesty makes a deposit, while lies make withdrawals.",
  "A friend is someone who makes it easy to believe in yourself.",
  "Friendship is like a tree; it takes years to grow but can be cut down in a moment.",
  "A strong friendship doesn’t need daily talks; it thrives on trust and understanding.",
  "If you have one loyal friend, you are richer than most.",
  "True friendship is a journey without an end.",
  "A good friend is one who helps you up when you fall and won’t let you fall again.",
  "Trust is knowing that your friend won’t betray you, even when given the chance.",
  "A friendship with trust is a friendship that lasts a lifetime.",
  "Real friendship is a promise kept forever.",
  "A true friend is the greatest of all blessings.",
  "A friendship built on honesty and trust can withstand anything.",
  "Friendship is like a candle—it burns bright when fueled by trust.",
  "No matter how dark it gets, a true friend will always shine a light for you.",
  "Friendship isn’t about who you’ve known the longest; it’s about who walked into your life and never left.",
  "Trust and loyalty form the foundation of every lasting friendship.",
  "The best friendships are the ones where you can be your true self.",
  "A real friend is one who sticks by you when the whole world walks away.",
  "Honesty and loyalty are the currency of true friendship.",
  "Friendship is like a beautiful garden; it needs trust and love to bloom.",
  "The secret to lifelong friendship is trust and kindness.",
  "The best friendships grow stronger with time and understanding.",
  "Friendship is about trusting each other, even when apart.",
  "Good friends bring sunshine into your darkest days.",
  "Trust and honesty form the glue that holds friendships together.",
  "A true friend is someone who sees the pain in your eyes when others only see your smile.",
  "Real friendship is rare but priceless.",
  "A strong friendship can survive any storm if built on trust.",
  "Friendship is an unspoken promise of loyalty and love.",
  "Trust is not just spoken in words; it’s shown in actions.",
  "A true friend will never betray your trust.",
  "Honest friendships outlast time, distance, and hardships.",
  "Friendship without trust is like a house built on sand.",
  "A friend who understands your silence is worth more than a thousand who only hear your words.",
  "The strongest friendships are forged in the fire of trust.",
  "Friendship grows stronger when nourished with trust and love.",
  "Friendship is life’s way of giving you family without blood ties.",
  "A trusted friend is a rare jewel.",
  "True friends inspire you to be your best self.",
  "Real friends are those who stand by your side when everyone else walks away.",
  "The best friendships are effortless because they are built on trust.",
  "A good friend will always find a way to support you.",
  "Loyalty is the foundation of any strong friendship.",
  "Friendship is a journey best traveled with trust and understanding.",
  "True friendship isn’t about being there when it’s convenient, it’s about being there when it’s not.",
  "A real friend is someone who walks in when the rest of the world walks out.",
  "Trust is the highest form of human motivation.",
  "The best friendships are built on a solid foundation of trust and love.",
  "A true friend is someone who sees the pain behind your smile.",
  "Friends show their love in times of trouble, not in happiness.",
  "Trust is like a paper, once it’s crumpled, it can’t be perfect again.",
  "Good friends help you find important things when you have lost them—your smile, your hope, and your courage.",
  "A friend is someone who makes you laugh even when you think you’ll never smile again.",
  "A friendship built on trust is a bond that lasts forever.",
  "Real friends accept you as you are, but also inspire you to be better.",
  "A friend who understands your tears is much more valuable than a hundred friends who only know your smile.",
  "Loyalty and trust are the pillars of true friendship.",
  "Friends are those rare people who ask how we are and then actually wait to hear the answer.",
  "Friendship is the only cement that will ever hold the world together.",
  "One loyal friend is worth ten thousand relatives.",
  "A true friend never gets tired of listening to your nonsense.",
  "The best friendships develop when both people genuinely care for each other.",
  "True friends stay by your side no matter the distance or time apart.",
  "Trust takes years to build but only moments to break.",
  "A strong friendship doesn’t need daily conversation, as long as trust exists.",
  "Friends are the family we choose.",
  "Good friends are like quilts—they never lose their warmth.",
  "A friend is one who knows you and loves you just the same.",
  "A friend is someone who gives you total freedom to be yourself.",
  "When friendship is real, trust comes naturally.",
  "A friend will always encourage you, even when you doubt yourself.",
  "Friendship isn’t about whom you’ve known the longest, it’s about who came and never left your side.",
  "Honesty and loyalty are the glue of true friendship.",
  "The greatest gift of life is friendship, and I have received it.",
  "Friendship means trusting someone with your deepest fears and highest dreams.",
  "A trusted friend is worth more than gold.",
  "Friendship is when people know all about you but like you anyway.",
  "A true friend is someone who is always there for you when they’d rather be anywhere else.",
  "The most valuable gift you can receive is an honest friend.",
  "Trust is the fruit of a relationship in which you know you are loved.",
  "Friendship is like a bank account—you cannot continue to draw on it without making deposits.",
  "The best friendships start with trust and honesty.",
  "A true friend is someone who sees your potential when you can’t see it yourself.",
  "Friendship isn’t a big thing—it’s a million little things.",
  "A single loyal friend is worth more than a thousand acquaintances.",
  "Friendship is a two-way street built on trust, love, and kindness.",
  "No friendship is an accident; it is built with love and trust.",
  "A true friend is someone who stays when the whole world walks away.",
  "Trustworthy friends are the best kind of wealth.",
  "The best thing about true friendship is that it is unconditional.",
  "A true friend is one who thinks you are a good egg even when they know you’re slightly cracked.",
  "The best friendships are the ones where you can be your true self.",
  "Friendship is a slow ripening fruit that requires trust to flourish.",
  "A real friend is one who walks in when the rest of the world walks out.",
  "Without trust, there can be no real friendship.",
  "A true friend is a safe place where you can be yourself without fear.",
  "Friendship is not about who is real to your face, but who stays real behind your back.",
  "Trusting someone with your heart is the greatest act of friendship.",
  "A best friend is someone who brings out the best in you.",
  "A friend is someone who makes you feel totally accepted.",
  "Friendship is built on a solid foundation of trust and loyalty.",
  "Trust in friendship means knowing that your secrets are safe.",
  "A true friend is one who overlooks your failures and celebrates your successes.",
  "Friends make the bad times good and the good times unforgettable.",
  "True friendship stands the test of time and distance.",
  "The strongest friendships are those built on trust and understanding.",
  "Trust is the currency of any meaningful friendship.",
  "A friend is someone who sees the best in you even when you see the worst in yourself.",
  "Real friends inspire each other to become better versions of themselves.",
  "The best friendships grow stronger over time, just like fine wine.",
  "A good friend knows all your stories; a best friend helped you write them.",
  "A trusted friend is one of life’s greatest treasures.",
  "A strong friendship is one that can withstand misunderstandings and still grow.",
  "The most powerful ingredient in any friendship is trust.",
  "Friends are the people who make your problems their problems, just so you don’t have to face them alone.",
  "A true friend believes in you even when you’ve stopped believing in yourself.",
  "Friendship is about being there, not just saying you will be.",
  "True friendship is like sound health; the value of it is seldom known until it is lost.",
  "Friendship flourishes at the fountain of trust.",
  "The best friendships are those where trust is never in question.",
  "Friendship is the purest form of trust between two souls.",
  "A friend who understands your past will help you build your future.",
  "A real friend is someone who challenges you to be better while accepting you as you are.",
  "Friendship without trust is like a phone without a signal—useless.",
  "True friends are those who lift you up when others bring you down.",
  "Friendship is not about perfection; it’s about trust and respect.",
  "Good friends are hard to find, harder to leave, and impossible to forget.",
  "A friend is one of the nicest things you can have, and one of the best things you can be.",
  "A friend’s trust is the most valuable thing they can offer.",
  "Friendship is not about having a perfect bond but about trusting each other through imperfections.",
  "True friends stick together through thick and thin.",
  "Real friends don’t count favors; they simply give with love and trust.",
  "Trust is the anchor that holds a true friendship in place.",
  "A true friend listens to what you don’t say.",
  "No matter how much time passes, true friends always pick up where they left off.",
  "Friendship is built in the moments of trust, understanding, and laughter.",
  "Friendship is not about convenience; it’s about commitment.",
  "The best friendships are forged in moments of trust and mutual respect.",
  "True friends don’t judge; they understand and support.",
  "A real friend walks with you, even when the road gets rough.",
  "The greatest friendships grow where trust is planted.",
  "A friend’s loyalty is measured in moments of hardship, not just moments of joy.",
  "Friendship is the art of never letting distance or time break the bond of trust.",
];

final List<String> friendshipImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled friendship quotes with random images.
final List<QuoteItem> friendshipQuotes = getShuffledQuotes(
  friendshipQuotesRaw,
  friendshipImages,
);
