import '../quotes_randomizer.dart';

/// **Kindness and Compassion Quotes & Images**
final List<String> kindnessQuotesRaw = [
  "No act of kindness, no matter how small, is ever wasted.",
  "Kindness is a language which the deaf can hear and the blind can see.",
  "A warm smile is the universal language of kindness.",
  "Compassion is the basis of morality.",
  "Be kind whenever possible. It is always possible.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "Kindness begins with the understanding that we all struggle.",
  "A single act of kindness throws out roots in all directions.",
  "You cannot do a kindness too soon, for you never know how soon it will be too late.",
  "Compassion is not a relationship between the healer and the wounded. It’s a relationship between equals.",
  "Wherever there is a human being, there is an opportunity for kindness.",
  "The world is full of kind people. If you can’t find one, be one.",
  "To err on the side of kindness is seldom an error.",
  "When words are both true and kind, they can change the world.",
  "A kind gesture can reach a wound that only compassion can heal.",
  "Kindness is seeing the best in others when they cannot see it in themselves.",
  "We rise by lifting others.",
  "Being kind is more important than being right.",
  "Kindness costs nothing but means everything.",
  "The greatest gift you can give someone is your kindness.",
  "Kind words can be short and easy to speak, but their echoes are truly endless.",
  "A little spark of kindness can put a colossal burst of sunshine into someone’s day.",
  "If you have the power to make someone happy, do it.",
  "Kindness is the golden chain by which society is bound together.",
  "Do things for people not because of who they are, but because of who you are.",
  "How beautiful a day can be when kindness touches it!",
  "What wisdom can you find that is greater than kindness?",
  "A good heart is the sun and the moon; or rather, the sun and not the moon, for it shines bright and never changes.",
  "Kindness is spreading sunshine into other people's lives regardless of the weather.",
  "When we give cheerfully and accept gratefully, everyone is blessed.",
  "A little kindness goes a long way.",
  "Kindness is like snow—it beautifies everything it covers.",
  "Unexpected kindness is the most powerful, least costly, and most underrated agent of human change.",
  "If we all do one random act of kindness daily, we just might set the world in the right direction.",
  "The simplest acts of kindness are by far more powerful than a thousand heads bowing in prayer.",
  "A life lived for others is a life worthwhile.",
  "Be the reason someone smiles today.",
  "The smallest act of kindness is worth more than the grandest intention.",
  "The purpose of human life is to serve, and to show compassion and the will to help others.",
  "One kind word can warm three winter months.",
  "There is no exercise better for the heart than reaching down and lifting people up.",
  "Where kindness is sown, love grows.",
  "Compassion is the keen awareness of the interdependence of all things.",
  "Love and kindness are never wasted.",
  "Sometimes it takes only one act of kindness and caring to change a person’s life.",
  "Be kind to unkind people—they need it the most.",
  "Being kind to yourself is just as important as being kind to others.",
  "A single act of kindness can make a ripple effect across the whole world.",
  "The fragrance always stays in the hand that gives the rose.",
  "A part of kindness consists in loving people more than they deserve.",
  "If we could read the secret history of our enemies, we should find in each man’s life sorrow and suffering enough to disarm all hostility.",
  "True kindness is not just about being nice, but about making a real difference in someone’s life.",
  "A kind word never broke anyone’s mouth.",
  "Every act of kindness is a piece of love we leave behind.",
  "If you want to lift yourself up, lift up someone else.",
  "Kindness and compassion are the keys to a meaningful life.",
  "People will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "Kindness is the best form of humanity.",
  "Every day may not be good, but there is something good in every day.",
  "You will never regret being kind.",
  "The greatest act of courage is kindness.",
  "Kind hearts are the gardens, kind thoughts are the roots, kind words are the flowers, kind deeds are the fruits.",
  "The more you extend kindness to yourself, the more it will become your automatic response to others.",
  "Kindness is a powerful tool that costs nothing but has infinite value.",
  "Compassion is the highest form of intelligence.",
  "We can’t help everyone, but everyone can help someone.",
  "Generosity isn’t an act, it’s a way of life.",
  "No one has ever become poor by giving.",
  "Helping one person might not change the world, but it could change the world for that one person.",
  "Always be kinder than necessary.",
  "If kindness was currency, the world would be a richer place.",
  "An open heart is an open mind.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "A little consideration, a little thought for others, makes all the difference.",
  "It is not the magnitude of our actions but the amount of love that is put into them that matters.",
  "Compassion and kindness are never wasted. They always make a difference.",
  "One person can make a difference, and everyone should try.",
  "A great nation is judged by how it treats its weakest members.",
  "Goodness is about character—integrity, honesty, kindness, generosity, moral courage.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "Do your little bit of good where you are; it’s those little bits of good put together that overwhelm the world.",
  "Treat everyone with kindness, even those who are rude to you—not because they are nice, but because you are.",
  "Kindness is the sunshine in which virtue grows.",
  "Compassion will cure more sins than condemnation.",
  "Forgiveness and compassion are forms of strength, not weakness.",
  "The only way to deal with pain is through compassion and understanding.",
  "There is no greater power than kindness.",
  "When you carry kindness in your heart, you bring light wherever you go.",
  "Kindness doesn’t have to be grand; even the smallest actions can make a huge impact.",
  "The way we treat people is a reflection of who we are.",
  "Compassion will make you stronger, not weaker.",
  "To be kind is to be truly human.",
  "Kindness is the most powerful, least costly, and most underrated agent of human change.",
  "Compassion is the greatest form of wisdom.",
  "If the world had more kindness, it would have fewer problems.",
  "One small act of kindness can change someone’s entire day.",
  "Kindness is an inner light that radiates outward.",
  "A true act of kindness expects nothing in return.",
  "Your kind words can change someone’s perspective on life.",
  "In a world where you can be anything, be kind.",
  "Kindness is like a seed; when you plant it, it grows.",
  "The smallest act of kindness is worth more than the grandest intention.",
  "Kindness is the language of the soul.",
  "A kind heart is a fountain of gladness, making everything in its vicinity freshen into smiles.",
  "Compassion is an action word with no boundaries.",
  "Sometimes it takes only one act of kindness to change a person’s life.",
  "Helping one person may not change the whole world, but it could change the world for that one person.",
  "Be a rainbow in someone else’s cloud.",
  "Do good, and good will come to you.",
  "A kind word is like a spring day.",
  "Kindness is free; sprinkle it everywhere.",
  "Compassion will cure more sins than condemnation.",
  "Kindness is an investment that never fails.",
  "The most beautiful thing in the world is a heart that loves and cares.",
  "One kind gesture can create a ripple of endless love.",
  "Kindness is the golden key that unlocks hearts.",
  "The more you give, the more you receive.",
  "Kindness is a gift everyone can afford to give.",
  "Kindness doesn’t need recognition; it shines by itself.",
  "Caring for others is an expression of self-love.",
  "Love and kindness go hand in hand.",
  "True kindness expects nothing in return.",
  "Kindness is the ultimate sign of strength.",
  "No beauty shines brighter than that of a good heart.",
  "Be kind, for everyone you meet is fighting a hard battle.",
  "If you can be anything in this world, be kind.",
  "Sometimes, a simple smile is the best way to show kindness.",
  "Kindness is a boomerang—it always comes back.",
  "Compassion is the essence of humanity.",
  "A little kindness can change a life forever.",
  "Your act of kindness may be the only light in someone’s darkness.",
  "There’s nothing stronger than gentleness.",
  "Kindness is the key to a happy heart.",
  "Even the smallest act of kindness can make a big difference.",
  "A candle loses nothing by lighting another candle.",
  "The best way to heal is through kindness and compassion.",
  "Always leave people better than you found them.",
  "Kindness is the language that the heart understands.",
  "It’s cool to be kind.",
  "Empathy is seeing with the eyes of another, listening with the ears of another, and feeling with the heart of another.",
  "The simplest way to show love is through kindness.",
  "Give without remembering, and receive without forgetting.",
  "Being kind to others is like giving yourself a gift.",
  "If you want kindness, be kind.",
  "Kindness is the highest form of intelligence.",
  "You never know what someone is going through; be kind always.",
  "Kindness doesn’t need a reason.",
  "A little kindness in words creates confidence, a little kindness in thinking creates profoundness, and a little kindness in giving creates love.",
  "Compassion makes the world a better place.",
  "Being kind is a choice. Choose wisely.",
  "A generous heart, a kind speech, and a life of service are the things that renew humanity.",
  "Acts of kindness make us feel more alive.",
  "Kindness bridges the gaps between people.",
  "The strongest people are those who uplift others.",
  "Kindness is the best form of humanity.",
  "Treat everyone with politeness, even those who are rude to you—not because they are nice, but because you are.",
  "Compassion is the heart’s whisper.",
  "Do small things with great love.",
  "A kind heart never goes out of style.",
  "Kindness multiplies when shared.",
  "Kindness is a daily practice, not just an occasional act.",
  "When you have the choice between being right and being kind, choose kindness.",
  "A heart filled with kindness is a heart full of love.",
  "Help the fallen rise, and one day, they will help you.",
  "Kindness and gratitude make life beautiful.",
  "The simplest things, like a kind word or a gentle touch, can mean the world to someone.",
  "You don’t need a reason to help others.",
  "Even in chaos, kindness is possible.",
  "Helping others is the best way to help yourself.",
  "Kindness is never wasted—it always leaves a mark.",
  "You can never be too kind.",
  "A loving and compassionate heart is the greatest wealth.",
  "There’s no such thing as too much kindness.",
  "In a world where you can be anything, be a light.",
  "Kindness is a powerful form of love.",
  "Gentle words can open even the hardest hearts.",
  "Be a blessing to someone every day.",
  "A simple act of kindness creates an endless ripple.",
  "Kindness is the magic that brings joy to life.",
  "Being nice costs nothing but means everything.",
  "Compassion is love in action.",
  "A heart filled with kindness is a heart that’s truly rich.",
  "If you can help, help. If you can’t, at least don’t hurt.",
  "Kindness is the light that dissolves all walls between souls.",
  "Every small act of kindness adds up to a big change.",
  "Where there is kindness, there is hope.",
  "A kind act is never wasted.",
  "There is no wrong time to be kind.",
  "The beauty of kindness is that it doesn’t require a reason.",
  "True kindness comes from an understanding heart.",
  "The best gifts in life are kindness, love, and time.",
  "Compassion is contagious—spread it.",
  "Kindness is the music of the soul.",
  "Acts of kindness make the world a softer place.",
  "Kindness is the heartbeat of humanity.",
  "Live with kindness, lead with compassion.",
  "Love and kindness are like boomerangs—they always come back.",
  "Every kind word and every kind act plants a seed of love.",
  "Give love, receive love, repeat.",
];

final List<String> kindnessImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled kindness and compassion quotes with random images.
final List<QuoteItem> kindnessQuotes = getShuffledQuotes(
  kindnessQuotesRaw,
  kindnessImages,
);
