import '../quotes_randomizer.dart';

/// **Self-Love and Confidence Quotes & Images**
final List<String> selfloveQuotesRaw = [
  "Love yourself first, and everything else falls into place.",
  "Confidence is not 'they will like me'; confidence is 'I’ll be fine if they don’t.'",
  "Your value doesn’t decrease based on someone’s inability to see your worth.",
  "Be yourself; everyone else is already taken.",
  "You are enough just as you are.",
  "Self-love is not selfish; you cannot truly love another until you know how to love yourself.",
  "The more you love yourself, the less nonsense you’ll tolerate.",
  "Confidence comes from embracing your uniqueness.",
  "Talk to yourself like someone you love.",
  "The moment you start acting like life is a blessing, it starts feeling like one.",
  "To love oneself is the beginning of a lifelong romance.",
  "Don’t wait for permission to be yourself.",
  "You are beautiful, powerful, and capable beyond measure.",
  "Your self-worth is determined by you. You don’t have to depend on someone telling you who you are.",
  "Be proud of who you are, and not ashamed of how someone else sees you.",
  "Self-confidence is the best outfit. Rock it and own it.",
  "You deserve your own love and affection as much as anyone else.",
  "Confidence is the key that unlocks every door.",
  "The only validation you need is your own.",
  "You are not a backup plan. You are the main event.",
  "Be your own kind of beautiful.",
  "Comparison is the thief of joy. Focus on your own journey.",
  "The more you believe in yourself, the more others will too.",
  "You are strong enough to face anything that comes your way.",
  "Your energy introduces you before you even speak.",
  "Be kind to yourself. You’re doing the best you can.",
  "No one is you, and that is your power.",
  "You have been criticizing yourself for years, and it hasn’t worked. Try approving of yourself and see what happens.",
  "If you want to be unstoppable, stop doubting yourself.",
  "Confidence doesn’t mean you never fail; it means you don’t let failure define you.",
  "You owe yourself the love you so freely give to others.",
  "Your self-respect must be stronger than your feelings.",
  "You are worthy of the life you dream of.",
  "Fall in love with taking care of yourself.",
  "Wear your confidence like a crown.",
  "You don’t need approval to be yourself.",
  "Stop shrinking to fit places you’ve outgrown.",
  "Doubt kills more dreams than failure ever will.",
  "Believe in yourself a little more every day.",
  "Nothing can dim the light that shines from within.",
  "Don’t let your mind bully your body.",
  "The way you speak to yourself matters.",
  "Your greatest responsibility is to love yourself and know you are enough.",
  "The world needs that special gift that only you have.",
  "Trust yourself. You know more than you think you do.",
  "Be your own biggest cheerleader.",
  "Your voice matters. Speak your truth with confidence.",
  "Learn to rest, not to quit.",
  "You deserve happiness just as much as anyone else.",
  "What makes you different is what makes you special.",
  "A flower does not think of competing with the flower next to it. It just blooms.",
  "You glow differently when you’re confident in who you are.",
  "Self-love is the foundation for everything beautiful in your life.",
  "The only limit is the one you set for yourself.",
  "You are stronger than you think.",
  "Confidence is not about being perfect; it’s about being real.",
  "Never dim your light to make others comfortable.",
  "You are allowed to take up space.",
  "The most powerful thing you can do is believe in yourself.",
  "Let go of the idea that you need to be perfect to be loved.",
  "No one can make you feel inferior without your consent.",
  "You are already worthy just by being you.",
  "The strongest relationship you will ever have is the one with yourself.",
  "You don’t find self-worth in others; you build it within yourself.",
  "Owning your story is the bravest thing you’ll ever do.",
  "Be the love you never received.",
  "Confidence looks good on you—wear it daily.",
  "Your dreams are valid because they are yours.",
  "You were born to be real, not perfect.",
  "Being yourself is your superpower.",
  "Love the person in the mirror, and they will love you back.",
  "You are not your mistakes; you are your growth.",
  "Celebrate yourself, even for small victories.",
  "Self-love isn’t about being narcissistic, it’s about embracing who you are.",
  "The opinion that matters most is your own.",
  "You are a masterpiece in progress.",
  "Don’t let negative self-talk steal your joy.",
  "Your confidence is contagious—spread it!",
  "You define your worth, not others.",
  "Be so completely yourself that others feel safe to be themselves too.",
  "Take a deep breath and remember who you are.",
  "Love yourself loudly, unapologetically, and completely.",
  "Confidence begins when you stop seeking validation.",
  "You are not behind; you are exactly where you need to be.",
  "The best investment you can make is in yourself.",
  "You are enough, exactly as you are.",
  "Don’t let the world dull your sparkle.",
  "Stand tall, wear your confidence, and own your power.",
  "The best revenge is massive self-love and success.",
  "You are worthy of love, respect, and all good things.",
  "Choose to believe in yourself today.",
  "Your self-love journey starts with a single step: acceptance.",
  "Act as if you already are the person you want to become.",
  "Speak to yourself as kindly as you would a friend.",
  "Your confidence will inspire others to find their own.",
  "You radiate beauty when you love yourself.",
  "The only permission you need to shine is your own.",
  "Be the reason someone believes in themselves today—starting with you.",
  "You are your own greatest asset—invest in yourself.",
  "Loving yourself is the first step to living a fulfilled life.",
  "Your confidence is like a muscle—the more you use it, the stronger it gets.",
  "Be yourself, because an original is worth more than a copy.",
  "Trust the process of becoming the best version of yourself.",
  "The most beautiful thing you can wear is your confidence.",
  "You define your own worth—never let others do it for you.",
  "Confidence is built through action, not overthinking.",
  "Shine bright, and don’t let anyone dim your light.",
  "You don’t need to prove your worth to anyone but yourself.",
  "Self-love is the key to unlocking your full potential.",
  "Speak to yourself with kindness, and watch your confidence grow.",
  "Your flaws make you unique—embrace them.",
  "You are enough, exactly as you are in this moment.",
  "Stop waiting for approval—validate yourself.",
  "Love yourself fiercely, and the world will follow.",
  "The way you treat yourself sets the standard for others.",
  "Your confidence is your power—use it wisely.",
  "You don’t have to be perfect to be amazing.",
  "Believe in yourself even when no one else does.",
  "Self-love is knowing you are valuable, even when no one tells you.",
  "Confidence is silent; insecurities are loud.",
  "The only approval you need is your own.",
  "Your uniqueness is your magic—own it.",
  "Never settle for less than you deserve.",
  "You are stronger than your doubts.",
  "The world needs your light—don’t hide it.",
  "Take up space. You belong here.",
  "The more you practice self-love, the more you attract love.",
  "Be your own biggest supporter.",
  "No one can love you better than you can love yourself.",
  "Stop comparing yourself—your journey is unique.",
  "Your self-worth isn’t tied to external validation.",
  "Confidence is an inside job.",
  "Choose yourself, every single day.",
  "Don’t let fear hold you back—believe in your greatness.",
  "You don’t need permission to be yourself.",
  "The only opinion that truly matters is your own.",
  "Your thoughts shape your reality—choose positivity.",
  "Every day is an opportunity to love yourself more.",
  "Your self-respect should never be compromised.",
  "You were born to be real, not to please others.",
  "Fall in love with becoming the best version of yourself.",
  "Dare to be different—it’s your superpower.",
  "If you want self-confidence, start by keeping promises to yourself.",
  "You are enough, even when you don’t feel like it.",
  "Your voice matters—speak up with confidence.",
  "The strongest relationship you have is the one with yourself.",
  "A confident mind creates a confident life.",
  "Stand tall and own your worth.",
  "You are capable of more than you imagine.",
  "The first step to confidence is accepting yourself as you are.",
  "Let go of self-doubt and embrace self-trust.",
  "Confidence is about being comfortable in your own skin.",
  "Nothing is more attractive than self-assurance.",
  "Don’t let negative thoughts define you.",
  "Your inner dialogue shapes your reality—make it positive.",
  "Celebrate your progress, no matter how small.",
  "The way you see yourself is the way the world sees you.",
  "Confidence is the courage to be unapologetically yourself.",
  "You are not behind; you are exactly where you need to be.",
  "Give yourself the love you so easily give to others.",
  "A confident person focuses on their strengths, not their flaws.",
  "Don’t let setbacks shake your self-worth.",
  "Be fearless in the pursuit of your happiness.",
  "No one can take away the love you have for yourself.",
  "The only limits you have are the ones you believe in.",
  "Confidence is built through experience, not perfection.",
  "Your worth isn’t measured by the opinions of others.",
  "Believe in yourself, and watch how life changes.",
  "Self-love is the foundation of all happiness.",
  "Dare to love yourself as deeply as you love others.",
  "Confidence is not about arrogance; it’s about self-respect.",
  "Your dreams are worth pursuing because you are worth it.",
  "You glow differently when you are confident in who you are.",
  "Fear fades when you trust yourself completely.",
  "You don’t need anyone’s approval to feel good about yourself.",
  "Stop overthinking—just believe in yourself and take action.",
  "Your self-love journey is the most important one you’ll take.",
  "You are worthy of kindness, especially from yourself.",
  "The way you talk to yourself matters more than you think.",
  "Self-confidence grows when you take care of yourself.",
  "Trust yourself; you have everything you need within you.",
  "Love yourself enough to set boundaries.",
  "No one can dim your light unless you let them.",
  "Success starts with self-belief.",
  "Embrace your imperfections—they make you human.",
  "Every day is a new opportunity to believe in yourself more.",
  "Self-love is not selfish; it’s essential.",
  "Your opinion of yourself should be the highest.",
  "Believe in your ability to create a life you love.",
  "Your confidence is contagious—spread it!",
  "Stand up for yourself with confidence and grace.",
  "The greatest love story begins with self-love.",
  "Be bold enough to own your worth.",
  "Choose to be confident even when you feel unsure.",
  "You are worthy of all the good things coming your way.",
  "Let go of self-doubt and trust your abilities.",
  "Happiness starts with self-acceptance.",
  "Confidence is about progress, not perfection.",
  "Love yourself like your life depends on it—because it does.",
];

final List<String> selfloveImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled self-love and confidence quotes with random images.
final List<QuoteItem> selfloveQuotes = getShuffledQuotes(
  selfloveQuotesRaw,
  selfloveImages,
);
