import '../quotes_randomizer.dart';

/// **Spirituality and Mindfulness Quotes & Images**
final List<String> spiritualityQuotesRaw = [
  "The journey inward is the most important journey of all.",
  "Peace comes from within. Do not seek it without.",
  "Mindfulness is the art of being present in every moment.",
  "In the silence of meditation, we find our true self.",
  "Spiritual growth begins when you let go of what you cannot control.",
  "Embrace the journey of self-discovery with an open heart.",
  "Awareness is the first step towards transformation.",
  "Let your soul be your guide, not your fears.",
  "Find stillness in the chaos, and you will discover serenity.",
  "True spirituality is living with compassion and love.",
  "Mindfulness turns chaos into clarity.",
  "The present moment is a gift; that’s why we call it the present.",
  "Quiet your mind, and the soul will speak.",
  "Meditation is the gateway to a peaceful life.",
  "Let go, and let your spirit soar.",
  "In every breath, find a moment of mindfulness.",
  "Spirituality is not a destination but a continuous journey.",
  "When you find inner peace, you create outer harmony.",
  "Awaken to the beauty of life through mindful living.",
  "The essence of spirituality is connection—to yourself, others, and the universe.",
  "Let your inner light shine and illuminate the path.",
  "The mind is a wonderful servant, but a terrible master.",
  "Peace begins with a smile and a mindful heart.",
  "Nurture your soul with moments of stillness and reflection.",
  "Your true self is not found in the noise, but in the silence.",
  "Mindfulness is the key to unlocking the treasures of the heart.",
  "A calm mind brings inner strength and self-confidence.",
  "Spiritual awakening is the realization of your own divine nature.",
  "Every moment is an opportunity to connect with your inner self.",
  "Let mindfulness be the bridge between your thoughts and your heart.",
  "Be present in all things and thankful for all things.",
  "Quiet the mind, and the soul will speak.",
  "Your soul knows the way. Trust it.",
  "Mindfulness is the key to a peaceful heart.",
  "True happiness is found within, not in external things.",
  "Breathe deeply and let go of what no longer serves you.",
  "Spirituality is not about religion; it’s about awakening.",
  "Live each moment fully, for it will never come again.",
  "Surrender to the flow of life and trust the process.",
  "Silence is the language of the soul.",
  "The greatest journey is the one within.",
  "Detach from the noise and listen to the whispers of your soul.",
  "A grateful heart is a magnet for miracles.",
  "Meditation is the soul’s way of connecting with the divine.",
  "Be still and know that you are exactly where you need to be.",
  "Mindfulness is the foundation of spiritual awakening.",
  "Let go of fear and embrace the power of the present moment.",
  "The universe responds to the vibrations of your thoughts.",
  "Wherever you are, be all there.",
  "The light you seek is already within you.",
  "The soul always knows what to do to heal itself.",
  "Your energy introduces you before you even speak.",
  "Happiness is not something you find; it’s something you create.",
  "Every breath is a new beginning.",
  "Stillness is where your true power lies.",
  "The present moment is all that truly exists.",
  "Trust that the universe is guiding you toward your highest good.",
  "Align your mind, body, and soul, and you will find peace.",
  "Awakening begins when you stop seeking outside yourself.",
  "Let go of attachments, and you will find true freedom.",
  "Peace comes from within. Do not seek it without.",
  "Your thoughts shape your reality—choose them wisely.",
  "Live with purpose, and the universe will support your journey.",
  "There is no path to peace. Peace is the path.",
  "Open your heart, and the universe will fill it with love.",
  "Gratitude transforms what we have into enough.",
  "The deeper you go within, the higher you rise in life.",
  "Compassion is the highest form of spiritual wisdom.",
  "When you focus on the present, you create a future of peace.",
  "You are not your thoughts; you are the awareness behind them.",
  "Find joy in the simple moments; they hold the deepest truths.",
  "Your mind is a garden—nourish it with positive thoughts.",
  "Let your soul guide you, and you will never be lost.",
  "A calm mind leads to a peaceful life.",
  "The path to enlightenment begins with self-awareness.",
  "Let go of the need to control and trust in divine timing.",
  "Your inner world creates your outer world.",
  "The answers you seek are already within you.",
  "The present moment is a gift—embrace it fully.",
  "Happiness is a byproduct of a mindful and grateful heart.",
  "Meditation is the gateway to your true self.",
  "Awareness is the greatest agent for change.",
  "Your soul is eternal; trust in its wisdom.",
  "Detach from the illusion of control, and peace will follow.",
  "You are a divine being having a human experience.",
  "Let love and kindness be your guiding light.",
  "Every experience is an opportunity for spiritual growth.",
  "The quieter you become, the more you hear.",
  "Forgiveness frees the soul and lightens the heart.",
  "Listen to your intuition—it is your soul’s voice.",
  "Faith is the bridge between where you are and where you are meant to be.",
  "You are one with the universe; separation is an illusion.",
  "Let go of expectations and embrace the flow of life.",
  "Simplicity is the ultimate form of spiritual richness.",
  "Love is the purest form of spiritual energy.",
  "The soul’s journey is about remembering, not learning.",
  "Mindfulness is the art of being fully alive.",
  "What you focus on expands—choose love over fear.",
  "Peace begins with acceptance.",
  "True wealth is measured by the depth of your inner peace.",
  "Trust in the divine plan, even when you cannot see it.",
  "Stillness speaks when the mind is silent.",
  "You are not alone; the universe is always supporting you.",
  "The best way to connect with your soul is to listen.",
  "Nothing is missing in the present moment—it is complete.",
  "Let your soul be light, free from the weight of worry.",
  "Be mindful of your words, for they shape your reality.",
  "Surrendering is not giving up; it is trusting fully.",
  "The purpose of life is to align with your highest self.",
  "The path to enlightenment is paved with love and awareness.",
  "The greatest spiritual practice is kindness.",
  "Nature is a reflection of the divine—spend time in it.",
  "Let your heart lead, and your soul will follow.",
  "Abundance flows to those who align with gratitude.",
  "True connection is found in moments of silence and presence.",
  "Breathe deeply, and let peace fill your soul.",
  "Mindfulness turns ordinary moments into sacred experiences.",
  "Your soul’s essence is pure love.",
  "The divine is within you—stop searching outside.",
  "You are the light you seek in the world.",
  "Detach from judgment, and you will experience true freedom.",
  "The journey inward is the greatest journey of all.",
  "Be mindful of the energy you bring into a space.",
  "Release what no longer serves you, and embrace what does.",
  "Love yourself as deeply as the universe loves you.",
  "Your spiritual path is uniquely yours—embrace it.",
  "Joy is found in the stillness of the present moment.",
  "Everything you need is already within you.",
  "Let go, trust, and watch the universe work its magic.",
  "Your vibration creates your reality—raise it with love.",
  "Be at peace with what is, and happiness will follow.",
  "Awareness is the greatest agent for change.",
  "Your soul is your best compass; follow it fearlessly.",
  "The quieter you become, the more you can hear.",
  "Do not seek peace outside yourself; it lies within.",
  "A heart at peace gives life to the body.",
  "Every step taken in mindfulness is a step toward true freedom.",
  "Your energy introduces you before you even speak.",
  "There is no path to peace; peace is the path.",
  "The universe is always whispering to you; listen carefully.",
  "You are never alone. The entire universe is within you.",
  "A grateful heart is a magnet for miracles.",
  "Align your energy with the universe, and watch the magic unfold.",
  "Stillness is where creativity and solutions are found.",
  "To connect with the divine, one must silence the noise of the mind.",
  "The power of now is the gateway to inner peace.",
  "Your breath is the bridge between the body and the soul.",
  "In surrender, we find our greatest strength.",
  "To be mindful is to be fully alive.",
  "Your true essence is beyond all labels and definitions.",
  "Be like a river—flowing, adapting, and unstoppable.",
  "Happiness does not come from things; it comes from the soul.",
  "In the depth of your being lies infinite peace.",
  "Detach from the chaos; embrace the stillness.",
  "The soul speaks in whispers; listen closely.",
  "When you let go, you create space for miracles.",
  "Your presence is the greatest gift you can offer the world.",
  "Be a witness to your thoughts, not a prisoner of them.",
  "Serenity is not freedom from the storm but peace within it.",
  "When you connect with nature, you connect with your soul.",
  "Find beauty in the simplicity of the present moment.",
  "A peaceful heart leads to a peaceful life.",
  "Live as though everything is a miracle.",
  "Let go of the need to control, and watch how life flows.",
  "A moment of silence holds infinite wisdom.",
  "Your soul is your greatest teacher; trust its guidance.",
  "Spirituality is the art of unfolding the highest version of yourself.",
  "Do not dwell in the past; do not dream of the future; concentrate on the present moment.",
  "There is great strength in surrendering to the flow of life.",
  "Embrace the silence, for in it, the soul speaks.",
  "You are not the storm; you are the sky watching over it.",
  "The only journey is the one within.",
  "Let love and light be your guiding forces.",
  "The greatest gift you can give yourself is inner peace.",
  "Radiate love, and the universe will reflect it back to you.",
  "To love yourself is the beginning of a lifelong romance with the soul.",
  "You are a spark of the divine; never forget your light.",
  "Patience, presence, and purpose create a peaceful life.",
  "Nothing is missing; you are already whole.",
  "The soul does not strive; it simply is.",
  "Let each breath remind you that you are alive, and that is enough.",
];

final List<String> spiritualityImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
  "assets/images/quotes/bg/11.jpg",
  "assets/images/quotes/bg/12.jpg",
  "assets/images/quotes/bg/13.jpg",
  "assets/images/quotes/bg/14.jpg",
  "assets/images/quotes/bg/15.jpg",
  "assets/images/quotes/bg/16.jpg",
  "assets/images/quotes/bg/17.jpg",
  "assets/images/quotes/bg/18.jpg",
  "assets/images/quotes/bg/19.jpg",
  "assets/images/quotes/bg/20.jpg",
  "assets/images/quotes/bg/21.jpg",
  "assets/images/quotes/bg/22.jpg",
  "assets/images/quotes/bg/23.jpg",
  "assets/images/quotes/bg/24.jpg",
  "assets/images/quotes/bg/25.jpg",
  "assets/images/quotes/bg/26.jpg",
  "assets/images/quotes/bg/27.jpg",
  "assets/images/quotes/bg/28.jpg",
  "assets/images/quotes/bg/29.jpg",
  "assets/images/quotes/bg/30.jpg",
  "assets/images/quotes/bg/31.jpg",
  "assets/images/quotes/bg/32.jpg",
  "assets/images/quotes/bg/33.jpg",
  "assets/images/quotes/bg/34.jpg",
  "assets/images/quotes/bg/35.jpg",
  "assets/images/quotes/bg/36.jpg",
  "assets/images/quotes/bg/37.jpg",
  "assets/images/quotes/bg/38.jpg",
  "assets/images/quotes/bg/39.jpg",
  "assets/images/quotes/bg/40.jpg",
  "assets/images/quotes/bg/41.jpg",
  "assets/images/quotes/bg/42.jpg",
  "assets/images/quotes/bg/43.jpg",
  "assets/images/quotes/bg/44.jpg",
  "assets/images/quotes/bg/45.jpg",
  "assets/images/quotes/bg/46.jpg",
  "assets/images/quotes/bg/47.jpg",
  "assets/images/quotes/bg/48.jpg",
  "assets/images/quotes/bg/49.jpg",
  "assets/images/quotes/bg/50.jpg",
  "assets/images/quotes/bg/51.jpg",
  "assets/images/quotes/bg/52.jpg",
  "assets/images/quotes/bg/53.jpg",
  "assets/images/quotes/bg/54.jpg",
  "assets/images/quotes/bg/55.jpg",
  "assets/images/quotes/bg/56.jpg",
  "assets/images/quotes/bg/57.jpg",
  "assets/images/quotes/bg/58.jpg",
  "assets/images/quotes/bg/59.jpg",
  "assets/images/quotes/bg/60.jpg",
  "assets/images/quotes/bg/61.jpg",
  "assets/images/quotes/bg/62.jpg",
  "assets/images/quotes/bg/63.jpg",
  "assets/images/quotes/bg/64.jpg",
  "assets/images/quotes/bg/65.jpg",
  "assets/images/quotes/bg/66.jpg",
  "assets/images/quotes/bg/67.jpg",
  "assets/images/quotes/bg/68.jpg",
  "assets/images/quotes/bg/69.jpg",
  "assets/images/quotes/bg/70.jpg",
  "assets/images/quotes/bg/71.jpg",
  "assets/images/quotes/bg/72.jpg",
  "assets/images/quotes/bg/73.jpg",
  "assets/images/quotes/bg/74.jpg",
  "assets/images/quotes/bg/75.jpg",
  "assets/images/quotes/bg/76.jpg",
  "assets/images/quotes/bg/77.jpg",
  "assets/images/quotes/bg/78.jpg",
  "assets/images/quotes/bg/79.jpg",
  "assets/images/quotes/bg/80.jpg",
  "assets/images/quotes/bg/81.jpg",
  "assets/images/quotes/bg/82.jpg",
  "assets/images/quotes/bg/83.jpg",
  "assets/images/quotes/bg/84.jpg",
  "assets/images/quotes/bg/85.jpg",
  "assets/images/quotes/bg/86.jpg",
  "assets/images/quotes/bg/87.jpg",
  "assets/images/quotes/bg/88.jpg",
  "assets/images/quotes/bg/89.jpg",
  "assets/images/quotes/bg/90.jpg",
  "assets/images/quotes/bg/91.jpg",
  "assets/images/quotes/bg/92.jpg",
  "assets/images/quotes/bg/93.jpg",
  "assets/images/quotes/bg/94.jpg",
  "assets/images/quotes/bg/95.jpg",
  "assets/images/quotes/bg/96.jpg",
  "assets/images/quotes/bg/97.jpg",
  "assets/images/quotes/bg/98.jpg",
  "assets/images/quotes/bg/99.jpg",
  "assets/images/quotes/bg/100.jpg",
  "assets/images/quotes/bg/101.jpg",
  "assets/images/quotes/bg/102.jpg",
  "assets/images/quotes/bg/103.jpg",
  "assets/images/quotes/bg/104.jpg",
  "assets/images/quotes/bg/105.jpg",
  "assets/images/quotes/bg/106.jpg",
  "assets/images/quotes/bg/107.jpg",
  "assets/images/quotes/bg/108.jpg",
  "assets/images/quotes/bg/109.jpg",
  "assets/images/quotes/bg/110.jpg",
];

/// Generate the final list of shuffled spirituality and mindfulness quotes with random images.
final List<QuoteItem> spiritualityQuotes = getShuffledQuotes(
  spiritualityQuotesRaw,
  spiritualityImages,
);
