import '../quotes_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> bouncebackQuotesRaw = [
  "Failure is not the opposite of success; it’s part of success.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "The comeback is always stronger than the setback.",
  "Every failure is a lesson. If you are not willing to fail, you are not ready to succeed.",
  "When life knocks you down, roll over and look at the stars.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Difficulties in life are intended to make us better, not bitter.",
  "The road to success is dotted with many tempting parking spaces.",
  "The only real mistake is the one from which we learn nothing.",
  "Rock bottom became the solid foundation on which I rebuilt my life.",
  "Do not be embarrassed by your failures, learn from them and start again.",
  "The phoenix must burn to emerge.",
  "It always seems impossible until it’s done.",
  "Failure is the condiment that gives success its flavor.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "Tough times never last, but tough people do.",
  "Failure is the tuition you pay for success.",
  "He who is not courageous enough to take risks will accomplish nothing in life.",
  "Turn your wounds into wisdom.",
  "If you fell down yesterday, stand up today.",
  "A failure is not always a mistake, it may simply be the best one can do under the circumstances. The real mistake is to stop trying.",
  "Only those who dare to fail greatly can ever achieve greatly.",
  "Do not judge me by my successes, judge me by how many times I fell down and got back up again.",
  "Failure is an event, not a person. Yesterday ended last night.",
  "Don’t let the fear of losing be greater than the excitement of winning.",
  "The difference between average people and achieving people is their perception of and response to failure.",
  "One who conquers the sea today is ready to conquer the ocean tomorrow.",
  "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
  "Winners are not afraid of losing. But losers are. Failure is part of the process of success.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "In order to succeed, we must first believe that we can.",
  "Your setback is just a setup for your comeback.",
  "Don’t be afraid to give up the good to go for the great.",
  "The biggest risk is not taking any risk.",
  "Never let success get to your head and never let failure get to your heart.",
  "Sometimes you win, sometimes you learn.",
  "Rise above the storm and you will find the sunshine.",
  "Don’t be discouraged. It’s often the last key in the bunch that opens the lock.",
  "Don’t let yesterday take up too much of today.",
  "When we give ourselves permission to fail, we, at the same time, give ourselves permission to excel.",
  "Success is most often achieved by those who don’t know that failure is inevitable.",
  "It’s fine to celebrate success, but it is more important to heed the lessons of failure.",
  "You may have to fight a battle more than once to win it.",
  "When you come out of the storm, you won’t be the same person who walked in. That’s what the storm is all about.",
  "Failure should be our teacher, not our undertaker. Failure is delay, not defeat. It is a temporary detour, not a dead end.",
  "A bend in the road is not the end of the road… unless you fail to make the turn.",
  "Don’t let rejection create self-doubt. The founder of Starbucks was turned down by 217 of the 242 investors he initially spoke with.",
  "Champions keep playing until they get it right.",
  "Embrace failure. Missteps and roadblocks are inevitable but are ultimately a sign of progress.",
  "Perseverance is failing 19 times and succeeding the 20th.",
];

final List<String> bouncebackImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<QuoteItem> bouncebackQuotes = getShuffledQuotes(
  bouncebackQuotesRaw,
  bouncebackImages,
);
