import '../quotes_randomizer.dart';

/// **Embracing Change Quotes & Images**
final List<String> changeQuotesRaw = [
  "Change is the only constant in life.",
  "Your life does not get better by chance, it gets better by change.",
  "Be the change that you wish to see in the world.",
  "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
  "Embrace uncertainty. Some of the most beautiful chapters in our lives won’t have a title until much later.",
  "Change is painful, but nothing is as painful as staying stuck somewhere you don’t belong.",
  "Don’t be afraid of change. You may lose something good, but you may gain something even better.",
  "When we are no longer able to change a situation, we are challenged to change ourselves.",
  "Adaptability is about the powerful difference between adapting to cope and adapting to win.",
  "The measure of intelligence is the ability to change.",
  "To improve is to change; to be perfect is to change often.",
  "We cannot become what we want by remaining what we are.",
  "Every great change is preceded by chaos.",
  "If you want to fly, give up everything that weighs you down.",
  "Don’t resist change. You might be missing out on something better.",
  "Growth and comfort do not coexist.",
  "You must be willing to let go of the life you planned to embrace the life that is waiting for you.",
  "Life begins at the end of your comfort zone.",
  "Nothing ever stays the same. You are either moving forward or you are left behind.",
  "It’s never too late to be what you might have been.",
  "Some people don’t like change, but you need to embrace change if the alternative is disaster.",
  "People resist change because they focus on what they have to give up instead of what they have to gain.",
  "It is not the strongest or the most intelligent who will survive but those who can best manage change.",
  "Change your thoughts and you change your world.",
  "A wise man adapts himself to circumstances, as water shapes itself to the vessel that contains it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "Every next level of your life will demand a different version of you.",
  "If you change the way you look at things, the things you look at change.",
  "The secret of change is to focus all your energy not on fighting the old but on building the new.",
  "Take risks: if you win, you will be happy; if you lose, you will be wise.",
  "Life will only change when you become more committed to your dreams than you are to your comfort zone.",
  "Let go of the old to make room for the new.",
  "Change is hard at first, messy in the middle, and gorgeous at the end.",
  "Fear, uncertainty, and discomfort are your compasses toward growth.",
  "You can’t change what’s going on around you until you start changing what’s going on within you.",
  "Nothing changes if nothing changes.",
  "The first step toward change is awareness. The second step is acceptance.",
  "The art of life lies in a constant readjustment to our surroundings.",
  "The moment you accept total responsibility for everything in your life is the moment you claim the power to change anything in your life.",
  "Life is about change. Sometimes it’s painful. Sometimes it’s beautiful. But most of the time, it’s both.",
  "Only when we let go of fear do we allow ourselves to truly live.",
  "Be open to new possibilities. The best is yet to come.",
  "Change is inevitable. Growth is optional.",
  "If you are not willing to risk the unusual, you will have to settle for the ordinary.",
  "To exist is to change, to change is to mature, to mature is to go on creating oneself endlessly.",
  "Change is an opportunity to do something amazing.",
  "Great things never come from comfort zones.",
  "Change is not a threat, it’s an opportunity. Survival is not the goal, transformative success is.",
];

final List<String> changeImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled change quotes with random images.
final List<QuoteItem> changeQuotes = getShuffledQuotes(
  changeQuotesRaw,
  changeImages,
);
