import '../quotes_randomizer.dart';

/// **Curiosity and Exploration Quotes & Images**
final List<String> curiosityQuotesRaw = [
  "Curiosity is the wick in the candle of learning.",
  "The important thing is not to stop questioning. Curiosity has its own reason for existing.",
  "Exploration is really the essence of the human spirit.",
  "Adventure is just bad planning.",
  "Somewhere, something incredible is waiting to be known.",
  "The world is full of magical things patiently waiting for our wits to grow sharper.",
  "Blessed are the curious, for they shall have adventures.",
  "Not all those who wander are lost.",
  "Curiosity is one of the great secrets of happiness.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "Science and exploration feed our curiosity and help us understand our place in the universe.",
  "Discovery consists of seeing what everybody has seen and thinking what nobody has thought.",
  "Never lose a holy curiosity.",
  "A ship is safe in harbor, but that's not what ships are for.",
  "The greatest gift you can give yourself is curiosity.",
  "Exploration is curiosity put into action.",
  "Curiosity is the engine of achievement.",
  "We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.",
  "To be curious is to dare to know.",
  "There are no foreign lands. It is the traveler only who is foreign.",
  "The greatest enemy of knowledge is not ignorance; it is the illusion of knowledge.",
  "The desire to explore is one of the deepest yearnings of the human soul.",
  "Exploration is wired into our brains. If we can see the horizon, we want to know what’s beyond.",
  "Curiosity is the essence of human existence.",
  "Without curiosity, there is no discovery.",
  "To travel is to take a journey into yourself.",
  "Every great advance in science has issued from a new audacity of imagination.",
  "Only those who risk going too far can possibly find out how far they can go.",
  "The cure for boredom is curiosity. There is no cure for curiosity.",
  "Curiosity will conquer fear even more than bravery will.",
  "In every walk with nature, one receives far more than he seeks.",
  "A mind stretched by a new experience can never go back to its old dimensions.",
  "It is not the destination where you end up but the mishaps and memories you create along the way.",
  "A journey of a thousand miles begins with a single step.",
  "Imagination will often carry us to worlds that never were. But without it, we go nowhere.",
  "Explorers seek what has not yet been found.",
  "We travel, some of us forever, to seek other states, other lives, other souls.",
  "The best journeys answer questions that in the beginning you didn’t even think to ask.",
  "Exploration is a wonderful way to open our eyes to the world.",
  "What if I fall? Oh, but my darling, what if you fly?",
  "Live, travel, adventure, bless, and don’t be sorry.",
  "Curiosity leads us down new paths.",
  "If we were meant to stay in one place, we’d have roots instead of feet.",
  "Dream. Explore. Discover.",
  "A person who never made a mistake never tried anything new.",
  "He who opens a school door, closes a prison.",
  "There are no shortcuts to any place worth going.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "Travel makes one modest. You see what a tiny place you occupy in the world.",
  "You must go on adventures to find out where you truly belong.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "Never be limited by other people’s limited imaginations.",
  "Wonder is the beginning of wisdom.",
  "It always seems impossible until it’s done.",
  "The only real voyage of discovery consists not in seeking new landscapes, but in having new eyes.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
  "Travel far enough, you meet yourself.",
  "Every mountain top is within reach if you just keep climbing.",
  "The greatest discoveries come from stepping outside your comfort zone.",
  "Don’t listen to what they say. Go see.",
  "Curiosity is the spark behind every great idea.",
  "The joy is in the journey.",
  "Dare to explore the unknown.",
  "The world belongs to the curious.",
  "There’s always something new to discover.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Life begins at the end of your comfort zone.",
];

final List<String> curiosityImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled curiosity quotes with random images.
final List<QuoteItem> curiosityQuotes = getShuffledQuotes(
  curiosityQuotesRaw,
  curiosityImages,
);
