import '../quotes_randomizer.dart';

/// **Family Bonds Quotes & Images**
final List<String> familyQuotesRaw = [
  "Family is not an important thing. It’s everything.",
  "The love of a family is life’s greatest blessing.",
  "A happy family is but an earlier heaven.",
  "Family means no one gets left behind or forgotten.",
  "The strength of a family, like the strength of an army, is in its loyalty to each other.",
  "Home is where you are loved the most and act the worst.",
  "In every conceivable manner, the family is link to our past, bridge to our future.",
  "The family is one of nature’s masterpieces.",
  "What can you do to promote world peace? Go home and love your family.",
  "Other things may change us, but we start and end with family.",
  "A family doesn’t need to be perfect; it just needs to be united.",
  "Family is where life begins and love never ends.",
  "Rejoice with your family in the beautiful land of life.",
  "Being a family means you are part of something very wonderful.",
  "Sticking with your family is what makes it a family.",
  "The most important thing in the world is family and love.",
  "The informality of family life is a blessed condition that allows us all to become our best.",
  "To us, family means putting your arms around each other and being there.",
  "The memories we make with our family is everything.",
  "There is no doubt that it is around the family and the home that all the greatest virtues are created.",
  "Family gives you the roots to stand tall and strong.",
  "When everything goes to hell, the people who stand by you without flinching are your family.",
  "Nothing is better than going home to family and eating good food and relaxing.",
  "You don’t choose your family. They are God’s gift to you, as you are to them.",
  "Family and friendships are two of the greatest facilitators of happiness.",
  "The bond that links your true family is not one of blood, but of respect and joy in each other’s life.",
  "Having somewhere to go is home. Having someone to love is family. Having both is a blessing.",
  "Happiness is having a large, loving, caring, close-knit family.",
  "My greatest treasure is my family. We are not perfect, but I love them with all my heart.",
  "Call it a clan, call it a network, call it a tribe, call it a family. Whatever you call it, whoever you are, you need one.",
  "It didn’t matter how big our house was; it mattered that there was love in it.",
  "Family means we have each other’s back.",
  "There’s nothing that makes you more insane than family. Or more happy. Or more exasperated. Or more secure.",
  "One day you will do things for me that you hate. That is what it means to be family.",
  "A house is made of walls and beams, a home is built with love and dreams.",
  "Family is the heart of a home.",
  "Blood makes you related, but loyalty makes you family.",
  "Family: where life begins and love never ends.",
  "No family is perfect, but every family is unique.",
  "Family members may drive you crazy, but they also make life worth living.",
  "There is no greater bond than that of a family.",
  "The love in our family flows strong and deep, leaving us memories to cherish and keep.",
  "A strong family unit is the best foundation for success.",
  "Family is the compass that guides us; it is the inspiration to reach great heights.",
  "Your family is the best team you could ever have.",
  "There is no wealth like the warmth of family.",
  "Family is a life jacket in the stormy sea of life.",
  "A family’s love is forever.",
  "Family keeps you grounded and lifts you up at the same time.",
  "A family’s love is the foundation of happiness.",
  "Family is the first school where we learn life’s lessons.",
  "Where there is family, there is love.",
  "True family love is unconditional and everlasting.",
  "Families are the ties that remind us of yesterday, provide strength for today, and give us hope for tomorrow.",
  "Home is people, not a place. If you go back there after the people are gone, then all you can see is what is not there anymore.",
  "The bond of family is the closest thing to heaven we will experience on earth.",
  "Nothing is more beautiful than the love shared within a family.",
  "A home filled with love is a home filled with happiness.",
  "Families are like branches on a tree; we grow in different directions, yet our roots remain as one.",
  "A family’s love endures all things.",
  "To love and be loved by family is a true blessing.",
  "A true family is built on love, laughter, and support.",
  "Family bonds never break, even through time and distance.",
  "Nothing compares to the comfort of family.",
  "A family’s love is the greatest strength in times of need.",
  "Family is a little bit of crazy, a little bit of loud, and a whole lot of love.",
  "A loving family inspires greatness in all of us.",
];

final List<String> familyImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled family quotes with random images.
final List<QuoteItem> familyQuotes = getShuffledQuotes(
  familyQuotesRaw,
  familyImages,
);
