import '../quotes_randomizer.dart';

/// **Forgiveness and Understanding Quotes & Images**
final List<String> forgivenessQuotesRaw = [
  "The weak can never forgive. Forgiveness is the attribute of the strong.",
  "Forgiveness does not change the past, but it does enlarge the future.",
  "To err is human; to forgive, divine.",
  "Forgiveness is the key to action and freedom.",
  "It's one of the greatest gifts you can give yourself, to forgive.",
  "Forgiveness is not an occasional act; it is a constant attitude.",
  "Holding a grudge doesn’t make you strong; it makes you bitter.",
  "Forgiveness is the fragrance that the violet sheds on the heel that has crushed it.",
  "True forgiveness is when you can say, ‘Thank you for that experience.’",
  "Forgive others, not because they deserve forgiveness, but because you deserve peace.",
  "We must develop and maintain the capacity to forgive.",
  "Resentment is like drinking poison and then hoping it will kill your enemies.",
  "Forgiveness is giving up the hope that the past could have been any different.",
  "Forgiveness liberates the soul. It removes fear. That is why it is such a powerful weapon.",
  "An eye for an eye will only make the whole world blind.",
  "Forgiveness is choosing to love. It is the first skill of self-giving love.",
  "Forgiveness is the best revenge.",
  "Mistakes are always forgivable if one has the courage to admit them.",
  "When you forgive, you heal. When you let go, you grow.",
  "Forgive yourself for your faults and your mistakes and move on.",
  "A life lived without forgiveness is a prison.",
  "Sometimes you don’t forgive people because they deserve it. You forgive them because you need it.",
  "Forgiveness is the needle that knows how to mend.",
  "Understanding is the first step to acceptance, and only with acceptance can there be recovery.",
  "Forgiveness means letting go of the hope for a better past.",
  "Forgive, forget, and move forward. It’s the only way to live.",
  "You cannot shake hands with a clenched fist.",
  "Forgiveness allows you to focus on the future rather than the past.",
  "The practice of forgiveness is our most important contribution to the healing of the world.",
  "Forgiveness does not excuse their behavior. Forgiveness prevents their behavior from destroying your heart.",
  "Without forgiveness, there’s no future.",
  "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.",
  "If we really want to love, we must learn how to forgive.",
  "Forgiving is rediscovering the shining path of peace that at first you thought others took away.",
  "To forgive is wisdom, to forget is genius. And easier.",
  "It’s not an easy journey, to get to a place where you forgive people. But it is such a powerful place, because it frees you.",
  "A happy marriage is the union of two good forgivers.",
  "Life is too short to wake up with regrets. So love the people who treat you right, forgive the ones who don’t.",
  "Forgiveness is a sign that the person who has wronged you means more to you than the wrong they have dealt.",
  "Sometimes what a person needs is not a brilliant mind that speaks, but a patient heart that listens.",
  "Forgiveness is the only way to break the cycle of hatred and revenge.",
  "It takes a strong person to say sorry, and an even stronger person to forgive.",
  "Forgiveness doesn’t mean accepting what they did. It means letting it go and preventing it from controlling your life.",
  "Forgiving someone doesn’t mean forgetting; it means remembering without anger.",
  "If you want to see the brave, look at those who can forgive.",
  "Understanding comes from communication, and forgiveness from acceptance.",
  "When you forgive, you in no way change the past—but you sure do change the future.",
  "Forgiveness is the final form of love.",
  "Compassion and tolerance are not a sign of weakness, but a sign of strength.",
  "Without forgiveness and love, you will live with resentment, bitterness, and strife every day.",
  "True understanding and forgiveness can only come when we realize our own imperfections.",
  "When you truly understand someone, you can find it easier to forgive them.",
  "Anger makes you smaller, while forgiveness forces you to grow beyond what you were.",
  "Forgiveness is not about forgetting. It’s about letting go of another person’s throat.",
  "Only the brave know how to forgive. A coward never forgives; it is not in his nature.",
  "Forgiveness is not just about others. It’s really for you. It’s about you letting go of the pain.",
  "Don’t wait for people to apologize. Forgive them and move on.",
  "Hating someone makes them important. Forgiving them makes them obsolete.",
  "Understanding is deeper than knowledge. Many know you, but very few understand you.",
  "Forgiveness is an act of self-love.",
  "It is easier to forgive an enemy than to forgive a friend.",
  "Forgive, not because they deserve forgiveness, but because you deserve peace.",
  "Revenge is weak. Forgiveness is powerful.",
  "Peace begins when expectation ends.",
  "Forgiveness is a funny thing. It warms the heart and cools the sting.",
];

final List<String> forgivenessImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled forgiveness quotes with random images.
final List<QuoteItem> forgivenessQuotes = getShuffledQuotes(
  forgivenessQuotesRaw,
  forgivenessImages,
);
