import '../quotes_randomizer.dart';

/// **Friendship and Trust Quotes & Images**
final List<String> friendshipQuotesRaw = [
  "A real friend is one who walks in when the rest of the world walks out.",
  "Friendship is born at that moment when one person says to another, ‘What! You too? I thought I was the only one.’",
  "True friendship comes when the silence between two people is comfortable.",
  "A friend is someone who understands your past, believes in your future, and accepts you just the way you are.",
  "Friendship is the only cement that will ever hold the world together.",
  "The greatest gift of life is friendship, and I have received it.",
  "A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.",
  "True friends are like diamonds—bright, beautiful, valuable, and always in style.",
  "Friendship is not about who you have known the longest, it is about who walked into your life and never left your side.",
  "A good friend knows all your best stories. A best friend has lived them with you.",
  "Friendship is a sheltering tree.",
  "Friends are the family we choose for ourselves.",
  "A single rose can be my garden… a single friend, my world.",
  "Walking with a friend in the dark is better than walking alone in the light.",
  "Friendship multiplies the good in life and divides its evils.",
  "Friendship is the golden thread that ties the heart of all the world.",
  "Many people will walk in and out of your life, but only true friends will leave footprints in your heart.",
  "A true friend is someone who sees the pain in your eyes while everyone else believes the smile on your face.",
  "Friends show their love in times of trouble, not in happiness.",
  "Friendship is the comfort of knowing that even when you feel alone, you aren’t.",
  "Trust is the fruit of a relationship in which you know you are loved.",
  "A true friend never gets in your way unless you happen to be going down.",
  "Friendship and trust go hand in hand; you cannot have one without the other.",
  "Trust takes years to build, seconds to break, and forever to repair.",
  "The best way to find out if you can trust somebody is to trust them.",
  "Trust is like a paper, once crumpled, it can never be perfect again.",
  "A loyal friend is worth ten thousand relatives.",
  "Friendship is built on trust, honesty, and loyalty.",
  "A friend is someone you can trust with all your secrets and never worry.",
  "No friendship is an accident.",
  "Friendship is a two-way street built on trust and understanding.",
  "The only way to have a friend is to be one.",
  "Sometimes being a friend means mastering the art of timing.",
  "A good friend is like a four-leaf clover; hard to find and lucky to have.",
  "Friendship is the shadow of the evening, which strengthens with the setting sun of life.",
  "Friends are the siblings God never gave us.",
  "Friendship improves happiness and abates misery by doubling our joys and dividing our grief.",
  "Life is partly what we make it, and partly what it is made by the friends we choose.",
  "True friends are those rare people who come to find you in dark places and lead you back to the light.",
  "A friend is one of the nicest things you can have, and one of the best things you can be.",
  "Friendship is a wildly underrated medication.",
  "The language of friendship is not words but meanings.",
  "Friendship is always a sweet responsibility, never an opportunity.",
  "Friendship means understanding, not agreement. It means forgiveness, not forgetting. It means the memories last, even if contact is lost.",
  "A friend is someone who makes it easy to believe in yourself.",
  "The best mirror is an old friend.",
  "Friendship is an art, and very few people are born with a natural gift for it.",
  "A friend is the one who comes in when the whole world has gone out.",
  "Sometimes, just a little trust and kindness go a long way in friendship.",
  "Friendship without trust is like a car without gas—you can stay in it, but it won’t go anywhere.",
  "One of the most beautiful qualities of true friendship is to understand and to be understood.",
  "Without trust, there is no friendship, just acquaintances.",
  "Friendship is not a big thing, it’s a million little things.",
  "A trustworthy friend is a priceless treasure.",
  "True friendship resists time, distance, and silence.",
  "No road is long with good company.",
  "The best friendships are built on a foundation of trust and shared laughter.",
  "Friendship is giving someone the ability to destroy you but trusting them not to.",
  "An honest friend is worth more than a hundred flatterers.",
  "Friendship grows stronger with trust and fades with betrayal.",
  "The greatest healing therapy is friendship and love.",
  "Love all, trust a few, do wrong to none.",
  "Sometimes we need someone to simply be there, not to fix anything, but just to let us feel supported and understood.",
  "The greatest sweetener of human life is friendship.",
  "A friend is what the heart needs all the time.",
  "A friend’s trust is the glue that holds everything together.",
  "A good friendship is a conversation that never ends.",
];

final List<String> friendshipImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled friendship quotes with random images.
final List<QuoteItem> friendshipQuotes = getShuffledQuotes(
  friendshipQuotesRaw,
  friendshipImages,
);
