import '../quotes_randomizer.dart';

/// **personal growth and development  Quotes & Images**
final List<String> growthQuotesRaw = [
  "Growth and comfort do not coexist.",
  "The only way to do great work is to love what you do.",
  "Your only limit is you.",
  "Be not afraid of growing slowly; be afraid only of standing still.",
  "The best way to predict the future is to create it.",
  "Believe you can and you're halfway there.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Don’t watch the clock; do what it does. Keep going.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Your future is created by what you do today, not tomorrow.",
  "Doubt kills more dreams than failure ever will.",
  "If it doesn’t challenge you, it won’t change you.",
  "The expert in anything was once a beginner.",
  "Push yourself, because no one else is going to do it for you.",
  "A year from now, you will wish you had started today.",
  "Every morning you have two choices: continue sleeping with your dreams or wake up and chase them.",
  "Discipline is choosing between what you want now and what you want most.",
  "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
  "You may have to fight a battle more than once to win it.",
  "Dream big, start small, but most of all, start.",
  "Small progress is still progress.",
  "Do something today that your future self will thank you for.",
  "The key to success is to start before you are ready.",
  "Difficult roads often lead to beautiful destinations.",
  "Personal growth is not a matter of learning new information but of unlearning old limits.",
  "Stay away from negative people. They have a problem for every solution.",
  "To be successful, the first step is falling in love with your work.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "You can’t change your future unless you change your habits today.",
  "Growth is never by mere chance; it is the result of forces working together.",
  "The secret of getting ahead is getting started.",
  "One day or day one. You decide.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "Don’t limit your challenges. Challenge your limits.",
  "If you want something you’ve never had, you must do something you’ve never done.",
  "Never stop learning because life never stops teaching.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Self-discipline is the magic power that makes you virtually unstoppable.",
  "What you do today can improve all your tomorrows.",
  "Set a goal so big that you can’t achieve it until you grow into the person who can.",
  "The only way to achieve the impossible is to believe it is possible.",
  "When everything seems to be against you, remember that the airplane takes off against the wind, not with it.",
  "Success is the ability to go from failure to failure without losing enthusiasm.",
  "Winners are not those who never fail, but those who never quit.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Stay hungry, stay foolish.",
  "A comfort zone is a beautiful place, but nothing ever grows there.",
  "What we fear doing most is usually what we most need to do.",
  "The best investment you can make is in yourself.",
  "Nothing will work unless you do.",
  "Act as if what you do makes a difference. It does.",
  "Big journeys begin with small steps.",
  "There is no elevator to success; you have to take the stairs.",
  "To improve is to change; to be perfect is to change often.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "A little progress each day adds up to big results.",
  "If opportunity doesn’t knock, build a door.",
  "Your growth is a reflection of your effort.",
  "Every expert was once a beginner.",
  "Your greatest self has been waiting your whole life; don’t make it wait any longer.",
  "Your life does not get better by chance, it gets better by change.",
  "If you want to grow, give up excuses.",
  "Success is a journey, not a destination.",
  "Take pride in how far you’ve come and have faith in how far you can go.",
];

final List<String> growthImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled perseverance quotes with random images.
final List<QuoteItem> growthQuotes = getShuffledQuotes(
  growthQuotesRaw,
  growthImages,
);
