import '../quotes_randomizer.dart';

/// **Kindness and Compassion Quotes & Images**
final List<String> kindnessQuotesRaw = [
  "No act of kindness, no matter how small, is ever wasted.",
  "A single act of kindness throws out roots in all directions, and the roots spring up and make new trees.",
  "Kindness is the language which the deaf can hear and the blind can see.",
  "Be kind whenever possible. It is always possible.",
  "Unexpected kindness is the most powerful, least costly, and most underrated agent of human change.",
  "A warm smile is the universal language of kindness.",
  "Sometimes it takes only one act of kindness and caring to change a person’s life.",
  "Kindness is a gift everyone can afford to give.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "If you see someone without a smile, give them one of yours.",
  "Carry out a random act of kindness, with no expectation of reward.",
  "The world is full of kind people. If you can’t find one, be one.",
  "You can always, always give something, even if it is only kindness.",
  "Compassion and tolerance are not a sign of weakness, but a sign of strength.",
  "Helping one person might not change the whole world, but it could change the world for one person.",
  "Do things for people not because of who they are or what they do in return, but because of who you are.",
  "What wisdom can you find that is greater than kindness?",
  "A kind word is like a spring day.",
  "One kind word can change someone's entire day.",
  "Kind words do not cost much. Yet they accomplish much.",
  "How do we change the world? One random act of kindness at a time.",
  "Tenderness and kindness are not signs of weakness and despair, but manifestations of strength and resolution.",
  "Wherever there is a human being, there is an opportunity for kindness.",
  "A little thought and a little kindness are often worth more than a great deal of money.",
  "Compassion brings us to a stop, and for a moment we rise above ourselves.",
  "Remember, there’s no such thing as a small act of kindness. Every act creates a ripple with no logical end.",
  "Act with kindness, but do not expect gratitude.",
  "The simplest acts of kindness are by far more powerful than a thousand heads bowing in prayer.",
  "Love and kindness are never wasted. They always make a difference.",
  "We can’t help everyone, but everyone can help someone.",
  "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.",
  "Kindness makes you the most beautiful person in the world, no matter what you look like.",
  "The greatest work that kindness does to others is that it makes them kind themselves.",
  "When words are both true and kind, they can change the world.",
  "Kindness begins with understanding that we all struggle.",
  "There is no exercise better for the heart than reaching down and lifting people up.",
  "Sometimes the smallest things take up the most room in your heart.",
  "No one has ever become poor by giving.",
  "Always be a little kinder than necessary.",
  "Kindness is doing what you can, where you are, with what you have.",
  "A candle loses nothing by lighting another candle.",
  "Every act of kindness benefits the giver as well as the receiver.",
  "There is no greater gift than kindness.",
  "Happiness is not something ready made. It comes from your own actions, especially acts of kindness.",
  "What you do makes a difference, and you have to decide what kind of difference you want to make.",
  "Compassion is the basis of morality.",
  "In a world where you can be anything, be kind.",
  "A kind gesture can reach a wound that only compassion can heal.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "Being kind to others is a way of being good to yourself.",
  "Kindness is free. Sprinkle it everywhere.",
  "Helping others is the way we help ourselves.",
  "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.",
  "Life is too short to be anything but kind.",
  "If you can be anything in this world, be kind.",
  "No beauty shines brighter than that of a good heart.",
  "Every time you smile at someone, it is an act of love, a gift to that person, a beautiful thing.",
  "Always help someone. You might be the only one who does.",
  "Do small things with great love.",
  "When you have the choice to be right or to be kind, choose kind.",
  "You can accomplish by kindness what you cannot by force.",
  "Kindness is a passport that opens doors and fashions friends.",
  "Kind hearts are the gardens, kind thoughts are the roots, kind words are the blossoms, kind deeds are the fruits.",
  "What you give, you get. What you see in others exists in you.",
  "Kindness is choosing to acknowledge and celebrate the goodness in others.",
  "To err on the side of kindness is seldom an error.",
];

final List<String> kindnessImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled kindness and compassion quotes with random images.
final List<QuoteItem> kindnessQuotes = getShuffledQuotes(
  kindnessQuotesRaw,
  kindnessImages,
);
