import '../quotes_randomizer.dart';

/// **Knowledge & Education Quotes & Images**

final List<String> knowledgeQuotesRaw = [
  "An investment in knowledge pays the best interest.",
  "Education is the most powerful weapon which you can use to change the world.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "Knowledge is power. Information is liberating. Education is the premise of progress, in every society, in every family.",
  "The only true wisdom is in knowing you know nothing.",
  "Education is not the filling of a pail, but the lighting of a fire.",
  "Develop a passion for learning. If you do, you will never cease to grow.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "A person who won’t read has no advantage over one who can’t read.",
  "Education is the key to unlocking the world, a passport to freedom.",
  "The expert in anything was once a beginner.",
  "Knowledge speaks, but wisdom listens.",
  "Learning is a treasure that will follow its owner everywhere.",
  "Education is not preparation for life; education is life itself.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "The roots of education are bitter, but the fruit is sweet.",
  "A well-educated mind will always have more questions than answers.",
  "To acquire knowledge, one must study; but to acquire wisdom, one must observe.",
  "Success is not just about making money. It’s about making a difference.",
  "You are always a student, never a master. You have to keep moving forward.",
  "Change is the end result of all true learning.",
  "A room without books is like a body without a soul.",
  "Education is not about memorizing facts; it’s about understanding concepts.",
  "Curiosity is the wick in the candle of learning.",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
  "Education is the foundation upon which we build our future.",
  "You don’t have to be great to start, but you have to start to be great.",
  "He who opens a school door, closes a prison.",
  "Do not train a child to learn by force or harshness, but direct them to it by what amuses their minds.",
  "A teacher affects eternity; he can never tell where his influence stops.",
  "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.",
  "Education’s purpose is to replace an empty mind with an open one.",
  "Self-education is, I firmly believe, the only kind of education there is.",
  "Every student can learn, just not on the same day, or the same way.",
  "Knowledge will bring you the opportunity to make a difference.",
  "The purpose of education is to make minds, not careers.",
  "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
  "The more I read, the more I acquire, the more certain I am that I know nothing.",
  "The whole purpose of education is to turn mirrors into windows.",
  "All knowledge is connected to all other knowledge. The fun is in making the connections.",
  "Education begins the gentleman, but reading, good company, and reflection must finish him.",
  "Never stop learning, because life never stops teaching.",
  "Education is learning what you didn’t even know you didn’t know.",
  "Knowledge is like a garden; if it is not cultivated, it cannot be harvested.",
  "The beautiful thing about education is that it creates endless possibilities.",
  "Education breeds confidence. Confidence breeds hope. Hope breeds peace.",
  "Not all classrooms have four walls.",
  "An educated mind is able to entertain a thought without accepting it.",
  "There is no wealth like knowledge, and no poverty like ignorance.",
  "A good education is a foundation for a better future.",
  "Knowledge is of no value unless you put it into practice.",
  "Education is the ability to listen to almost anything without losing your temper or your self-confidence.",
  "When you know better, you do better.",
  "In learning, you will teach, and in teaching, you will learn.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "Learning never exhausts the mind.",
  "Without knowledge, action is useless, and knowledge without action is futile.",
  "Your education is a dress rehearsal for a life that is yours to lead.",
  "Wisdom begins in wonder.",
  "A society grows great when old men plant trees whose shade they know they shall never sit in.",
  "The educated differ from the uneducated as much as the living from the dead.",
  "Education is not just about earning a degree; it’s about developing intelligence and character.",
  "The greatest gift you can give someone is the chance to learn.",
];

final List<String> knowledgeImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

final List<QuoteItem> knowledgeQuotes = getShuffledQuotes(
  knowledgeQuotesRaw,
  knowledgeImages,
);
