import '../quotes_randomizer.dart';

/// **Motivation for Hard Work Quotes & Images**
final List<String> motivationQuotesRaw = [
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.",
  "The only place where success comes before work is in the dictionary.",
  "Opportunities are usually disguised as hard work, so most people don’t recognize them.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "I’m a greater believer in luck, and I find the harder I work the more I have of it.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Dreams don’t work unless you do.",
  "Work like there is someone working 24 hours a day to take it away from you.",
  "Effort only fully releases its reward after a person refuses to quit.",
  "Without hustle, talent will only carry you so far.",
  "The future depends on what you do today.",
  "The harder the battle, the sweeter the victory.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Discipline is the bridge between goals and accomplishment.",
  "A dream does not become reality through magic; it takes sweat, determination, and hard work.",
  "If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Do what you love and success will follow.",
  "The key to success is to focus on goals, not obstacles.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Winners embrace hard work. They love the discipline of it, the trade-off they’re making to win.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don't limit your challenges. Challenge your limits.",
  "Hard work pays off. The harder you work, the more people will notice.",
  "A little progress each day adds up to big results.",
  "Push yourself, because no one else is going to do it for you.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Do what you have to do until you can do what you want to do.",
  "Stay humble. Work hard. Be kind.",
  "Success usually comes to those who are too busy to be looking for it.",
  "If you work on something a little bit every day, you end up with something massive.",
  "Discipline is choosing between what you want now and what you want most.",
  "Genius is 1% inspiration and 99% perspiration.",
  "Work hard in silence; let success make the noise.",
  "Set your goals high and don’t stop till you get there.",
  "Action is the foundational key to all success.",
  "If something stands between you and your success, move it.",
  "The difference between who you are and who you want to be is what you do.",
  "Quality means doing it right when no one is looking.",
  "If you cannot do great things, do small things in a great way.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "Dream big. Start small. Act now.",
  "Great things come from hard work and perseverance.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Your talent determines what you can do. Your motivation determines how much you’re willing to do. Your attitude determines how well you do it.",
  "Hard work keeps the wrinkles out of the mind and spirit.",
  "Small daily improvements over time lead to stunning results.",
  "Hustle until your haters ask if you're hiring.",
  "Be so good they can’t ignore you.",
];

final List<String> motivationImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled motivation quotes with random images.
final List<QuoteItem> motivationQuotes = getShuffledQuotes(
  motivationQuotesRaw,
  motivationImages,
);
