import '../quotes_randomizer.dart';

/// **Living in the Present Quotes & Images**
final List<String> presentQuotesRaw = [
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Be where you are; otherwise, you will miss your life.",
  "The present moment is the only time over which we have dominion.",
  "Realize deeply that the present moment is all you ever have.",
  "Yesterday is history. Tomorrow is a mystery. Today is a gift. That’s why it’s called the present.",
  "Happiness is not something you postpone for the future; it is something you design for the present.",
  "Don’t let the past steal your present.",
  "Live in the present, launch yourself on every wave, find eternity in each moment.",
  "You cannot start the next chapter of your life if you keep re-reading the last one.",
  "The past has no power over the present moment.",
  "Your power is in the present moment. Don’t waste it dwelling on the past or worrying about the future.",
  "Wherever you are, be all there.",
  "Life is available only in the present moment.",
  "Stop waiting for Friday, for summer, for someone to fall in love with you. Happiness is achieved when you stop waiting for it and make the most of the moment you are in now.",
  "The best way to prepare for the future is to take care of the present moment.",
  "Now is the only time we have, and the only time we have any control over.",
  "Don’t rush through life. Savor the moments as they come.",
  "Today is life—the only life you are sure of.",
  "Every moment is a fresh beginning.",
  "Live for today, plan for tomorrow, but never forget to enjoy the present moment.",
  "The secret of health for both mind and body is to live in the present moment wisely and earnestly.",
  "When you try to control everything, you enjoy nothing. Sometimes you just need to relax, breathe, let go, and live in the moment.",
  "The best present you can give yourself is being fully present.",
  "Don’t let yesterday take up too much of today.",
  "Live in the sunshine, swim in the sea, drink the wild air.",
  "Mindfulness isn’t difficult, we just need to remember to do it.",
  "Do what makes your soul shine today.",
  "Be present in all things and thankful for all things.",
  "Worry does not empty tomorrow of its sorrow; it empties today of its strength.",
  "Live in the moment and make it so beautiful that it will be worth remembering.",
  "Enjoy the little things in life, for one day you may look back and realize they were the big things.",
  "Don’t count the days, make the days count.",
  "Each morning we are born again. What we do today is what matters most.",
  "Sometimes you will never know the value of a moment until it becomes a memory.",
  "Stop and smell the roses.",
  "Life is short, and if we enjoy every moment of every day, we will be happy no matter what happens or what changes along the way.",
  "Live each moment as if it were your last.",
  "If you want to be happy, do not dwell in the past, do not worry about the future, focus on living fully in the present.",
  "The ability to be in the present moment is a major component of mental wellness.",
  "Nothing is worth more than this day.",
  "Take a deep breath and just enjoy your life.",
  "Every day is a new beginning. Take a deep breath, smile, and start again.",
  "Live today. Not yesterday. Not tomorrow. Just today.",
  "You are exactly where you need to be.",
  "Whatever the present moment contains, accept it as if you had chosen it.",
  "The here and now is all we have, and if we play it right, it’s all we’ll need.",
  "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
  "Surrender to what is. Let go of what was. Have faith in what will be.",
  "You don’t have to see the whole staircase, just take the first step.",
  "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.",
  "The best time for new beginnings is now.",
  "All you have is this moment. Make it count.",
  "Make the most of today. Time doesn’t wait.",
  "Nothing ever happened in the past. It happened in the Now.",
  "Presence is more than just being there.",
  "Take life one day at a time and make every day better than the last.",
  "Let go of the past and go for the future. Live the life you imagined.",
  "Don’t wait for everything to be perfect before you decide to enjoy your life.",
  "Be present in the moment and create memories worth remembering.",
  "The past is behind, learn from it. The future is ahead, prepare for it. The present is here, live it.",
  "The key to happiness is letting each situation be what it is instead of what you think it should be.",
  "Learn to enjoy every minute of your life. Be happy now.",
  "You can’t go back and change the beginning, but you can start where you are and change the ending.",
  "Sometimes the most productive thing you can do is relax and enjoy the moment.",
  "Don’t let life pass you by while you’re waiting for the perfect moment.",
  "Joy is found not in finishing an activity but in doing it.",
  "Living in the moment brings you a sense of reverence for all of life’s blessings.",
];

final List<String> presentImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled living in the present quotes with random images.
final List<QuoteItem> presentQuotes = getShuffledQuotes(
  presentQuotesRaw,
  presentImages,
);
