import '../quotes_randomizer.dart';

/// **Finding Purpose Quotes & Images**
final List<String> purposeQuotesRaw = [
  "Your purpose in life is to find your purpose and give your whole heart and soul to it.",
  "The meaning of life is to find your gift. The purpose of life is to give it away.",
  "Find out who you are and do it on purpose.",
  "Act as if what you do makes a difference. It does.",
  "Your work is to discover your world and then with all your heart give yourself to it.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "When you walk in purpose, you collide with destiny.",
  "Success demands singleness of purpose.",
  "Purpose is the reason you journey. Passion is the fire that lights your way.",
  "Knowing your purpose gives meaning to your life.",
  "A life without purpose is like a ship without a rudder.",
  "Your purpose is not just a job or a title, it is your impact on the world.",
  "Follow your passion. It will lead you to your purpose.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Don’t ask yourself what the world needs. Ask yourself what makes you come alive, and go do that.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "The purpose of life is to contribute in some way to making things better.",
  "To live is the rarest thing in the world. Most people just exist.",
  "Efforts and courage are not enough without purpose and direction.",
  "You were born with a purpose. You were born to make an impact.",
  "Clarity about your purpose helps you make better decisions.",
  "Find your purpose, and then throw yourself into it with everything you have.",
  "Each of us is here for a reason. Discover yours and live it fully.",
  "Great minds have purposes; others have wishes.",
  "Your passion is for you, but your purpose is for others.",
  "The greatest tragedy is not death, but life without purpose.",
  "Live with purpose. Walk with confidence. Work with passion.",
  "Your purpose is where your deep gladness and the world’s hunger meet.",
  "Your purpose is your legacy—what you leave behind.",
  "The key to a fulfilling life is finding your unique purpose and embracing it.",
  "Find what brings you joy and do more of it.",
  "A strong sense of purpose fuels resilience and perseverance.",
  "Your life has meaning, and your actions shape the world around you.",
  "Dare to pursue the path that leads to your true purpose.",
  "Stop searching for purpose—start creating it.",
  "Your purpose is not a destination; it’s a journey.",
  "Discovering your purpose gives direction to your dreams.",
  "When you align with your purpose, you attract the right opportunities.",
  "The purpose of our lives is to be happy and to help others find happiness too.",
  "The path to purpose is paved with curiosity, courage, and commitment.",
  "Find a way to serve, and you’ll find a way to thrive.",
  "A meaningful life is built on purpose, passion, and perseverance.",
  "When you find your purpose, you find your power.",
  "Don’t just exist—live with purpose and intention.",
  "Living on purpose brings fulfillment, not just success.",
  "Finding purpose is not about finding a job, it’s about making a difference.",
  "Your purpose should be bigger than your fears.",
  "True purpose isn’t found in comfort but in challenge.",
  "Your heart knows the way. Run in that direction.",
  "Live life as if everything is rigged in your favor.",
  "Purpose makes the impossible possible.",
  "Don’t wait for purpose to find you—chase it down.",
  "Find your spark and set the world on fire.",
  "The world needs what you have to offer—live your purpose.",
  "A purpose-driven life is a powerful life.",
  "Be the reason someone finds hope today.",
  "A fulfilled life is a life lived with purpose and passion.",
  "The secret to success is having a clear purpose and unwavering dedication.",
  "Life isn’t about finding yourself; it’s about creating yourself.",
  "Your impact is your purpose—embrace it.",
  "Live with intention, walk with direction, and act with purpose.",
  "Every day is a step toward fulfilling your purpose—take it boldly.",
  "You are here for a reason. Find it, embrace it, and live it.",
];

final List<String> purposeImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled purpose quotes with random images.
final List<QuoteItem> purposeQuotes = getShuffledQuotes(
  purposeQuotesRaw,
  purposeImages,
);
