import '../quotes_randomizer.dart';

/// **Self-Love and Confidence Quotes & Images**
final List<String> selfloveQuotesRaw = [
  "Love yourself first, and everything else falls into line.",
  "Self-love is not selfish; you cannot truly love another until you know how to love yourself.",
  "Confidence is not ‘They will like me.’ Confidence is ‘I’ll be fine if they don’t.’",
  "Be yourself; everyone else is already taken.",
  "You are enough just as you are.",
  "Owning our story and loving ourselves through that process is the bravest thing we’ll ever do.",
  "Talk to yourself like someone you love.",
  "Beauty begins the moment you decide to be yourself.",
  "You are stronger than you think, braver than you believe, and more loved than you know.",
  "Happiness is an inside job. Don’t assign anyone else that much power over your life.",
  "The only approval you need is your own.",
  "The more you love yourself, the less nonsense you’ll tolerate.",
  "Self-love is the best kind of love.",
  "You were born to stand out, not to fit in.",
  "The real difficulty is to overcome how you think about yourself.",
  "You owe yourself the love that you so freely give to others.",
  "Doubt kills more dreams than failure ever will.",
  "Be your own biggest fan.",
  "Be proud of who you are, and not ashamed of how someone else sees you.",
  "To love oneself is the beginning of a lifelong romance.",
  "You are not your mistakes; they are what you did, not who you are.",
  "The moment you start acting like life is a blessing, it starts feeling like one.",
  "Your self-worth is determined by you. You don’t have to depend on someone telling you who you are.",
  "Don’t be afraid to sparkle a little brighter.",
  "You deserve to take up space.",
  "Surround yourself with people who make you feel like sunshine.",
  "Confidence is silent. Insecurities are loud.",
  "Be yourself unapologetically.",
  "You are entirely up to you.",
  "Stop waiting for permission to be yourself.",
  "If you are always trying to be normal, you will never know how amazing you can be.",
  "Your vibe attracts your tribe.",
  "Don’t compare your chapter one to someone else’s chapter twenty.",
  "Do not tame the wolf inside you just because you’ve met someone who doesn’t have the courage to handle you.",
  "Never allow someone to be your priority while allowing yourself to be their option.",
  "You don’t need to be accepted by others. You need to accept yourself.",
  "Self-care is giving the world the best of you instead of what’s left of you.",
  "You don’t find self-love. You build it.",
  "You were given this life because you are strong enough to live it.",
  "Nothing is more attractive than confidence, once you see your own beauty, so will everyone else.",
  "Do what makes your soul shine.",
  "Life is too short to spend it at war with yourself.",
  "Your relationship with yourself sets the tone for every other relationship you have.",
  "Confidence is sexy. Own it.",
  "Be so completely yourself that everyone else feels safe to be themselves too.",
  "Self-respect is the greatest gift you can give yourself.",
  "Don’t let anyone dull your sparkle.",
  "Your worth is not measured by others’ opinions of you.",
  "The most beautiful thing you can wear is confidence.",
  "You are magic. Don’t ever apologize for the fire in you.",
  "Learn to rest, not to quit.",
  "Self-love is the foundation of all love.",
  "Don’t be afraid of being different. Be afraid of being the same as everyone else.",
  "Invest in yourself; it pays the best interest.",
  "You don’t have to be perfect to be amazing.",
  "It’s not who you are that holds you back, it’s who you think you’re not.",
  "Dare to love yourself as if you were a rainbow with gold at both ends.",
  "Trust yourself. You know more than you think you do.",
  "Be your own kind of beautiful.",
  "Know your worth and then add tax.",
  "Confidence is not thinking you are better than anyone else, it’s realizing you have no reason to compare yourself to anyone else.",
  "Don’t underestimate yourself. You are capable of more than you think.",
  "You were never meant to be ordinary.",
  "Your dreams are valid. Take yourself seriously.",
  "Your potential is endless.",
  "Fall in love with taking care of yourself.",
  "Loving yourself is the greatest revolution.",
  "You can be a masterpiece and a work in progress at the same time.",
];

final List<String> selfloveImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled self-love and confidence quotes with random images.
final List<QuoteItem> selfloveQuotes = getShuffledQuotes(
  selfloveQuotesRaw,
  selfloveImages,
);
