import '../quotes_randomizer.dart';

/// **Workplace Ethics & Values Quotes & Images**
final List<String> workplaceQuotesRaw = [
  "Integrity is doing the right thing, even when no one is watching.",
  "Work hard in silence, let your success be your noise.",
  "Honesty is the cornerstone of workplace ethics.",
  "Ethics is knowing the difference between what you have a right to do and what is right to do.",
  "Quality means doing it right when no one is looking.",
  "Values are like fingerprints. Nobody’s are the same, but you leave them all over everything you do.",
  "Treat employees like they make a difference, and they will.",
  "Respect is how to treat everyone, not just those you want to impress.",
  "Do the right thing, even when it’s hard.",
  "A strong ethical culture is the backbone of a great organization.",
  "In matters of style, swim with the current; in matters of principle, stand like a rock.",
  "Honesty and transparency make you vulnerable. Be honest and transparent anyway.",
  "Do what is right, not what is easy nor what is popular.",
  "Success without integrity is failure.",
  "Great teams are built on trust, respect, and integrity.",
  "Responsibility equals accountability equals ownership. And a sense of ownership is the most powerful weapon a team or organization can have.",
  "Ethical behavior is doing the right thing when no one else is watching.",
  "Moral authority comes from following universal and timeless principles.",
  "Leadership is not about being in charge. It is about taking care of those in your charge.",
  "Hard work spotlights the character of people.",
  "Culture eats strategy for breakfast. Build a culture of ethics and values.",
  "Character is how you treat those who can do nothing for you.",
  "Fairness is not an attitude. It’s a professional skill that must be developed and exercised.",
  "Trust takes years to build, seconds to break, and forever to repair.",
  "A workplace without ethics is like a house without a foundation.",
  "Excellence is not an exception; it is a prevailing attitude.",
  "Workplace ethics start with small, consistent actions.",
  "Integrity is the seed for achievement. It is the principle that never fails.",
  "You don’t build a business; you build people, and then people build the business.",
  "Accountability breeds response-ability.",
  "When values, mission, and ethics are aligned, employees thrive.",
  "Real integrity is doing the right thing, knowing that nobody’s going to know whether you did it or not.",
  "The strength of a workplace is its ethical foundation.",
  "A company’s ethics are its most enduring competitive advantage.",
  "Your ethical behavior defines your professional reputation.",
  "The highest reward for a person’s toil is not what they get for it, but what they become by it.",
  "Integrity is choosing courage over comfort.",
  "Your work is a reflection of your character. Strive for excellence.",
  "The best way to predict the future is to create it with integrity.",
  "Success is measured by the impact of your integrity.",
  "True leadership is serving others with integrity and humility.",
  "A reputation of integrity is worth more than money.",
  "Without trust, nothing works in an organization.",
  "Small ethical choices shape the culture of a workplace.",
  "A workplace built on ethics and values fosters growth and success.",
  "Ethical work practices create sustainable success.",
  "Great leaders inspire ethical work environments.",
  "Transparency builds trust in every professional relationship.",
  "A good reputation is more valuable than money.",
  "Ethics and values define the soul of a company.",
  "If you tell the truth, you don’t have to remember anything.",
  "The right thing and the hard thing are often the same.",
  "Be ethical, even when no one is looking.",
  "Your ethics determine your worth in the professional world.",
  "Ethical behavior fosters a productive work culture.",
  "Leadership is not about titles; it’s about impact, influence, and inspiration.",
  "Choose what is right, not what is easy.",
  "Ethics + Hard Work = Long-Term Success.",
  "Doing good work means more than following procedures; it means putting your heart into it.",
  "Ethics is not a rulebook, it’s a way of life.",
  "Professionalism is knowing how to do it, when to do it, and doing it the right way.",
  "Honesty first, business second.",
  "Stand firm in your values, even when it’s tough.",
  "The ethical choice is always the right choice.",
  "Your values at work define your legacy.",
  "A workplace driven by values is a workplace that thrives.",
  "Stay true to your ethics, and success will follow.",
];

final List<String> workplaceImages = [
  "assets/images/quotes/bg/1.jpg",
  "assets/images/quotes/bg/2.jpg",
  "assets/images/quotes/bg/3.jpg",
  "assets/images/quotes/bg/4.jpg",
  "assets/images/quotes/bg/5.jpg",
  "assets/images/quotes/bg/6.jpg",
  "assets/images/quotes/bg/7.jpg",
  "assets/images/quotes/bg/8.jpg",
  "assets/images/quotes/bg/9.jpg",
  "assets/images/quotes/bg/10.jpg",
];

/// Generate the final list of shuffled workplace ethics and values quotes with random images.
final List<QuoteItem> workplaceQuotes = getShuffledQuotes(
  workplaceQuotesRaw,
  workplaceImages,
);
