import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> cultivatepositivityAffirmationRaw = [
  "I choose to focus on the good in every situation.",
  "Positivity flows through me effortlessly.",
  "I am grateful for all the blessings in my life.",
  "Happiness is a choice, and I choose it every day.",
  "I attract positive energy into my life.",
  "I am surrounded by love, joy, and abundance.",
  "Every challenge is an opportunity for growth.",
  "I radiate kindness, compassion, and positivity.",
  "I am resilient and strong in the face of adversity.",
  "I choose to see the bright side of every situation.",
  "My thoughts are filled with positivity and hope.",
  "I am worthy of happiness and success.",
  "I spread joy and positivity wherever I go.",
  "Every day is a new beginning filled with endless possibilities.",
  "I create a life filled with love and happiness.",
  "I trust that everything is working out for my highest good.",
  "I believe in the power of a positive mindset.",
  "I choose to let go of negativity and embrace positivity.",
  "My positive energy attracts amazing opportunities.",
  "I am grateful for the simple joys of life.",
  "I see the good in myself and others.",
  "I radiate confidence, positivity, and self-love.",
  "I choose to replace fear with hope and optimism.",
  "Every day is a fresh start full of opportunities.",
  "I trust that the universe is guiding me towards happiness.",
  "I am surrounded by positive and supportive people.",
  "I let go of negative thoughts and focus on the present.",
  "I am in control of my thoughts and emotions.",
  "I choose to embrace the beauty of life.",
  "I am grateful for every moment and every experience.",
  "My heart is filled with love and joy.",
  "I am at peace with myself and the world around me.",
  "I focus on solutions instead of problems.",
  "I have the power to create the life I desire.",
  "I am confident, strong, and full of positive energy.",
  "I attract happiness and abundance effortlessly.",
  "I choose to smile, even in difficult situations.",
  "I see the beauty in every day and every experience.",
  "I release what no longer serves me and embrace happiness.",
  "I trust that better things are coming my way.",
  "I am grateful for all the love and support in my life.",
  "My positive energy influences those around me.",
  "I am at peace with my past and excited for my future.",
  "I choose to be happy regardless of my circumstances.",
  "I am blessed with limitless opportunities for joy.",
  "I allow myself to enjoy life and have fun.",
  "I am a beacon of positivity and kindness.",
  "I choose thoughts that uplift and inspire me.",
  "I am always growing and improving.",
  "I embrace optimism in every situation.",
  "I welcome each day with gratitude and positivity.",
  "I choose to focus on what I can control.",
  "My positive mindset creates a fulfilling life.",
  "I let go of stress and welcome peace into my life.",
  "I am grateful for the lessons life teaches me.",
  "I deserve to be happy and successful.",
  "I choose love, kindness, and joy every day.",
  "I am open to the goodness life has to offer.",
  "I trust that everything is happening for my highest good.",
  "I embrace the journey of life with enthusiasm.",
  "I focus on progress, not perfection.",
  "I have the power to turn challenges into opportunities.",
  "I choose to cultivate an attitude of gratitude.",
  "I am capable of overcoming any obstacle.",
  "I appreciate the beauty that surrounds me.",
  "I am worthy of all the happiness that comes my way.",
  "My happiness is my responsibility.",
  "I choose to let go of worry and embrace peace.",
  "I wake up every morning with a positive mindset.",
  "I celebrate my achievements, big and small.",
  "I trust that everything is unfolding as it should.",
  "I spread love and kindness wherever I go.",
  "I attract joyful and uplifting experiences.",
  "My thoughts and actions create my reality.",
  "I am filled with boundless positive energy.",
  "I find joy in the little things.",
  "I radiate warmth, kindness, and happiness.",
  "I choose to live with an open heart and mind.",
  "I let go of fear and welcome positivity.",
  "Every day is an opportunity to be better and happier.",
  "I focus on what brings me joy and fulfillment.",
  "I trust in the process of life.",
  "I am grateful for every breath I take.",
  "I find happiness in the present moment.",
  "I choose to see the best in people.",
  "I surround myself with people who uplift me.",
  "My life is full of endless possibilities.",
  "I am a source of light and positivity.",
  "I appreciate all the good that life has to offer.",
  "I let go of negativity and embrace happiness.",
  "I celebrate my life and all the blessings in it.",
  "I believe in the power of positive thinking.",
  "I am strong, capable, and worthy of happiness.",
  "I choose to be hopeful and optimistic.",
  "I accept myself with love and kindness.",
  "I am deserving of love, joy, and abundance.",
  "I trust myself to make choices that bring happiness.",
  "I wake up each day with a grateful heart.",
  "I choose to find joy in every experience.",
  "I welcome new experiences with excitement and optimism.",
  "I believe that good things are always coming my way.",
  "I am open to the positive energy of the universe.",
  "I fill my mind with thoughts that uplift me.",
  "I see setbacks as opportunities for growth.",
  "I embrace the flow of life with grace and gratitude.",
  "I am grateful for all the wonderful things in my life.",
  "I allow positivity to flow through me in every moment.",
  "I focus on the good in every person and situation.",
  "I welcome happiness and success into my life.",
  "I am grateful for today and all it has to offer.",
  "I radiate confidence, positivity, and inner peace.",
  "I create a joyful and fulfilling life.",
  "I let go of fear and step into happiness.",
  "I am capable of turning my dreams into reality.",
  "I trust that my life is unfolding in beautiful ways.",
  "I attract love, happiness, and success effortlessly.",
  "I am full of positive energy and enthusiasm.",
  "I am deeply grateful for the abundance in my life.",
  "I choose to enjoy the present moment.",
  "I am strong enough to handle anything life brings.",
  "I believe that everything happens for a reason.",
  "I choose to let my light shine brightly.",
  "I am at peace with myself and my journey.",
  "I choose to see the silver lining in every situation.",
  "My heart is filled with love, peace, and positivity.",
  "I deserve all the happiness and success in the world.",
  "I choose joy in every moment.",
  "Positivity is my natural state of mind.",
  "I focus on what brings me happiness and peace.",
  "My heart is open to love and kindness.",
  "I create a life filled with joy and gratitude.",
  "I radiate confidence and positive energy.",
  "Happiness flows through me effortlessly.",
  "I trust that everything is working out for my highest good.",
  "I am grateful for the beauty in my life.",
  "Every challenge is an opportunity to grow.",
  "I embrace each day with a positive attitude.",
  "I choose to be optimistic in all situations.",
  "I am surrounded by love and positivity.",
  "I focus on what I can control and let go of the rest.",
  "I see the good in every experience.",
  "I welcome happiness into my life.",
  "My mind is filled with uplifting thoughts.",
  "I attract positive experiences effortlessly.",
  "I choose to see the bright side of life.",
  "I spread kindness and joy wherever I go.",
  "My thoughts are powerful, and I choose them wisely.",
  "I am resilient and capable of overcoming any challenge.",
  "I choose to let go of negativity.",
  "I attract happiness and abundance effortlessly.",
  "I am grateful for all the small joys in life.",
  "I trust that the universe supports my happiness.",
  "I deserve happiness and success.",
  "I release stress and welcome peace into my heart.",
  "I focus on solutions, not problems.",
  "I let go of worry and embrace confidence.",
  "I appreciate the beauty in the present moment.",
  "I am open to receiving love and happiness.",
  "I am surrounded by positive and uplifting energy.",
  "I choose to be happy, no matter what happens.",
  "I am grateful for every lesson life teaches me.",
  "I believe in my ability to create happiness.",
  "My life is full of blessings, big and small.",
  "I focus on the good and let go of the rest.",
  "I welcome positive energy into my day.",
  "I see every setback as a stepping stone to success.",
  "I am in control of my emotions and thoughts.",
  "I choose peace over worry.",
  "I fill my mind with hope and positivity.",
  "Every day brings new reasons to be grateful.",
  "I let go of fear and embrace excitement.",
  "I radiate love, light, and positivity.",
  "My happiness is contagious and spreads to others.",
  "I see opportunities in every challenge.",
  "I am becoming the best version of myself every day.",
  "I allow positivity to guide my actions.",
  "I attract happiness by being happy.",
  "I believe in the power of a positive mindset.",
  "I create a ripple effect of joy in the world.",
  "I welcome laughter and fun into my life.",
  "I focus on what makes me feel good.",
  "I choose to live with enthusiasm and gratitude.",
  "I celebrate my progress, no matter how small.",
  "I choose to speak uplifting and encouraging words.",
  "I am a source of light and inspiration to others.",
  "I let go of what I can't change and focus on what I can.",
  "I choose to be kind to myself and others.",
  "I welcome all the good things coming my way.",
  "I allow myself to feel happy and free.",
  "I see beauty in the little things around me.",
  "I surround myself with uplifting and supportive people.",
  "I let go of doubts and trust in my journey.",
  "I believe in my ability to create a fulfilling life.",
  "I replace negative thoughts with positive ones.",
  "I wake up each day excited for new opportunities.",
  "I find joy in the simple moments of life.",
  "I trust that everything is happening for my benefit.",
  "I release past worries and focus on today.",
  "I am thankful for the love in my life.",
  "I choose to see the goodness in myself and others.",
  "I am capable of turning my dreams into reality.",
  "I fill my life with positivity and laughter.",
  "I welcome each day with gratitude and enthusiasm.",
  "I see setbacks as opportunities for growth.",
  "I appreciate every moment and make the most of it.",
  "I am worthy of all the joy life has to offer.",
  "I radiate positivity and attract good energy.",
  "My heart is filled with gratitude and love.",
  "I focus on what makes me feel happy and at peace.",
  "I choose to let go of past regrets and move forward.",
  "I embrace the beauty of life with open arms.",
  "I welcome abundance, happiness, and success into my life.",
  "I trust that things are always working out for me.",
  "I allow myself to shine and inspire others.",
  "I am in harmony with myself and the world around me.",
  "I attract wonderful experiences by being positive.",
  "I choose to be present and enjoy each moment.",
  "I embrace positivity as my way of life.",
  "I have the power to create happiness from within.",
  "I choose to see life with a hopeful perspective.",
  "I let go of fear and embrace love and confidence.",
  "I am constantly growing and improving.",
  "I am grateful for today and all that it brings.",
  "I trust in the magic of new beginnings.",
  "I create joy in my life through my thoughts and actions.",
  "I let go of stress and welcome inner peace.",
  "I choose to believe in the goodness of life.",
  "I am strong, confident, and full of joy.",
];

final List<String> cultivatepositivityImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> cultivatepositivityAffirmation =
    getShuffledaffirmations(
      cultivatepositivityAffirmationRaw,
      cultivatepositivityImages,
    );
