import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> dailygratitudeAffirmationRaw = [
  "I am grateful for this new day and the opportunities it brings.",
  "I appreciate all the love and kindness in my life.",
  "I am thankful for my health and well-being.",
  "I find joy in the little things every day.",
  "I am grateful for the challenges that help me grow.",
  "I choose to focus on the abundance in my life.",
  "I am thankful for the people who support and uplift me.",
  "I appreciate the beauty of nature around me.",
  "I am grateful for the lessons I have learned.",
  "I am thankful for the ability to learn and improve.",
  "I find gratitude in every experience, good or bad.",
  "I am blessed with everything I need.",
  "I appreciate the love and kindness I receive daily.",
  "I am grateful for my past, present, and future.",
  "I choose to see the good in every situation.",
  "I am thankful for the simple moments that bring me happiness.",
  "I appreciate the air I breathe and the life I live.",
  "I am grateful for the strength within me.",
  "I am thankful for the opportunities that come my way.",
  "I find gratitude in every person I meet.",
  "I cherish the relationships in my life.",
  "I am grateful for the food that nourishes my body.",
  "I appreciate the roof over my head and the comfort it provides.",
  "I am thankful for my ability to grow and change.",
  "I am blessed with the ability to make a difference.",
  "I appreciate the love I share with others.",
  "I am grateful for moments of peace and relaxation.",
  "I am thankful for my resilience and determination.",
  "I see each day as a gift filled with possibilities.",
  "I am grateful for the ability to express myself freely.",
  "I appreciate the support and encouragement I receive.",
  "I am thankful for laughter and joy in my life.",
  "I embrace each moment with gratitude.",
  "I am grateful for the experiences that shape me.",
  "I appreciate the kindness of strangers and friends alike.",
  "I am thankful for the lessons that make me stronger.",
  "I choose to live with an open and grateful heart.",
  "I am blessed with a life full of abundance.",
  "I am grateful for my ability to love and be loved.",
  "I appreciate the opportunities that help me grow.",
  "I am thankful for the power of gratitude in my life.",
  "I am grateful for my unique journey.",
  "I appreciate the wisdom that comes with experience.",
  "I am thankful for today’s fresh start.",
  "I am grateful for my ability to see the good in others.",
  "I appreciate the small blessings that make life special.",
  "I am thankful for my ability to overcome difficulties.",
  "I choose to focus on positivity and gratitude.",
  "I am grateful for the chance to make a difference.",
  "I appreciate the beauty in every moment.",
  "I am thankful for the love that surrounds me.",
  "I embrace each day with a grateful heart.",
  "I am grateful for my dreams and the courage to pursue them.",
  "I appreciate my ability to give and receive kindness.",
  "I am thankful for the warmth of the sun and the cool breeze.",
  "I see gratitude as the key to happiness.",
  "I am grateful for my strength and perseverance.",
  "I choose to be thankful for every blessing.",
  "I am grateful for the opportunity to create a meaningful life.",
  "I appreciate every new beginning.",
  "I am thankful for the ability to rest and recharge.",
  "I am grateful for my heart’s ability to heal.",
  "I embrace the present moment with gratitude.",
  "I am thankful for the music that uplifts my soul.",
  "I appreciate the power of a smile and kind words.",
  "I am grateful for the comfort of home.",
  "I choose to see the best in every situation.",
  "I am grateful for my body and all it does for me.",
  "I appreciate the peace that comes with gratitude.",
  "I am thankful for the ability to learn from my mistakes.",
  "I embrace the abundance in my life with gratitude.",
  "I am grateful for the ability to forgive and move forward.",
  "I appreciate the beauty in diversity and uniqueness.",
  "I am thankful for the love that flows into my life.",
  "I choose to be present and grateful in every moment.",
  "I am grateful for the chance to inspire and uplift others.",
  "I appreciate my journey and trust in its direction.",
  "I am thankful for all the blessings that continue to unfold.",
  "I find joy in expressing gratitude every day.",
  "I am grateful for the infinite possibilities of life.",
  "I appreciate the strength that gratitude gives me.",
  "I am thankful for today and all it brings.",
  "I choose to fill my heart with gratitude and love.",
  "I am grateful for the peace that gratitude brings.",
  "I appreciate every lesson and challenge I have faced.",
  "I am thankful for the unconditional love in my life.",
  "I embrace gratitude as a way of life.",
  "I am grateful for the courage to be myself.",
  "I appreciate the magic in ordinary moments.",
  "I am thankful for the opportunities to create a better future.",
  "I choose to be grateful for all that I have.",
  "I am grateful for the kindness and generosity around me.",
  "I appreciate the time I have to enjoy life’s wonders.",
  "I am thankful for my dreams and the journey ahead.",
  "I embrace each new day with an open heart.",
  "I am grateful for my creativity and inspiration.",
  "I appreciate the balance in my life.",
  "I am thankful for my family and friends.",
  "I am grateful for the love I give and receive.",
  "I choose to focus on gratitude rather than lack.",
  "I am thankful for my health and vitality.",
  "I appreciate the gift of each breath I take.",
  "I am grateful for the lessons of patience and persistence.",
  "I embrace gratitude as my daily practice.",
  "I am thankful for the power of love in my life.",
  "I choose to radiate gratitude and positivity.",
  "I am grateful for every sunrise and sunset.",
  "I appreciate the chance to live fully each day.",
  "I am thankful for the abundance of love in my life.",
  "I find gratitude in my journey, no matter where it leads.",
  "I am grateful for the hope that fills my heart.",
  "I appreciate every step forward I take.",
  "I am thankful for the strength to face each day.",
  "I choose gratitude as my mindset.",
  "I am grateful for the endless possibilities before me.",
  "I embrace the joy of living in gratitude.",
  "I am thankful for the gift of today.",
  "I am grateful for all that I am and all I will become.",
  "I am grateful for the gift of this new day.",
  "I appreciate every breath I take.",
  "I find joy in the little things around me.",
  "I am thankful for the love in my life.",
  "I embrace each moment with a heart full of gratitude.",
  "I am grateful for the lessons I have learned.",
  "I appreciate the kindness I receive and give.",
  "I am thankful for the support of my loved ones.",
  "I see the beauty in every situation.",
  "I am grateful for the food that nourishes me.",
  "I choose to focus on abundance and blessings.",
  "I am thankful for the opportunities that come my way.",
  "I appreciate the warmth of the sun and the coolness of the breeze.",
  "I am grateful for my body and its strength.",
  "I welcome this day with gratitude and optimism.",
  "I am thankful for the laughter that brightens my life.",
  "I appreciate the journey I am on.",
  "I am grateful for the peace in my heart.",
  "I embrace the present moment with gratitude.",
  "I am thankful for my dreams and the chance to pursue them.",
  "I appreciate the beauty of nature all around me.",
  "I am grateful for the lessons that challenges bring.",
  "I choose gratitude as my daily practice.",
  "I am thankful for the gift of learning and growth.",
  "I appreciate the comfort of my home.",
  "I am grateful for the love and friendships in my life.",
  "I see each challenge as an opportunity to grow.",
  "I am thankful for the kindness I experience daily.",
  "I appreciate the wisdom I gain from each experience.",
  "I am grateful for the simple joys in life.",
  "I welcome today with an open heart.",
  "I am thankful for my inner strength and resilience.",
  "I appreciate the love I share with others.",
  "I choose to see the blessings in every moment.",
  "I am grateful for the freedom to express myself.",
  "I appreciate my past, present, and future.",
  "I am thankful for the support that surrounds me.",
  "I find gratitude in both big and small moments.",
  "I embrace each day with a grateful heart.",
  "I am thankful for the new experiences that shape me.",
  "I appreciate the good in people and the world.",
  "I am grateful for the laughter and happiness in my life.",
  "I choose to be thankful for what I have.",
  "I am grateful for the peaceful moments I experience.",
  "I appreciate the opportunities that help me grow.",
  "I am thankful for the strength to overcome obstacles.",
  "I find joy in expressing gratitude.",
  "I am grateful for the comfort and safety in my life.",
  "I appreciate my ability to love and be loved.",
  "I am thankful for the music and art that inspire me.",
  "I see gratitude as a way of life.",
  "I embrace every challenge with a grateful heart.",
  "I am grateful for the beauty in each new day.",
  "I appreciate the laughter shared with friends and family.",
  "I am thankful for my unique talents and skills.",
  "I choose to live with an attitude of gratitude.",
  "I am grateful for my ability to learn and improve.",
  "I appreciate the power of a kind word and a smile.",
  "I am thankful for the memories that bring me happiness.",
  "I am grateful for the chance to make a difference.",
  "I choose to see the best in every situation.",
  "I am thankful for the endless possibilities before me.",
  "I appreciate the quiet moments that bring clarity.",
  "I am grateful for the lessons of patience and persistence.",
  "I welcome each new day with appreciation.",
  "I am thankful for the love and laughter in my life.",
  "I appreciate the positive energy that surrounds me.",
  "I am grateful for the kindness of others.",
  "I embrace gratitude as my daily practice.",
  "I am thankful for the fresh start each morning brings.",
  "I appreciate the gift of time and how I use it.",
  "I am grateful for my ability to create and inspire.",
  "I choose to be mindful and thankful in each moment.",
  "I am grateful for the happiness I find in simple things.",
  "I appreciate the guidance I receive from life’s experiences.",
  "I am thankful for the peace I create within myself.",
  "I welcome each day with love and gratitude.",
  "I am grateful for the journey of self-discovery.",
  "I appreciate the wonderful people in my life.",
  "I am thankful for the hope that fills my heart.",
];

final List<String> dailygratitudeImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> dailygratitudeAffirmation = getShuffledaffirmations(
  dailygratitudeAffirmationRaw,
  dailygratitudeImages,
);
