import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> embracepresentAffirmationRaw = [
  "I fully embrace the present moment.",
  "I am exactly where I need to be right now.",
  "I release the need to control everything and trust the process.",
  "I find joy in the little moments of today.",
  "I am grateful for the beauty of this moment.",
  "I let go of worries about the future and focus on now.",
  "I accept and appreciate the present as it is.",
  "I choose to live fully in the here and now.",
  "I inhale peace and exhale worry.",
  "Every breath I take grounds me in the present.",
  "I allow myself to simply be.",
  "I am free from the weight of yesterday.",
  "I let go of regrets and embrace what is.",
  "I choose to focus on the positives in my present.",
  "I release distractions and immerse myself in the now.",
  "I find joy in the simple things in life.",
  "I am fully present in every conversation.",
  "I cherish the experiences that today brings.",
  "I am aware of the beauty around me.",
  "I appreciate this moment, knowing it will never come again.",
  "I am at peace with where I am right now.",
  "I embrace life as it unfolds before me.",
  "I am grateful for the lessons of today.",
  "I trust that I am right where I need to be.",
  "I honor this moment with my full presence.",
  "I let go of expectations and enjoy the flow of life.",
  "I am exactly who I am meant to be at this moment.",
  "I allow myself to experience this moment without judgment.",
  "I am in tune with my breath, bringing me back to now.",
  "I am deeply connected to this moment.",
  "I let go of stress and embrace peace.",
  "I allow joy to flow freely in this moment.",
  "I am present in my own life.",
  "I find calm in simply being here.",
  "I accept each moment as it comes.",
  "I trust the timing of my life.",
  "I am grateful for all that I have right now.",
  "I embrace the beauty of the present.",
  "I focus on what I can control, which is this moment.",
  "I am open to the magic of now.",
  "I let go of the need to rush and savor the present.",
  "I am mindful of each step I take today.",
  "I feel the warmth of the present moment.",
  "I allow myself to be at peace with the now.",
  "I honor my journey by being present in it.",
  "I focus on today rather than worrying about tomorrow.",
  "I welcome each experience as an opportunity to grow.",
  "I am grounded in the now.",
  "I allow myself to rest in the present.",
  "I release all distractions and embrace clarity.",
  "I accept life as it comes and find peace in it.",
  "I trust that I am right where I need to be.",
  "I am mindful of the beauty in each moment.",
  "I focus on being, not just doing.",
  "I choose to live with awareness and gratitude.",
  "I let go of overthinking and embrace simplicity.",
  "I breathe deeply and center myself in the now.",
  "I see the gift that is this present moment.",
  "I am thankful for the now, knowing it is enough.",
  "I listen to life as it unfolds naturally.",
  "I allow myself to move at my own pace.",
  "I find joy in the ordinary moments of today.",
  "I choose happiness in the present moment.",
  "I savor the sensations of this moment.",
  "I trust life’s timing and enjoy where I am now.",
  "I am patient with myself and my journey.",
  "I embrace today with open arms.",
  "I appreciate the now without comparison to the past.",
  "I am aligned with the rhythm of life.",
  "I feel peace knowing I am fully here.",
  "I welcome life as it comes with gratitude.",
  "I release anxiety and embrace stillness.",
  "I am fully immersed in the present experience.",
  "I am calm, centered, and at peace.",
  "I find serenity in the now.",
  "I observe my thoughts without judgment.",
  "I let go of regrets and welcome what is.",
  "I choose to be happy in this moment.",
  "I release attachment to the past and future.",
  "I trust that all I need is already within me.",
  "I embrace the now with love and gratitude.",
  "I acknowledge and celebrate my present progress.",
  "I accept the unpredictability of life with grace.",
  "I am in harmony with this present moment.",
  "I bring my full attention to what I am doing.",
  "I focus on what truly matters now.",
  "I find joy in the process, not just the outcome.",
  "I embrace uncertainty and trust in life.",
  "I choose to respond to life with peace and patience.",
  "I acknowledge this moment as a precious gift.",
  "I take life one step at a time.",
  "I enjoy where I am on my journey.",
  "I trust that each moment holds something valuable.",
  "I appreciate my growth in the present.",
  "I am grateful for the love and kindness in my life.",
  "I let go of distractions and focus on the now.",
  "I accept each moment as part of my journey.",
  "I breathe in peace and exhale worry.",
  "I trust that life is unfolding perfectly for me.",
  "I let go of self-judgment and accept myself now.",
  "I choose presence over perfection.",
  "I let go of impatience and allow things to unfold naturally.",
  "I allow myself to fully experience joy in the present.",
  "I am exactly where I need to be at this moment.",
  "I let go of fear and embrace what is.",
  "I choose to savor the now.",
  "I bring love and kindness into each moment.",
  "I appreciate the people around me fully.",
  "I allow myself to enjoy the simple things in life.",
  "I am open to the beauty in everyday moments.",
  "I choose to be present for myself and others.",
  "I embrace today with enthusiasm and joy.",
  "I am patient with the pace of my life.",
  "I trust in the unfolding of my journey.",
  "I let go of stress and embrace calm.",
  "I choose to live each moment with mindfulness.",
  "I let go of unnecessary worries and focus on now.",
  "I am fully engaged in the beauty of this moment.",
  "I give myself permission to simply be.",
  "I am present, aware, and alive.",
  "I embrace each day as a fresh start.",
  "I find fulfillment in each moment of my life.",
  "I accept and appreciate my journey as it is.",
  "I trust in life’s natural flow.",
  "I welcome each day with a grateful heart.",
  "I allow myself to slow down and be present.",
  "I am grateful for this moment and all it offers.",
  "I let go of distractions and immerse myself in life.",
  "I am at home in the present moment.",
  "I choose to fully experience each second of today.",
  "I open my heart to the joy of now.",
  "I embrace each moment as an opportunity to grow.",
  "I appreciate the richness of my life as it is.",
  "I allow myself to find peace in the present.",
  "I welcome each moment with an open heart.",
  "I am present in every experience today.",
  "I trust the flow of life as it unfolds.",
  "I choose to focus on the beauty of now.",
  "I let go of worries and embrace this moment.",
  "I find peace in simply being here.",
  "I am grateful for this moment and all it brings.",
  "I surrender to the rhythm of life.",
  "I release control and allow life to happen.",
  "I embrace the now with love and joy.",
  "I am centered and grounded in the present.",
  "I let go of the past and focus on today.",
  "I breathe deeply and appreciate this moment.",
  "I trust that the present holds all I need.",
  "I fully experience each moment with awareness.",
  "I am calm, mindful, and at peace.",
  "I focus on what truly matters in this moment.",
  "I appreciate the simple joys of life.",
  "I embrace today with gratitude and grace.",
  "I choose to be happy in the now.",
  "I let go of distractions and immerse myself in the present.",
  "I am fully engaged in my life right now.",
  "I find joy in the small moments of today.",
  "I accept the present moment exactly as it is.",
  "I allow life to unfold naturally.",
  "I cherish the gift of today.",
  "I am grateful for all that I have right now.",
  "I choose to live in the present with peace.",
  "I allow myself to fully enjoy this moment.",
  "I release all that no longer serves me.",
  "I trust that I am where I need to be.",
  "I am mindful of each breath I take.",
  "I accept and appreciate my journey.",
  "I let go of fear and embrace what is.",
  "I allow myself to slow down and be present.",
  "I welcome each experience with curiosity and wonder.",
  "I am fully present in my relationships.",
  "I find joy in the journey, not just the destination.",
  "I appreciate the beauty around me every day.",
  "I am exactly where I need to be in this moment.",
  "I trust the natural flow of life.",
  "I feel calm and centered right now.",
  "I bring awareness to the now.",
  "I choose presence over perfection.",
  "I am grateful for the now and all it offers.",
  "I am in harmony with the present moment.",
  "I listen to life with an open heart.",
  "I release impatience and accept life as it comes.",
  "I savor each moment as a precious gift.",
  "I allow myself to rest and recharge in the now.",
  "I welcome life with open arms.",
  "I find happiness in being, not just doing.",
  "I focus on today instead of worrying about tomorrow.",
  "I embrace the present with love and kindness.",
  "I bring mindfulness to all that I do.",
  "I choose to enjoy where I am right now.",
  "I accept that each moment is enough.",
  "I trust the timing of my life.",
  "I am present and fully engaged in my day.",
  "I choose to live today with joy and ease.",
  "I release the need to rush and embrace the pace of now.",
  "I observe my thoughts without judgment.",
  "I appreciate the here and now deeply.",
  "I focus on the blessings of this moment.",
  "I trust that life is unfolding perfectly for me.",
  "I am at peace with where I am.",
  "I choose to respond to life with grace and patience.",
  "I honor this moment with my full presence.",
  "I release all distractions and bring my awareness to the now.",
  "I embrace the simplicity and beauty of the present.",
  "I am grateful for the love and peace I feel now.",
  "I choose to savor life one moment at a time.",
  "I let go of yesterday and embrace today.",
  "I allow joy to flow freely in the now.",
  "I am mindful and at ease in this moment.",
  "I am content with where I am today.",
  "I accept this moment as it is, without resistance.",
  "I welcome the unknown with confidence and peace.",
  "I open my heart to the joy of the present.",
  "I trust that everything I need is within me now.",
];

final List<String> embracepresentImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> embracepresentAffirmation = getShuffledaffirmations(
  embracepresentAffirmationRaw,
  embracepresentImages,
);
