import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> faithgratitudeAffirmationRaw = [
  "I trust that everything is unfolding for my highest good.",
  "I have faith in the journey of my life.",
  "I surrender my worries and trust the process.",
  "I believe that I am guided and protected.",
  "I trust that the universe has a plan for me.",
  "I am open to receiving divine wisdom.",
  "I choose faith over fear in all situations.",
  "I am supported in all that I do.",
  "I trust that I am exactly where I need to be.",
  "I am confident that all things are working in my favor.",
  "I let go of doubt and embrace faith.",
  "I trust in my ability to overcome challenges.",
  "I believe that everything happens for a reason.",
  "I have faith in my inner strength and resilience.",
  "I am aligned with divine timing.",
  "I choose to see obstacles as opportunities for growth.",
  "I release the need for control and trust in the universe.",
  "I have faith in my ability to handle whatever comes my way.",
  "I trust that every experience is shaping me into my best self.",
  "I am guided by love, faith, and inner wisdom.",
  "I believe that all my needs will be met.",
  "I am surrounded by divine love and protection.",
  "I have faith in the abundance of the universe.",
  "I trust that everything is falling into place.",
  "I am grateful for the lessons that strengthen my faith.",
  "I choose to trust myself and my decisions.",
  "I have unshakable faith in my dreams and aspirations.",
  "I let go of fear and embrace faith wholeheartedly.",
  "I trust that every challenge is a blessing in disguise.",
  "I am filled with faith, hope, and optimism.",
  "I believe that miracles happen every day.",
  "I choose to focus on the good in every situation.",
  "I trust that I am always supported by a higher power.",
  "I am at peace, knowing that all is well.",
  "I have faith in the limitless possibilities ahead of me.",
  "I am divinely guided to my highest good.",
  "I embrace uncertainty with faith and confidence.",
  "I trust that my life is unfolding perfectly.",
  "I believe in the power of faith to transform my life.",
  "I am grateful for the abundance that surrounds me.",
  "I appreciate all the blessings in my life, big and small.",
  "I wake up each day with a heart full of gratitude.",
  "I am thankful for the love and support in my life.",
  "I find joy in the simple moments of life.",
  "I express gratitude for all that I have and all that is to come.",
  "I am grateful for the lessons that shape me into who I am.",
  "I appreciate the beauty of nature and the world around me.",
  "I choose to focus on gratitude and positivity.",
  "I am thankful for the challenges that make me stronger.",
  "I find something to be grateful for in every situation.",
  "I am grateful for the opportunities that come my way.",
  "I appreciate the kindness of others and express my gratitude freely.",
  "I am thankful for the gift of today.",
  "I cultivate a grateful heart and embrace life's blessings.",
  "I see abundance in every aspect of my life.",
  "I appreciate the little things that bring me joy.",
  "I am grateful for the support and love of those around me.",
  "I acknowledge the good in my life and celebrate it.",
  "I am thankful for my health, happiness, and well-being.",
  "I choose to fill my heart with gratitude every single day.",
  "I express gratitude for the love I give and receive.",
  "I am grateful for the present moment and all that it holds.",
  "I recognize and appreciate the goodness in my life.",
  "I am thankful for the strength and resilience within me.",
  "I embrace a grateful mindset and attract more blessings.",
  "I am surrounded by abundance, and I appreciate it deeply.",
  "I am grateful for the lessons that help me grow.",
  "I find happiness in the act of being thankful.",
  "I am open to receiving even more blessings with gratitude.",
  "I appreciate the opportunities that shape my journey.",
  "I am thankful for the relationships that bring joy to my life.",
  "I am grateful for every moment that teaches me something new.",
  "I acknowledge the beauty of life with gratitude.",
  "I am thankful for my ability to learn, grow, and evolve.",
  "I welcome each day with an open and grateful heart.",
  "I appreciate the love and kindness that surrounds me.",
  "I express gratitude daily and live a life full of abundance.",
  "I am grateful for the wisdom that life has given me.",
  "I trust that gratitude opens the door to even greater blessings.",
  "I have faith that everything is working out for my highest good.",
  "I am thankful for the divine guidance that leads me forward.",
  "I choose faith and gratitude in every situation.",
  "I am grateful for the unseen blessings that are on their way.",
  "I trust that expressing gratitude brings more abundance into my life.",
  "I have faith that the universe always supports me.",
  "I am thankful for the divine love that surrounds and protects me.",
  "I believe in the power of gratitude to transform my life.",
  "I trust that my heart's desires are being fulfilled in perfect timing.",
  "I am grateful for the faith that keeps me strong and resilient.",
  "I choose to live each day with faith, love, and gratitude.",
  "I trust that my path is divinely guided and protected.",
  "I am thankful for the challenges that help me grow spiritually.",
  "I have faith that all things are working in my favor.",
  "I am grateful for the love and miracles that fill my life.",
  "I trust that I am being led toward my highest good.",
  "I appreciate the abundance that flows into my life effortlessly.",
  "I choose to see every moment as an opportunity for gratitude.",
  "I have unwavering faith in the blessings that are coming my way.",
  "I am grateful for the lessons that strengthen my faith.",
  "I believe in divine timing and trust the process.",
  "I am thankful for the infinite possibilities that surround me.",
  "I trust that my gratitude attracts even greater abundance.",
  "I am grateful for the love and peace within my heart.",
  "I choose faith and gratitude as my guiding principles.",
  "I appreciate all that I have and all that is yet to come.",
  "I trust that my life is unfolding exactly as it should.",
  "I am grateful for the strength that faith provides me.",
  "I choose to celebrate each day with a grateful heart.",
  "I trust that my gratitude creates a life of abundance.",
  "I am thankful for the divine blessings in my life.",
  "I believe in the power of faith and gratitude to transform me.",
  "I am grateful for the endless opportunities that life presents.",
  "I trust that every challenge leads me to something greater.",
  "I embrace faith and gratitude as my foundation for happiness.",
  "I trust that the universe is always working in my favor.",
  "I have unshakable faith in my dreams and my journey.",
  "I surrender my fears and embrace divine guidance.",
  "I believe in my ability to overcome any challenge.",
  "I trust the process of life and know that all is well.",
  "I choose faith over doubt in all aspects of my life.",
  "I am guided by love, wisdom, and divine protection.",
  "I believe that everything is unfolding as it should.",
  "I let go of control and trust the divine plan.",
  "I have faith in my inner strength and resilience.",
  "I embrace uncertainty with courage and confidence.",
  "I trust that my challenges are leading me to something greater.",
  "I believe that miracles happen every day.",
  "I am always supported, even when I cannot see the way forward.",
  "I am aligned with the divine energy of the universe.",
  "I release all worry and embrace peace and faith.",
  "I trust that every experience is shaping me into my highest self.",
  "I am divinely guided toward success and happiness.",
  "I have faith that every setback is a setup for a comeback.",
  "I trust in the infinite wisdom that directs my path.",
  "I let go of fear and embrace faith wholeheartedly.",
  "I know that my heart’s desires are already on their way to me.",
  "I have faith in my ability to create a beautiful future.",
  "I trust the divine timing of my life.",
  "I am exactly where I need to be at this moment.",
  "I am filled with faith, hope, and positivity.",
  "I trust my intuition and the wisdom it provides.",
  "I believe in the goodness of life and the people around me.",
  "I release all doubts and step forward with faith.",
  "I trust that my prayers are always answered in the best way.",
  "I have faith that I am capable of achieving my dreams.",
  "I trust that my struggles will lead to beautiful growth.",
  "I am safe, protected, and divinely guided.",
  "I have faith that love and joy are always within reach.",
  "I trust that my journey is unfolding in perfect harmony.",
  "I believe that I am worthy of all good things.",
  "I let go of resistance and allow faith to lead me.",
  "I know that every ending is a new beginning.",
  "I am confident in the divine support that surrounds me.",
  "I trust the wisdom of the universe to guide me.",
  "I have faith that abundance flows effortlessly to me.",
  "I embrace the unknown with faith and enthusiasm.",
  "I trust that I am always being led toward my highest good.",
  "I release negativity and allow faith to uplift me.",
  "I am grateful for the divine presence in my life.",
  "I have faith that everything happens for a reason.",
  "I trust that life is filled with endless possibilities.",
  "I am open to divine guidance and new opportunities.",
  "I have unwavering faith in the path I am walking.",
  "I am grateful for the many blessings in my life.",
  "I appreciate all that I have and all that is yet to come.",
  "I wake up each day with a heart full of gratitude.",
  "I am thankful for every lesson life has given me.",
  "I recognize and appreciate the abundance around me.",
  "I am grateful for the love that fills my life.",
  "I choose to focus on gratitude and positivity.",
  "I appreciate the simple joys that make life beautiful.",
  "I am thankful for the opportunities that come my way.",
  "I express gratitude freely and with joy.",
  "I am grateful for the strength that each challenge brings.",
  "I appreciate the kindness I receive and give to others.",
  "I find something to be grateful for in every moment.",
  "I am thankful for my health, happiness, and well-being.",
  "I cultivate a grateful heart and a positive mindset.",
  "I am grateful for the lessons that shape my soul.",
  "I acknowledge the beauty and goodness in my life.",
  "I am thankful for my ability to grow and evolve.",
  "I recognize the power of gratitude in creating joy.",
  "I am grateful for the relationships that bring me happiness.",
  "I choose to see every day as a gift.",
  "I am thankful for the love and kindness I experience.",
  "I find peace in appreciating life’s little moments.",
  "I am grateful for the infinite possibilities in my life.",
  "I welcome each day with a grateful heart.",
  "I embrace gratitude as a daily practice.",
  "I appreciate the beauty of nature and the world around me.",
  "I am grateful for my journey and all it has taught me.",
  "I find joy in the act of giving and receiving gratitude.",
  "I am thankful for the wisdom and strength within me.",
  "I choose to celebrate life with an open heart.",
  "I am grateful for the abundance that surrounds me.",
  "I am thankful for the guidance that life provides me.",
  "I recognize and appreciate the good in every situation.",
  "I express gratitude for the experiences that shape me.",
  "I am grateful for the support and love I receive.",
  "I choose to focus on what I have, rather than what I lack.",
  "I appreciate the journey of my life and its beautiful unfolding.",
  "I am grateful for my past, present, and future.",
  "I am thankful for the people who bring positivity into my life.",
  "I express gratitude for the peace within me.",
  "I find strength in being thankful for all that I have.",
  "I welcome abundance into my life through gratitude.",
  "I am grateful for the experiences that have made me stronger.",
  "I trust that my gratitude attracts more blessings.",
  "I choose to see the goodness in everything around me.",
  "I celebrate life’s journey with gratitude and joy.",
  "I am grateful for every moment of love and connection.",
  "I trust that gratitude will bring more abundance into my life.",
  "I acknowledge and appreciate the divine gifts in my life.",
];

final List<String> faithgratitudeImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> faithgratitudeAffirmation = getShuffledaffirmations(
  faithgratitudeAffirmationRaw,
  faithgratitudeImages,
);
