import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> findingjoyAffirmationRaw = [
  "Joy is my natural state.",
  "I find happiness in the little moments of life.",
  "I choose to see the beauty in every day.",
  "I deserve joy and happiness in abundance.",
  "My heart is open to happiness and laughter.",
  "I create my own happiness.",
  "I find joy in the present moment.",
  "Happiness flows to me effortlessly.",
  "I allow myself to experience pure joy.",
  "I am worthy of a life filled with happiness.",
  "I attract joyful experiences and people into my life.",
  "I focus on what brings me happiness and peace.",
  "I wake up each day with a joyful heart.",
  "I am grateful for all the joyful moments in my life.",
  "Smiles and laughter are part of my daily life.",
  "Happiness is always available to me.",
  "I embrace positivity and joy in all situations.",
  "I radiate happiness from within.",
  "I find joy in the simple things.",
  "I deserve to feel happy and fulfilled.",
  "My life is filled with love and joy.",
  "I choose to be happy, no matter what.",
  "I surround myself with joyful and uplifting energy.",
  "I focus on the blessings in my life.",
  "Every day is a fresh start filled with happiness.",
  "I bring joy into the lives of others.",
  "Laughter is my natural response to life.",
  "I celebrate the joy in every moment.",
  "My happiness comes from within.",
  "I let go of worries and embrace joy.",
  "I am grateful for the happiness that fills my life.",
  "I choose happiness over stress and worry.",
  "Joy is my birthright, and I claim it now.",
  "I attract happiness, positivity, and love.",
  "I create joy in my life by being present.",
  "I am worthy of love, joy, and peace.",
  "Every breath I take fills me with happiness.",
  "I let go of negativity and welcome joy.",
  "I choose to see the good in everything.",
  "I deserve to experience deep joy every day.",
  "I am open to moments of pure happiness.",
  "My heart is light, and my spirit is free.",
  "I create my own sunshine wherever I go.",
  "I am thankful for the joy that surrounds me.",
  "I laugh often and deeply.",
  "I find happiness in the journey, not just the destination.",
  "I am at peace with my life and enjoy every moment.",
  "I embrace the happiness that life offers me.",
  "I choose to spread joy wherever I go.",
  "I am grateful for the happiness in my life.",
  "I cherish every joyful experience.",
  "I deserve happiness and abundance.",
  "Every day is an opportunity to find joy.",
  "I focus on what makes me happy.",
  "I attract positivity and joy effortlessly.",
  "My life is filled with moments of pure bliss.",
  "I welcome happiness into my heart and soul.",
  "I embrace laughter and fun.",
  "I am surrounded by things that bring me joy.",
  "I create happiness through my thoughts and actions.",
  "Joy is within me, always.",
  "I find joy in unexpected places.",
  "I appreciate the simple joys of life.",
  "I choose happiness as my way of life.",
  "My life is filled with light and laughter.",
  "I release stress and welcome joy.",
  "I celebrate every joyful moment.",
  "I am grateful for the happiness in my life.",
  "Happiness is a choice, and I choose it daily.",
  "I deserve a life full of laughter and fun.",
  "I spread joy wherever I go.",
  "My heart is light and filled with happiness.",
  "I let go of anything that does not bring me joy.",
  "I am excited about the joyful moments ahead.",
  "Joy and gratitude fill my life.",
  "I attract people and experiences that bring me joy.",
  "I create moments of joy every day.",
  "I see happiness in every situation.",
  "I welcome happiness with open arms.",
  "I choose to live a joyful life.",
  "I find joy in giving and receiving love.",
  "Laughter is a natural part of my day.",
  "I appreciate all the joyful moments in my life.",
  "My life is a beautiful adventure filled with happiness.",
  "I am surrounded by positivity and happiness.",
  "I focus on the present and find joy in it.",
  "I allow myself to experience joy without guilt.",
  "I deserve to live a life filled with joy and excitement.",
  "Joy is contagious, and I share it with others.",
  "I smile easily and often.",
  "I find joy in my relationships and connections.",
  "I appreciate the small things that make me happy.",
  "I am grateful for the joy that fills my heart.",
  "I trust that joy is always available to me.",
  "I embrace each day with a joyful heart.",
  "I choose to see joy even in difficult moments.",
  "I am aligned with happiness and fulfillment.",
  "I radiate joy and attract happiness effortlessly.",
  "I find joy in learning and growing.",
  "Every moment holds the potential for happiness.",
  "I appreciate the laughter that fills my life.",
  "I choose to let joy be my guiding light.",
  "I focus on what brings me the most joy.",
  "I am always open to new sources of happiness.",
  "My heart overflows with gratitude and joy.",
  "I live a life full of passion and happiness.",
  "Joy is my priority, and I welcome it daily.",
  "I celebrate the happiness of others as well as my own.",
  "My inner joy shines brightly in the world.",
  "Happiness flows through me in every situation.",
  "I attract joyful experiences with ease.",
  "Every day, I find new reasons to be happy.",
  "I allow joy to fill my soul completely.",
  "I am worthy of experiencing deep, fulfilling joy.",
  "My life is filled with laughter and love.",
  "Happiness is my natural state of being.",
  "I welcome every moment of happiness with gratitude.",
  "I focus on the joys of today, not the worries of tomorrow.",
  "I embrace the happiness within and around me.",
  "My heart beats in rhythm with the joy of life.",
  "I bring happiness into every space I enter.",
  "I choose to surround myself with happiness.",
  "Joy is my choice, and I choose it daily.",
  "I deserve a life filled with laughter and love.",
  "Happiness comes naturally to me.",
  "I find peace in joyful moments.",
  "I appreciate the little joys life offers me.",
  "My happiness is limitless and ever-expanding.",
  "I am free to experience joy in all areas of my life.",
  "I radiate positivity and attract joyful experiences.",
  "My heart is always open to happiness.",
  "I seek out and embrace joyful moments every day.",
  "I trust that my life is filled with joy and abundance.",
  "I am surrounded by happiness in all forms.",
  "I choose to let go of negativity and embrace joy.",
  "I celebrate my life with love and happiness.",
  "I am grateful for all the moments of joy in my life.",
  "I welcome joy into my life with open arms.",
  "Happiness is a choice, and I choose it daily.",
  "I find joy in the simple pleasures of life.",
  "My heart is filled with gratitude and happiness.",
  "I attract positive energy and joyful experiences.",
  "I am worthy of deep, lasting joy.",
  "Every day brings new reasons to smile.",
  "I create my own happiness.",
  "I embrace moments of laughter and love.",
  "Joy flows through me effortlessly.",
  "I celebrate life and all its beauty.",
  "I find happiness in every moment.",
  "I deserve to feel light, free, and joyful.",
  "Laughter fills my heart and soul.",
  "I am surrounded by things that make me happy.",
  "My life is filled with bright and joyful moments.",
  "I focus on what brings me peace and joy.",
  "I let go of worries and welcome happiness.",
  "Joy is my natural state of being.",
  "I radiate happiness from within.",
  "Every breath I take fills me with peace and joy.",
  "I am grateful for the joy that surrounds me.",
  "Smiling comes naturally to me.",
  "I choose to see the beauty in life every day.",
  "My life is an adventure filled with happiness.",
  "I embrace joy and positivity in all situations.",
  "Happiness flows to me effortlessly.",
  "I spread joy wherever I go.",
  "I trust that my life is full of wonderful surprises.",
  "I find happiness in the present moment.",
  "I am open to new sources of joy.",
  "Joy and laughter uplift my spirit.",
  "I attract happiness and positivity effortlessly.",
  "Every day is an opportunity for joy.",
  "I appreciate all the little things that bring me happiness.",
  "I release negativity and embrace pure joy.",
  "I am a magnet for joyful experiences.",
  "I am at peace with my life and find joy in every moment.",
  "I focus on the blessings that bring me happiness.",
  "I allow myself to fully enjoy life’s simple pleasures.",
  "My joy is contagious and inspires others.",
  "Happiness is always available to me.",
  "I fill my life with laughter and love.",
  "I cherish each moment of joy in my life.",
  "I wake up every day with a happy heart.",
  "I choose to be happy, no matter what.",
  "I surround myself with positivity and joy.",
  "Every challenge brings an opportunity for happiness.",
  "I see joy in every experience, big or small.",
  "Happiness comes easily and naturally to me.",
  "I am deeply grateful for the joy in my life.",
  "My joy multiplies as I share it with others.",
  "I bring happiness to those around me.",
  "I deserve a life filled with peace, love, and joy.",
  "I celebrate life’s victories, big and small.",
  "Joy is my birthright, and I claim it now.",
  "Laughter brightens my soul and lifts my spirit.",
  "My happiness shines through everything I do.",
  "I let go of stress and welcome happiness.",
  "I am aligned with happiness, success, and abundance.",
  "I choose to focus on what makes me happy.",
  "I embrace happiness as a way of life.",
  "My heart is full of joy and gratitude.",
  "I find joy in sharing kindness and love.",
  "I am thankful for all the happiness in my life.",
  "I allow myself to experience pure happiness.",
  "I am in control of my own happiness.",
  "I see joy and beauty everywhere I go.",
  "I make space for joy and laughter every day.",
  "Happiness starts within me, and I nurture it daily.",
  "I trust that joy will always find its way to me.",
  "I choose to let go of fear and embrace happiness.",
  "I focus on what brings me the most joy.",
  "Happiness is my natural state of mind.",
  "I create joyful moments for myself and others.",
  "My life is filled with moments of pure joy.",
  "I cherish every opportunity to smile and laugh.",
  "I choose to live with joy and enthusiasm.",
  "I am grateful for the little things that make life special.",
  "I allow happiness to flow into my life effortlessly.",
  "Every day, I discover new reasons to be joyful.",
];

final List<String> findingjoyImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> findingjoyAffirmation = getShuffledaffirmations(
  findingjoyAffirmationRaw,
  findingjoyImages,
);
