import '../affirmation_randomizer.dart';

/// **Bouncing Back from Failure Quotes & Images**
final List<String> spreadhappinessAffirmationRaw = [
  "I choose happiness and joy every day.",
  "I radiate positivity wherever I go.",
  "My happiness is contagious and inspires others.",
  "I spread kindness and joy to everyone I meet.",
  "I choose to see the beauty in every moment.",
  "My smile has the power to brighten someone's day.",
  "I bring love and happiness into the world.",
  "I am a source of light and positivity.",
  "Happiness flows through me effortlessly.",
  "I choose to focus on the good in life.",
  "I find joy in the simplest things.",
  "I have the power to make others feel loved and valued.",
  "I share my happiness freely and openly.",
  "Every day, I create positive experiences for myself and others.",
  "I spread love, laughter, and happiness wherever I go.",
  "I uplift and encourage those around me.",
  "I am grateful for all the happiness in my life.",
  "I choose to be a beacon of light in the world.",
  "My energy radiates warmth and joy.",
  "I inspire others to embrace happiness.",
  "My heart is open to joy and laughter.",
  "I create happiness in my life and the lives of others.",
  "I attract positivity and joy effortlessly.",
  "I am a magnet for smiles and good vibes.",
  "Happiness is my natural state of being.",
  "I celebrate the joy of living every day.",
  "I see the good in every situation.",
  "I bring peace, love, and joy into every room I enter.",
  "I find joy in giving to others.",
  "I spread happiness through my words and actions.",
  "My happiness increases when I share it with others.",
  "I am grateful for the happiness I experience daily.",
  "I choose laughter over stress.",
  "I am surrounded by joyful and loving people.",
  "My positive energy transforms any environment.",
  "I see life as a beautiful adventure filled with joy.",
  "I bring out the best in others through kindness.",
  "I create happiness by appreciating the little things in life.",
  "I make the world a better place through my happiness.",
  "I attract joyful experiences into my life.",
  "I find reasons to be happy every single day.",
  "I inspire happiness in others by being my authentic self.",
  "I am grateful for every smile I see today.",
  "I radiate love and joy in every interaction.",
  "I embrace every moment with gratitude and joy.",
  "My happiness grows as I share it with others.",
  "I choose to surround myself with positivity and joy.",
  "I find peace and happiness within myself.",
  "Every day is a new opportunity to spread happiness.",
  "I spread happiness by uplifting and supporting others.",
  "My life is filled with love, laughter, and happiness.",
  "I choose to focus on what brings me joy.",
  "I am happy, and I spread that happiness to others.",
  "My words bring encouragement and joy to others.",
  "I create a ripple effect of joy and positivity.",
  "I am grateful for the simple pleasures in life.",
  "I choose to be a source of light and happiness.",
  "I find joy in connecting with others.",
  "I am surrounded by happiness and abundance.",
  "Every day is a gift filled with joy and love.",
  "I bring out the best in others through kindness.",
  "I find happiness in making others smile.",
  "I am grateful for the opportunity to spread happiness.",
  "I choose to see life through the lens of joy.",
  "I make happiness a priority in my life.",
  "I let go of negativity and embrace joy.",
  "I am worthy of happiness, love, and laughter.",
  "My happiness is a gift to the world.",
  "I focus on the good and let joy guide my day.",
  "I attract people who uplift and inspire me.",
  "I live in a state of happiness and gratitude.",
  "I am happy, healthy, and full of life.",
  "I embrace positivity and joy with an open heart.",
  "I spread happiness with my kind words and actions.",
  "I choose to be joyful, no matter the circumstances.",
  "I appreciate the little joys in life.",
  "I am surrounded by happiness and positivity.",
  "I share happiness through acts of kindness.",
  "I am a source of peace, love, and laughter.",
  "I wake up every day with a joyful heart.",
  "I inspire happiness in others effortlessly.",
  "I let go of worry and embrace happiness.",
  "I radiate positivity and attract happy moments.",
  "I enjoy spreading happiness wherever I go.",
  "I bring light and love into the lives of others.",
  "I see happiness in every moment.",
  "I focus on what makes me feel alive and joyful.",
  "I live each day with an open heart and a happy spirit.",
  "I express gratitude for all the happiness in my life.",
  "My presence fills the world with warmth and joy.",
  "I choose love and happiness in all I do.",
  "I am grateful for every opportunity to smile.",
  "My laughter is music to the universe.",
  "Happiness is a choice, and I choose it daily.",
  "I spread happiness by being kind and compassionate.",
  "My happiness lifts the spirits of those around me.",
  "I bring positivity and laughter into every space I enter.",
  "I celebrate life with happiness and gratitude.",
  "I spread joy with every action and word.",
  "I choose to see the good in others and situations.",
  "I find joy in the little things life offers.",
  "I focus on all the reasons to be happy.",
  "I am surrounded by love, laughter, and happiness.",
  "I have a heart full of gratitude and joy.",
  "I am grateful for the happiness that surrounds me.",
  "Every day, I find new reasons to smile.",
  "I spread joy simply by being myself.",
  "My heart overflows with happiness and love.",
  "I let go of worries and embrace happiness.",
  "I attract happiness into my life effortlessly.",
  "I live my life with joy and excitement.",
  "I believe happiness is always within my reach.",
  "I inspire others to embrace joy and positivity.",
  "I choose to be a source of happiness for those around me.",
  "My happiness is reflected in everything I do.",
  "I create an atmosphere of joy and positivity.",
  "I uplift others by sharing my happiness.",
  "I am grateful for the beautiful moments in my life.",
  "My happiness is a reflection of my gratitude.",
  "I celebrate the small victories with joy.",
  "I make time for laughter and fun every day.",
  "I appreciate the joy that life brings.",
  "I choose happiness as my daily habit.",
  "I let my joy shine brightly for others to see.",
  "I am an ambassador of happiness and love.",
  "I believe in the power of happiness to heal.",
  "I celebrate each day with a heart full of joy.",
  "I welcome happiness into my life with open arms.",
  "Happiness is my natural state of being.",
  "I find happiness in being kind to others.",
  "I am a beacon of joy and positivity.",
  "I bring happiness to everyone I meet.",
  "I choose to be a source of happiness every day.",
  "My happiness spreads like sunshine to those around me.",
  "I bring joy to others through my words and actions.",
  "Smiling is my superpower, and I use it often.",
  "I am a carrier of positivity and light.",
  "Happiness flows effortlessly through me.",
  "I choose joy in every situation.",
  "My happiness is a reflection of my gratitude.",
  "I inspire others to find joy in the little things.",
  "Laughter is a gift, and I share it generously.",
  "I radiate happiness, love, and positivity.",
  "My heart is open to giving and receiving joy.",
  "I uplift others with my kind words and gestures.",
  "I spread happiness by being my authentic self.",
  "I find joy in sharing and giving to others.",
  "My happiness increases when I help others smile.",
  "Happiness is contagious, and I love to spread it.",
  "I create positive experiences for myself and others.",
  "I bring love and light into every space I enter.",
  "Every day, I have the power to brighten someone’s day.",
  "I make the world a happier place just by being in it.",
  "I share my happiness freely and abundantly.",
  "I choose to see beauty in the world around me.",
  "Happiness is my natural state of being.",
  "I spread kindness, joy, and warmth wherever I go.",
  "I am surrounded by love, joy, and happiness.",
  "I find joy in the simple pleasures of life.",
  "My heart overflows with happiness and gratitude.",
  "I welcome joy and happiness into my life.",
  "I celebrate life with laughter and positivity.",
  "I create a ripple effect of happiness everywhere I go.",
  "My happiness inspires others to embrace their own joy.",
  "I see the good in every situation and focus on it.",
  "Happiness is a choice, and I choose it daily.",
  "I attract happy and positive people into my life.",
  "I make happiness a priority in my life.",
  "My joy is limitless and ever-expanding.",
  "I bring smiles to the faces of those around me.",
  "My happiness is a gift to the world.",
  "I choose to radiate love, peace, and happiness.",
  "I find happiness in giving and serving others.",
  "I am grateful for the joy that fills my life.",
  "I embrace each day with a heart full of happiness.",
  "I inspire others to live with joy and gratitude.",
  "I see joy in the present moment.",
  "I appreciate the love and happiness surrounding me.",
  "Happiness is my birthright, and I claim it fully.",
  "I celebrate life’s beautiful moments with gratitude.",
  "Every act of kindness I do brings happiness to the world.",
  "I attract positive experiences that bring me joy.",
  "I let go of negativity and embrace happiness.",
  "I am a magnet for happiness, love, and laughter.",
  "I uplift others with my positive energy.",
  "I create happiness wherever I go.",
  "I choose to make someone’s day brighter today.",
  "I find joy in making others feel valued and appreciated.",
  "My happiness is unshakable and deeply rooted.",
  "I give myself permission to be truly happy.",
  "I see the world through a joyful lens.",
  "Happiness flows to me effortlessly and abundantly.",
  "I am a source of inspiration and positivity.",
  "My life is filled with joyful moments.",
  "I choose to focus on the good in people.",
  "I am at peace, and my happiness radiates outward.",
  "I deserve happiness, and I welcome it into my life.",
  "My heart is filled with love, laughter, and happiness.",
  "I embrace happiness in all areas of my life.",
  "I find happiness in every new experience.",
  "I am a beacon of joy for those around me.",
  "I let happiness guide my thoughts and actions.",
  "I spread happiness by showing appreciation and love.",
  "My happiness is independent of external circumstances.",
  "I have an abundance of happiness to share with the world.",
  "I allow myself to enjoy every moment fully.",
  "I radiate joy and attract joyful experiences.",
  "I am grateful for the happiness I experience each day.",
  "Every day is an opportunity to spread happiness.",
  "I bring positive energy into every interaction.",
  "I make happiness a habit in my daily life.",
  "I celebrate my life and the joy it brings.",
  "I choose to find reasons to smile every day.",
  "My happiness uplifts those around me.",
  "I see happiness in the faces of my loved ones.",
  "I am filled with happiness, peace, and love.",
  "I bring joy to my community through kindness.",
  "I am a source of positivity in every situation.",
  "My presence brightens up the lives of others.",
  "Happiness is always within my reach.",
  "I spread happiness through acts of kindness.",
  "I choose laughter over worry.",
  "I am grateful for the joy in my life.",
  "I wake up each morning excited to share happiness.",
  "My words bring encouragement and joy to others.",
  "I focus on what makes me feel alive and joyful.",
  "I appreciate all the happiness life offers me.",
  "I choose to see the world with love and joy.",
  "I create happiness by embracing each moment.",
  "I find happiness in lifting others up.",
  "I am constantly surrounded by love and positivity.",
  "I bring joy into my life by spreading kindness.",
];

final List<String> spreadhappinessImages = [
  "assets/images/affermations icons/bg/1.jpg",
  "assets/images/affermations icons/bg/2.jpg",
  "assets/images/affermations icons/bg/3.jpg",
  "assets/images/affermations icons/bg/4.jpg",
  "assets/images/affermations icons/bg/5.jpg",
  "assets/images/affermations icons/bg/6.jpg",
  "assets/images/affermations icons/bg/7.jpg",
  "assets/images/affermations icons/bg/8.jpg",
  "assets/images/affermations icons/bg/9.jpg",
  "assets/images/affermations icons/bg/10.jpg",
  "assets/images/affermations icons/bg/11.jpg",
  "assets/images/affermations icons/bg/12.jpg",
  "assets/images/affermations icons/bg/13.jpg",
  "assets/images/affermations icons/bg/14.jpg",
  "assets/images/affermations icons/bg/15.jpg",
  "assets/images/affermations icons/bg/16.jpg",
  "assets/images/affermations icons/bg/17.jpg",
  "assets/images/affermations icons/bg/18.jpg",
  "assets/images/affermations icons/bg/19.jpg",
  "assets/images/affermations icons/bg/20.jpg",
  "assets/images/affermations icons/bg/21.jpg",
  "assets/images/affermations icons/bg/22.jpg",
  "assets/images/affermations icons/bg/23.jpg",
  "assets/images/affermations icons/bg/24.jpg",
  "assets/images/affermations icons/bg/25.jpg",
  "assets/images/affermations icons/bg/26.jpg",
  "assets/images/affermations icons/bg/27.jpg",
  "assets/images/affermations icons/bg/28.jpg",
  "assets/images/affermations icons/bg/29.jpg",
  "assets/images/affermations icons/bg/30.jpg",
  "assets/images/affermations icons/bg/31.jpg",
  "assets/images/affermations icons/bg/32.jpg",
  "assets/images/affermations icons/bg/33.jpg",
  "assets/images/affermations icons/bg/34.jpg",
  "assets/images/affermations icons/bg/35.jpg",
  "assets/images/affermations icons/bg/36.jpg",
  "assets/images/affermations icons/bg/37.jpg",
  "assets/images/affermations icons/bg/38.jpg",
  "assets/images/affermations icons/bg/39.jpg",
  "assets/images/affermations icons/bg/40.jpg",
  "assets/images/affermations icons/bg/41.jpg",
  "assets/images/affermations icons/bg/42.jpg",
  "assets/images/affermations icons/bg/43.jpg",
  "assets/images/affermations icons/bg/44.jpg",
  "assets/images/affermations icons/bg/45.jpg",
  "assets/images/affermations icons/bg/46.jpg",
  "assets/images/affermations icons/bg/47.jpg",
  "assets/images/affermations icons/bg/48.jpg",
  "assets/images/affermations icons/bg/49.jpg",
  "assets/images/affermations icons/bg/50.jpg",
  "assets/images/affermations icons/bg/51.jpg",
  "assets/images/affermations icons/bg/52.jpg",
  "assets/images/affermations icons/bg/53.jpg",
  "assets/images/affermations icons/bg/54.jpg",
  "assets/images/affermations icons/bg/55.jpg",
  "assets/images/affermations icons/bg/56.jpg",
  "assets/images/affermations icons/bg/57.jpg",
  "assets/images/affermations icons/bg/58.jpg",
  "assets/images/affermations icons/bg/59.jpg",
  "assets/images/affermations icons/bg/60.jpg",
  "assets/images/affermations icons/bg/61.jpg",
  "assets/images/affermations icons/bg/62.jpg",
  "assets/images/affermations icons/bg/63.jpg",
  "assets/images/affermations icons/bg/64.jpg",
  "assets/images/affermations icons/bg/65.jpg",
  "assets/images/affermations icons/bg/66.jpg",
  "assets/images/affermations icons/bg/67.jpg",
  "assets/images/affermations icons/bg/68.jpg",
  "assets/images/affermations icons/bg/69.jpg",
  "assets/images/affermations icons/bg/70.jpg",
  "assets/images/affermations icons/bg/71.jpg",
  "assets/images/affermations icons/bg/72.jpg",
  "assets/images/affermations icons/bg/73.jpg",
  "assets/images/affermations icons/bg/74.jpg",
  "assets/images/affermations icons/bg/75.jpg",
  "assets/images/affermations icons/bg/76.jpg",
  "assets/images/affermations icons/bg/77.jpg",
  "assets/images/affermations icons/bg/78.jpg",
  "assets/images/affermations icons/bg/79.jpg",
  "assets/images/affermations icons/bg/80.jpg",
  "assets/images/affermations icons/bg/81.jpg",
  "assets/images/affermations icons/bg/82.jpg",
  "assets/images/affermations icons/bg/83.jpg",
  "assets/images/affermations icons/bg/84.jpg",
  "assets/images/affermations icons/bg/85.jpg",
  "assets/images/affermations icons/bg/86.jpg",
  "assets/images/affermations icons/bg/87.jpg",
  "assets/images/affermations icons/bg/88.jpg",
  "assets/images/affermations icons/bg/89.jpg",
  "assets/images/affermations icons/bg/90.jpg",
  "assets/images/affermations icons/bg/91.jpg",
  "assets/images/affermations icons/bg/92.jpg",
  "assets/images/affermations icons/bg/93.jpg",
  "assets/images/affermations icons/bg/94.jpg",
  "assets/images/affermations icons/bg/95.jpg",
  "assets/images/affermations icons/bg/96.jpg",
  "assets/images/affermations icons/bg/97.jpg",
  "assets/images/affermations icons/bg/98.jpg",
  "assets/images/affermations icons/bg/99.jpg",
  "assets/images/affermations icons/bg/100.jpg",
];

/// Generate the final list of shuffled bounce back quotes with random images.
final List<AffirmationItem> spreadhappinessAffirmation =
    getShuffledaffirmations(
      spreadhappinessAffirmationRaw,
      spreadhappinessImages,
    );
